### ISSUE TITLE
Philio-Devices > Motion- and Sabotage-Alarm stay on 

### ISSUE THREAD

**Issue by CyberSponk** [athombv/homey#2143] opened 2018-01-06 17:52 UTC
* **Homey Version**: 1.5.8-rc8
* **Homey Log Code**: -
* **Smartphone Platform**: -
* **Smartphone App Version**: -

**If related to a Homey App: -**
* **Homey App Version**: -
* **Homey App Log Code**: -
* **Affected Devices (preferably product codes)**:
PST02-A 4:1 (Manufacturer 316, ProductType 2, ProductID 12)

**What did you try to achieve?**
Turning Light On when Motion detected with a Flow: When > MotionDevice1 detect Motion, Then > Turn Light1 On.

**What did you expect as result?**
That the Light turns On.

**What was the result?**
Standing in the Dark.

**Any other remarks**
In 1.5.6-rc6 it works a long time very good. Didn't tryed 1.5.6-rc7. Since a week sometimes delays between "Motion Detected" and "Turn Light On". 

The last Days it works only sometimes and the Sensor shows Motion or Sabotage while there is no Motion in the Room. 

It's not every time the same Sensor-/Light-Combination. The Issue is absolutley random.

Seem to be the same Problem as on Fibaro-Devices reported here: 
https://github.com/athombv/homey/issues/1785

**Comment by WeeJeWel** [comment] 2018-01-17 13:04
Indeed duplicate of #1785

**Closed by WeeJeWel** 2018-01-17 13:04 UTC
Labels: Z-Wave, bug, watch
