### ISSUE TITLE
[com.dyson] App does not start. Crashes immediately.

### ISSUE THREAD

**Issue by hhhau** [athombv/homey#2731] opened 2018-08-01 20:22 UTC
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**: e3b869d8-73fe-414c-ab1f-da106d4c4353
* **Smartphone Platform**: iOS
* **Smartphone App Version**: 

**What did you try to achieve?**

I installed the app and it does not start. The app in Homey crashes immediately.

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by Dijker** [comment] 2018-08-01 20:52
Duplicate of #2730

**Comment by WeeJeWel** [comment] 2018-08-02 09:49
This has been fixed in v2.0.1.

**Closed** 2018-08-02 09:49 UTC
