### ISSUE TITLE
Unable to add Fibaro Dimmer 2 or Double Switch to ZWave

### ISSUE THREAD

**Issue by MdeRhoter** [athombv/homey#917] opened 2016-09-28 12:42 UTC
On 0.10.0, it's no longer possible to add Fibaro Dimmer 2 or Fibaro Double Switch (both Zwave+). A Fibaro Dimmer 2 added before the update works fine.

With a lot of rebooting I can get the Zwave wizard to get past "wait for Zwave network to become ready", it sees the node, exchanges the security key (slowly), it the times out during the command classes.

I've tried different dimmers (three new ones in total) at different distances. One is right next to the already paired dimmer and no dimmer is more than 5 meters from Homey (2 with direct line of sight, 1 is behind a small wall but next to an already paired one).

**Comment by caseda** [comment] 2016-09-28 13:11
Even though the add commands can also go through the routing protocol, it is recommended that the distance is less then 2 meters from homey itself (not other modules), less is better. 
It really looks like a distance problem because it timesout at the getting command classes

**Comment by MdeRhoter** [comment] 2016-09-28 14:54
Well that worked for 1 out of 3 dimmers, the other two won't pair beyond "retrieving command classes", no matter what the distance (next to it, 50 cm, 1m, 1,5m).

What doesn't help the process that removing a half-paired device takes about 20 minutes of fruitlessly clicking "remove device", seeing it grey out, then becoming clickable again, repeat until you get the message "put your device in learn mode".

It's been a while since I've found a single device *this* annoying!

**Comment by caseda** [comment] 2016-09-28 16:04
that should fix itself when you reboot homey from the settings -> system -> [reboot system], not even a PTP

**Comment by MdeRhoter** [comment] 2016-09-28 17:40
No, PTP is only for when I have to move Homey to be near enough the Zwave node - is there a Github issue for the Remove Device behavior?

**Comment by caseda** [comment] 2016-09-28 17:56
i don't think so, haven't had the problem for some time now so can't send a log to help explain the problem

**Comment by MdeRhoter** [comment] 2016-09-29 16:49
Update: the dimmers can now be added just fine, but the double switch gets stuck at this part:

![image](https://cloud.githubusercontent.com/assets/15713184/18963443/4a8edfea-8675-11e6-8097-8ce88651a706.png)

Everything before that (security key, command classes etc) goes really really fast, so it doesn't look like this fails due to connectivity issues (Homey <-> dimmer 2 = 50 cm)

**Comment by caseda** [comment] 2016-09-29 17:10
the double switch 2 problem has been fixed (partly) in the next fibaro app update (1.0.12).
iIt's partly because only switch 1 (S1/Q1) can be used as of now thanks to a bug in homey.

**Comment by MdeRhoter** [comment] 2016-09-29 17:24
Partly? :0)

**Comment by caseda** [comment] 2016-09-29 17:41
yup part(l)y 🎉

**Comment by sizarkamar** [comment] 2016-09-30 11:47
I have after updating to 0.10.0 (and 0.10.1) the same problem but with fibaro dimmer 1. Also not able to add it to devices. I just made a new issue in the fibaro app github section.

**Comment by MdeRhoter** [comment] 2016-09-30 11:59
@sizarkamar; moving Homey to within a meter from the device made it work for me, all four Fibaro Dimmer 2 modules are paired correctly.

**Comment by sizarkamar** [comment] 2016-09-30 12:27
thank you @MdeRhoter en @caseda the problem is solved by resetting the dimmer module itself. The distance to Homey was less then 2 meters

**Comment by MdeRhoter** [comment] 2016-09-30 12:37
Good tip for the FAQ!

**Comment by RobinBol** [comment] 2016-12-01 20:14
Z-Wave has improved a lot in the mean time, as I can read your issues are resolved therefore I'll close this issue, if not please re-open!

**Closed by RobinBol** 2016-12-01 20:14 UTC
