### ISSUE TITLE
logitech

### ISSUE THREAD

**Issue by fransko** [athombv/homey#1728] opened 2017-08-06 09:10 UTC
**What is your Homey version (Settings → System)?**

x.x.x

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by fransko** [comment] 2017-08-06 09:13
i must always reset my logitech app then it works wy?

**Comment by bvdbos** [comment] 2017-08-06 09:17
That's not much info you give.... I'm just guessing but are you talking about the Harmony app? Then you should better file an issue there.. And please close this one or, if you think it's about main Homey, open a new issue with the information asked (like versions etc).
https://github.com/netactivenl/com.logitech.harmony.hub

**Comment by bvdbos** [comment] 2017-08-11 05:16
@fransko Did you open an issue at the Logitech-repo?

**Comment by jeroenvollenbrock** [comment] 2017-08-15 17:40
The logitech app is not mantained by Athom. You can contact the logitech app developers through https://github.com/netactivenl/com.logitech.harmony.hub/issues if you require their support. If you believe the issue is actually caused by Homey, and not by the logitech app, please submit a new issue here with more info and answers to all questions.

**Closed by jeroenvollenbrock** 2017-08-15 17:40 UTC
