### ISSUE TITLE
Homey not able to send and receive 433MHz signals (KaKu) after rc11 update

### ISSUE THREAD

**Issue by Berna3rd** [athombv/homey#2218] opened 2018-02-10 16:10 UTC
**Metadata**

* **Homey Version**:
 1.5.6-rc.11
* **Homey Log Code**:
22DDDE4835
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:
All my 433MHz devices - wall switches, temperature sensors, sockets etc. 

**What did you try to achieve?**

Automatic update was made

**What did you expect as result?**

**What was the result?**

**Any other remarks**
If I will restart microcontroller or reboot Homey for few minutes Homey is able to receive and send 433MHz signals. 
I noticed also that flows are freezing - should be flip every minute
![image](https://user-images.githubusercontent.com/35953262/36063990-985f51f8-0e84-11e8-9c76-efe89db446a1.png)

Performed factory reset and wiped all data - no any improvement.
Installed version 1.5.3 and after 1.5.6-rc.11 - added some devices - was working fine for about 45 minutes - after that time the same issue. 
Before factory reset I pulled power plug off for 20 minutes.

**Comment by hanek004** [comment] 2018-02-10 19:17
After same update my Homey has exactly the same problem, that is: none of mij KaKu and Action-devices are working.

**Comment by bvdbos** [comment] 2018-02-11 06:57
For troubleshooting 433 devices it's always advisable to pull the plug for a couple of minutes.

**Comment by hanek004** [comment] 2018-02-12 10:54
This is the same issue as https://github.com/athombv/homey/issues/2219

**Comment by jeroenvollenbrock** [comment] 2018-02-12 18:53
Duplicate of #2219 and probably caused by the fix for #2075. The fix for #2075 was a revert of a change to pre-1.5.6 behavior. Can you confirm you also encountered this problem before 1.5.6?

**Comment by Berna3rd** [comment] 2018-02-12 19:33
I have Homey for 2 weeks now and I ran it only on 1.5.6-rc.8 and was working fine. #2075 is only about receiving from weather sensors but my case is that Homey is  also not sending signals to units / I cannot switch on&off any unit. Now I installed 1.5.3 and KaKu works again but Z-Wave not.

**Comment by bvdbos** [comment] 2018-02-12 20:45
Yes, that's a known issue. Reverting from 1.5.6rc to 1.5.3 stable loses the zwave-capabilities because the zwave-chipp got an own firmware-update when going to 1.5.6. It's expected that 1.5.6 stable will be released really soon so you might have t wait a few days. So you confirmed it worked pre-1.5.6....

**Comment by jeroenvollenbrock** [comment] 2018-02-12 20:51
Actually, the zwave functionality can be restored on 1.5.3. Please send an email to support@athom.com to request this. In order to restore zwave functionality, the support staff will require an invitation to your homey (settings->users->invite, support@athom.com), and your homey ID (settings->system->cloud ID)

**Comment by Berna3rd** [comment] 2018-02-12 20:56
Yes I confirm that it worked on 1.5.6-rc8
I know about Z wave issue - I will wait for stable 1.5.6

**Comment by OskarBrink** [comment] 2018-02-12 23:00
I still have the same issue with KAKU, also after update from rc11 to rc.13. 
It works for 2-3 times a device on/off and after than it just stops.
PTP does not help either.

**Comment by hanek004** [comment] 2018-02-13 14:42
I can confirm my KaKu- and Action-devices (as mentioned by me in duplicate issue https://github.com/athombv/homey/issues/2219) were working well in the updates before rc11. My Homey has been updated with each new rc. Therefore I conclude it was working well with 1.5.6-rc8 (the devices are used on a daily basis, controlling many of the lights in my living room, hence I surely would have noticed, were they were malfunctioning because of a previous update).

**Comment by nilsaw11** [comment] 2018-02-15 18:34
My Homey starts working again with KAKU.

After a clean install to stable release and a fix for de z-wave problem(via Athom) that's came by downgrading) i was first **not** able to get it working again.

now i found a solution for my KAKU apa3-1500r's problem
i have clear the memory  from de kaku devices end than i whas abled te pair again with homey.

now it's working again as it should be ;-)

**Comment by OskarBrink** [comment] 2018-02-16 21:00
Thanks for the change in version.
all back to normal again

**Closed** 2018-02-26 13:53 UTC
