### ISSUE TITLE
Flow duplicate or save give message only 1 trigger

### ISSUE THREAD

**Issue by robiebab** [athombv/homey#1475] opened 2017-04-16 07:24 UTC
**What is your Homey version (Settings → System)?**

1.2.0

**What did you try to achieve?**

It is hard for me to reproduce; sometimes if i work on the flow it suddenly gives me this error and i can't save or duplicate until i change the trigger and save

**What was the result?**
can't save or duplicate
...

**What did you expect as result?**
i can save or [duplicate](url
<img width="1170" alt="schermafbeelding 2017-04-16 om 09 18 29" src="https://cloud.githubusercontent.com/assets/18186327/25069608/8694114c-2286-11e7-9a68-92084d6e671a.png">
)
...

**Any other remarks**

...

**Comment by Dijker** [comment] 2017-04-16 08:03
Duplicate of #1097 will probably be fixed in 1.3.0

**Comment by jeroenvollenbrock** [comment] 2017-04-24 11:53
Closing as duplicate of #1097

**Closed by jeroenvollenbrock** 2017-04-24 11:53 UTC
