### ISSUE TITLE
Cannot rename a Zone in Homey

### ISSUE THREAD

**Issue by mveck** [athombv/homey#2251] opened 2018-02-20 19:46 UTC
**Metadata**

* **Homey Version**: 1.5.6
* **Homey Log Code**: 
* **Smartphone Platform**: PC Windows 10
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Homey Desktop

**What did you try to achieve?**

When running Homey Desktop, added zones... Zones are named "Nieuwe Zone".
Click on Zone name to rename to a usefull name
Then view/Reload.... zone is again named "Nieuwe Zone".

**What did you expect as result?**

I expected that zones after renaming get a new name, and this is persistently stored on Homey.

**What was the result?**

Zone rename is undone after refreshing screen (and/or) when stopping restarting Homey Desktop.

**Any other remarks**
Installation of Homey Desktop did not run as expected. Installation errors.. see log... 
[SquirrelSetup.log](https://github.com/athombv/homey/files/1741622/SquirrelSetup.log)

**Comment by Dijker** [comment] 2018-02-20 20:25
Duplicate #2239

**Comment by jeroenvollenbrock** [comment] 2018-02-21 16:19
Closing as duplicate of #2239 which is resolved in 1.5.7

**Closed by jeroenvollenbrock** 2018-02-21 16:19 UTC
