### ISSUE TITLE
Homey hangs after voice command

### ISSUE THREAD

**Issue by OskarBrink** [athombv/homey#686] opened 2016-06-12 12:10 UTC
**What is your Homey version: 
0.8.38

**What did you try to achieve? 
Voice command: "Wat is de demperatuur?"

*Please include detailed steps how we can reproduce the issue*
With this specific command I see the ring go solid white and homey hangs

**What was the result?**
System hang
...

**What did you expect as result?**
Feedback on the temperature, from my fibar sensor, being the only temperature sensor active.
...

**Any other remarks**
no
...

**Comment by jghaanstra** [comment] 2016-06-12 20:36
Seems to be a duplicate of https://github.com/athombv/homey/issues/684

**Comment by OskarBrink** [comment] 2016-06-12 21:35
It does not look like it. 
I have no loss of connectivity and have been able to recreate this behavior several times now. Actually so far only with the specific command mentioned above.

**Comment by jeroenvollenbrock** [comment] 2016-08-18 12:54
Fixed in 0.9.3

**Comment by jeroenvollenbrock** [comment] 2016-09-02 10:27
Can you please let me know whether this issue persists or not?

**Closed** 2016-09-14 15:59 UTC
Labels: bug, Homey Core, Native, Staged for release
