### ISSUE TITLE
Failing export.realtime on short Device toggle delay 

### ISSUE THREAD

**Issue by freemann** [athombv/homey#832] opened 2016-08-29 11:13 UTC
**What is your Homey version (Settings → System)?**
0.9.3

**What did you try to achieve?**
My ETHRelayboard isn't reporting its status after a relay switch and only reports if a switching command is received successfully. The relays support toggling and the toggle delay can be send with a switch command. So if I switch a relay with optional toggle time, I need to sync the relay in Homey by doing a export.realtime on setTimeout with the delayed time. 
So if the relay is set to toggle with a delay of 600ms, I want to programmatically toggle the onoff capability in Homey after 600ms to keep track of the relay status.

**Please include detailed steps how we can reproduce the issue**
In the Setter of the capability add a setTimeout of 600ms with a module.export.realtime which toggles the onoff.

**What was the result?**
At timeouts <5000ms the export.realtime fails and the onoff capability isn't toggling and Homey loses track of the relay status.

**What did you expect as result?**
The onoff capability toggles on the delay which was set in setTimeout.

**Any other remarks**
Tested with several timeouts and it looks like the tipping point is at 5000ms. Everything below that value is failing and above it is working.

**Comment by WeeJeWel** [comment] 2016-11-01 11:03
Yes, this is a duplicate of #788

**Closed by WeeJeWel** 2016-11-01 11:03 UTC
Labels: App-SDK, bug, Homey Core
