### ISSUE TITLE
Flow card hidden

### ISSUE THREAD

**Issue by JTThe** [athombv/homey#940] opened 2016-09-30 19:48 UTC
**What is your Homey version (Settings → System)?**

0.10.1 (0.10.3 still contains the flow)

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

I have created a flow in a lower version of Homey, which is not appearing when I look in the flow screen.
But when I create a new flow and then select a Flow Card to add in the ...and... column I still see the old Flow Card. 

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by WeeJeWel** [comment] 2016-10-03 15:19
I'm sorry, but I don't entirely get the issue. Can you maybe post screenshots to elaborate?

**Comment by JTThe** [comment] 2016-10-03 19:48
Hi Emile,

Zie de bijlages. Ik heb er nu 1 Flow in staan. En de andere Brand is zichtbaar  als selecteerbare Flow terwijl die er in het overzicht niet is.

Thanks,

Grts Jacco


________________________________
Van: Emile Nijssen <notifications@github.com>
Verzonden: maandag 3 oktober 2016 17:19
Aan: athombv/homey
CC: JTThe; Author
Onderwerp: Re: [athombv/homey] Flow card hidden (#940)


I'm sorry, but I don't entirely get the issue. Can you maybe post screenshots to elaborate?

-

**Comment by bvdbos** [comment] 2016-10-07 06:37
confirmed on the forum:
https://forum.athom.com/discussion/comment/33532/#Comment_33532

**Comment by sanderbontje** [comment] 2016-10-07 07:44
I have the same issue after updating to 0.10.3. 

To recap:
My Homey updated itself from v 0.8.x stable to 0.10.3. Unfortunately the flows created before the update are no longer visible. I tried a reboot, but they were still not there. So I recreated some of them, there were not that many.

Now both the new and the old flow are being triggered! I'm sure because the new and old flows are set up using different sounds and voice messages. They are played simultaneously.

The old flows are still there in the background, but I cannot reach them for editing or deletion. They are not visible in the new flow manager. But apparently are still there somewhere in Homey. 

The old flows are gone from the flow manager, but when I add a Flow Card to a test flow, the old and the new flows are listed in the selection panel of the card.

When I type part of a flow name in the search field of the flow manager, only the new flows are left. The old ones do not show up.

**Comment by Ikke24** [comment] 2016-10-07 17:32
same here, although I can't tell what they are called, but I get double push messages of a single action. One of the 'new'flow and 1 from a "Ghost flow". In a other flow Homey tells me the that he/ she?? will turn on the lights.

**Comment by WeeJeWel** [comment] 2016-10-10 18:04
I think they're 'lost'. They should re-appear in the next update :-)

**Comment by bvdbos** [comment] 2016-10-10 18:07
I think they should only re-appear with a name-change -> old_flowname... I think everyone recreated them already...

**Comment by jeroenvollenbrock** [comment] 2016-10-17 12:39
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.

**Comment by JTThe** [comment] 2016-10-18 08:01
Still see the old flow hidden.

**Comment by WeeJeWel** [comment] 2016-10-18 10:46
@JTThe can you invite me to your Homey please?

**Closed** 2016-10-24 14:37 UTC
Labels: Staged for release

**Comment by sanderbontje** [comment] 2016-11-03 10:34
My Homey updated to 0.10.7 stable a few days ago. I have let it reboot once more, just to be sure. I still cannot see the old flows in the top left flow manager. So I cannot remove them. They do pop up in the selection area of the 'Flow card', however. I was able to create a new flow that disables all the old flows this way. But I would really like to just delete them. If you need access to my Homey, that can be arranged!

**Comment by JTThe** [comment] 2016-11-08 19:44
Works now that 0.10.9
