### ISSUE TITLE
Milight add device gives "true" error

### ISSUE THREAD

**Issue by Nreall** [athombv/homey#477] opened 2016-04-20 10:34 UTC
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**

Add Milight devices

*Please include detailed steps how we can reproduce the issue*

Install the App, go to Devices -> Add -> Milight -> RGBW -> Error

**What was the result?**

Blank screen with title: Select the devices you want to add.

And a error screen with the text "true"

...

**What did you expect as result?**

The choise to add my Milight hub / Lights.
...

**Any other remarks**

Am i doing something wrong or is it a "real" bug? ;-)

Screenshots:

![image](https://cloud.githubusercontent.com/assets/18572509/14671729/b1336e2a-06f3-11e6-8693-ce9072a49ba6.png)
![image](https://cloud.githubusercontent.com/assets/18572509/14671825/41dcacc0-06f4-11e6-898d-cea758a08d34.png)

...

**Comment by freekwebdesign** [comment] 2016-04-21 18:43
It seems to be a "real" bug indeed. ;-)
We will try to reproduce it and get back to you a soon as we found a solution!

**Comment by Nreall** [comment] 2016-04-21 19:36
"Lucky me!" ;-)

**Comment by RobinBol** [comment] 2016-04-28 13:30
Should be fixed with next release of the Milight app, please let me know if this is not the case!

**Closed by RobinBol** 2016-04-28 13:30 UTC
