### ISSUE TITLE
Disable default built in voice commands defined by Athom

### ISSUE THREAD

**Issue by mwandzik** [athombv/homey#1489] opened 2017-04-21 08:40 UTC
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**
Defining my own logical voice commands. Without homey trying to overrule them with pre defined versions by athom.

*Please include detailed steps how we can reproduce the issue*
Make a flow which listens to "lights on" to turn on my desired lights and not all the lights.
Same goes for curtains and temperature control. I want to make homey listen to my own logical spoken commands and not to make illogical commands for my own speech input because of homey doing its own logical things with predefined stuff.

**What was the result?**
After i give homey the command to close my curtains homey responds with: "I have not found any curtains to close", but also executes my flow and closes my curtains.

**What did you expect as result?**
To be in control of the commands homey listens to. I don't care about the predefined commands. They are intrusive and force you to make up illogical speech commands for your own flows...

**Any other remarks**
A possibility would be a bit-flip option in settings to enable/disable the Athom speech recognition.

**Comment by bvdbos** [comment] 2017-04-21 09:13
#1259 #1048 dupes? Partly to be fixed by #142

**Comment by mwandzik** [comment] 2017-04-21 09:25
Definitely a dupe of #1048 sorry for that.

But would really like the "Disable all default triggers" option.

**Comment by jeroenvollenbrock** [comment] 2017-04-24 11:42
Closing as duplicate of #1048

**Closed by jeroenvollenbrock** 2017-04-24 11:42 UTC

**Comment by rogierhofboer** [comment] 2017-11-28 14:34
Please reopen this issue  #1048 is a more advanced solution. This is about just disabling all built-in speech flows
