### ISSUE TITLE
433 Mhz Crasht not send/Receive any signal (On Homey 1.5.6)

### ISSUE THREAD

**Issue by CliffBroeren** [athombv/homey#2261] opened 2018-02-24 19:35 UTC
**Metadata**

* **Homey Version**:            1.5.6
* **Homey Log Code**:      1ADBEEB945 Before Restart Microcontroller 
                                             1329EAD450 After Restart Microcontroller

**What did you try to achieve?**

I pushed a Kaku WallRemote, and homey did nothing 
I Switch a light (kaku) on with homey  And the light stays off

After restart Micro controller 433Mhz works fine again,

It's now the 3th Time since 1.5.6 

**What did you expect as result?**

That homey  sends and receive 433mhz signals

**What was the result?**

Nothing happend

**Any other remarks**

**Comment by CliffBroeren** [comment] 2018-02-24 19:37
Above is the 3th time Crash.

This is the log of the 2nd Crash Before Restating microcontroller LOG: 2336DB01FF

**Comment by jeroenvollenbrock** [comment] 2018-02-26 13:48
Closing as duplicate of #2023

**Closed by jeroenvollenbrock** 2018-02-26 13:48 UTC
