### ISSUE TITLE
App background changes back to default 

### ISSUE THREAD

**Issue by timk1990** [athombv/homey#1420] opened 2017-03-26 07:20 UTC
**What is your Homey version (Settings → System)?**

1.2.0rc9 Andriod app 2.3.2 build 68

**What did you try to achieve?**
 When i first start the app the chosen background loaden and displayed. When i send the app to the background and than reopen it again it changes back to default 

**What was the result?**

No chosen background 

**What did you expect as result?**

...

**Any other remarks**
LG g4 Andriod version 6.0 kernel 3.10.84

**Comment by bvdbos** [comment] 2017-03-26 07:35
? Works for me, do you have more info?

**Comment by timk1990** [comment] 2017-03-26 07:48
Very strange! Filled in the form... Will update it!

**Comment by Dijker** [comment] 2017-03-26 09:03
Correct, issue confirmed!
same app versions here and on  an Samsung Galaxy Tab I have the same.  Even when pushing the button to switch apps and immediately switching back to the Homey app the  old default background loads. 
Switching Homey again loads the users preferred  background.

**Comment by jeroenvollenbrock** [comment] 2017-03-29 15:09
This issue has been resolved in 2.3.3

**Closed by jeroenvollenbrock** 2017-03-29 15:09 UTC
Labels: bug, smartphone
