### ISSUE TITLE
Date and time are wrong

### ISSUE THREAD

**Issue by HomeyRichy** [athombv/homey#1866] opened 2017-10-08 18:49 UTC
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**
Correct date and time.
Date and time on Homey incorrect.

*Please include detailed steps how we can reproduce the issue*
After an auto update to 1.5.3 date and time wrong, around 18-09-2017.
Softreset helped.
Yesterday after some powerlosses: same problem raised again.
Switchíng to manual location and back to auto location didnt help.

**What was the result?**
Right date/time then: 8-10-2017, 15:10
Homey date/time: 18-9-2017, 13:54
Again around the same date.

Now: 8-10-2017 20:47

Homey:
date | 2017-09-18T17:29:44.509Z
date_dst | true
date_human maandag 18de september 2017 19:30:39

**What did you expect as result?**
Right date and time

**Any other remarks**
Softreset helped last time. Not executed yet this time.

**Please attach a Homey System log (Settings -> System -> Send Log)**
70956B376A

**Comment by HomeyRichy** [comment] 2017-10-08 19:03
Did a restart again through the System-> Restart button. Result:

date | 2017-09-17T12:36:21.825Z
date_dst | true
date_human | zondag 17de september 2017 14:36:21

Date and time now: 8-10-2017, 21:01

**Comment by bvdbos** [comment] 2017-10-08 20:46
You already know this is a dupe of #1832 so please close this one...

**Comment by HomeyRichy** [comment] 2017-10-09 07:56
Thank you for your reaction. 
True. But author of other issue sort of  finished that things work after reset. That can be taken as ending this issue, while I think it isnt solved.

If you still think I have to close it I will.
If I need to do something else, please tell me. It is new for me.


Verstuurd vanaf mijn telefoon

**Comment by jeroenvollenbrock** [comment] 2017-10-23 17:55
Closing as duplicate of #1832

**Closed by jeroenvollenbrock** 2017-10-23 17:55 UTC
