### ISSUE TITLE
Aeotec Recessed door sensor battery drain

### ISSUE THREAD

**Issue by raymondkoning** [athombv/homey#1418] opened 2017-03-25 08:53 UTC
**What is your Homey version (Settings → System)?**
Issue was not yet solved in 1.1.9 (recently my homey version is updated to 1.2.0.rc.9)

**What did you try to achieve?**
Normally the battery in the Aeotec recessed door sensor should at least last one year, but I wasted 3 batteries in about 6 months. 

*Please include detailed steps how we can reproduce the issue*
Put a battery in the Aeotec and wait 2 or 3 months to see if the battery level is dropped. 

**What was the result?**
Battery drained.

**What did you expect as result?**
Battery not draining

**Any other remarks**
I understood (from Erik van Dongen) that this issue should already be fixed in a previous version. I tested it for 2 months with a new battery, and the results can be seen in the graphic (not good). The test in done using 9 recessed door sensors. All nine showed about the same results. 

...
![image](https://cloud.githubusercontent.com/assets/26574488/24320858/93f1af92-113e-11e7-8f99-e4bbe7865402.png)

**Comment by irritanterik** [comment] 2017-03-25 08:57
Can confirm this. Aeotec Recessed Door Sensor settings are not changed after pairing.

**Comment by StraDijk** [comment] 2017-03-25 19:05
#https://github.com/athombv/homey/issues/1404

**Comment by jeroenvollenbrock** [comment] 2017-04-04 07:41
Closing as duplicate of #1404

**Closed by jeroenvollenbrock** 2017-04-04 07:41 UTC
