### ISSUE TITLE
Hue lights issues

### ISSUE THREAD

**Issue by jordenc** [athombv/homey#345] opened 2016-03-16 17:04 UTC
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**
Control the Philips Hue lights in the hallway and at my dining table by saying 'Turn all lights on', 'all lights off', 'lights on in the hallway', 'lights off in the hallway', 'turn all lights pink'

**What was the result?**
Results vary. Sometimes all lights in my living room go on or off, sometimes all but the dining table lights react.
Sometimes the hallway works and sometimes they don't. Sometimes the dining table lights work but get dimmed very low.

I have noticed that the lights that are not working well, are visible in the 'Insights' (see screenshot). I didn't do anything different to those lights, and all other lights are not visible there.
<img width="1280" alt="schermafbeelding 2016-03-16 om 17 58 21" src="https://cloud.githubusercontent.com/assets/17727803/13821285/3dc037d8-eba1-11e5-8d8a-09674f501782.png">

However, the lights in the bedroom often also don't react to the 'all lights' commands.

**Comment by Fire69** [comment] 2016-03-18 14:48
I noticed that when I open a card for a Hue light it's always grey, even when the light is on.
To have it show the correct status, I have to 'turn on the light' by clicking it.
Looks like the app doesn't poll the Hue hub.

**Comment by nattlip** [comment] 2016-03-18 15:34
this is already commented by athom a few weeks ago, no polling fir the time being.

**Comment by freemann** [comment] 2016-03-18 15:51
@nattlip;
We is that said ?

**Comment by nattlip** [comment] 2016-03-18 15:52
the assignee

**Comment by freemann** [comment] 2016-03-18 15:56
Not in this issue, so where and what did he say?

**Comment by WeeJeWel** [comment] 2016-03-18 15:57
Don't worry, I'm gonna add polling soon when I have the time.

**Comment by freemann** [comment] 2016-03-18 15:58
Thanx emile!

Though you change your mind;
https://github.com/athombv/homey/issues/10#issuecomment-170507897

**Comment by nattlip** [comment] 2016-03-18 16:00
for the googlebetics or lazy ones : https://github.com/athombv/homey/issues/179

i must say with three forums discussions homey: slack athomforum and github it is easy to lose the road (like van gaal)

**Comment by Fire69** [comment] 2016-03-18 16:56
https://github.com/athombv/homey/issues/345#issuecomment-198411607

Right, I remember reading that now...

Good thing the polling will be added.

The Hue hub is flawed imho, so polling is the only way to make it work decently.
If you would only use your Homey to control the hues there wouldn't be a problem, but that's not a real world scenario I'm afraid...

**Comment by freemann** [comment] 2016-03-18 17:18
I use my Ver3 to control my Hue's automagicly and we also use the Widgets of the official Hue app.
This combination works great and especially the Widget of the Hue app is really great KISS.

**Comment by WeeJeWel** [comment] 2016-03-25 22:34
Please try again with v0.9.10 of the Hue app.

(And closing this issue as it's a duplicate of #94 )

**Closed by WeeJeWel** 2016-03-25 22:34 UTC
