### ISSUE TITLE
[com.ikea.tradfri] Request: add supported device  TRÅDFRI afstandsbediening/remote 5 knops/button

### ISSUE THREAD

**Issue by wjay85** [athombv/homey#2126] opened 2018-01-02 20:50 UTC
* **Homey Version**:
1.5.3
* **Smartphone Platform**:
android

**What did you try to achieve?**
I tried to add  the TRÅDFRI afstandsbediening/remote 5 knops/button to homey

**What did you expect as result?**
that it would work

**What was the result?**
not working because no support yet

**Comment by bvdbos** [comment] 2018-01-02 21:00
This is an issue for the Ikea-app, already exists there:
https://github.com/athombv/com.ikea.tradfri/issues/29

**Comment by jeroenvollenbrock** [comment] 2018-01-10 16:02
Closing as duplicate of https://github.com/athombv/com.ikea.tradfri/issues/29

**Closed by jeroenvollenbrock** 2018-01-10 16:02 UTC
