### ISSUE TITLE
Controlling pre-programmed sentences

### ISSUE THREAD

**Issue by yellowmousy** [athombv/homey#1491] opened 2017-04-21 14:21 UTC
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**
**What was the result?**

Trigger: "Lights of in the living room"
My programmed output: "Lights of in the living room". Lights dim. Timer 60 sec: Lights out.
The result because of the pre-programmed sentence: "All lights off in the living room." Lights instantantly go off
My frustration: I would like some time to get out of the room and not go complete darkness.

Trigger: "I am home."
My programmed output: "Welcome home, it is <temp living room> degrees."
The result because of the pre-programmed sentence: "Welcome <My name>, good to see you again! Welcome home, it is <temp living room> degrees."
My frustration: It adds an extra sentence which can not be changed and it uses only my name, while my gf uses it as well.

**What did you expect as result?**
The ability to turn off pre-programmed sentences in the control panel. For example:
Trigger                                Status
"Lights of in room X"         on | off
"I am home"                       on | off

**Any other remarks**
I posted the request on the forum: https://forum.athom.com/discussion/3060/idea-urgent-request#latest

**Comment by yellowmousy** [comment] 2017-04-21 14:29
Sorry: Same issue: https://github.com/athombv/homey/issues/1489
The post on the forum stays the same: https://forum.athom.com/discussion/3060/idea-urgent-request#latest

**Comment by jeroenvollenbrock** [comment] 2017-04-24 11:42
Closing as duplicate of #1489

**Closed by jeroenvollenbrock** 2017-04-24 11:42 UTC
