### ISSUE TITLE
Insights not showing all updates

### ISSUE THREAD

**Issue by ewikner** [athombv/homey#1279] opened 2017-01-18 15:21 UTC
**What is your Homey version (Settings → System)?**
1.1.3

**What did you try to achieve?**
I disovered that the insight is not showing values if it is the same value as before.

In mysensors you can say that the sensor will report data every 15min.
I look in the insight to see that all sensors is reporting data, now i don't know if the sensor is dead or not.

**Comment by WeeJeWel** [comment] 2017-02-06 12:52
This is intended behavior to save disk space. I'm closing this issue for now because of that, but we might change this behavior in the future!

**Closed by WeeJeWel** 2017-02-06 12:52 UTC
