### ISSUE TITLE
Homey does not recognize negative numbers in speech

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1362] opened 2017-03-17 19:32 UTC
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**
I try to make a few flows to control TV volume by positive or negative steps.

*Please include detailed steps how we can reproduce the issue*
I say: "OK Homey... TV volume min vijf"  (dutch)

**What was the result?**

Homey speech input: "TV volume 5"

...

**What did you expect as result?**
Homey speech input: "TV volume min 5"

...

**Any other remarks**
I tried this with several negative values, but "min" is always missing

This could be related to the issue where Homey doesn't SAY minus when (decimal) negative numbers are involved, but be aware that this issue is about what Homey doesn't HEAR.

...

**Comment by Tweake** [comment] 2017-03-22 15:29
Duplicate of #1277

**Comment by OpenMindNL** [comment] 2017-03-22 15:32
Are you sure? As I said, this is about missing minus with integers... not with decimals.

**Comment by Tweake** [comment] 2017-03-22 16:55
I took another look and you're right, they are separate issues. I'll look into it

**Comment by bvdbos** [comment] 2017-04-20 05:03
works for me now : -1.9 works...

**Closed** 2017-04-20 12:45 UTC
Labels: bug, speech-input, Staged for release
