### ISSUE TITLE
Somfy sunscreens don

### ISSUE THREAD

**Issue by rogiervanwijk** [athombv/homey#737] opened 2016-07-30 21:48 UTC
**What is your Homey version (Settings → System)?**

x.x.x

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Comment by RoadXY** [comment] 2016-07-31 06:43
@jeroenvollenbrock Close?

**Comment by WeeJeWel** [comment] 2016-08-01 07:07
Duplicate of #738

**Closed by WeeJeWel** 2016-08-01 07:07 UTC
