### ISSUE TITLE
Ternary component should not assume state change

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#788] opened 2016-08-15 19:45 UTC
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

Use a Ternary component on a mobile card. The current state is nicely highlighted. When pressing another button, this button immediately gets highlighted. This assumes that the state has changed to the state of the button pressed. However, this does not have to be the case.

**What was the result?**

Pressed button was highlighted, displaying the wrong state. Closing & opening the mobile card did show the right state again.

**What did you expect as result?**

The button highlighting stays the same until the driver changes the state.

**Any other remarks**

Document states that custom icons are only supported for firmware version > 0.9.3. Is this correct? Latest version available is 0.9.2.

**Comment by jeroenvollenbrock** [comment] 2016-08-16 12:05
This is intended behavior. The card is designed this way to let the user know the action was received correctly and is being processed. Older versions of homey did not do this, which resulted in the user thinking they mis-clicked, especially on slower connections. Could you describe the situation in which this behavior is causing problems? That way we can determine if we should reconsider the current implementation.

**Comment by nlrb** [comment] 2016-08-16 12:47
I am using the component to dis-/arm an alarm system. When the user presses 'arm away' the panel can take e.g. 30 seconds to become armed. So it is not armed instantly. It can even be that the system is unable to arm, since e.g. zone is open. Furthermore, a device setting can prevent the user from dis-arming the alarm via Homey. (For the latter case it would be nice if each individual button could be made read-only).

**Comment by nlrb** [comment] 2016-08-16 19:20
What is worse, after pressing a button the component doesn't react to realtime updates anymore (for approx. 4 seconds). Realtime updates send during this period are completely ignored.

**Comment by WeeJeWel** [comment] 2016-11-01 12:05
Fixed in 0.10.8!

**Comment by WeeJeWel** [comment] 2016-11-11 21:38
I'm closing this issue as it should be fixed. If it persists, please re-open.

**Closed by WeeJeWel** 2016-11-11 21:38 UTC
Labels: Devices, enhancement, Homey Core, interface, Staged for release
