### ISSUE TITLE
Homey stops working after opening Insights settings page

### ISSUE THREAD

**Issue by robertraaijmakers** [athombv/homey#2145] opened 2018-01-08 07:07 UTC
**Metadata**
* **Homey Version**:
1.5.6-RC.7

* **Homey Log Code**:
0595A1CE8D

**What did you try to achieve?**
Open my insights settings page.

**What did you expect as result?**
The insights settings page is shown.

**What was the result?**
The settings page isn't loaded. And when switching to another page Homey is reported offline.

**Any other remarks**
I've been experiencing issues for a longer time now with Homey Insights (since version 1.5.1/1.5.3 I guess). When trying to generate graphs and retrieve data it takes an awful lot of time and often after the circles stop rotating there is no data shown. I was hoping that when I remove some data (e.g. only store the data for about a month) that my insights would start to work properly. I have to mention that storing data for only a month is absolutely not desirable, but if I have to chose between no insights at all and insights for only one month I will have to deal with the latter.

![image](https://user-images.githubusercontent.com/1773099/34661508-711eabc4-f44a-11e7-8b04-683d6279cc24.png)

![image](https://user-images.githubusercontent.com/1773099/34661755-0d097e6e-f44c-11e7-9beb-0518270b546e.png)

**Comment by bvdbos** [comment] 2018-01-08 08:07
#2110 ?

**Comment by camilleversteeg** [comment] 2018-01-08 08:07
I have the same issue.

**Comment by robertraaijmakers** [comment] 2018-01-08 08:21
Looks indeed as a duplicate of #2210. Didn't find that one when searching for insights... strange.
Installed RC.8, issue still persists.

And it does come back online (automatically) after 5 or 10 minutes, like @camilleversteeg mentions.

**Comment by jeroenvollenbrock** [comment] 2018-01-10 16:52
Closing as duplicate of #2110

**Closed by jeroenvollenbrock** 2018-01-10 16:52 UTC
