### ISSUE TITLE
[com.athom.homeyscript] When I save a script an error is generated

### ISSUE THREAD

**Issue by iOurea** [athombv/homey#2021] opened 2017-12-04 20:56 UTC
![image](https://user-images.githubusercontent.com/23391397/33575718-d8478618-d93d-11e7-9495-67278397c229.png)

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by Dijker** [comment] 2017-12-04 21:12
Is it possible the script is still running while you press Save or Save & Test again?

**Comment by iOurea** [comment] 2017-12-04 21:18
Because of this error I disabled the app. When I enable it and the save a script I get the message.
So no script is running.
I get this error since the update to 1.5.6

**Comment by Dijker** [comment] 2017-12-04 21:34
I created a small dummy script and saved it on my Homey on 1.5.6-rc.3,  but no problem here....  
Do you still have free storage (or did you fill up the 1.64 GB?) 
Guess it is up to WeeJeWel or  jeroenvollenbrock than....

**Comment by iOurea** [comment] 2017-12-04 21:46
When I create a new script and save it I don't get the message. But when I delete the script and then create a script with the same I get the old content back.

**Comment by Dijker** [comment] 2017-12-04 21:51
I think I have seen that before, Could not reproduce....
I think I also lost a script that way.

**Comment by iOurea** [comment] 2017-12-04 21:55
That is possible. When I have this, I disable the app and then enable it again, and then the scripts is available again.
For the moment I have recreated all the scripts. So now no errors

**Comment by xeor** [comment] 2018-01-22 06:33
Any more info about this? It is still a problem in the latest version.
For me, it some times deletes the scripts from the device one by one when I try to save. It is like it the first part of the save (deletion), succeeds, but the new file can't be created.
Doing a save&run sais `invalid_script`.

**Comment by jeroenvollenbrock** [comment] 2018-02-12 15:26
Should be resolved in 1.5.6-rc.13, can you confirm this?

**Comment by xeor** [comment] 2018-02-13 20:34
Cool.. This works for me now at `1.5.6-rc.13` 👍

**Closed** 2018-02-26 14:24 UTC
Labels: Homey Core, Staged for release, bug, waiting for user feedback
