### ISSUE TITLE
[com.fibaro] Describe your issue here

### ISSUE THREAD

**Issue by vantilight** [athombv/homey#2432] opened 2018-04-15 18:36 UTC
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by bvdbos** [comment] 2018-04-15 18:47
This is an empty issue ?

**Comment by jeroenvollenbrock** [comment] 2018-04-30 09:50
Closing as duplicate of #2267

**Closed by jeroenvollenbrock** 2018-04-30 09:50 UTC
