### ISSUE TITLE
Slow Memory Leak

### ISSUE THREAD

**Issue by Veldkornet** [athombv/homey#1624] opened 2017-06-12 18:01 UTC
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**

Use Homey

**What was the result?**

Slow Homey

**What did you expect as result?**

Normal Homey

**Any other remarks**

Homey is stuttering with speech and is turning on lights delayed and everything. Most notably is the speech. I originally noticed that in the mornings it was slow, so I've put in an automatic reboot every evening, although even that doesn't really help.

I think there's maybe a slow memory leak, but I can't figure out what...

**Please attach a Homey System log (Settings -> System -> Send Log)**

474D0FAF22

**Comment by Veldkornet** [comment] 2017-06-12 18:03
Before reboot:
![r40ye03go1c2](https://user-images.githubusercontent.com/10297361/27047927-119fb1ec-4faa-11e7-87fc-06aa39013166.png)

After reboot:
![r](https://user-images.githubusercontent.com/10297361/27047933-16a2965a-4faa-11e7-8b99-cf22e4092b8b.jpg)

It's not this bad every day of course, but I reboot it every night now...

**Comment by bm480** [comment] 2017-07-06 06:09
My Homey is suffering from the same kind of problems. Removing unneeded apps and deactivating apps that are not currently used and a reboot afterwards seems to improve performance a lot. About 50+ apps were installed when my Homey started to get really slow. I now have only 39 apps installed and Homey seems to perform at reasonable speed. 

However, I consider this the bare minimum because most apps are used to as drivers for devices and Homey is still warning about too many apps, e.g.: "Door het aantal geïnstalleerde apps (39), kan Homey langzamer worden of niet meer reageren." I'm worried that as Homey's core is getting more functionality less memory for apps remains. Improved memory management is of utter importance.

**Comment by jeroenvollenbrock** [comment] 2017-07-12 15:36
Duplicate of  #1195

**Closed by jeroenvollenbrock** 2017-07-12 15:36 UTC
