### ISSUE TITLE
No kaku doorbell in insights

### ISSUE THREAD

**Issue by posthok** [athombv/homey#558] opened 2016-05-02 10:36 UTC
**What is your Homey version (Settings → System)?**

0.8.29

**What did you try to achieve?**
kaku doorbel tracking in homey insights

*Please include detailed steps how we can reproduce the issue*
there's no tracking of doorbell, only light devices are shown.

**Comment by Dennishacq** [comment] 2016-06-10 17:19
Duplicate of #676

**Closed by Dennishacq** 2016-06-10 17:19 UTC
