### ISSUE TITLE
 module.exports.realtime seems broken

### ISSUE THREAD

**Issue by PatrickSannes** [athombv/homey#1155] opened 2016-12-12 22:44 UTC
Since one of the last updates this action does not work anymore

 module.exports.realtime(changedVariable.name, 'onoff', changedVariable.value);

This worked before, but does not seem to do anything currently. Tested the code path and the log line just before it is triggered.
```
'
`"use strict";
var util = require('../../lib/util/util.js');
var variableManager = require('../../lib/variablemanagement/variablemanagement.js');

var devices = [];

var self = module.exports =  {
    init: function(devices_data, callback) {
        Homey.log(devices_data);
        for (var x = 0; x < devices_data.length; x++) {
            devices.push(devices_data[x]);
        }

        Homey.manager('settings').on('set', function (action) {
            if (action == 'boolValueChanged') {
                var changedVariable = Homey.manager("settings").get('boolValueChanged');
                Homey.log(changedVariable);
                if (changedVariable.type == 'boolean') {
                    Homey.log('+++++++');
                    Homey.log(changedVariable);
                    module.exports.realtime(changedVariable.name, 'onoff', changedVariable.value);
                }
            }
        });
       
        callback();
    },
    capabilities: {
        onoff: {
            get: function (device_data, callback) {
                var variable = variableManager.getVariable(device_data.id);
                if (variable) {
                    callback(null, variable.value);
                    return;
                }
                callback(null, false);
            },
            set: function (device_data, onoff, callback) {
                var variable = variableManager.getVariable(device_data.id);
                if (variable) {
                    variableManager.updateVariable(device_data.id, onoff, device_data.type);
                 
                    self.realtime(device_data, 'onoff', onoff);
                    callback(null, onoff);
                    return;
                } else {
                    callback(null, false);
                }
            }
        }
    },
    pair : function(socket) {
        
        socket.on('list_devices', function (data, callback) {
            Homey.log('list devices');
            var vars = variableManager.getVariables();
            Homey.log(vars);
            var bools = variableManager.getVariables().filter(util.findVariable('', 'boolean'));

            var devices = [];

            bools.forEach(function (variable) {
                Homey.log(variable);
                var device = {
                        name: variable.name,
                        state: {onoff : variable.value
                    },
                    data: {
                        id: variable.name,
                        type: variable.type,
                        value: variable.value
                    }
                }
                devices.push(device);

            });
            Homey.log(devices);
            callback(null, devices);

        });
        socket.on("add_device", function(device, callback) {

            Homey.log('add device');

            // Store device globally
            devices.push(device);

        });
    }
}




`

```

**Comment by RobinBol** [comment] 2016-12-13 13:49
You could try to add a callback as fourth parameter to check whether it throws an error. Based on that you should be likely to deduce the cause of your issue.

**Comment by PatrickSannes** [comment] 2016-12-13 13:54
like this?
  module.exports.realtime(changedVariable.name, 'onoff',
changedVariable.value, function(err) {
                        Homey.log(err);
                    });

(that does not seem to work)

**Comment by RobinBol** [comment] 2016-12-13 14:28
```
module.exports.realtime(devicesData[0], 'target_temperature', 20, function (err, result) {
	console.log('realtime callback', err, result);
});
```
The above result in --> 'realtime callback null undefined'.

But you need to use the device_data object as first parameter, I am not sure what is in your `changedVariable.name` but my guess is that is the issue.

**Comment by PatrickSannes** [comment] 2016-12-13 14:33
This used to work a few updates ago. The changedVariable.name is the name I
gave to the device. So I guess it used to lookup by device name, but it
seems to not do that anymore.

**Comment by PatrickSannes** [comment] 2016-12-13 14:35
Correction, it is the Id I gave to the device.

**Comment by RobinBol** [comment] 2016-12-13 14:37
I think it is already quite some versions back that this used to work, but now the whole device data object is necessary. Will close this issue, as it doesn't seem to be a bug of any sorts.

**Closed by RobinBol** 2016-12-13 14:37 UTC
