### ISSUE TITLE
Connect with other Homey

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#2919] opened 2018-11-18 19:59 UTC
As my parents are using a Homey as well, it would be great to have a flow card at my own Homey to switch the gate at their house instead of me switching between my and theire Homey in the user app.

**Comment by KyleAthom** [comment] 2018-12-05 06:21
Hi @Arjanvde ,

You might be able to create this with HTTP request or API calls between the Homeys. You can check the forum for some inspiration: https://community.athom.com/

Since this is not a bug or a issue with Homey I'm closing this issue.

**Closed by KyleAthom** 2018-12-05 06:21 UTC
