### ISSUE TITLE
Homey presence not working on iOS11

### ISSUE THREAD

**Issue by Rido** [athombv/homey#1683] opened 2017-07-08 14:56 UTC
**What is your Homey version (Settings → System)?**
1.3.2

**What did you try to achieve?**
Trigger flows when arriving & leaving home.

Flow I use for testing:
![image](https://user-images.githubusercontent.com/1889864/27986352-7e0a17b0-63fe-11e7-89dc-956993d97f9f.png)

**What was the result?**
The flows weren't triggered.

**What did you expect as result?**
Presence detection to trigger the flows.

**Any other remarks**
Last week I received a new iPhone because the previous one had some hardware issues. After I installed this one the Homey presence detection isn't working anymore.
One thing that I noticed is a double presence tag:
![image](https://user-images.githubusercontent.com/1889864/27986294-d95790a8-63fd-11e7-9d7e-7ce6df0f4598.png)

I did set a custom location in Homey and I set the homeradius in the iOS app on 200m.

**Please attach a Homey System log (Settings -> System -> Send Log)**
89B8EE7205

**Comment by Dijker** [comment] 2017-07-08 15:12
I don't have an IOS device, but I guess this is the same as on Android: 
Did you remove the old phone from your My Athom account?

https://my.athom.com/#/phones

and check and update your flows, maybe they try to msg the old mobile. If you configured the mobile app correct it should work.

**Comment by Rido** [comment] 2017-07-08 15:15
@Dijker Thanks for the reply.

I did remove the phone from the phones list. Currently there's only one phone on it:
![image](https://user-images.githubusercontent.com/1889864/27986565-dcf160ce-6400-11e7-9cd8-5e9932b680b5.png)

And the flows will trigger on anyone coming or leaving home and not one specific person so I guess that won't be a problem as well.

**Comment by jeroenvollenbrock** [comment] 2017-07-12 15:53
Does disabling and enabling the home detection setting, or changing its range in the app resolve this issue?

**Comment by Rido** [comment] 2017-07-12 17:10
No 🙁 I tried it multiple times but that doesn't resolve the issue.

**Comment by chrisboer** [comment] 2017-07-12 20:37
start using owntracks this works really good and you can setup multiple perimiters/geofences which you can trigger within Homey owntracks app. 
You can use a public MQTT server or create a private Mosquitto Server on your NAS.

**Comment by Rido** [comment] 2017-07-15 10:18
@chrisboer, I tried to use the Owntracks app but that one isn't working as well. It registers the users but the public geofences won't come through.

The Homey presence worked great before so I hoped that Athom could help me with this problem.

**Comment by swttt** [comment] 2017-07-15 10:33
@Rido 
Seen the developer of ownTracks working on a version that doesn't need a broker anymore 😀

Might be worth a shot ;)

**Comment by gldrenthe89** [comment] 2017-08-17 07:53
I have the same problem on 1.5rc5
Double presence tags and no working location

**Comment by jeroenvollenbrock** [comment] 2017-08-18 12:36
As a sidenote, presence detection using the smartphone app on iOS 11 is broken, we are working on a smartphone app update to resolve this.

**Comment by Rido** [comment] 2017-08-18 12:44
@jeroenvollenbrock great! I'm using iOS 11 so I guess that's the reason for the problem 😉

**Comment by jeroenvollenbrock** [comment] 2017-08-18 13:15
I'm hoping to submit a build to Apple App review next week. I'll get back to you once we have a beta version available.

**Comment by Swiftnesses** [comment] 2017-08-19 19:10
@Rido, had this for a while too (need iOS 11 on my phone sadly for dev builds). Jeroen will fix it I'm sure :)

**Comment by jeroenvollenbrock** [comment] 2017-08-23 14:22
A new version has been submitted to apple for review.

**Comment by gldrenthe89** [comment] 2017-09-18 16:45
After installing via TestFlight it stil isn't working at all. Please fix ASAP!

**Comment by chrisboer** [comment] 2017-09-18 16:57
Also still not working in IOS 10 so I don't see a new problem still the same

**Comment by pietpiet50** [comment] 2017-09-18 18:56
hope to see a fix or program update for the presence. It's about a month ago now, and ios 11 is released (gm) , and the new app is maybe at xmas time.  It's dark inside my house when i arrive.
Testflight is also possible for me.

**Comment by gldrenthe89** [comment] 2017-09-18 19:00
It worked for me perfactly on iOS10. after updating to iOS11 not anymore. Even with the version i got in testflight the problem is stil there. Please fix this ASAP

**Comment by Peerlkamp** [comment] 2017-09-20 17:31
Same problem here. Worked fine in IOS10, but after IOS11 the presence detection does not work anymore . Can you please fix this, because presence is very important for home automation.

**Comment by jeroenvollenbrock** [comment] 2017-09-21 07:36
Fixed in smartphone app 1.3.3#70, which is available through the regular app store since yesterday.

**Closed** 2017-09-21 17:08 UTC
Labels: bug, smartphone
