### ISSUE TITLE
[setup] Typo in dutch

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#1216] opened 2017-01-01 21:44 UTC
Typo: "your Mac" must be "uw/jouw mac"
<img width="730" alt="schermafbeelding 2017-01-01 om 22 36 56" src="https://cloud.githubusercontent.com/assets/13370203/21583131/284b1794-d073-11e6-8b0a-4a755acdc486.png">

Same typo (I hide my network name)
<img width="906" alt="schermafbeelding 2017-01-01 om 22 34 27" src="https://cloud.githubusercontent.com/assets/13370203/21583152/db13946e-d073-11e6-9f5a-650a07f96991.png">

Consideration:  coffee at 22:39?
<img width="925" alt="schermafbeelding 2017-01-01 om 22 39 56" src="https://cloud.githubusercontent.com/assets/13370203/21583140/45284d6e-d073-11e6-83ed-9f54c7d73ad1.png">

**Comment by caseda** [comment] 2017-01-01 21:55
Device calling is still English for all devices, setup on Android also states "your Android device" on Dutch. 
And last time I did it on Windows, it was the same with "Windows device" on Dutch

**Comment by WeeJeWel** [comment] 2017-01-02 11:46
Thanks for reporting! I'm closing however as this is a duplicate of #1083

**Closed by WeeJeWel** 2017-01-02 11:46 UTC
