### ISSUE TITLE
[com.aeotec] include falls at “Setting default association groups”, or times out

### ISSUE THREAD

**Issue by ks2018ks** [athombv/homey#2396] opened 2018-04-02 19:14 UTC
**Metadata**
? what does this mean?
* **Homey Version**: 1.5.8
* **Homey Log Code**: What does this mean?
* **Smartphone Platform**: Do you mean OS?  If so, Android
* **Smartphone App Version**: Don't know - my issue is not related to the smartphone app

**If related to a Homey App:**
* **Homey App Version**:  Do you mean desktop app? If so, 1.04
* **Homey App Log Code**:  Don't know what this means
* **Affected Devices (preferably product codes)**:MultiSensor 6

**What did you try to achieve?**
Include device

Click +, then Aeotec, then Multisensor 6

**What did you expect as result?**

Device to be added

**What was the result?**

Falls over/fails/times out, either at:
“Setting default association groups”, or "“vdevice.drivers.zwavebasic.pair.senddata_timeout”

**Any other remarks**
 “No Z-Wave device has been found.”
 Try to add it again.  “This device is already paired. Try removing it first through Settings -> Z-Wave.”.  Already paired but apparently not listed anywhere.  Go to settings > Z-Wave.  Blank page.  Quit & Restart desktop app.  Try again.  Same over and over.

**Comment by bvdbos** [comment] 2018-04-02 20:26
When creating the bug-report it stated:
_
The Homey log code can be generated at Settings -> System -> Send Log.
The Homey App log code can be generated at Settings -> Apps (hold ALT to show the 'Send Log' link).
_
You'd better drop the desktop-app (but not related to this bug) and use chrome-browser. After deleting the device from Homey, did you hardware-reset the device (look in the manual)?

**Comment by ks2018ks** [comment] 2018-04-02 21:17
​Thanks for your quick reply.
​
*You'd better drop the desktop-app (but not related to this bug) and use
chrome-browser.*

If I try to use Chrome it says "Browsers are not supported. Please use the
Homey Desktop App".


* After deleting the device from Homey, did you hardware-reset the device
(look in the manual)? *
Yes: Held Action button. LED turns into a Green then released.


I missed the explanation about the logs
​The System Log code is
: 074956DCFB

​I don't understand this:
*The Homey App log code can be generated at Settings -> Apps (hold ALT to
show the 'Send Log' link).*​

​I go to Settings > Apps then hold Alt on my keyboard but don't see any
link ​






ᐧ

**Comment by ks2018ks** [comment] 2018-04-02 21:20
OK, I found it doesn't like Apple keyboard on windows PC.  I used another
keyboard and got the log code for
Aeotec  a7610aa1-c1e4-4ddd-a299-7b267f1907e4
ᐧ

**Comment by ks2018ks** [comment] 2018-04-02 22:51
Removed

**Comment by cbho** [comment] 2018-04-03 09:39
Seems like the same behaviour as described in #2333

**Comment by ks2018ks** [comment] 2018-04-03 09:44
> Seems like the same behaviour as described in #2333

Possibly - was it solved?

**Comment by cbho** [comment] 2018-04-03 09:44
Then the issue would have been closed.

**Comment by jeroenvollenbrock** [comment] 2018-04-03 09:56
Closing as duplicate of #2333

**Closed by jeroenvollenbrock** 2018-04-03 09:56 UTC

**Comment by ks2018ks** [comment] 2018-04-03 09:57
Are you sure it's the same?

**Comment by ks2018ks** [comment] 2018-04-03 11:29
For Aeotec Multisensor 6 it was solved with a firmware update from v1.07 to version 1.11
