### ISSUE TITLE
APPV2 Toon screen is empty

### ISSUE THREAD

**Issue by laurenssss** [athombv/homey#1902] opened 2017-10-19 08:44 UTC
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**
TOON screen is empty

![fullsizeoutput_e0b](https://user-images.githubusercontent.com/17315800/31762101-76b87724-b4ba-11e7-8f9f-093ffe356d34.jpeg)

**Comment by WeeJeWel** [comment] 2017-11-20 16:37
I cannot reproduce this issue, so I assume it's fixed in a recent release.

![screen shot 2017-11-20 at 17 37 03](https://user-images.githubusercontent.com/319873/33029645-722c417c-ce19-11e7-8493-b1deab277d10.png)

**Closed by WeeJeWel** 2017-11-20 16:37 UTC
Labels: bug, Homey Smartphone App (UI)
