### ISSUE TITLE
Z-Wave many timeout and ack errors

### ISSUE THREAD

**Issue by Sillec123** [athombv/homey#1668] opened 2017-06-28 19:52 UTC
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**
Reset the complete Z-Wave Network, exclude and include all z-wave devices after that.

*Please include detailed steps how we can reproduce the issue*

3x NEO Switches, 3x Fibaro Motion Sensors, 3x Fibaro Sensors, 2x Aeotec Smart Switch V2

**What was the result?**
Same issue like before.

The first timeout comes with the first devices. (Aeotec & FIbaro Motion Sensors)

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

Log Key:
210B7D42D8

[2017-06-28T19:42:01.670Z] ProcessSendData[138]: Error: senddata_timeout
[2017-06-28T19:42:03.726Z] ProcessSendData[139]: Error: senddata_timeout
[2017-06-28T19:42:05.955Z] ProcessSendData[137]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:42:06.147Z] ProcessSendData[136]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:42:06.323Z] ProcessSendData[135]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:42:06.429Z] ProcessSendData[134]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:42:06.607Z] ProcessSendData[133]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:42:06.786Z] ProcessSendData[132]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:45:38.531Z] ProcessSendData[151]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:45:38.729Z] ProcessSendData[153]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:45:38.907Z] ProcessSendData[154]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:45:39.117Z] ProcessSendData[152]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:45:42.028Z] ProcessSendData[155]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:46:21.338Z] ProcessSendData[156]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:46:21.497Z] ProcessSendData[159]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:46:21.627Z] ProcessSendData[158]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:46:21.787Z] ProcessSendData[157]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:46:39.722Z] ProcessSendData[160]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:46:39.897Z] ProcessSendData[163]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:46:40.057Z] ProcessSendData[162]: Error: TRANSMIT_COMPLETE_NO_ACK
[2017-06-28T19:46:40.177Z] ProcessSendData[161]: Error: TRANSMIT_COMPLETE_NO_ACK

**Comment by jeroenvollenbrock** [comment] 2017-07-12 15:46
TRANSMIT_COMPLETE_NO_ACK means the device did not respond to Homey, so this is most likely a device issue. It is also possible that there is a high amount of Z-Wave traffic in the air, causing too much noise to reliably communicate. Do you happen to have a very short reporting interval set?

**Comment by Sillec123** [comment] 2017-07-17 19:29
All devices are using the default Settings.

**Comment by bvdbos** [comment] 2017-08-15 18:03
#1715 dupe?

**Comment by WeeJeWel** [comment] 2017-11-02 14:39
Duplicate of #1899

**Closed by WeeJeWel** 2017-11-02 14:39 UTC
Labels: bug, Z-Wave
