### ISSUE TITLE
Infrared remotes not working (won't send signal)

### ISSUE THREAD

**Issue by alvarosanchez** [athombv/homey#1805] opened 2017-09-05 22:16 UTC
**What is your Homey version (Settings → System)?**

1.5.1

**What did you try to achieve?**

I have tried to add remotes as infrared devices. Tried with a home cinema and an AC. As they don't show up as known devices, I used the "Copy from remote" feature. Every time I press a button, the animation does move, so somehow the signal is received.

**What was the result?**

When using them in a flow then card (using a virtual device as trigger), nothing happens. Tried with both "Push a button" and "Repeatedly push a button" actions.

**What did you expect as result?**

Infrared signals are sent.

**Any other remarks**

How far should be Homey from the IR sensor of the device? The home cinema is underneath a table, and Homey is above it. The AC unit is in the wall, ~2 metres away.

Do Homey and IR devices have to be in line of sight of each other?

**Please attach a Homey System log (Settings -> System -> Send Log)**

563492831A

**Comment by bvdbos** [comment] 2017-09-06 04:31
IR needs a line of sights but it might bounce back from walls. You can check if IR sending works through your phone: https://forum.athom.com/discussion/2497/homey-doesnt-seem-to-send-any-infrared-signal

**Comment by Kingster2** [comment] 2017-09-06 14:09
I still have the same problem, even in line of sight. Learning IR doesn't work well (sometimes it works but most times not (interference of other lightsources can be a problem). Please make a test and edit option when learning a IR button. Now it's only possible to test in a flow.

**Comment by bvdbos** [comment] 2017-09-06 14:14
Test is bug #1759 and edit is bug #267.

**Comment by Kingster2** [comment] 2017-09-06 14:23
Yes, we are waiting for a long time for resolving these issues. Until then IR learning is a pain / non functional. Please be honest about this so we don't have to spend hours not knowing if we're doing something wrong ourselfs. More information about this issue would be very helpfull.

**Comment by Inversion-NL** [comment] 2017-09-06 17:33
You do know that @bvdbos is, just like u and me, an enthusiast trying to help and not an Athom employee?

**Comment by jeroenvollenbrock** [comment] 2017-09-11 11:36
Closed as duplicate of #1759 and #267

**Closed by jeroenvollenbrock** 2017-09-11 11:36 UTC
