### ISSUE TITLE
[nl.klikaanklikuit] none of my Telldus wall plugs works after the update

### ISSUE THREAD

**Issue by BusterKrabba** [athombv/homey#2724] opened 2018-08-01 06:52 UTC
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**:2A6C353AE3
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**Klikaanklikuit
* **Homey App Version**:4 0 2
* **Homey App Log Code**:89eab558-01eb-4cf4-820f-54e81cf7374e
* **Affected Devices (preferably product codes)**:Telldus Wall plugs (outlets) 312537 433 MHz (KlikAanKlikUit device ACD3500)  

**What did you try to achieve?**

The devices do no longer work in flows after update to The 4 0 2 version. The direct control of the devices do however work.

**What did you expect as result?**

see above

**What was the result?** see above

**Any other remarks**

**Comment by BusterKrabba** [comment] 2018-08-01 07:07
The plugs do neither work within the app Device groups

**Comment by KyleAthom** [comment] 2018-08-01 08:52
Can you please try to remove the powerplug from Homey for a short time (e.g. 10 seconds) and then try if the devices respond correctly again?

**Comment by BusterKrabba** [comment] 2018-08-01 09:07
No, unfortunately it did not help.  Discovered after my notification that one out of six devices was not affected, one that is placed farest away from my Homey

Från: Kyle <notifications@github.com>
Svara till: athombv/homey <reply@reply.github.com>
Datum: onsdag 1 augusti 2018 10:52
Till: athombv/homey <homey@noreply.github.com>
Kopia: Peter Svenburg <peter@svenburg.se>, Author <author@noreply.github.com>
Ämne: Re: [athombv/homey] [nl.klikaanklikuit] Describe your issue here (#2724)


Can you please try to remove the powerplug from Homey for a short time (e.g. 10 seconds) and then try if the devices respond correctly again?

**Comment by BusterKrabba** [comment] 2018-08-01 09:08
No, unfortunately it did not help.  Discovered after my notification that one out of six devices was not affected, one that is placed farest away from my Homey

**Comment by KyleAthom** [comment] 2018-08-01 09:12
Alright, are your devices also displaying the error mentioned in https://github.com/athombv/homey/issues/2722 ?
Or are they just not responding?

**Comment by BusterKrabba** [comment] 2018-08-01 09:17
no error message. just not responding in flows. as mentioned earlier, direct control on device level works

**Comment by KyleAthom** [comment] 2018-08-01 09:19
How many of those plugs have you paired with Homey?

**Comment by KyleAthom** [comment] 2018-08-01 09:24
Which type did you use for the Nexa plugs? The same as for the Telldus?

**Comment by BusterKrabba** [comment] 2018-08-01 09:29
yes the same. for both makes the pairing was done by copying a remote signal

**Comment by KyleAthom** [comment] 2018-08-01 09:32
Ah, that might be related. I assume you used a different remote for the Nexa?

**Comment by BusterKrabba** [comment] 2018-08-01 09:34
yes, the nexa remote for the nexa devices and the telldus remote for the Telldus devices

**Comment by BusterKrabba** [comment] 2018-08-01 09:37
...but please not that direct controlling works. The problems are just related to flows

**Comment by cbho** [comment] 2018-08-01 09:40
Pls remember you chat is relayed to all subscribers on this channel (athombv/homey)...

**Comment by BusterKrabba** [comment] 2018-08-01 09:46
I have no problems with that :-)

**Comment by BusterKrabba** [comment] 2018-08-01 16:46
I removed two of the "obstructing" Telldus wall plugs and paired them again, now using the APA3-1500R driver with IR signal copying and inserted them in my concerned flows. And they work !!
Hoping for a fix so I and the rest of the concerned Homey user community do not have to go through a process of deleting/repairing and subsequent flow changes

**Comment by BusterKrabba** [comment] 2018-08-03 07:52
I was to optimistic. Initially, it seemed that the two rapaired plugs works again after the repairing. Now I have however noticed that they function very irregularly. Sometimes they are not started by the flow and sometimes they turn on without any flow! I have now also got the error message in my iPhone homey app "invalid_device_data" on one of the plugs that did not obstruct earlier.
The Klikaanklikuit app is a very central one for many Homey users. The launching of a new version causing these kind of problems puts Athos´ reputation at serious stake!!

**Comment by KyleAthom** [comment] 2018-08-03 08:11
Which device throwed the error? One that you re-paired?
Also, there is a dedicated Telldus app coming, as using KlikaanKlikuit devices for other brands and types is unsupported.

**Comment by djeskoswe** [comment] 2018-08-03 08:37
its easy to say that this app is only klikaanklikuit but a lot of homes uses nexa etc that did work before...

**Comment by KyleAthom** [comment] 2018-08-03 15:08
We have worked the whole day trying to figure it out, but it's hasn't been easy. We tried with a lot off different sockets and even combined all of them to test the flows, but in all our scenario's we have not been able to reproduce the issue that the sockets are not responding.

Nevertheless, we have made some small changes and a new beta version with a few potential fixes has been deployed (v4.0.3).
If you are using devices from Telldus, we suggest you to use the new Telldus app instead, which now has been published as a beta app in the app store.
If you report bugs or issues, please report them very detailed because we cannot reproduce any of the problems stated.

**Comment by BusterKrabba** [comment] 2018-08-04 08:45
Appreciate the Telldus app. Works fine so far!

**Comment by KyleAthom** [comment] 2018-08-06 12:32
I'm closing this issue since we now have the Telldus app to use with that devices. If you experience issues with that app or if you experience further issues with the KlikaanKlikuit app, please create a new issue for them.

**Closed by KyleAthom** 2018-08-06 12:32 UTC
Labels: RF
