### ISSUE TITLE
ZWave.me pairing fails with timeout in state INTERVIEW_MULTI_CHANNEL

### ISSUE THREAD

**Issue by bm480** [athombv/homey#1318] opened 2017-02-06 21:50 UTC
**What is your Homey version (Settings → System)?**

1.1.2

**What did you try to achieve?**

Pairing the WALLC-S device with Homey.

**What was the result?**

> Add Device
> Z-Wave
- Z-Wave Apparaat toevoegen
> enter pairing mode on WALLC-S device
- in browser console all discovery states are shown quickly
- until INTERVIEW_MULTI_CHANNEL is shown in browser console
- after a few seconds, pairing process is shown again and no new device created

**What did you expect as result?**

Device to be found and added to the device list

**Any other remarks**

Also see this thread: https://forum.athom.com/discussion/1791/app-z-wave-me/p5

**Comment by bvdbos** [comment] 2017-02-06 21:52
same as #1261 ?

**Comment by bm480** [comment] 2017-02-09 08:06
Probably the same, yes. I'm pretty sure the issue is somewhere in the Homey Z-Wave code, not in the device driver, So this might apply to multiple device types, I guess.

**Comment by jeroenvollenbrock** [comment] 2017-02-13 10:52
Closed as duplicate of #1261

**Closed by jeroenvollenbrock** 2017-02-13 10:52 UTC
