### ISSUE TITLE
Cards pop under Zones

### ISSUE THREAD

**Issue by Fire69** [athombv/homey#328] opened 2016-03-10 12:07 UTC
**What is your Homey version (Settings → System)?**

0.8.22

**What did you try to achieve?**

Open a device card

**What was the result?**

![image](https://cloud.githubusercontent.com/assets/1757287/13669002/c6bd0fe2-e6c0-11e5-8332-ea0740badb27.png)

**What did you expect as result?**

See the entire card :-)

**Any other remarks**

This is not specific to the Hues as in the example, all cards for the first device in a zone are only partially visible

**Comment by nlrb** [comment] 2016-03-10 13:10
Looks like a duplicate of #322.

**Comment by Fire69** [comment] 2016-03-10 14:03
Nope, https://github.com/athombv/homey/issues/322 is about an icon that is missing on the card.
I have that problem also, it happens even the card is not all the way to the left.

**Comment by WeeJeWel** [comment] 2016-03-10 14:36
@Fire69 could you post a screenshot of what you describe?

**Comment by Fire69** [comment] 2016-03-10 14:41
@WeeJeWel, there's a screenshot in my first post.
Or do you mean for the comment above yours? (https://github.com/athombv/homey/issues/328#issuecomment-194857899)

**Comment by WeeJeWel** [comment] 2016-03-10 14:41
@Fire69 this: ` I have that problem also, it happens even the card is not all the way to the left.`

**Comment by Fire69** [comment] 2016-03-10 14:49
Not for the moment, I had to remove the z-wave device that had this problem because it was not responding anymore (again).

**Comment by Arjanvde** [comment] 2016-03-10 15:05
@Fire69 Somthing like this?

![card shown](https://cloud.githubusercontent.com/assets/17526110/13673574/e9c20402-e6d9-11e5-85f2-2b380421b9e2.png)

**Comment by Fire69** [comment] 2016-03-10 17:13
Yep
So in your screenshot, there are 2 problems.
Pops under and icon missing :)

**Closed** 2016-04-20 14:58 UTC
