### ISSUE TITLE
[APP V2] [FeatureRequest] Start/trigger flows/virtual devices from native Android/IOS widgets

### ISSUE THREAD

**Issue by kukel** [athombv/homey#2105] opened 2017-12-26 13:13 UTC
Almost a 'must' to be able from the app to 'add this to the homescreen' (or via 'add widget' from the OS) so there are good quick access buttons to turn things on/off/dim/...

**Comment by bvdbos** [comment] 2017-12-26 14:33
https://github.com/athombv/homey/search?q=widget&type=Issues&utf8=%E2%9C%93
so #1095

**Comment by kukel** [comment] 2017-12-26 14:45
@bvdbos: Sorry, for not finding this duplicate, but I searched for 'V2' and 'App' and widgets and it dis not show up. The duplicate was originally for V1.01 and since V2 is not being developed, maybe that should be tagged with V2 and all all real (github) labels should be used/standardized/documented for finding issues related to specific things

**Comment by PrismSub7** [comment] 2018-01-09 12:36
Meanwhile, I'm using 'HTTP Request Widget' on my android phone in combination with 'HTTP request flow cards' on the homey. Saves about 7 seconds compared to using the V2 app. This feature would be a great timesaver.

**Comment by kukel** [comment] 2018-01-09 21:28
I have two of these too, but the amount of work it costs should not be needed. Would have hoped Athom put more effort into the widget/controls part of the new app instead of flow-editing... Would have made way more people 'happy'.

**Comment by jeroenvollenbrock** [comment] 2018-01-10 15:29
Closing as duplicate of #1095

**Closed by jeroenvollenbrock** 2018-01-10 15:29 UTC
