### ISSUE TITLE
Spacing "then" in the flow editor is wrong on a mac

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#314] opened 2016-03-07 18:14 UTC
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**
Seems that scrolling has been implemented in the flow editor. However, spacing is wrong and some cards are hidden.

![schermafbeelding 2016-03-07 om 19 12 09](https://cloud.githubusercontent.com/assets/17526110/13578517/bd010afa-e498-11e5-8322-010fcf8390e6.png)

**What was the result?**

Result is that i can't adjust the lights anymore from the first card which is actually the top one, i can't reach that card anymore. Secondly all cards do touch/overlap each other which makes it looks messy.

**What did you expect as result?**

Regular spacing as with a flow with less used cards and that all cards would still be visable.

**Comment by Arjanvde** [comment] 2016-03-07 18:17
Little addition, this is how the same flow looks a windows computer, even the scroll bar was added automatically and good visible as well.

![scrolling works](https://cloud.githubusercontent.com/assets/17526110/13578598/39362f1a-e499-11e5-8115-cc8452f7ef2a.png)

**Comment by Dijker** [comment] 2016-03-07 18:20
Duplicate off #200 #219 #245 #274 not only on Mac.

**Comment by Arjanvde** [comment] 2016-03-08 20:30
In 0.8.22 spacing seems to be resolved, however, the top flow cards are missing. Looks like the flow editor is starting to align in the middle of a "then" flow and scrolling starts at the top so the cards on top could be missed.

![schermafbeelding 2016-03-08 om 21 27 35](https://cloud.githubusercontent.com/assets/17526110/13615287/e6aedf8a-e574-11e5-9b03-c7e9ad3303e7.png)

Printscreen is from the same flow as yesterday.

**Comment by Arjanvde** [comment] 2016-03-10 21:03
Small workaround for this issue is to adjust the zoom from in my case 100% to 50% to see all the cards.

**Comment by jeroenvollenbrock** [comment] 2016-07-27 12:35
Duplicate of #200

**Closed** 2016-07-27 12:36 UTC
Labels: duplicate
