### ISSUE TITLE
After setting a variable the casing goes lost

### ISSUE THREAD

**Issue by PatrickSannes** [athombv/homey#628] opened 2016-05-20 19:09 UTC
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**

Set a variable in the variable store of the homey

**What was the result?**

A broken app

**What did you expect as result?**

When setting a variable from the settings page section with
vm.homey.set('changedVariables', changeObject);

In the backend in:
  Homey.manager('settings').on('set', function (action) {}

That the action would be changedVariables. Currently it is changedvariables.....

**Comment by WeeJeWel** [comment] 2016-05-22 11:37
Ahh. Actually all variable names are lowercased on purpose. I think I forgot to document that, sorry!

Will close this issue for now as it's intended behavior.

**Closed** 2016-07-28 12:17 UTC
Labels: App-SDK, bug
