### ISSUE TITLE
Toon not working with Homey v1.5.6

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2293] opened 2018-03-05 13:41 UTC
* **Homey Version**: 1.5.6
* **Homey Log Code**:  08286BAB3C
* **Smartphone Platform**: 
* **Smartphone App Version**:

**If related to a Homey App:** Toon
* **Homey App Version**: beta 1.3.6 
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Toon 

**What did you try to achieve?**
change the program status on homey, from Thuis to Weg ... nothing happened on Toon. When change on Toon device the information is published within Homey

**What did you expect as result?**
Homey to be able to control Toon device

**What was the result?**
Toon not working via Homey

**Any other remarks**
Related issue #2279

**Comment by bvdbos** [comment] 2018-03-05 16:08
#2279 in itself is a dupe of #2271 so no need to create another issue for this....

**Comment by jeroenvollenbrock** [comment] 2018-03-12 10:40
Closing as duplicate of #2279 and #2271

**Closed by jeroenvollenbrock** 2018-03-12 10:40 UTC
