### ISSUE TITLE
Day selection in Alarm/wekker broken

### ISSUE THREAD

**Issue by goyaweb** [athombv/homey#1585] opened 2017-05-25 14:56 UTC
**What is your Homey version
1.3.0 RC7

**What did you try to achieve?**
Set the alarm in the mobile app to only go of Tuesdays. Regardless on Wednesday the alarm went of again waking me up unnecessary.

**What was the result?**
I woke up.

**What did you expect as result?**
More sleep

**Comment by Dijker** [comment] 2017-05-25 16:43
Duplicate of https://github.com/athombv/homey-issues-dp/issues/31 
But I understand you didn't expect it there....

**Comment by Jovink** [comment] 2017-05-25 17:31
It's fixt in the next build

**Comment by jeroenvollenbrock** [comment] 2017-05-31 13:54
Fixed in 1.3.0-rc.9/10

**Closed by jeroenvollenbrock** 2017-05-31 13:54 UTC
