### ISSUE TITLE
Mobile card does not work in when column

### ISSUE THREAD

**Issue by bliekp** [athombv/homey#1794] opened 2017-09-01 06:52 UTC
**What is your Homey version (Settings → System)?**

1.5.0

**What did you try to achieve?**

Just trying out the "Mobile" card in a flow. 

**What was the result?**

I can select my phone from a list when I use the Mobile card in the IF or THEN column, but in the When column it says "No results found..."

**What did you expect as result?**

To be able to select my phone in the WHEN column too.

**Any other remarks**

Phone is a Xiaomi Mi 5s running LineageOS 14.1 (20170703 NIGHTLY-capricorn)
I am using the *beta* Homey app from the PlayStore.

**Please attach a Homey System log (Settings -> System -> Send Log)**

B4FBB4889F

<img width="294" alt="screen shot 2017-09-01 at 08 46 10" src="https://user-images.githubusercontent.com/2614897/29958370-cf1c49b0-8ef2-11e7-9f3c-dc82a2635023.png">
<img width="314" alt="screen shot 2017-09-01 at 08 47 58" src="https://user-images.githubusercontent.com/2614897/29958371-cf3c3996-8ef2-11e7-9656-78913bc0b63e.png">

**Comment by bvdbos** [comment] 2017-09-01 07:18
This will only work with an updated version of the app...
https://forum.athom.com/discussion/comment/57270/#Comment_57270

**Comment by jeroenvollenbrock** [comment] 2017-09-04 12:37
Closing as duplicate of #1709

**Closed by jeroenvollenbrock** 2017-09-04 12:37 UTC
