### ISSUE TITLE
Philips Hue 

### ISSUE THREAD

**Issue by spikerm** [athombv/homey#914] opened 2016-09-27 22:21 UTC
**What is your Homey version (Settings → System)?**

0.10.0

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*
Brightness control in flows 

**What was the result?**
Flow hangs at brightness control card and does not continue 

...

**What did you expect as result?**
before this update the flow worked fine so when the light was at 50% the flow executed and the brightness was set to the desired level 

...

**Any other remarks**

...

**Comment by Arjanvde** [comment] 2016-09-28 07:19
Duplicate of #913 and #893 , this should be solved in 10.1

**Comment by WeeJeWel** [comment] 2016-09-28 10:14
What @Arjanvde says ^.^

**Closed by WeeJeWel** 2016-09-28 10:14 UTC

**Comment by MdeRhoter** [comment] 2016-09-29 17:49
On 0.10.1 this is still an issue.

**Comment by WeeJeWel** [comment] 2016-09-29 17:53
@MdeRhoter care to elaborate? We've tested this thoroughly and didn't encounter any issues

**Comment by spikerm** [comment] 2016-09-29 17:54
Emile

I Will test with in 20 min and let you now

Op donderdag 29 september 2016 heeft Emile Nijssen <notifications@github.com>
het volgende geschreven:

**Comment by MdeRhoter** [comment] 2016-09-29 17:55
Sure, I can show you:

![image](https://cloud.githubusercontent.com/assets/15713184/18965710/9c5121f4-867e-11e6-8a1d-d41f857c8b5f.png)

**Comment by spikerm** [comment] 2016-09-29 18:06
Ok brightness Control does work

Onlywhen running test flow you keep a circle

Op donderdag 29 september 2016 heeft MdeRhoter <notifications@github.com>
het volgende geschreven:

**Comment by MdeRhoter** [comment] 2016-09-30 11:58
Hmm - it works, but not always, and there's definitely a difference between 0.9.x and 0.10.x. Not all brightness settings are applied consistently.
