### ISSUE TITLE
Start up with a brand new homey

### ISSUE THREAD

**Issue by Neo-NL** [athombv/homey#725] opened 2016-07-22 06:46 UTC
Hey Guys,

I want to let you know what i've experience with the new homey.
Sorry for the bad english.

First off all, it's a beautiful piece of technic!

At the first start up, homey asked me to go to the setup page.
I followed the instruction.
First few times it hangs with the connection to the wifi homeysetup. (doesn't work smooth)
After that, updating was a little problem, 4 times i've got the message that there was something wrong.

when i went through that, it was time to set connection to my router:

Wifi setup:
I've read about more problems with this, Homey won't connect to my router with the normal setup.
I've solved it by making a hotspot on a android, and afterthat, making a guest network on my router with the same settings. 
I'm wondering why i can't setup the wifi in the normal settings to change the connection??
And why i have to make my normal home wifi setup a mess to make the homey connected??

Now i can explore the homey. 
I'm hoping the part of the wifi setup is helping some guys here.

Keep on the good work.

**Comment by Dijker** [comment] 2016-07-22 22:08
Thanks for the msg, @Neo-NL. 
It only doesn't belong here. 
please read my comment to an other new Homey User here. 
https://github.com/athombv/homey/issues/723#issuecomment-234026757 
You are Welcome in the forum with all kind of discussions. 

Your findings are already reported as issues / software bugs here as #470 #482 #495

**Comment by jeroenvollenbrock** [comment] 2016-07-27 16:06
Duplicate of #470

**Closed by jeroenvollenbrock** 2016-07-27 16:06 UTC
