### ISSUE TITLE
tamper alarm stays active while there is no tamper

### ISSUE THREAD

**Issue by fvhuizen** [athombv/homey#2309] opened 2018-03-08 21:23 UTC
**Metadata**

* **Homey Version**: 1.5.8
* **Homey Log Code**:552725A410
* **Smartphone Platform**:iOS
* **Smartphone App Version**:2.0

**If related to a Homey App:**
* **Homey App Version**:1.5.17
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:Fibaro flood sensor

**What did you try to achieve?**

Flood sensor gives tamper alarm while there is no tamper

**What did you expect as result?**

No tamper alarm

**What was the result?**

Tamper alarm

**Any other remarks**
After updating and restarting the flood sensor still a tamper problem which is drowning the batterie

**Comment by Dijker** [comment] 2018-03-08 21:32
duplicate of combination Issue #2267 ? 
and all issues already mentioned there and closed!

**Comment by fvhuizen** [comment] 2018-03-10 10:40
2 Days ahead the tamper alarm stopped, so maybe Athom does some magic or else the update took some time to publish the correct state.

**Closed** 2018-03-12 11:00 UTC
