### ISSUE TITLE
Can't uncheck the experimental updates checkbox

### ISSUE THREAD

**Issue by PeterEIER** [athombv/homey#1907] opened 2017-10-21 09:57 UTC
**What is your Homey version (Settings → System)?**

Homey Firmware Versie: 1.5.3

**What did you try to achieve?**
Turn off experimental updates

*Please include detailed steps how we can reproduce the issue*
1/ Enabled automatic download of updates
2/ Experimental updates checkbox stays grey, unable to disable feature / uncheck checkbox.

**What was the result?**
When automatic updates is enabled I always will receive the experimental which I do not want.

**What did you expect as result?**
Being able to uncheck the experimental checkbox

**Any other remarks**
-

**Please attach a Homey System log (Settings -> System -> Send Log)**
?? Is sent directly??? Not applicable for this issue I guess.

![screen shot 2017-10-21 at 11 52 38](https://user-images.githubusercontent.com/25422313/31850662-697ecd40-b656-11e7-8292-3861d719b085.png)

**Comment by PeterEIER** [comment] 2017-10-21 09:59
![screen shot 2017-10-21 at 11 58 41](https://user-images.githubusercontent.com/25422313/31850702-3ecc2416-b657-11e7-8b94-360180c3d0d1.png)

**Comment by bvdbos** [comment] 2017-10-21 10:02
If you chose for experimental, you can't go back without resetting Homey...
https://www.athom.com/nl/ondersteuning/KB000041/
https://www.athom.com/en/support/KB000041/

**Comment by PeterEIER** [comment] 2017-10-21 10:07
LOL, time for improvement...

**Comment by bvdbos** [comment] 2017-10-21 10:24
Well, the UI warned you before you ticked "experimental" too...
but that was bug https://github.com/athombv/homey/issues/1102

**Comment by PeterEIER** [comment] 2017-10-21 10:43
"Great" workarround.... Imho making it hard for the "novice user" to enable experimental would probably be a better approach then making it hard to disable it. Thanks for pointing out the "done that been there". I will check manual for updates and decide if I install them.

**Comment by mruiter** [comment] 2017-10-21 14:30
Yes we need a big improvement.. Anybody know where the git repo is for RTFM ignorant people ;)

**Comment by jeroenvollenbrock** [comment] 2017-10-23 18:23
Closing as this is intended behaviour.

**Closed by jeroenvollenbrock** 2017-10-23 18:23 UTC
