### ISSUE TITLE
Same issue as #1301 homey also not responsive to OK HOMEY

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1525] opened 2017-05-03 15:21 UTC
**What is your Homey version (Settings → System)?**
1.2.2

**What did you try to achieve?**
Same issue as #1301 

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**
Homey repeated about 10 times Oeps ik kan de server niet bereiken.

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
BB2C4F773F
...

**Comment by Tweake** [comment] 2017-05-08 11:31
Duplicate of #1301, probably a temporary cloud or wifi glitch.

**Closed by Tweake** 2017-05-08 11:31 UTC
