### ISSUE TITLE
Infrared on 0.8.20 not working

### ISSUE THREAD

**Issue by edtst** [athombv/homey#249] opened 2016-02-26 12:30 UTC
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

Use infrared

*Please include detailed steps how we can reproduce the issue*

I tried to pair my Grundig and LG remotes. None recognized. I used the manual wizard and it recognizes every button. When I use the IR in a flow, nothingb happens, neither on my LG or Grundig

**What was the result?**
Nothing

**What did you expect as result?**
My LG and Grundig would respond to the added buttons

**Comment by goldenice** [comment] 2016-02-26 14:51
Hi @edtst, could you try if you the pairing wizard can find the remotes if you try tapping 10 to 15 times very fast instead of holding the button for a few seconds? 

I suspect the problem is that your remotes do not repeat the entire signal when keeping a button pressed, but rather emit a tiny 'pulse' to show the device it's still pressed. As the pairing wizard needs a few samples of the entire signal to match accurately, it doesn't show a valid signal in the pairing wizard. Tapping very fast to repeat the signal (as most remotes do when the button is still pressed) might fool the pairing wizard into thinking the button is being pressed.

**Comment by JesperJanssen** [comment] 2016-02-26 16:10
I have a different problem with IR in version 0.8.20

I'm able to pair my remote with Homey and I'm able to ley Homey send IR commands. However, when I want Homey to power on for example my surround set (which is the same button to power off my surround set) Homey send multiple IR commands (most of the time 3/4) to my surround set. So my surround set goes on, off, on, off or on, off, on. I guess this is programmed as a safety so that one of the commands reaches the device but in this case (and a lot of other cases) this does not work.

**Comment by goldenice** [comment] 2016-02-26 16:22
This happens when you try to turn on or off using the flow card right? I'll see if I can add a card which only emits the signal once.

The reason Homey transmits it multiple times is that most devices have a so called toggle bit; this is a part of the signal that flips every time the button is pressed. A device can recognize if it's just a long press by checking the toggle bit: if it hasn't flipped, it's just a long press, but if it has, the button has been pressed multiple times. I suspect your surround set doesn't use such a construct, which causes the problem you mentioned.

**Comment by JesperJanssen** [comment] 2016-02-26 16:39
That indeed happens when I use the test flow button. It also happens when I for example use my KaKu remote to trigger a flow to power on my surround set.

A flow card or a flow card setting to fix this would be awesome and very helpfull for a lot of users I think.

**Comment by edtst** [comment] 2016-02-26 17:33
I tried adding by pressing multiple times, but it doesn't help. No remote is recognized. Only manual buttons.

**Comment by Wimstradamus** [comment] 2016-02-28 08:31
Also on 0.8.20 added
LG tv remote - sending signal and LG tv responds
Humax cable decoder remote - sends a signal but Humax does not respond
Yamaha audio reciever remote - sends a signal but Yamaha does not respond

i know it send a signal because i use ir extender en can see the ir leds on the devices blink (multiple times)
Also tried Humax without the ir extender, still doesn't work.

**Comment by freemann** [comment] 2016-02-28 09:08
Humax 5050c is produced with 2 different IR "signals". 
My harmony One remote warns my all the time when I'm configuring the remote. Default it uses a particular signal and if that's not working you need to change a setting in the remote so it uses a different signal. In my case I always need to change that setting else it won't work.

**Comment by bvdbos** [comment] 2016-02-28 10:15
Turning my radio ([Philips mci500](http://tweakers.net/pricewatch/245645/philips-mci500h.html)) on or off is no problem when using "devices" or a trigger by the Kaku-contact sensor. However, my Blueray ([Philips HTB3260/12](https://www.philips.nl/c-p/HTB3260_12/2.1-3d-blu-ray-home-cinema) would only work when I placed homey closer to it.

**Comment by Qx5** [comment] 2016-02-28 13:00
I also have still some problems with my IR.

Most annoying is that buttons sometimes just aren't recognized in manual but also automatic mode.

i.e. I have an simple IR on/off remote for some candles. The on-button is recognised after some really intens light saber battle between me with my remote and homey (Trying all positions and distances to get it to recognize). The off-button is never recognised.  (The on-button does work though in flows!)

My philips fidelio E5 remote is not recognised in automatic mode and when adding some buttons manually they won't work afterwards. 

My Samsung remote (AA59-00786A) is also not recognised. Similar models wont work. Is there a way to add models to the IR database?

**Comment by goldenice** [comment] 2016-02-29 18:09
@JesperJanssen This toggling behaviour, in which your device turns on off on off on when using the flow card, was this with an automatically detected device, or have you added the signals manually? Because I fixed a bug in the signal service, in which recognized signals had way to many repetitions specified in their signal definition. This means that if you've added your device by automatically recognizing, you can just do that again, and it is probably fixed.

I'm still working on a fix for manually added signals.

**Comment by goldenice** [comment] 2016-03-01 12:21
@kitkat14 created a thread for sending the signal multiple times instead of one, I suggest we continue the conversation about that issue in that thread. Generic IR problems, like remotes not being recognized can be discussed here.

@edtst Sadly not all remotes are in our database, because on most there is only incomplete or no data at all available. Unfortunately as this may be, we don't consider it a bug. However, when adding the signal manually the buttons should always work.

For everyone in this thread having problems with IR not being recognized by the target device: can you try putting Homey right next to the device, and try whether it recognizes it that way. I won't get too technical, but every IR-signal has a base frequency on which the 1's and 0's are modulated. When this basefrequency is off, the range may decrease dramatically. Most devices use a base frequency of 38kHz, so that's the default for manually added signals. The target device should recognize signals on another basefrequency, but the range may be well under 1 metre or so. It would be very helpful if a few of you could verify if that's the case.

**Comment by edtst** [comment] 2016-03-01 12:50
I did as you asked, setup homey in front of my LG at 0 cm, 10 cm, 20 cm etc, but it won't switch on. This is also the case for my Grundig FINE ARTS 55 FLX 9490 SL Ultra HD TV.

When I learn signals to Homey, it detects every key I press, weather it is pressed 1 second , 3 seconds, or multiple times. I attach how Homey Detects my LG signal.

![ir1](https://cloud.githubusercontent.com/assets/17183305/13427428/3ab3a50a-dfb4-11e5-9de6-1b30e85a2c72.JPG)

**Comment by goldenice** [comment] 2016-03-01 12:56
@edtst That's indeed not even near a valid signal, it should have way more 'blocks'. Looks like your remote is pretty odd: it probably has very long intervals between flank changes, which makes it hard for Homey to detect properly.

**Comment by edtst** [comment] 2016-03-01 13:06
This is my Grundig remote

![ir grundig](https://cloud.githubusercontent.com/assets/17183305/13427762/74f3fc22-dfb6-11e5-8196-71811cf197ea.JPG)

These are not odd devices, so many of your customers will have those and expect them to work with Homey.

**Comment by goldenice** [comment] 2016-03-01 13:09
@edtst Yes, you're right, I've just never seen that behaviour before...
The Grundig remote looks like it should work though. Very interesting, I'll see if I can find something causing this behaviour.

**Comment by edtst** [comment] 2016-03-01 13:25
Is it an idea to add a checkbox to the detector so you can start and stop detection and then possibly crop the signal by hand? That would make it easier to debug.

**Comment by JesperJanssen** [comment] 2016-03-01 18:13
I now added my Sony remote automatically and when I now test a flow in the flow editor it indeed seems to just send one signal. However, to reach my HDMI 3 input I have to press the source button 3 times and when I configure a flow which presses the source button 3 times it will only go up from AV to HDMI 1 instead of AV > HDMI 1 > HDMI 2 > HDMI 3

For my surround set (logitech Z5500) it is not possible to use the automatic recognition.

But I will first wait until 0.8.21 is released and I did some testing with that version before I will report some more IR issues.

**Comment by goldenice** [comment] 2016-03-01 18:21
@JesperJanssen Have you tried putting in a longer delay in the flow editor? In the top right corner of the cards there is a little icon, which allows you to specify how much time should pass before executing that card. The TV probably sees it as one button press because there is too little time between each sent command. This behaviour might occur when the tv doesn't support toggle bits.

The other reason this behaviour might trigger is when the signal in our database doesn't have toggle bits specified, but your tv does use them: that way the bit doesn't get flipped, and the tv will think it was just a long press of the button.

Can you tell me the exact brand and model number of your TV and/or the used configuration when automatically detecting? Then I can verify which one of the two possibilities mentioned above is at hand here.

**Comment by JesperJanssen** [comment] 2016-03-02 21:37
I tried a flow with a delay of 2 sec for the 1st card 4 for the 2nd card 6 for the 3rd card and 8 for the  4th card. All card should switch the input once so it shoulf switch it a total of 4 times but it actually only switches the input once.

My tv is a Sony KDL-40EX402. The remote for the TV is a RM-ED022 (but both the TV and remote are not in the database). So I chose on of the 5 left over remotes after I pressed 5 buttons in the automatic recognition. I eventually chose MT-V767

**Comment by edtst** [comment] 2016-03-08 15:50
Confirmed this is not working in 0.8.22.

**Comment by matjaz** [comment] 2016-03-10 09:04
I am also having issues with adding IR. Even trying manually detect keypress does not work.
I see a TV led blink, but Homey does not recognise signal. I've tried multiple buttons, with long press, fast short keypresses, etc. Not a single success.
Can you add at least some indicator Homey is receiving some IR signal (similar to tv led).

**Comment by edtst** [comment] 2016-03-16 14:26
Confirmed this is still a problem in 0.8.24. Infrared is not working.

**Comment by Qx5** [comment] 2016-03-16 15:22
I had quite some successes with IR.

For Homey IR receiving it's crucial to have the LED ring on very low brightness. Otherwise Homey won't recognize you triggered an IR signal. Also triggering a remote from the same height or lower as Homey is also seems to help. Probably due to the openings in Homey casing below the LED ring?

I do have some problems with my samsung remote. It is still not found in the database so I added the colored buttons manually. That worked fine (except for the yellow one which it will never recognize during manual pairing). They work fine but when I'm pressing other buttons like volume or power, Homey also thinks I pressed one of the colored buttons, resulting in lots of flows triggered :wink: 

For my stereo I thought controlling it via Homey IR didn't work but apparantly it was a line of sight problem (Philips fidelio E5 has a terrible hidden IR receiver).

This is all in regard to 0.8.22 by the way but from what I read nothing has changed in respect to IR?

**Comment by Arjanvde** [comment] 2016-03-16 19:20
Had quite some success with infrared, but on 0.8.24 it stopped completely with working. Used the yellow, red, green and blue buttons to chance the lights to the corresponding color but it stopped working completely, even with the LED ring off.

**Comment by Qx5** [comment] 2016-03-17 08:01
Actually having the same issue now in 0.8.24 as @Arjanvde

**Comment by goldenice** [comment] 2016-03-21 14:26
Found the issue, fixed it already. This should be fixed in 0.8.25 :)

**Comment by Qx5** [comment] 2016-04-01 18:29
@goldenice ,  Just updated to 0.8.27 but IR receiving still seems to be broken. I tried adding the remote again (that part did work with IR receiving) but then simple flows are not activated on button presses. Also tried it with the LED ring at 0% but that didn't help.

**Comment by edtst** [comment] 2016-04-03 07:28
IR still not working in 0.8.27

**Comment by bvdbos** [comment] 2016-04-03 07:40
IR is working for me on my stereo but not on my dvd. I think it's device-dependant... For my dvd I have to keep the power-button pressed for at least a full second. So I guess I have to set a repeat-value to some higher value (btw: "default : 10" doesn't use 10 as a default, you really have t enter a value so there's no default)

**Comment by Arjanvde** [comment] 2016-04-04 06:45
Repairing my Philips Remote made Homey work again with IR Commands. However, I have the feeling that on a previous firmware version IR was working more smoothly.

**Comment by jordenc** [comment] 2016-04-05 16:01
Tried teaching Homey to learn the IR buttons for Netflix and 'power' on my Sony RMT-TX100D device. Used it in a flow. Even tried to make the LED ring go to 0% dim.
However, I can not make it turn on or off the television or start Netflix. Is this just my TV that has troubles or is anyone else on 0.8.27 having these issues?

**Comment by bliekp** [comment] 2016-04-06 20:50
I tried pairing an Onkyo RC-834M and a Samsung AA59-00790A. Both: nothing. Sometimes button presses are shown with black dots with a number in it. The wizard is totally unclear. This is very user unfriendly.
In Manual mode: no idea what to do here. Also, no button presses are even seen.

Totally unusable.
Running 0.8.29.

**Comment by imtt1980** [comment] 2016-04-09 12:24
IR is far from running acceptable. Database (Automatic) is not up to date. Learning single buttons (manual) sometimes works, but sometimes not. Even when a button is successfully learned and used in a flow, the device doesn't react to the signal, if it is send out at all (?).

Running version: 0.8.29

**Comment by bvdbos** [comment] 2016-04-09 12:35
It's not a general problem, see
https://forum.athom.com/discussion/comment/16401/#Comment_16401
both receiving IR by Homey (distance 2 meters, send from about 80 cm below Homey) and sending IR by Homey (to tv which is about 4 meters from Homey and about 1,2 meters below Homey) works for me...

**Comment by serelsnauw** [comment] 2016-04-20 13:33
Received my Homey yesterday, running version 0.8.29 and it does not respond to any IR remote at all. I've tried long presses, short presses, long distance, short distance, different buttons etc. No reaction at all (except from the devices the remote belongs to).. :-) 

So anybody any luck or advice?

**Comment by Fiek1** [comment] 2016-04-21 16:38
Hi....Received my homey on Tuesday, running 0.8.30. Homey doesn't respond to any remote at all when I use it in a flow. Tried both methods automatic and manual learning.

**Comment by Wimpje** [comment] 2016-04-22 12:54
Hi same problem here, (also) trying to add my Yamaha RX-V667 which doesn't work. No key presses are showing in the setup UI either. If I can help out with providing info let me know, and I'll do my best!

**Comment by Wimpje** [comment] 2016-04-24 08:48
OK, I answered my own question by just stupidly trying out yamaha remote codes. It also helped I found out in the atom forums that the device numbers found in the remote search are type numbers of the remotes, not the actual devices! (a message in the remote UI might be helpful) 

@Wimstradamus For the Yamaha RX-V667 I found that the AV294 remote worked!

**Comment by Fiek1** [comment] 2016-05-05 11:28
Hi all, any ETA ont this issue?

**Comment by gkroone** [comment] 2016-05-14 15:48
On the version before 0.8.32 I was able to add my Samsung remote with some of the buttons functioning fromt he automatic section and when doing the manual add, most of the buttons could be learned by homey. However since doing a full reset and erase to start fresh, I can't learn any manual IR. during the automatic learing, it does detect a samsung remote(the wrong one is detected) but it doesn't actually work when trying to send commands to my Samsung TV. Nothing changed now on 0.8.34 this issue still persists.

**Comment by bvdbos** [comment] 2016-05-14 15:51
Did you turn down the led-ring?

**Comment by edtst** [comment] 2016-05-18 09:36
This still is an issue. No remotes will pair exActly as described.

**Comment by maaikekaasenbrood** [comment] 2016-05-26 16:31
received my homey yesterday and started trying to add IR-devices no such luck.
most of my remotes are not recognized.. so I went for the manual pairing option. 
pushing the same button multiple times resulted in more buttons to add. 
sadly none of these buttons found actually where right for the devices, and did not turn on anything.

Homey does recognize the buttons added when these are used as triggers. and when used as 'then' homey does send out an IR signal (which you can check with the camera on your phone). However, this signal seems to be waaaayyyy weaker than what is send by the normal remote, at least the light seen on the camera is way weaker. 

homey version: 0.8.32

**Comment by jeroenvollenbrock** [comment] 2016-07-27 11:46
Can you please let me know whether this issue persists or not?

**Comment by edtst** [comment] 2016-07-27 12:41
Yes, no change yet.

**Comment by maaikekaasenbrood** [comment] 2016-07-28 13:54
Indeed there is no clear improvement, the put-the-button-in-the-flow-twice-trick also stopped working it seems

**Comment by Inversion-NL** [comment] 2016-09-23 18:35
What about iR in version 0.10.0 (currently in Experimental) ?

**Comment by maaikekaasenbrood** [comment] 2016-09-27 09:35
letting Homey learn from an old remote does not work properly. 
The learning sequence is done successfully but when using these buttoms as output of a flow does not turn on the device. 
homey version 0.10.0

**Comment by goldenice** [comment] 2016-09-27 09:38
Thank you for reporting, we're indeed receiving more reports of manual learning not quite working properly yet. I'm going to look into it today, and try to pinpoint the issue. What is the brand and model number of the remote you encountered this with?

**Comment by maaikekaasenbrood** [comment] 2016-09-28 18:59
its a rather generic remote: SMC-0510-BZ(R)
 it's from a fantilator light combination

**Comment by jeroenvollenbrock** [comment] 2016-10-03 14:01
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.

**Closed by jeroenvollenbrock** 2016-10-03 14:01 UTC
Labels: bug, Homey Core, Infrared

**Comment by matjaz** [comment] 2016-10-03 20:02
What about [IR API](https://developers.athom.com/library/signals/ir/)?
Can a generic "clone button" be added?

**Comment by WeeJeWel** [comment] 2016-10-03 20:10
In theory yes, the ir api is the same as the 433 MHz api

**Comment by matjaz** [comment] 2016-10-03 20:14
Without good tools to **define signals**, it's required a lot of domain knowledge, and thus voids wider adoption.
You should reconsider adding support for sending raw signals.

**Comment by WeeJeWel** [comment] 2016-10-03 20:22
That's definitely true! We're actively working on that :)

**Comment by matjaz** [comment] 2016-10-03 20:39
I hope *working on* was referring to raw signals :)

**Comment by WeeJeWel** [comment] 2016-10-03 20:41
We have a way of sending Pronto hex codes, we just need to finalize it for
developers!
