### ISSUE TITLE
[com.danalock] Does not work if homey is longer then 50cm away.

### ISSUE THREAD

**Issue by Asfaltsystem** [athombv/homey#2742] opened 2018-08-06 10:02 UTC
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**:
* **Smartphone Platform**: Iphone X
* **Smartphone App Version**: 

**If related to a Homey App:**
* **Homey App Version**: 1.3.3 build 70
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What was the result?**

**Any other remarks**

**Comment by mruiter** [comment] 2018-08-06 11:12
Please leave Some more info.

What Danalock version what have you tried is iT in mesh when not working etc.....

**Comment by mruiter** [comment] 2018-08-06 12:58
Guess this is the default mesh flirs trouble of the homey zwave stack . There are also multiple issues already but good you reported iT 👍

Verstuurd vanaf mijn iPhone

**Comment by WeeJeWel** [comment] 2018-08-13 11:46
We cannot reproduce the issue, in my own home it even works 7m across.

Have you tried healing the device using https://developer.athom.com?

I'm closing the issue because it cannot be fixed in the traditional sense.

**Closed by WeeJeWel** 2018-08-13 11:46 UTC
