### ISSUE TITLE
[1.5.8] - Issue after issue - as usual

### ISSUE THREAD

**Issue by rafi1975** [athombv/homey#2307] opened 2018-03-08 19:43 UTC
Hi,

Another update, another issues/s. No surprise here.
Does anyone check the apps before the update is released?
Every update Philips Hue app loses access to all devices and I have to reboot the bridge and re-add it back to Homey. It's even worse with Heatmiser. Now none of the device are manageble. I had to re-add tchem and they are seen during the addition but I can't control tchem and they don't report any temperaturs.
It's always the same case. Now I can't control my heating through Homey at all. Waste of money.

Thanks,

Rafe

**Comment by bvdbos** [comment] 2018-03-08 19:52
Apparantly you're the only one as you had to create a new ticket? Could you start by filling in the requested information so Athom might be able to see if something is wrong with your Homey or your settings? And waste of money, how much did you pay for your Heatmiser?

**Comment by rafi1975** [comment] 2018-03-08 20:16
It's waste of money with Homey. I've had reported the similar issue with other updates as well. Not sure how many users are using Heatmiser though. Last time I created a ticket I was told to reboot the Heatmiser Hub and re-add it tpo Homey. It didn't help at all.

**Comment by Dijker** [comment] 2018-03-08 21:03
Hi Rafe, 
Sorry to say but this isn't going to help you, nor Help Athom or the community. 

Did you read the Contributing guidelines?
https://github.com/athombv/homey/blob/master/CONTRIBUTING.md

Please follow that, 

Before submitting a bug or feature request:
- Have you actually read the error message?
- Have you searched for similar issues?
[...]

A great bug report contains: 
- Context – what were you trying to achieve?
- Detailed steps to reproduce the error from scratch. 
- Try isolating the minimal amount of code needed to reproduce the error.
- Any applicable log files or ID's.
- Evidence you've looked into solving the problem and ideally, a theory on the cause and a possible solution.

Both Athom and the community are committed to help solve problems even if they are not real bugs in Homey or the Apps.
With the Problem you describe it really could be anything.

For just problems you want to isolate and help from community peers please use Slack or the Forum. 
To get direct help on using Homey and Athom Apps please contact support direct by email. 
(Guess you know where to find the address)

If you really want help use those channels. 
If you want to report something like a bug in Homey or an App create new  separate Issues  on those in the appropriate issue trackers and fill in all requested information. 

I expect this issue being closed soon by an admin (or you could close this issue self)

**Comment by rafi1975** [comment] 2018-03-08 21:47
Hi,
Replying to your email:

Before submitting a bug or feature request:

   - Have you actually read the error message? - there's no error message
   at all. I can't control my thermostats any more.
   - Have you searched for similar issues? - I couldn't find any.
   [...]

A great bug report contains:

   - Context – what were you trying to achieve? - As already mentioned - to
   be able to control all Heatmiser thermostats.
   - Detailed steps to reproduce the error from scratch. - All stopped
   working after Homey upgrade.
   - Try isolating the minimal amount of code needed to reproduce the
   error. - I'm not a programmer.
   - Any applicable log files or ID's. - Already provided when submitting a
   ticket.
   - Evidence you've looked into solving the problem and ideally, a theory
   on the cause and a possible solution. - The theory is that it stops working
   every each Homey upgrade.

**Comment by bvdbos** [comment] 2018-03-09 06:33
Do you have multiple Thermostates? Really difficult to guess what devices you have and what could be wrong without supplying the info...

**Comment by rafi1975** [comment] 2018-03-09 07:59
I have provided all requested logs - from OS and the application -
Heatmiser. As already mentioned, I'm using Heatmiser NeoHub that controls
all thermostats.
They are seen by Homey but you can't see any temperature readings and can't
control them using Homey any more.
It's all ok using the native Heatmiser app though.
Homey is at 1.5.8 and Heatmiser app - 2.0.0 - all the latest.

**Comment by kukel** [comment] 2018-03-11 10:35
@rafi1975: I never had any issues with Philips Hue after any update/ugrade. (Toon is another thing, but that is in the Toon App (or the Toon server, not under control by Athom))...

**Comment by jeroenvollenbrock** [comment] 2018-03-12 10:58
Please follow the contributing guidelines and open a new issue for your specific problem. This is an issue tracker, not a complaint tracker.

**Closed by jeroenvollenbrock** 2018-03-12 10:58 UTC
