### ISSUE TITLE
All Kaku devices do not work anymore

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1445] opened 2017-04-03 19:41 UTC
**What is your Homey version (Settings → System)?**
1.2.0 rc10

**What did you try to achieve?**
Normal daily outside lights go on with flow

*Please include detailed steps how we can reproduce the issue*
All lights on z-wave go on all lights on Kaku do not respond to anything

**What was the result?**
Lights remain off

**What did you expect as result?**
Lights to be on

**Any other remarks**

**Comment by chrisboer** [comment] 2017-04-03 19:43
Log send id 2763E28027

**Comment by jeroenvollenbrock** [comment] 2017-04-04 07:19
Does the issue persist through a reboot and a powercycle of Homey?

**Comment by chrisboer** [comment] 2017-04-04 08:28
After a reboot Kaku worked again.

**Comment by chrisboer** [comment] 2017-04-04 08:30
But I did not change anything in Kaku devices nor in their flows so it is only the new 1.2.0 rc10 release what stopped the working of the Kaku devices.

**Comment by jeroenvollenbrock** [comment] 2017-04-04 09:06
Closing as duplicate of #1228. Unfortunately, we do not have a solution available at this time, but we are working on stability improvements to prevent this in the future.

**Closed by jeroenvollenbrock** 2017-04-04 09:06 UTC
