### ISSUE TITLE
Homey performs extremely poor when using voice commands

### ISSUE THREAD

**Issue by JvdHaak** [athombv/homey#498] opened 2016-04-23 09:05 UTC
Homey Version
0.8.29

**What did you try to achieve?**
Voice activated commands

_Please include detailed steps how we can reproduce the issue_
Any flow that is triggered by voice. 
Example: I created a flow where I have to say 'Good morning', and then Homey should answer with 'Good morning Sir', show a LED pulse and switch brightness to 100%.

**What was the result?**
After receiving the OK Homey, it thinks for a bit and then switches back to idle. Nothing happens. 
...

**What did you expect as result?**
That my voice command actually works. A simple 'good morning' and trying to get a 'good morning Sir' back is already too much. Doesn't work.
...

**Any other remarks**
It only works when I'm 50cm away from Homey. Any further messes up the outcome. 
...

**Comment by sossienl** [comment] 2016-04-25 22:02
+1

**Comment by jghaanstra** [comment] 2016-05-25 13:03
There are a lot of issues reported about the performance of the voice recognizition. I have decided to contribute to this one as it describes my situation best. I'm currently on firmware 0.8.35.

My situation is that speech to text recognizition worked reasonably well using English language. I then switched to Dutch somewhere around firmware 0.8.29. As far as I can remember this worked reasonably well in the beginning but at some point I started having the situation as described in this issue (but could be straight away). Homey reacts really well to the "OK Homey" trigger and I dont have any false positives. The problem is that after giving a voice command Homey's LED ring keeps spinning white for a long time and no speech to text recognition response is given (none at all, not even a misinterpreted one as in previous cases which I have check on the speech-input page).  If I give the same command through the Android app a speech to text response is given almost always. So obviously there is something not properly working within Homey between the mic and the speech to text services.

Hopefully this helps in further solving this issue.

**Comment by matjaz** [comment] 2016-05-25 13:09
Speech is hard.
I was thinking if Athom is keen to open a little more by providing raw flac audio to apps. Similar for other hardware access (raw 433 signal, raw BT, BLE etc.) Thoughts?

**Comment by kruimel0** [comment] 2016-05-26 06:32
@matjaz I would actually dislike this, because then troubleshooting and user's annoying would only increase ("Voice recognisition works great with app X, but not with app Y!" or "This keyword should work with app X, but because app Y (which I don't want to address) has better speech recognition, app X never triggers!")

**Comment by matjaz** [comment] 2016-05-26 06:38
Not sure if we understood correctly.
App could register itself as drop-in replacement for built-in speech recognition (user could change speech recognition app) similar to how apps can add screen savers.
Also, app could request raw audio and do whatever it wants to do wi it (separate permissions).

**Comment by bvdbos** [comment] 2016-12-10 11:01
@JvdHaak Did speech-recognition improve a lot for you too after april 23th? Could you check what Homey heard on http://[homey-ip]/manager/speech-input ?

**Comment by bvdbos** [comment] 2016-12-10 11:02
@matjaz I wouldn't go that far for now but it would be nice if we could troubleshoot speech-recognition by being able to hear recorded sounds, to learn what Homey really heard...

**Comment by flipflopsandrice** [comment] 2018-03-06 21:32
Any updates on this? This still happens on 90% of my speech input.

**Comment by WeeJeWel** [comment] 2018-03-23 20:13
Closing this issue because speech will not be actively improved upon anymore. For more details I invite you all to read our explanation why at our blog: https://blog.athom.com/take-speech-music/.

**Closed by WeeJeWel** 2018-03-23 20:13 UTC
Labels: Homey Core, bug, speech-input
