### ISSUE TITLE
KAKU all plug are broken

### ISSUE THREAD

**Issue by jjtbsomhorst** [athombv/homey#728] opened 2016-07-27 05:18 UTC
**What is your Homey version (Settings → System)?**
8.0.39

**What did you try to achieve?**

Execute a flow that disables by kaku wall plug which is behind a wall. 

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

Before kaku 2.0.5 everything worked well. Currently the app seems broken or the kaku chip crashes I dont know. I have re-added all kaku devices and after adding they work but as soon as I add them to a flow they seem to get broken. 

Manually triggering using the devices panel also doesn't work anymore. Have to reboot Homey to solve. 

**What did you expect as result?**

To have it working as before kaku 2.0.5. Kaku always worked over here..

**Comment by magtimmermans** [comment] 2016-07-27 16:10
Have the same issue.

**Comment by jeroenvollenbrock** [comment] 2016-07-27 16:14
Can you please let me know if this issue persists after 0.9.0 has been released?

**Comment by jjtbsomhorst** [comment] 2016-07-28 04:58
@jeroenvollenbrock  I will update the call with my experience when .9 has been released. Currently I reboot Homey every morning just to be sure the kaku functionality is working again.

**Comment by jeroenvollenbrock** [comment] 2016-07-28 07:12
@backslashgithub: Did you reboot using the button at the settings page, or by pulling the plug?

**Comment by backslashgithub** [comment] 2016-07-28 07:51
Reboot button

Groeten, 

Backslash.

**Comment by jeroenvollenbrock** [comment] 2016-07-28 07:56
Could you try if pulling&re-inserting the plug fixes the problem? The reboot button currently does not restore a crashed chip. A fix for chip crashes is included in Homey version 0.9.0

**Comment by backslashgithub** [comment] 2016-07-28 13:19
Hi there, just pulled and re-inserting the plug on Homey. But still not able to pair the devices, not bij remote and/or new signal on the fysical device.(4xacd-xxx and asun-650).
Also re installed the KlikaanKlikuit app but no luck. Operating the remote to switch device's is working. ps app Thermosmart is working.

**Comment by jjtbsomhorst** [comment] 2016-07-29 05:04
For me when I reboot the issue seems to be solved for a couple of hours. So I guess that the kaku app is crashing for some reason

**Comment by Luukvis** [comment] 2016-07-29 17:31
Unfurtunately, the Kaku devices are not working, even after update 0.9.1. I removed the kaku app and reinstalled it, but that did not solve the problem. The devices do not respond anymore.

**Comment by dhanstede** [comment] 2016-07-30 18:19
I have now paired 4 APA3-1500R switches. (firmware 0.9.1. and kaku app 2.1.0) and they are working very well. I had also the problem that i can't pair one switch, but after i did a full reset on that kaku switch (apa3-1500r) i can pair that switch to. Maybe you can try that?

**Comment by Luukvis** [comment] 2016-07-31 08:54
@dhanstede I don't have a kaku switch. I only have ACD-1000 plugs. So that doesn't work for me. 
It seems that there is no signal send when I ask homey to turn on the lights. On the device list homey shows that the the light is turned on, but the kaku device itself does not respond. 
I was able to pair three AYCT-102 remotes. I can use these with my Hue lights. So maybe the problem only concerns the ACD-1000 devices.

**Comment by backslashgithub** [comment] 2016-07-31 10:32
have ACD-1000 plugs and a asun-650, sun doesn't work either . so @Luukvis it is not only the ACD-xxx problem.
ps i don't have the idea someone from athom is being to try to solve the problem or give some exp. if there going to do something. i don't know wat to do. return the homey or risking to have a falty homey with no working 433...

**Comment by ReinierH** [comment] 2016-08-01 09:00
Are non of the 433 devices working or is it only the kaku app that isn't working? in 0.9.1 we improved the receiver sensitivity. For what i can think of now is that in some cases the sensitive receiver gets saturated with noise, blocking the transmitter from sending signals. It's hard to determine the sensitivity because it varies in different surroundings. 

Is there anybody that managed to get a remote paired but after that failed to use it in flows etc?
If so please send me your homey logs so i can verify if this is actually is the problem.

**Comment by backslashgithub** [comment] 2016-08-01 13:42
i did a full reset on that kaku switch (ACD-1000) i can't pair that switch with the remote or to generate a signal voor the device (with Homey) after full reset it is easy to pair it manual without Homey :-(

**Comment by Luukvis** [comment] 2016-08-01 18:23
@ReinierH I have send you the log of my Homey (code 942E9E83A9). I find it a little strange that for the ACD1000 a dimming function is added in the new App. But that Kaku device has no dimming option. It can only be turned on or off. 
![homey-kaku](https://cloud.githubusercontent.com/assets/16554361/17304396/bc2fd236-5825-11e6-847d-e63abaaad944.JPG)

**Comment by jeroenvollenbrock** [comment] 2016-08-11 10:42
Did 0.9.2 Resolve the communication issues?

**Comment by backslashgithub** [comment] 2016-08-11 11:46
0.9.2 did not solve the issues for me i am using  klikaanklikuit V2.1.2. :-(
What to do, now i get nervus because the 2 weeks for returning the homey is nearly there. Dont mind to wait for a solution but don't want to get stuck with a broken one!

**Comment by jjtbsomhorst** [comment] 2016-08-12 04:52
For us the issue is solved at the moment. Running kaku 2.0.6 and 0.8.39.

**Comment by backslashgithub** [comment] 2016-08-12 08:22
@jjtbsomhorst did you manual update? or is it possible to downgrade? want to get the kaku working again.

@jeroenvollenbrock is it possible to downgrade to kaku 2.0.6 and Homey 0.8.39.??

**Comment by backslashgithub** [comment] 2016-08-12 17:42
using Homey 0.9.2 and klikaanklikuit V2.1.2
Did a new install of the KAKU, but now aligned Homey and socket with KAKU close to each other.
This worked for 2 devices, after pairing a placed the 2 KAKU - devices back on there originally places. And there still working. 1 KAKU died (placed it on a waterboiler so i cold see if it workes but is maybee to much watt ??) and de last KAKU of my 4 devices (light in the garden and the socket with the KAKU device) i paired without putting them close to homey. So for now i dont know what was differant. but before the update from Homey they worked all good regardless of the distance between the KAKU and Homey.
ps when i use the remote and put the light on (for example) then the device pictogram dos not change to "on/off". I must manualy switch the KAKU in the Homey zone   on/off. 
conclusion; i think the range of the 433 is less? greets

**Comment by jeroenvollenbrock** [comment] 2016-08-16 15:30
The 433Mhz range in 0.9.2 has changed a bit. For some users it increased, while for others it decreased slightly. A decrease in range can be caused by high amounts of 433MHz noise. A few known sources for 433MHz noise are improperly connected (or disconnected) coax TV cables, and some ethernet-over-powerline adapters. I'm going to close this issue, as the original reported issue (KAKU does not work at all) has been resolved. If you are experiencing other issues, please submit a new ticket.

**Closed by jeroenvollenbrock** 2016-08-16 15:30 UTC
Labels: Athom App, bug, RF, waiting for user feedback

**Comment by sleutelsnet** [comment] 2016-08-24 10:03
Issue with Kaku/Homey:

Pairing is OK, but then after one or two communications, homey does not seem to receive any signal any more.
I seems that signals sent from Homey to KaKu are fine, but the reception is the problem with Homey.
