### ISSUE TITLE
App store contributor not showing

### ISSUE THREAD

**Issue by denniedegroot** [athombv/homey#311] opened 2016-03-06 08:57 UTC
**What did you try to achieve?**

To show a contributor's name in the app store.
The entry in the app.json looks valid, I double checked this with other apps.
Maybe it's related to the dots in the email?

The current app.json which is used in the app store for iTunes version 1.0.0:
https://github.com/denniedegroot/com.apple.itunes/blob/1.0.0/app.json

**What was the result?**

No name of the contributor in the app store.

**What did you expect as result?**

The contributor's name in the app store.

**Comment by joachimroeleveld** [comment] 2016-03-07 14:54
This is because the email address that you entered for the contributor is not known (not linked to a user id) in the Athom database. The possibility to add anonymous users will be added in one of the following releases.

**Comment by denniedegroot** [comment] 2016-03-08 18:20
Ok thanks, I will close the issue for now.

**Comment by denniedegroot** [comment] 2016-03-24 17:58
The app store now shows a wrong contributor for my app. I expected "Maarten Jansen" but I am seeing "Matjaz Lipus" as a contributor?! See the attached image.

![schermafbeelding 2016-03-24 om 18 51 05](https://cloud.githubusercontent.com/assets/662966/14026213/11d23246-f1f2-11e5-80c9-c77a9df9a563.png)

**Comment by joachimroeleveld** [comment] 2016-03-25 00:51
@denniedegroot, now that was a weird issue. A fix has been rolled out, thanks!

**Closed by joachimroeleveld** 2016-03-25 00:51 UTC

**Comment by joachimroeleveld** [comment] 2016-03-25 00:56
For further notice: it is not possible to add the app author as contributor as well. An app author gets filtered out from the contributors array. The contributors field is for users that contributed to the app *alongside* the app owner.

**Comment by matjaz** [comment] 2016-03-25 08:06
so for author website/avatar is not used anywhere?

**Comment by joachimroeleveld** [comment] 2016-04-06 19:33
I can confirm that from now on, it is possible to add anonymous contributors.

**Comment by joachimroeleveld** [comment] 2016-04-06 19:35
@matjaz, a website is not used anywhere for neither the app author or the contributors. Concerning the author's avatar, I may add this in the future, but right now I don't see a way to (aesthetically) do this.

**Comment by denniedegroot** [comment] 2016-04-06 19:37
@joachimroeleveld my app already has a anonymous contributor but it is not showing yet. Will it show when I do a new app update?

Also the Harmony Hub app (https://apps.athom.com/app/com.logitech.harmony.hub) shows Matjaz as a contributor but he is not listed in the JSON so it seems to be the same issue I encountered with my iTunes app.

**Comment by joachimroeleveld** [comment] 2016-04-06 19:50
@denniedegroot, it will when you update your app indeed. 

I think that the issue with the Logitech app could happen because the fix for that problem was not yet deployed. Anyway, I changed it to reflect the JSON, thanks.
