### ISSUE TITLE
Speech output is consistently 'hanging' at same sentence

### ISSUE THREAD

**Issue by MathijsG** [athombv/homey#2465] opened 2018-05-07 13:14 UTC
**Metadata**

* **Homey Version**: 1.5.9
* **Homey Log Code**: C5899CD37A
* **Smartphone Platform**: N/A
* **Smartphone App Version**: N/A

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Tried to start a flow, which consists of: pressing a certain 443 Mhz remote control button and then let homey send out a certain IR signal to the television.

I have setup random respones from Homey, to make it all a bit more lively. I have this filled in: Happy Movie time! Don't forget to bring me some popcorn; Turning the television on

Making the sentences:
- Movie time! Don't forget to bring me some popcorn
- Turning the television on

**What did you expect as result?**

A correct spoken sentence, instead of it being randomly stuck with my sentence.

**What was the result?**

The second sentence is consistently working, the first sentence is consistently 'hanging' Homey. It goes like this: Movie Time! Don't forget to bring me... and then it stays in yellow glow, semi-unresponsive and without any voice response anymore.

Flow is this one:
![image](https://user-images.githubusercontent.com/529552/39703377-2b1b78f2-5208-11e8-94de-314bd29bb8fb.png)

Even filmed the result:

https://www.youtube.com/watch?v=LbFadP9-8ec

**Any other remarks**

**Comment by bvdbos** [comment] 2018-05-07 20:35
isn't this the same as #2052 ? Removing the IR-action does work for the voice-part?

**Comment by MathijsG** [comment] 2018-05-07 21:31
Will try this tomorrow.

**Comment by jjtbsomhorst** [comment] 2018-05-10 06:02
For some reason Homey busy doing the IR thing. What you could do is having a timeout on your speech card ( little clockwork on the right top corner) so it will talk to you a second after the command IR command has finished. I know this is a workaround but maybe it can help you out here.

**Comment by MathijsG** [comment] 2018-05-10 07:41
That sounds like a proper workaround for the time being. Will try it later, I rather have first voice and then IR, so maybe I can delay it the other way around.

**Comment by jeroenvollenbrock** [comment] 2018-05-10 17:57
Closing as duplicate of #2052

**Closed by jeroenvollenbrock** 2018-05-10 17:57 UTC
