### ISSUE TITLE
Qubino ZMNHOD1 Flush shutter centrale bedieningsunit smart home

### ISSUE THREAD

**Issue by fvanbeenen** [athombv/homey#2140] opened 2018-01-06 11:59 UTC
Metadata

Homey Version: 1.5.6-rc.8
Homey Log Code:
Smartphone Platform:
Smartphone App Version:
If related to a Homey App: qubino

Homey App Version: v1.1.8
Homey App Log Code:
Affected Devices (preferably product codes):Qubino ZMNHOD1 Flush shutter centrale bedieningsunit smart home
What did you try to achieve?
Install the driver

What did you expect as result?
Homey to pickup the right driver

What was the result?

There was no driver to install

Any other remarks

**Comment by JPe2** [comment] 2018-01-07 17:58
I guess you try to ask to implement this module, well it is already asked on the Github page and acknowledged by Athom as an enhancement:
https://github.com/athombv/com.qubino/issues
Support for ZMNHOD1? enhancement
#22 opened on 29 Oct 2017 by Krisstenswe

**Comment by fvanbeenen** [comment] 2018-01-07 20:15
That is correct.  Do you know when it will become available? And will you gif me a sign when it is there, please?

**Comment by JPe2** [comment] 2018-01-07 21:51
I'm just a user and just following some issues, there seem to be some problems that Athom is discussing with Qubino to solve several problems in the communication of the devices, let's hope they soon are solved
see also https://github.com/clandmeter/com.qubino.shutter

**Comment by jeroenvollenbrock** [comment] 2018-01-10 16:45
Closing as duplicate of https://github.com/athombv/com.qubino/issues/22. You can subscribe to the issue to receive a notification email when anyone comments or changes the status there. 

To subscribe or unsubscribe, just click the subscribe button in the right sidebar of the issue tracker
<img width="382" alt="schermafbeelding 2018-01-10 om 17 43 50" src="https://user-images.githubusercontent.com/4551130/34784220-fbde0306-f62d-11e7-87fc-d6e3341847df.png">

**Closed by jeroenvollenbrock** 2018-01-10 16:45 UTC
