### ISSUE TITLE
Dimmer-values, in general

### ISSUE THREAD

**Issue by lurendrejer** [athombv/homey#1764] opened 2017-08-20 10:30 UTC
**What is your Homey version (Settings → System)?**

1.5.rc6

**What did you try to achieve?**
Check if dimmers have numerical values

*Please include detailed steps how we can reproduce the issue*
Buy i dimmer, add it, reboot homey

**What was the result?**
Dimmers doesn't have numerical values
...

**What did you expect as result?**

...

**Any other remarks**
Maybe duplicate of: https://github.com/athombv/homey/issues/1745

The dimmers shown in the attachments are z-wave based dimmers, all with empty values.
![image](https://user-images.githubusercontent.com/30922656/29494088-4662b8fa-85a3-11e7-8828-bf303deae985.png)

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by lurendrejer** [comment] 2017-08-20 10:30
Stuff goes wrong in flows when checking for values in the "AND/OR" columns.

**Comment by jeroenvollenbrock** [comment] 2017-08-21 17:04
Closing as duplicate of #1745

**Closed by jeroenvollenbrock** 2017-08-21 17:04 UTC

**Comment by lurendrejer** [comment] 2017-08-21 17:48
@joachimroeleveld #1745 only fixes Ikea bulbs, shouldn't this be fixed at the Core of Homey or should every app developer implement a fix? (Domitech, zhc, etc.)
