### ISSUE TITLE
Flow speech commands issue

### ISSUE THREAD

**Issue by BSWG** [athombv/homey#532] opened 2016-04-26 20:42 UTC
I have now several small flows that should respond to 'something said' or 'anything said' resulting in actions. However after a long time of processing by Homey it does not execute anything. Including my 'Debugger' flow that simply relays anything said to a speech action. Probably this is still Work in Progress, but not quite stable yet.

0.8.30

**Comment by jeroenvollenbrock** [comment] 2016-07-27 14:47
Duplicate of #338

**Closed** 2016-07-28 11:21 UTC
Labels: speech-input
