### ISSUE TITLE
[KaKu] No lamp icon in device picture by direct pairing

### ISSUE THREAD

**Issue by KroontjesPen** [athombv/homey#991] opened 2016-10-12 08:23 UTC
**What is your Homey version (Settings → System)?**

Homey 0.10.3
KaKu 2.6.2

**What did you try to achieve?**
A direct pairing of an ADC-1000 socket for switching a lamp 

**Please include detailed steps how we can reproduce the issue**
The normal direct pairing rules.

**What was the result?**
Only the pictures of the socket.
...

**What did you expect as result?**
A lamp icon right under.

...

**Any other remarks**
If you do a pairing by **remote** e.g AYCT-102, wall switch then lamp icon right under is there.
See right picture.

...
![wereldbol](https://cloud.githubusercontent.com/assets/5736105/19302741/d19bc8a0-9065-11e6-9f27-1b6e794a8512.png)

**Comment by KroontjesPen** [comment] 2016-10-12 09:50
New info:
The ADC-300 (dimmer) is given in **both** pairing cases the lamp icon.

**Comment by bvdbos** [comment] 2016-10-12 10:00
Probably you should wait a while (10-30 sec? don't know) before choosing the type of device... Emile metioned that in another bug...

**Comment by WeeJeWel** [comment] 2016-10-12 10:34
Yep, this is a duplicate of #968

**Closed by WeeJeWel** 2016-10-12 10:34 UTC

**Comment by KroontjesPen** [comment] 2016-10-12 10:54
Oops sorry.
