### ISSUE TITLE
Window blinds (rolluikschakelaar) use configuration 

### ISSUE THREAD

**Issue by mwandzik** [athombv/homey#1470] opened 2017-04-13 13:34 UTC
**What is your Homey version (Settings → System)?**
Homey Firmware Versie: 1.1.9

**What did you try to achieve?**
The dutch command for close/open curtains (Gordijnen dicht & Gordijnen open) also adresses sunsceens and beamer screens.

An option to add a tag/category to a window blind device to let homey know if it is a real curtain of another device would be nice.

**Comment by Tweake** [comment] 2017-04-24 11:56
duplicate of #1295

**Closed by Tweake** 2017-04-24 11:56 UTC
