### ISSUE TITLE
KAKU ABST-604 unreliable

### ISSUE THREAD

**Issue by magtimmermans** [athombv/homey#807] opened 2016-08-20 19:06 UTC
**What is your Homey version (Settings → System)?**

Homey Firmware Version: 0.9.2

**What did you try to achieve?**

I have a simple flow. When it gets dark (sensed by the ABST 604) the lights should go on and a pushover message will be send to my phone. At 23.00 the light will be put off by another flow.

_Please include detailed steps how we can reproduce the issue_

ABST 604 notice it get dark and I have a time after 16.00 o clock it switch the lights on. (KAKU)

**What was the result?**

It works reasonable in the 8 version but in the 9 it does not work most of the time. It seems also that the range of the signal is shorten a lot. A lamp that did work in the 8 version now never goes on anymore.

**What did you expect as result?**

That it work stable always.

**Any other remarks**

...

**Comment by waariswallie** [comment] 2016-08-21 08:18
I have the same problem, with the same sensor type. Just after rebooting the Homey, the flow works once, switching on the light. The next times, when the sensor switches on, the light does not turn on, however the dashboard shows the light is on, b ut there is a signal sent to my phone. Same software version on my Homey.

**Comment by jeroenvollenbrock** [comment] 2016-08-22 15:02
@ReinierH: This is actually the same issue as #728. In 0.9, the behavior of the 433Mhz subsystem has changed slightly to automatically restore the 433Mhz capabilities upon crashes and timeouts, but apparently, the fix for this issue does not cover the case where _just_ the receiving side of the 433MHz system crashes.

**Comment by magtimmermans** [comment] 2016-08-22 20:41
I am not sure this is the same issue. If this is the automatic restore capability then it looks like this is not working. But in my case it is only this device abst 604 and the range is a lot shorter. My lamp at 7 meters distance is not working anymore at all. I have completely reset homey and add a dedicated the devices and flows again without any improvement. 

In addition it is less reliable as version 0.8.x

**Comment by sleutelsnet** [comment] 2016-08-24 10:07
Same problem here (0.9.2 and KAKU 2.2.0).

Homey and Kaku connect, but after a while (1 or 2communication events), Homey does not respond any more to Kaku signals (Homey can still send signals to Kaku, but does NOT receive any). 
Reset fixes the issue only temporarily.

**Comment by magtimmermans** [comment] 2016-08-24 11:00
I saw when the device is one meter away then it is a little bit better... The distance is really decreased.

**Comment by sleutelsnet** [comment] 2016-08-24 12:04
I have tested the distance by moving the sender and/or receiver closer to Homey, but my conclusion is that the distance is not an issue here.
The Kaku app seems to have stopped (crashed?).

**Comment by magtimmermans** [comment] 2016-08-24 13:03
In my case it takes 3-4 times is tops working and with a distance of 7 meter it works only once?!

**Comment by magtimmermans** [comment] 2016-08-27 11:25
I have only that 1 of the 3 lamps switch off (~3 meter distance) and the other not (the fourth one is at 7 meters and never works).

**Comment by ReinierH** [comment] 2016-09-06 15:55
To make things clear, after rebooting everything works normal. After sending approx 3 times the range decreases? Does it effects both the sending and receiving distances?

@sleutelsnet 
Are you sure it wont receive anymore or could it be a significant decrease in distance?

Could everyone regarding this issue provide me a log?  i'm pretty sure i have solved the problem but i'm unable to reproduce this issue myself.

**Comment by magtimmermans** [comment] 2016-09-06 17:09
Hi,

Some more info. Try to add a PAR 1000. You can add them with selecting the adapter or the remote. When using the adapter try to switch this to "channel" B3 (anything other then A1-3). This will fail all the time for me. When I use A1-3 it works but sometimes. When I add the Switch using the remote, it is much more reliable?!?!  I will try to send you a log file in the weekend as I am now not at home.

Succes!

**Comment by jeroenvollenbrock** [comment] 2017-12-05 15:07
Closing to combine under #2023.

**Closed by jeroenvollenbrock** 2017-12-05 15:07 UTC
Labels: bug, Homey Core, Native, RF
