### ISSUE TITLE
Fibaro FGS222 endpoints mix-up with main device

### ISSUE THREAD

**Issue by freemann** [athombv/homey#806] opened 2016-08-19 21:50 UTC
**What is your Homey version (Settings → System)?**
0.9.2

**What did you try to achieve?**
Reliable/proper UX on switching the relay endpoints, where the main-device is also switching the first endpoint end mixing things.

**Please include detailed steps how we can reproduce the issue**
Pair a Z-Wave switching device with multiple endpoints and switch the main-device and first endpoint.

**What was the result?**
When switching the main-device, it switches endpoint 1, but endpoint 1 isn't updated. 

**What did you expect as result?**
I expected that if the main-device is "switched" and the first relay(endpoint 1) is switched, that the GUI also shows endpoint 1 is switched.

**Any other remarks**

...

**Comment by caseda** [comment] 2016-08-19 22:28
It's actually not a mix-up, the main device is now endpoint 1 as well, homey can't send reports to 2 different devices (Endpoints in this occasion) with 1 report,
that's why endpoint 1 (relay 1) now isn't updating/changing.

Conclusion, the main device should not be endpoint 1, but a main controller (that switches both relais at the same time, or not be able to switch at all, but that would need a big change in capability settings)

**Comment by freemann** [comment] 2016-08-19 22:34
No idea what is causing this problem and/or how to fix it. Switch main device and endpoint1 isn't giving a great UX and that should be fixed. 
For me it could work if main device is switched, endpoint1 is also changed and visa versa.

**Comment by jeroenvollenbrock** [comment] 2016-08-20 06:06
Can you send me a log after this occurs? Can you confirm if this only occurs with certain command classes, or with all of them? (I've seen cmd-cls-meter multichannel nodes that do work). Can you also check your association groups and tell me if they're valid?

**Comment by freemann** [comment] 2016-08-20 07:52
From the manual:
> Fibaro Switch provides association of three groups.
> 1st group is assigned to key no. 1
> 2nd group is assigned to key no. 2
> 3rd group reports state of devices. Only one device can be
> associated to this group.

Settings of the Z-Wave node in Homey;
![screenshot - 20_08_2016 09_44_45](https://cloud.githubusercontent.com/assets/601053/17829826/efc06ba8-66ba-11e6-94f7-94da8d76676a.png)

From which point do you guys want a log? Pairing? Switch certain endpoints? or... ?

**Comment by jeroenvollenbrock** [comment] 2016-08-20 07:55
About 15 seconds after the gui fails to update would suffice.

**Comment by freemann** [comment] 2016-08-20 08:09
Its not really a fact of failing to update the GUI.
I added this 2x1,5 relay, which has 2 endpoints and Homey "thinks" there are 3 endpoints.
Here a screenie from the Android App;
![untitled-2](https://cloud.githubusercontent.com/assets/601053/17829889/09a55ce8-66bd-11e6-9268-4fbda315cc94.png)

When I tick the first mobile card switch on; relay1 is switched on
When I tick the second mobile card switch on; there's no reaction
When I tick the third mobile card switch on; relay2 is switched on

When I tick the third mobile card switch off; there's no reaction
When I tick the second mobile card switch off; relay1 is switched off
When I tick the third mobile card switch off; relay2 is switched off

So both GUI switches 1 and 2 are "associated" with relay1, but the are not "working together" where I click Switch1 and Relay1 is switch, I would expect Switch2 to update.

I did some switching and send you guys a log; 6C73603910

**Comment by jeroenvollenbrock** [comment] 2016-08-22 12:25
(Possible duplicate of #804)

**Comment by caseda** [comment] 2016-08-22 14:54
Not a duplicate
FGS-222 (command class "binary switch") end points are adressabel,
command class "multilevel switch" end points are not.

The real issue is that it's not adressabel like #804.
The issue is, that endpoint 1 is **not** being reported to, because it is only being reported to the main device.
Even though endpoint 2 is being reported to properly.
Conclusion: main device also holds the "endpoint 1" tag, and homey only reports to 1 endpoint 1.

main device should only be there to:
1. turn on/off both relays
2. have no on/off capabilities but that is not possible.

**Comment by WeeJeWel** [comment] 2016-08-23 11:01
This is more an issue for https://github.com/athombv/node-homey-zwavedriver, as Homey seems to implement the Z-Wave protocol correctly.

I agree that the mapping of a 'main' device to endnode 1 is counter-intuitive, but it's the 'Z-Wave way of things'

**Closed by WeeJeWel** 2016-08-23 11:01 UTC
Labels: bug, Homey Core, zwave
