### ISSUE TITLE
IKEA Trådfri and KaKu Zigbee stopped working after 1.5.4

### ISSUE THREAD

**Issue by dbonsaksen** [athombv/homey#1950] opened 2017-11-10 15:40 UTC
**Metadata**

* **Homey Version**: 1.5.4
* **Homey Log Code**: 58C792172C
* **Smartphone Platform**: IOS
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**: IKEA / KaKu Zigbee
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
After the 1.5.4 experimental update a lot of mye zigbee devices stopped working. This happend to both my 6 IKEA trådfri GU10 dimmables and some devices i've used with the KaKu zigbee app. PTP does not work, neither does removing the KAKU devices from my network, that actually made it worse.

When including the device again it appears like this, just a standard device with no dimming possibilities. Which used to be there.

![skjermbilde 2017-11-10 kl 16 38 21](https://user-images.githubusercontent.com/28441083/32665741-9760a7f8-c635-11e7-9de1-5681f9144d84.png)
 

**What did you expect as result?**
Working as usual.

**What was the result?**
Not being able to control my entire bathroom.

**Any other remarks**

**Comment by bvdbos** [comment] 2017-11-10 15:42
See #1936 ? Fix for next release probably...

**Comment by jeroenvollenbrock** [comment] 2017-11-10 19:27
Closing as duplicate of #1936

**Closed by jeroenvollenbrock** 2017-11-10 19:27 UTC
