### ISSUE TITLE
[nl.klikaanklikuit] ACM-3500 doesn't always switch since v4.0.2

### ISSUE THREAD

**Issue by corkorten** [athombv/homey#2734] opened 2018-08-02 10:58 UTC
**Metadata**

* **Homey Version**: 1.5.12
* **Homey Log Code**:
* **Smartphone Platform**: ios
* **Smartphone App Version**: homey

**If related to a Homey App:**
* **Homey App Version**: latest
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

my homey workt pereftly with klikaanklikuit acm3500 with the update you can program it as another device but sometimes it switch sometimes not in a flow i does not rspond t

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by WeeJeWel** [comment] 2018-08-03 12:32
Duplicate of #2728, please follow the discussion there.

**Closed by WeeJeWel** 2018-08-03 12:32 UTC
