### ISSUE TITLE
[nl.klikaanklikuit] Unable to manage devices after a few days

### ISSUE THREAD

**Issue by efriethoff** [athombv/homey#2167] opened 2018-01-19 15:03 UTC
**Metadata**

* **Homey Version**: 1.5.6-rc.8
* **Homey Log Code**: D214BDEA69
* **Smartphone Platform**: Android
* **Smartphone App Version**: v2.4.9 build 79

**If related to a Homey App:**
* **Homey App Version**: v3.1.5 - 22.06.17
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
I wanted to switch off all the lights

**What did you expect as result?**
Turn off all the lights

**What was the result?**
All the lights turned off, but the Klik-aan-klik-uit-devices

**Any other remarks**
It did not matter what i tried to do, no response from the mobile devices, nor with voice-commands, nor via my laptop.
Nothing changed the status of the KAKU-devices.

The only way to solve the issue was to power-off homey and turn it on again after a few seconds.
This behavior occurs more often after a few days.

I encountered this behavior never before and started a few days after homey was updated to 1.5.6-rc.8.

I don't know if this is a KAKU issue, because that app remained the same, but it is affected by something.

Maybe some other users encountered this behavior as well...

Kind regards,
Eric

**Comment by Vincent75b** [comment] 2018-01-21 09:23
Same here, all of the KAKU device do not work anymore!

**Comment by CootNL** [comment] 2018-01-24 19:28
I am also have the Homey Firmware Versie: 1.5.6-rc.8.
But I have the same problem with the Ikea Bulb.

**Comment by Dijker** [comment] 2018-01-24 21:11
@CootNL 
Can you tel me the link between this problem and your problem? 
IKEA and [nl.klikaanklikuit]   do not share anything in radio or drivers as far as I know.

**Comment by CootNL** [comment] 2018-01-25 18:43
@Dijker I have exact the same problem but with an other driver. I do not know if this is connected but maybe the problem is in the core.

**Comment by jeroenvollenbrock** [comment] 2018-02-12 15:35
Closing as duplicate of the concatinated issue #2023

**Closed by jeroenvollenbrock** 2018-02-12 15:35 UTC
Labels: RF, bug, watch
