### ISSUE TITLE
[APPv2]   Settings --> Language

### ISSUE THREAD

**Issue by priknr1** [athombv/homey#1874] opened 2017-10-11 06:24 UTC
**What is your Homey version (Settings → System)?**
1.5.3

**What did you try to achieve?**
Just browsing the app

*Please include detailed steps how we can reproduce the issue*
In the new app, go to More-->settings --> Language

**What was the result?**
It shows English is selected

**What did you expect as result?**
Showing Dutch is selected, since my homey is set to Dutch

**Comment by Inversion-NL** [comment] 2017-10-11 11:15
Confirmed (and double checked in Homey settings).
I do have my phone set to English. Don't know if you guys have your phones set to English?

**Comment by Dijker** [comment] 2017-10-11 11:43
Phone OS is English of course 
;-)

**Comment by joachimroeleveld** [comment] 2017-10-11 14:55
Should be fixed in the next release!

**Comment by antigreja** [comment] 2017-10-23 14:26
On iOS, when I changed the language from English to Dutch my Homey must be restarted? I do not understand, does this changes the language of Homey itself or only in the app? This because the language of Homey itself was already in Dutch. Also after a couple of days (do not know when) the language of the app has automagically changed back to English. Will this bug also be solved by the next release?

**Comment by priknr1** [comment] 2017-10-24 05:43
@antigreja    That is what is stated in my issue:   my Homey is alrewady set to Dutch,  Yes it is for your homey, not for your app.

On the right side of this page you can see the status:
bug
Homey Smartphone App (Core)
**Staged for release**

So yes, in the next version it should be fixed

**Comment by antigreja** [comment] 2017-10-24 07:40
@priknr1 not completely, because my question is also about the language of the app itself. This also changes between Dutch and English.

**Comment by joachimroeleveld** [comment] 2017-10-24 10:29
The setting changes both the app language and Homey's language (which determines selectable voices for example). The app has not been translated into Dutch yet, but in the next release at least your Homey's language should change.

**Comment by antigreja** [comment] 2017-10-24 11:32
The confusion here is that app indeed is translated into Dutch, but perhaps only partially. When I set the language to Dutch (and Homey reboots) for example it states 'Apparaten' in the left lower corner. When it changes back to English (for no apparent reason) it is 'Devices' again.

**Comment by joachimroeleveld** [comment] 2017-10-24 11:53
Yes, this was actually added to indicate that the language has changed. However, other translations are not added yet. But I understand the confusion. I will remove those Dutch translation strings so it does not seem that the app has already been translated.

**Comment by joachimroeleveld** [comment] 2017-10-30 20:25
This should be fixed in the next release which has just been released. Feel free to reopen if you still encounter issues. Thanks!

**Closed by joachimroeleveld** 2017-10-30 20:25 UTC
Labels: bug, Homey Smartphone App (Core), Staged for release
