### ISSUE TITLE
Appstore error

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2423] opened 2018-04-11 21:05 UTC
In appstore I get this

![afbeelding](https://user-images.githubusercontent.com/23163409/38643186-9e2ca4be-3ddc-11e8-82da-16e0b0ade3ce.png)

when clicking on 
Leendert de Kok his app (which I can install from homey) 
I get this error in the appstore
![afbeelding](https://user-images.githubusercontent.com/23163409/38643247-cf5c2ce4-3ddc-11e8-81e8-89d8a345c0d0.png)

I see differences in how for the 2 apps are develloped so maybe it will be wise to combine / merge sources

**Comment by Dijker** [comment] 2018-04-11 21:35
The Xiaomi mi flora is still a closed alpha app. 
See the forum: 
https://forum.athom.com/discussion/5030/app-xiaomi-mi-flora-sensor-ropot-community-app/p1

Searching in the App store and finding alpha apps is a know issue #1670 

only your last point remain, but that's up to the developers, else we have two Apps and you can Choose witch suites you best.

**Comment by jeroenvollenbrock** [comment] 2018-04-12 18:44
Closing as duplicate of #1670

**Closed by jeroenvollenbrock** 2018-04-12 18:44 UTC
