### ISSUE TITLE
issue:INTERVIEW_MULTI_CHANNEL

### ISSUE THREAD

**Issue by vanderaatje** [athombv/homey#1261] opened 2017-01-13 20:53 UTC
**What is your Homey version (Settings → System)?**
Homey Firmware Versie: 1.1.2

**What did you try to achieve?**
Pair my Duwi Everlux dimmer (Everlux SKU: ZME_05433)

*Please include detailed steps how we can reproduce the issue*
Use an Duwi Everlux dimmer SKU: ZME_05433 and try to pair it

**What was the result?**
The pairing stops/times out at INTERVIEW_MULTI_CHANNEL part

**What did you expect as result?**
I would expect the device was added

**Any other remarks**
This type of dimmer was working for in [november](https://forum.athom.com/discussion/comment/36560/#Comment_36560) for all three dimmers that I have of this brand

**Comment by jeroenvollenbrock** [comment] 2017-02-14 12:18
Can you please let me know whether this issue persists in v1.1.9 or not?

**Comment by bm480** [comment] 2017-02-20 18:13
Still not working in v1.1.9.

See: https://github.com/IcarusProject/me.zwave/issues/11

**Comment by vanderaatje** [comment] 2017-02-24 08:52
Still not working in version 1.1.9

**Comment by RobinBol** [comment] 2017-03-02 15:27
We have found the cause of this issue, it is fixed in an upcoming Homey firmware update. Please re-open if you are, by then, still encountering this issue.

**Closed by RobinBol** 2017-03-02 15:27 UTC
Labels: waiting for user feedback
