### ISSUE TITLE
hue app doesnt see all lamps in version 1.0 with fresh reinstall

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#668] opened 2016-06-04 06:45 UTC
**What is your Homey version (Settings → System)?**

0.8.36

**What did you try to achieve?**

installing my second homey . Homey only sees 6 of 14 devices. i have all kind off lights, hue bulbs living whites and philips plugs.

*Please include detailed steps how we can reproduce the issue*

add devices with hue app
**What was the result?**
only 6 devices were detected by hue app
...

**What did you expect as result?**

...

**Any other remarks**
3days later : someone put down the power of homey in the weekend while i was away , i powered homey up and 4 times a red ring as result but the fifth time he did it correct and all my lights of hue are back......... 

...

**Comment by bvdbos** [comment] 2016-06-04 18:45
confirmed: https://forum.athom.com/discussion/comment/24622/#Comment_24622

**Comment by philsniff** [comment] 2016-06-04 18:52
i habe exactly the same issue. only 3 of 10 devices are mentioned. osram light are complete onoff: invalid_type.

reinstall the app, reboot homey : nothing works

before on 0.8.32 all lights were in place and worked

**Comment by nattlip** [comment] 2016-06-05 18:05
3days later : someone put down the power of homey in the weekend while i was away , i powered homey up and 4 times a red ring as result but the fifth time he did it correct and all my lights of hue are back.........

**Comment by WeeJeWel** [comment] 2016-06-07 09:46
Can you guys run the app using `athom-cli` and paste the output here?

**Comment by philsniff** [comment] 2016-06-07 11:34
i am at work now, but i will run the app in the evening and paste it here. will be late in the evening...

**Comment by WeeJeWel** [comment] 2016-06-07 11:37
Alright. Also please update to 1.0.2, I've fixed some bugs here and there.

**Comment by philsniff** [comment] 2016-06-07 11:39
jepp, ok! ;-)

**Comment by philsniff** [comment] 2016-06-07 16:47
with version 1.0.2 all hue devices are now shown!! perfect ;-)
but when you want to go to settings of the device there is something wrong:

![schnappschuss_060716_064537_pm](https://cloud.githubusercontent.com/assets/7848863/15866750/48b38e58-2ce0-11e6-9756-f578bccaefc5.jpg)

**Comment by philsniff** [comment] 2016-06-07 16:48
i am back at 9:30 p.m. ...

**Comment by nattlip** [comment] 2016-06-07 17:08
i cant test untill friday.

**Comment by ThaYoung1** [comment] 2016-06-08 11:38
All my hue lights (and via the hue bridge 2.0 connected Osram garden spots) suddenly stopped working yesterday. I already had 0.8.36 running since release day and the lights did work correct until yesterday. 

![image](https://cloud.githubusercontent.com/assets/5597548/15893137/15fafd22-2d7e-11e6-96f0-cfa329057bc3.png)

The message my lights give in the devices screen is: **onoff:invalid_type**.

**Comment by bvdbos** [comment] 2016-06-08 11:43
Yesterday a new version (1.0.2) of the hue-app was published but it seems like a removal and re-install is needed for this to work.

**Comment by WeeJeWel** [comment] 2016-06-08 11:59
Yep. Actually all <1.0.2 versions contained a bug that prevented 1.0.2 from working. Uninstalling the app and re-adding devices should work.

**Comment by philsniff** [comment] 2016-06-08 12:04
i removed the hue app, reboot homey, installed hue app 1.0.2:
all lights were shown (perfect :-))

but when i clicked in the device in its settings it showed the 'onoff:invalid_type.'.
disable/enable then the app -> two of my seven light came back, the others not just showd the broken chain symbol

**Comment by Arjanvde** [comment] 2016-06-08 12:34
@WeeJeWel, If I will uninstall the HUE app, do i have to re-add all the lights again to all flows or is this back-up in the memory. I've got close to 100 flows with HUE lights, and this would be the second time I've got to recreate all flows.

**Comment by ThaYoung1** [comment] 2016-06-08 19:16
I deleted all devices, uninstalled the Hue App, reinstalled the Hue App, added all devices and still I get the error **onoff:invalid_type**.

@Arjanvde I had to re-add all the lights again to all flows. :(

**Comment by philsniff** [comment] 2016-06-08 19:31
i just tested a lot:
i just added one by one device. every time push the hue button for one light.

and it worked...until i had to add a osram light (gu10 spot, i have three of it).
what then happend: two of my philips were ok, but the other two (lightstrip and nomal bulb) were showing the broken chain symbol.

disable/enable brought no success!
then i dropped the osram spot and disabled/enabled the hue app: all philips light were there and ok!

i did this with the ather osram spots and the result was the same.

so when there are osram gu10 spots in the hue, the hue app of homey will have problems to add these and also break other lights!

before 0.8.36 i was on 0.8.32 and the old hue app.
there were no problems adding the osrams, but i wasn't able to edit there settings.

so i just think_ when there are other lights than original philips, then the new hue app from athom can't handle them right.

is this helpful @WeeJeWel or was this just allready known?

**Comment by ThaYoung1** [comment] 2016-06-08 20:23
@philsniff I have the Osram Lightify Garden Spots RGBW connected to my Philips Hue Bridge 2.0. When removing this lights from Homey the Hue App on Homey works.

**Comment by philsniff** [comment] 2016-06-08 20:33
So when you remove the osram garden Spots the hue App Works. But with the spots the app breaks right?

So are my thoughts.  

Okay, i would have a comment from @WeeJeWel about our research 😏

**Comment by Arjanvde** [comment] 2016-06-08 21:05
If Osram is the issue, I suppose that would be the same for the Dresden FLS PP IP controller which is also linked with my HUE.

**Comment by philsniff** [comment] 2016-06-08 21:09
I could bet on it. You can test it: drop the dresden and other third Partie devices fron the hue app, disable the hue app under Settings and enable the App. Then gibt back to devices and see in the hue lights will come back.

**Comment by Arjanvde** [comment] 2016-06-08 21:33
Can confirm, the Dresden unit is causing HUE to crash. Had to do a reboot in order to get everything to work after pairing.

Did a fresh instal on HUE, removed the app and had to instal it again. Will probably wait with re-adding all HUE's back to the flows 👎  (For the second time!) as a fix is not yet there.

**Comment by philsniff** [comment] 2016-06-08 21:36
Sorry for that, but i think that underlines my theory :-(

**Comment by Fire69** [comment] 2016-06-09 08:21
It's not linked to Osram/Dresden alone.  I only have Philips devices, but some are LivingWhites bulbs and plugs.
When I added all my devices, none were reachable.
Some lights are behind physical switches and aren't powered.  Some plugs are not used for the moment.
When I removed/installed the app and paired it to the bridge, I didn't select these devices.
All my other lights are working OK now.
Seems like the app has a problem with unreachable devices.

**Comment by philsniff** [comment] 2016-06-09 08:23
but my devices are all reachable. and the hue app won't conect to them

**Comment by Fire69** [comment] 2016-06-09 08:25
Maybe the bridge sends back something the hue app doesn't understand when the device is 3rd party or unreachable? :-)

**Comment by philsniff** [comment] 2016-06-09 08:26
yes something like that, right. curious :-)

**Comment by WeeJeWel** [comment] 2016-06-09 10:32
Thanks for all the info guys! I'm going to work on it today, hope I can fix all your issues :)

**Comment by philsniff** [comment] 2016-06-09 11:06
it is a pleasure to help you if we can ;-)

**Comment by WeeJeWel** [comment] 2016-06-09 11:24
I've pushed a new version (1.0.3) to GitHub. Could you guys check if it's working correctly now?

If you had any Osram lights paired, you might need to re-add them to Homey for the Dim slider to appear (blame crappy Hue docs haha).

**Comment by freemann** [comment] 2016-06-09 11:36
Just installed 1.0.3 and directly after install all lights were unreachable.
Then did a disable/enable and after it all light came back for 1 sec, then all got unreachable again and after 5-10 sec the one-for-one came back again.

did some testing with Homey and the Hue Android app shows me that the lights are reacting.

**Comment by WeeJeWel** [comment] 2016-06-09 11:40
That sounds good. They start out as unreachable, and when they're 'found' they become reachable :)

Good to hear!

**Comment by philsniff** [comment] 2016-06-09 12:00
i will test it when i come home ;-)

**Comment by ThaYoung1** [comment] 2016-06-09 12:47
I'll test it too when I get home

**Comment by philsniff** [comment] 2016-06-09 17:12
perfect @WeeJeWel !

all lights incl. osram spots work now. and the sliders too!

thank you!

**Comment by daneedk** [comment] 2016-06-09 18:41
@WeeJeWel 
I still have a problem, most likely caused by a Living Whites Plug (http://www.philips.nl/c-p/6916531PH/livingwhites-stekker)

I added all devices from my hue and got the above mentioned error 'onoff:invalid_type.' and unreachable after disabling and enabling the app. After removing devices one by one some devices got available. Tried it a couple off times more and found out that when a Living Whites Plug was included the unreachable would not go away. After removing the Living Whites Plus the other devices instantly become reachable.

Lamp info:
{
	"state": {
		"on": false,
		"bri": 0,
		"alert": "none",
		"reachable": true
	},
	"type": "Dimmable plug-in unit",
	"name": "Televisie lampen",
	"modelid": "LWL001",
	"manufacturername": "Philips",
	"uniqueid": "00:17:88:01:00:2e:9c:4f-0c",
	"swversion": "1.0.1.4591"
}

Bridge info:
{
	"name": "DK en DK",
	"zigbeechannel": 25,
	"bridgeid": "001788FFFE23BE26",
	"mac": "00:17:88:23:be:26",
	"dhcp": true,
	"ipaddress": "192.168.1.98",
	"netmask": "255.255.255.0",
	"gateway": "192.168.1.1",
	"proxyaddress": "none",
	"proxyport": 0,
	"UTC": "2016-06-09T18:25:58",
	"localtime": "2016-06-09T20:25:58",
	"timezone": "Europe/Amsterdam",
	"modelid": "BSB002",
	"swversion": "01033370",
	"apiversion": "1.13.0",
	"swupdate": {
		"updatestate": 0,
		"checkforupdate": false,
		"devicetypes": {
			"bridge": false,
			"lights": [],
			"sensors": []
		},
		"url": "",
		"text": "",
		"notify": false
	},
	"linkbutton": false,
	"portalservices": true,
	"portalconnection": "connected",
	"portalstate": {
		"signedon": true,
		"incoming": true,
		"outgoing": true,
		"communication": "disconnected"
	},
	"factorynew": false,
	"replacesbridgeid": "001788FFFE1035ED",
	"backup": {
		"status": "idle",
		"errorcode": 0
	},
	"whitelist": {
		//
		snip
		//
		"FgvId3ceemJmff7Ur4n7zTDlbpm832L5ajedakIw": {
			"last use date": "2016-06-08T20:48:53",
			"create date": "2016-06-07T17:43:33",
			"name": "Node.js API"
		},
		"igArom9Cv0yBDm4Rcffn0rFerR6M9yQ6SrqDm714": {
			"last use date": "2016-06-09T18:25:58",
			"create date": "2016-06-09T18:09:19",
			"name": "Node.js API"
		},
		"EnduJGvDi7ffN7t6D3HUmQFUoWGoMiioX2VP95sg": {
			"last use date": "2016-06-09T18:25:58",
			"create date": "2016-06-09T18:14:00",
			"name": "Node.js API"
		},
		"rvJVdUbLfcIjJzf95jMgcEJ1PhgiVdLzPwsS20IZ": {
			"last use date": "2016-06-09T18:25:58",
			"create date": "2016-06-09T18:19:55",
			"name": "Node.js API"
		},
		"qactLD6LXiT48vVP37cgRWaO-z9hk9Jj3flHO9-h": {
			"last use date": "2016-06-09T18:25:58",
			"create date": "2016-06-09T18:20:33",
			"name": "Node.js API"
		}
	}
}

I must say I'm very happy with the progress that is being made on this app! 
Would like it however that we don't need to authenticate homey on the bridge every time we want to add a light, see how the whitelist fills up. 
Also a more recognizable name would be nice, something like: {"devicetype":"nl.philips.hue#homey"} perhaps, also something that is asked for in the API http://www.developers.meethue.com/documentation/configuration-api#71_create_user

**Comment by WeeJeWel** [comment] 2016-06-09 18:52
Should be fixed in 1.0.5. Could you run that version from the github repository and verfify that it works?

*Philips' API documentation is seriously lacking...*

**Comment by nattlip** [comment] 2016-06-09 19:01
@WeeJeWel  #: Well that could be a tip for Homey, The non Athom developers of Homey experience that every day......

**Comment by daneedk** [comment] 2016-06-09 19:05
@WeeJeWel just ran 1.0.5, The Living Whites Plug is no longer causing a problem, Great! Thanks!

**Comment by nattlip** [comment] 2016-06-09 19:09
@WeeJeWel : indeed runs perfect everything works now , also the plugs etc.

**Closed** 2016-06-09 19:10 UTC

**Comment by WeeJeWel** [comment] 2016-06-09 19:34
Great to hear :)

@nattelip if you're having trouble with our docs, please let us know! We
want to improve them as well, and that's hard when everything is already so
familiar.

**Comment by nattlip** [comment] 2016-06-09 20:05
@WeeJeWel; I read a lot of explanation of how some functions should be used or written in the slack community. It would be handy to reference this in the documents, a lot of very valuable info for developers is lost this way in the enormous amount of discussion lines in Slack.  

Thr RF and Ir section isn't documented at all yet. https://github.com/athombv/node-homey-signal-validator shows a lot more properties then exposed in the api Someone already asked himself , how can homey adress Somfy, the433  frequency is not 433.92  but 433.42. Well the vlidator has the answer.

**Comment by WeeJeWel** [comment] 2016-06-10 10:20
That's true. IR & RF is to be documented (because it'll change a little bit soon).

We'll keep working on the docs!
