### ISSUE TITLE
Stutter and stall using voice.

### ISSUE THREAD

**Issue by Povlov** [athombv/homey#2249] opened 2018-02-20 17:20 UTC
**Metadata**

* **Homey Version**: 1.5.3
* **Homey Log Code**: B865147C43
* **Smartphone Platform**: n/a
* **Smartphone App Version**: n/a

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Execute long existing flow as per screenshot

**What did you expect as result?**

Regular actions and speech announcement

**What was the result?**

Speech sounds interrupted, and halts; yellow LED ring glows persistently 

**Any other remarks**
Homey needs soft reboot after that.
![screenshot 2018-02-20 at 18 19 23](https://user-images.githubusercontent.com/24312420/36438562-9d66911e-166a-11e8-8aa0-7aa0d329fda9.png)

**Comment by lubbertkramer** [comment] 2018-02-20 17:47
When you would use the search function you would know this issue is a duplicate off -> https://github.com/athombv/homey/issues/2237

**Comment by Povlov** [comment] 2018-02-21 09:02
The speech stutter issue is known and reported by me before, and I am/was
aware of existing reports.
What is new is that my Homey now freezes over this.
In my humble opinion, this is an issue in itself,


Peter de Vries

2018-02-20 18:47 GMT+01:00 lubbertkramer <notifications@github.com>:

**Comment by jeroenvollenbrock** [comment] 2018-02-26 13:30
Closing as duplicate of #2237

**Closed by jeroenvollenbrock** 2018-02-26 13:30 UTC
