### ISSUE TITLE
Missing error feedback

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#93] opened 2016-02-11 06:35 UTC
When speaking to Homey, I noticed that quite a number of times Homey seems to do something, and then nothing happens. I ask it to turn off the lights, homey does its thing with the led ring, and then... silence. No lights change. 

This is annoying. Of course, voice control is not perfect yet. But at least give me some insight in what wend wrong. Give feedback that the command was not understood. Perhaps even ask for clarification.

**Comment by bvdbos** [comment] 2016-02-11 11:30
dupe of #101 ?

**Comment by WeeJeWel** [comment] 2016-02-11 14:45
For now, the speech quality isn't perfect, so it would get rather annoying. We will definitely add this when the speech is a lot better.

**Closed by WeeJeWel** 2016-02-11 14:45 UTC

**Comment by bvdbos** [comment] 2016-02-11 14:50
Better dupe this to #104 ... feedback doesn't have to be audible...
