### ISSUE TITLE
Speech very slow

### ISSUE THREAD

**Issue by laurenssss** [athombv/homey#2237] opened 2018-02-14 18:55 UTC
The speech output is very slow and hickerish, a sentence like “ik zet het licht in de woonkamer aan” can take up to a minute to complete with some pauses in between

Running 1.5.6 rc13

**Comment by bvdbos** [comment] 2018-02-14 19:07
dupe of #1297 
Could you provide answers to the questions asked (like log-code etc). How many lights do you have in the livingroom, how many devices do you have? Are other flows running?

**Comment by laurenssss** [comment] 2018-02-15 09:07
Metadata

Homey Version:1.5.6-rc.13
Homey Log Code:E4F313E9D6

Smartphone Platform:
Iphone

Smartphone App Version:
Beta release (testflight)

If related to a Homey App:
Homey App Version: n.a.
Homey App Log Code: n.a 
Affected Devices (preferably product codes): speech output
What did you try to achieve?
when I trigger via speech " zet alle lampen in de woonkamer uit" . then homey says " ik zet het licht in de woonkamer uit" 
tried to get this as smooth sentence
What did you expect as result?
homey talking smooth
What was the result?
homey stuttering, in total the sentence takes approx a minute to complete
Any other remarks
38 apps running
approx 40 devices connected in total and some virtual ones
approx 6/7 lights in the living room
no other flows running at the same time

**Comment by ferdw** [comment] 2018-02-18 10:56
Same experience over here, for example a flow which will play every whole hour a few times the same soundfile: first four or five are played at the same time, the rest is unregulary played while they are supposed to play each with 1 sec delay. Solved this with increasing every card with 10 seconds extra delay.
Looks like a massive load on the processor, started with 1.5.6exp.

**Comment by laurenssss** [comment] 2018-02-19 08:37
same experience still on 1.5.6 firmware
example: switching off lights is triggered by fibaro lux and action card is emulate speech : 'woonkamer lampen uit" 
lights switched instantly, speech stuttering

**Comment by laurenssss** [comment] 2018-03-06 10:13
must say the last few days the speech performance is very good, maybe after upgrade to 1.5.7

only thing is, it first executes the commands in the flow (like turning lights off) and then the speech will happen, which is a bit " mosterd na de maaltijd" .
maybe something can be done about that, something like when a flow or command triggers speech, first execute speech and after execute the other commands?

**Comment by Dijker** [comment] 2018-03-06 18:29
Personally delay of execution doesn't look good for me. 
Execution should be as fast as possible.
and Speech takes some time. (preparing and the playing) 

But if you delay the execution (with the delay on the card) for a couple of seconds. Does it work as expected for you then? ( good speech and switching / action after the speech. )

**Comment by laurenssss** [comment] 2018-03-12 08:00
With 1.5.8 speech is back to slow and stuttering again

**Comment by jeroenvollenbrock** [comment] 2018-09-17 09:39
Closing as duplicate of #2217

**Closed by jeroenvollenbrock** 2018-09-17 09:39 UTC
