### ISSUE TITLE
FW 1.5.5 multiple Z-Wave issues

### ISSUE THREAD

**Issue by Eternity-again** [athombv/homey#1958] opened 2017-11-12 20:58 UTC
**Metadata**

* **Homey Version**: 1.5.5
* **Homey Log Code**: 78E03B8D1E
* **Smartphone Platform**: android
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Installed v1.5.5
- sensors from Aeotec stop reporting motion / tamper
- if the sensor does report motion, it fails as trigger in flows
= sensor report motion, but does not recover to non-motion
- Greenwave powernodes go offline

**What did you expect as result?**

Z-wave to improve, not the reverse

**What was the result?**

A worse Homey experience.

**Any other remarks**

**Comment by WeeJeWel** [comment] 2017-12-01 14:04
Duplicate of #1899

**Closed by WeeJeWel** 2017-12-01 14:04 UTC
Labels: bug, Z-Wave
