### ISSUE TITLE
ZWAVE VISION DC/AC POWER SIREN inclusion fails on step retreiving commands

### ISSUE THREAD

**Issue by jcastrol07** [athombv/homey#1354] opened 2017-03-06 22:53 UTC
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**

Include a ZWAVE VISION DC/AC POWER SIREN

*Please include detailed steps how we can reproduce the Hello

I have been trying several times to include this vision siren ant it always fails on the same step when trying to retreive commands..then the device does not appear in the devive screen, but going to the settings area under the Zwave section in the nerwork graph appears (as unknown z wave device)

**What was the result?**

Device is not included 

**What did you expect as result?**

Device included

**Any other remarks**
I used to have this device working on another network so i know device is ok

...

**Comment by RobinBol** [comment] 2017-03-10 14:38
What is the exact step the pairing fails on? INTERVIEW_MULTI_CHANNEL maybe?

**Comment by jcastrol07** [comment] 2017-03-10 22:38
Hi

It fails on step "Retrieving Command Class Version"..it stays there frozen
and then reverts the screen back to "No Z-Wave device has been found" and
no new icon on devices appears ..but it really added something on the
background because if you go to the Network graph in settings appears a new
Unknown Z-Wave device

Some screen shots to see if it has a solution
[image: Inline image 1]

[image: Inline image 2]


[image: Inline image 3]

   -

**Comment by WeeJeWel** [comment] 2017-03-14 19:31
Can you disable the app, include the device as a basic device while the Chrome Console is open and paste the output here?

**Comment by jcastrol07** [comment] 2017-03-14 20:34
Hello

Sorry, but Not sure how to follow your instructions

How do I disable the app?..I was including the device through the general
Homey Zwave icon on adding devices (see print screen) ..and i do not see
How to disable that or what alternative I have then to include the device
I access through the Windows exe - HomeySetup-v1.0.2

[image: Inline image 2]

**Comment by WeeJeWel** [comment] 2017-03-15 12:16
Ah, if you didn't install a specific app, you can skip that step.

Please visit https://my.athom.com in Google Chrome, and open the console while pairing to provide me with a debug log, so I can further troubleshoot your issue.

**Comment by jcastrol07** [comment] 2017-03-15 19:59
Hello

I have finished replicating the issue as you described

I also generated the logs and got the code 7947FFD250

Please let me know if you need anything else

Thanks again

**Comment by RobinBol** [comment] 2017-03-16 11:11
Hi! Thanks for your effort, what Emile meant is the console output of the browser, not so much the Homey log.

In order to do this go to my.athom.com, and click on your Homey. Then right click in the browser and click inspect (Google Chrome), then open the console tab. If you now pair the device as generic Z-Wave device, there will be some text shown in the console tab. After the pairing is done/aborted, please copy the text from the console to here so that we can inspect what is going wrong.

**Comment by jcastrol07** [comment] 2017-03-16 23:04
Hi
Thanks for the instructions

I am enclosing the details copied from the console when tryng to pair the
device. Please let me know if this gives some light to the problem


Synchronous XMLHttpRequest on the main thread is deprecated because of its
detrimental effects to the end user's experience. For more help, check
https://xhr.spec.whatwg.org/.
send @ jquery.js:3
ajax @ jquery.js:3
Z._evalUrl @ jquery.js:3
domManip @ jquery.js:2
append @ jquery.js:2
(anonymous) @ jquery.js:2
Z.access @ jquery.js:2
html @ jquery.js:2
window.Homey.showView @ drivers.js:1
(anonymous) @ drivers.js:1
c @ jquery.js:2
fireWith @ jquery.js:2
n @ jquery.js:3
(anonymous) @ jquery.js:3
VM493:1 status WAIT
VM493:1 status ADD_NODE_STATUS_LEARN_READY
VM493:1 status ADD_NODE_STATUS_NODE_FOUND
VM493:1 status ADD_NODE_STATUS_ADDING_SLAVE
VM493:1 status ADD_NODE_STATUS_PROTOCOL_DONE
VM493:1 status ADD_NODE_STATUS_DONE
VM493:1 status INTERVIEW_CC
VM493:1 status ADD_NODE_STATUS_LEARN_READY

**Comment by WeeJeWel** [comment] 2017-03-17 12:22
Thanks for the log. The issue seems to be on the device's end. To be sure, I would need to inspect the device myself. You could send it to us so I can take a look, but I can imagine that's too much effort from your side.

**Comment by WeeJeWel** [comment] 2017-03-17 12:22
I'm closing this issue because the issue is device-related, until proven otherwise.

**Comment by jcastrol07** [comment] 2017-03-17 12:29
Hello

I really do not think it is a device problem itself...at least
compatibility with Homey  - Device. Tis device was included with no issues
in another Zwave network with another controller. I was migrating my
devices from this other controller to Homey

Is there nothing else to be done?

Regards

**Comment by WeeJeWel** [comment] 2017-03-17 12:35
Some controllers don't follow the Z-Wave specification, or are more limited in functionality which enables them to be less picky.

As a last resort, can you try pairing the device with the Z-Wave Log open? You can find it under Settings -> Z-Wave -> Show stuff for geeks

Then paste the log you find there. Otherwise I really have to get my hands on this device to see where it goes wrong.

**Comment by jcastrol07** [comment] 2017-03-20 22:09
Hello

Here below see the logs while trying to include it
If this does not share more light to solve the issue I have no problem
sending by mail the device over to you so can be tested..please provide an
address

It was node 30 the one being assigned to the device and Home ID: 3399280201

Thanks

Logs

[2017-03-20T22:01:46.023Z] Node[8]: Received application command for
COMMAND_CLASS_WAKE_UP, data: 0x07

[2017-03-20T22:01:46.036Z] Node[8]: Marked as online

[2017-03-20T22:01:46.513Z] command status: addNode, status: INTERVIEW_CC

[2017-03-20T22:01:46.519Z] Node[30]: sendData to COMMAND_CLASS_VERSION,
params 0x1325

[2017-03-20T22:01:46.519Z] Command start: sendData

[2017-03-20T22:01:46.535Z] ProcessSendData[58252]: To node: 30 with data:
0x861325 and txOptions: ACK,AUTO_ROUTE,EXPLORE

[2017-03-20T22:01:46.611Z] Command end: sendData

[2017-03-20T22:01:56.050Z] Node[8]: Marked as offline

[2017-03-20T22:02:16.511Z] Node[16]: Received application command for
COMMAND_CLASS_CRC_16_ENCAP, data:
0x01600d0103320221340000042e0009000004be2e53

[2017-03-20T22:02:16.548Z] Node[16]: Decapsulated frame from
COMMAND_CLASS_MULTI_CHANNEL to COMMAND_CLASS_METER, data
0x0221340000042e0009000004be

**Comment by jcastrol07** [comment] 2017-04-04 17:02
Hello

Have you had a chance to look at the logs?
If you need me to send the device for you to solve the issue tehre is no problem on my side
Please provide address

**Comment by WeeJeWel** [comment] 2017-04-05 12:15
Hi, yes, sorry for the late reply!

If you could send the device to:

Athom B.V.
t.a.v. Emile Nijssen (from jcastrol07)
Rigtersbleek-Zandvoort 10
7521BE Enschede

Then I'll gladly take a look!

**Comment by jcastrol07** [comment] 2017-04-10 10:23
I have already sent the device

Thanks for the support

**Comment by WeeJeWel** [comment] 2017-05-02 13:19
Fixed. The device is faulty, because if a command is sent too fast it refuses to pair. I've added a 1s delay, which solves the problem.

**Comment by WeeJeWel** [comment] 2017-05-02 13:35
I've revised my solution. The delay can now be set manually by the app developer by specifying `getCommandClassVersionsWait` in the `driver.zwave` object. For example:

```
      "zwave": {
	"getCommandClassVersionsWait": 1000,
        "manufacturerId": 1,
        "productTypeId": 2,
        "productId": 3,
```

Please note that these properties are only used when the user clicks on the right driver icon, so not the generic Z-Wave pair wizard.

**Closed** 2017-06-14 10:43 UTC
Labels: Staged for release, Z-Wave
