### ISSUE TITLE
Feature request: improve presence cards

### ISSUE THREAD

**Issue by bliekp** [athombv/homey#1831] opened 2017-09-22 11:06 UTC
It would be very nice if the presence cards were better suited for multiple users in the home. I would suggest cards like:

- the first user came home
- the last user left the home

Because now if I leave the house, the heating and lighting turns off, while my girlfriend is still in the house... There is no other way to create the expected behaviour which is that Homey should know when *someone* is home or *all* have left the house.... They only way to create this now is with BetterLogic variables and it gets too complex too fast.

**Comment by chrisboer** [comment] 2017-09-22 13:05
There is use owntracks with geofence and you can trigger Homey away or home with that

**Comment by Heki2017** [comment] 2017-09-24 10:00
@chrisboer can you elaborate a little on "use owntracks" ? Is it separate software or build in functionality in Homey ? Thanks for the effort

**Comment by bvdbos** [comment] 2017-09-24 10:11
https://forum.athom.com/discussion/1910/app-owntracks-client-for-homey/

**Comment by Heki2017** [comment] 2017-09-24 10:18
thanks @bvdbos for fast response

**Comment by bliekp** [comment] 2017-09-24 10:53
Owntracks is not a solution to the lack of functionality in Homey. It is a workaround. It works, but it drains too much battery from my phone. Also, since a while the geofencing in the Homey app finally works... let's use it.

This feature request should be relatively simple to create for Athom. Let's encourage them too do this. It should be basic functionality (and frankly I think this should've been in from the start!).

**Comment by Dijker** [comment] 2017-09-24 12:56
I see definitely a use-case for flows that trigger on First and last user as you describe and want to think in the Box, sorry In the globe of Homeys default capability. 

Thinking Out of the Box, sorry out of the Single Flow card: Both flows are easy to create with only two cards extra (and one tag). 
If you only need one of the two flows, you still need to create both to let it function. 

![image](https://user-images.githubusercontent.com/12412734/30782537-60d60fdc-a134-11e7-8391-679479fc5a51.png)

 
![image](https://user-images.githubusercontent.com/12412734/30782481-4b7b7740-a133-11e7-9fbc-056e338405a6.png)

Testing both once to set the Tag once to initialize then it should work as requested.

So don't know if this justifies an extra card.

**Comment by WeeJeWel** [comment] 2017-11-20 16:11
Duplicate of https://github.com/athombv/homey/issues/1954 (Yes you were first ;-))

**Closed by WeeJeWel** 2017-11-20 16:11 UTC
Labels: enhancement
