### ISSUE TITLE
[Android App] Wrong scala on Tablet 

### ISSUE THREAD

**Issue by dondanny82** [athombv/homey#1227] opened 2017-01-03 21:59 UTC
I'm using a 10.1 Samsung Tab. 
First request is to enable the landscape mode, because I think that many people would use a tablet as a wall mount.  
Second is a bug: the size of the icons in the app is to big. Because of this you didn't see all of the required information. The devices don't fit on the screen so the slider isn't visible. 
Maybe the whole "device box" can be a little bit decreased?!

**Comment by WeeJeWel** [comment] 2017-01-09 16:41
Can you post a screenshot?

**Comment by dondanny82** [comment] 2017-01-09 16:47
![image](https://cloud.githubusercontent.com/assets/24892310/21774725/ab932c24-d693-11e6-9e99-edd8f02eb244.png)

**Comment by JPe2** [comment] 2017-01-21 14:39
@WeeJeWel  Same as  https://github.com/athombv/homey/issues/1231
 Samsung Tablet SM-T520 with Android 4.4.2

**Comment by WeeJeWel** [comment] 2017-05-16 11:01
Duplicate of #1231

**Closed by WeeJeWel** 2017-05-16 11:01 UTC
Labels: waiting for user feedback
