### ISSUE TITLE
z-wave unable to add device

### ISSUE THREAD

**Issue by tunf** [athombv/homey#1173] opened 2016-12-19 16:00 UTC
**What is your Homey version (Settings → System)?**

1.0.4

**What did you try to achieve?**
Include a fibaro door sensor or a popp wall dimmer or z-wave.me wall dimmer. first 4 z-wave smoke detectors seems to work (added by homey z-wave add). first 3 door sensors include and working. I had to restart each time in between and wait for about 10/15 mins but then could add them. Number 4 and all others are not being found. 
Including fibaro door sensor tryed by z-wave by homey and by the fibaro app, same result. 
Resetted the door sensor(s) still no luck. 

I can see in system-Z-wave -> geeks that there is a include starting.

Sometimes the include is not timing out and homey keeps telling me that i need to place the device in include mode.

**Comment by WeeJeWel** [comment] 2016-12-19 17:33
Have you tried removing the devices first using `Settings -> Z-Wave -> Remove a device`?

**Comment by tunf** [comment] 2016-12-19 17:34
Yes but it was not connected at all. Also did a device reset.

**Comment by jeroenvollenbrock** [comment] 2017-03-06 13:53
Can you please let me know whether this issue persists or not?

**Comment by tunf** [comment] 2017-03-06 14:42
Yes it is still there (last try 2 weeks ago)

**Comment by jeroenvollenbrock** [comment] 2017-05-16 10:33
1.3.0-rc.7 was released to the experimental channel yesterday. It contains a lot of Z-Wave fixes, can you test if your issue is resolved there?

**Comment by tunf** [comment] 2017-05-16 19:23
Tried, unit identified, something went wrong error. Beside that all is slow now, so door sensor action reacts about 3 seconds to late then before this update.

**Comment by jeroenvollenbrock** [comment] 2017-06-12 16:18
Can you please let me know whether this issue persists or not in version 1.3.1?

**Comment by tunf** [comment] 2017-06-12 18:47
Same issue, unit identified, after adding in same wizard it tells me that the unit cannot be reached anymore, please put it closer to homey (with homey away and within 30 cm) 

Door sensor was reacting fast but after a couple of days it is very slow again, until restart. But perhaps thats another thing as speech and other apps are also slow/ stuttering.

**Comment by WeeJeWel** [comment] 2017-12-01 14:12
Duplicate of #1678

**Closed by WeeJeWel** 2017-12-01 14:12 UTC
Labels: bug, Z-Wave
