### ISSUE TITLE
App settings partly saved in App settings

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#936] opened 2016-09-30 05:49 UTC
![knipsel](https://cloud.githubusercontent.com/assets/7040452/18981956/c22bcf50-86e2-11e6-888d-e2f8b614973c.PNG)
0.10.1

my app plugwisesource has 4 app settings to contact the plugwisesourceserver: ip port username password.

*Please include detailed steps how we can reproduce the issue*

try to save the settings after entering the values.

**What was the result?**

app only saves one setting the ip.
...

**What did you expect as result?**

save 4 settings.

...

worked well in 0.10.0 and all lower firmware versions

...

**Comment by jghaanstra** [comment] 2016-09-30 07:44
Interesting, could very well be that the Harmony Hub app is affected by this as well. It crashes saying the ipaddress is null.

**Comment by nattlip** [comment] 2016-09-30 07:58
mine crashes to , the most frustrating thing is the app was updated to comply with
 0.10.0 but released yesterday together with 0.10.1 , and still crashing ..........................

**Comment by nattlip** [comment] 2016-09-30 08:39
will this issue be repaired or is there an api change , so i have to save each varriable apart.

**Comment by BasKiers** [comment] 2016-09-30 12:50
I did try to reproduce this issue but was not directly able to reproduce it. Further inspection is needed. 

Could you please check if the steps I've taken produce your issue? 
What I did was 

- install the app
- enter "1", "2", "3", "4" in the input fields
- click the save button
- wait 1 minute (important! settings are stored on the disk every 1 minute)
- console shows all 4 settings being used
- uninstall app
- install app
- all settings still persist after reinstall (visible in the console output)

**Comment by nattlip** [comment] 2016-09-30 12:54
install ? not run

**Comment by nattlip** [comment] 2016-09-30 13:04
@BasKiers . yes indeed it happens what you wrote. i shall postphone the reading of the xml from the server with more then 1 minute because the app crashes now  immediately after the savinf of the server variables. if it works which will then i will close the issue

**Comment by BasKiers** [comment] 2016-09-30 15:00
I've found the issue, It causes all apps to only be able to store settings in the first minute since it launched. The fix is staged for v0.10.2. Thanks for reporting this issue!

**Comment by bvdbos** [comment] 2016-09-30 15:07
augh, that sounds critical for a stable-release... You know, it is possible to release a FW with just one or just a few fixes (hint...)

**Comment by nattlip** [comment] 2016-09-30 19:55
i got it running in 0.10.1 by entering the values within 1 minute and restarting the app.

**Comment by jeroenvollenbrock** [comment] 2016-10-07 14:09
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.

**Closed by jeroenvollenbrock** 2016-10-07 14:09 UTC
Labels: bug, Homey Core, Staged for release
