### ISSUE TITLE
Home goes to away mode when i tell homey that i am home when he is already in home mode

### ISSUE THREAD

**Issue by basd82** [athombv/homey#1574] opened 2017-05-22 08:25 UTC
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**

Let homey know that i am home so i told 

Oke homey i am home.

*Please include detailed steps how we can reproduce the issue*

But i when i left home i forgot to tell home that i went away.

**What was the result?**

Homey put me in away mode strange

**What did you expect as result?**

that homey stayes in home mode 

**Any other remarks**

The same problem is there with sleep and awake mode.

When i ask homey to go in a mode i most not do the opposite mode 

**Please attach a Homey System log (Settings -> System -> Send Log)**

632E66A8F2

is the send log code 
...

**Comment by Tweake** [comment] 2017-05-22 15:19
Hi basd82, this is intended behaviour. Please see the [Athom support article](https://www.athom.com/nl/support/KB000044/) for details about the presence and sleep status.

**Comment by basd82** [comment] 2017-05-22 16:43
Why ????

This behavior is not describe in this article ....
I think it is strange when i ask sleep mode it must not go in awake mode .
Or at least warn me en not give the answer of sleep

**Comment by bvdbos** [comment] 2017-05-22 16:54
The title of this issue is not the same as the contents:

According to the title : when you tell Homey you're home and Homey's status is already home, you claim it's set to away?

According to the contents : Homey sets herself to away without you telling her...

Or was your status "home" all the time you were away (judging "But i when i left home i forgot to tell home that i went away.") and it was set to "away" only when you arrived home? 

Can you replicate this?

**Comment by basd82** [comment] 2017-05-22 17:01
Here is example with sleep mode https://youtu.be/Lx9QJUJ5CjE
Homey first wend correctly in to sleep mode second time it wend in to awake mode

**Comment by bvdbos** [comment] 2017-05-22 17:03
yep, can conform this for sleep...

**Comment by basd82** [comment] 2017-05-22 17:07
here an example for away away

https://youtu.be/Xa1FVn_d-dY

![image](https://cloud.githubusercontent.com/assets/1219705/26320100/ea13d010-3f21-11e7-9473-e25dfd67c11e.png)

**Comment by Tweake** [comment] 2017-05-24 10:48
I misunderstood your description of the issue. Did you mean your problem was that Homey was toggling your status when you said the same thing twice? Like this:

You: "good night" --> Homey: "Good night basd82!" (status changed to sleeping)
and once your status is set to sleeping you repeat the command
You: "good night" --> Homey: "Good night basd82!" (status changed to **awake**)

If this is the issue you were experiencing I have found the error and it will be fixed in the next update. This could occur both for sleep status and presence.

**Comment by bvdbos** [comment] 2017-05-24 11:09
Yep, somewhere it the status wasn't set but flipped...

**Comment by basd82** [comment] 2017-05-24 11:31
@tweaked that's the isue

**Closed** 2017-06-14 10:43 UTC
Labels: Homey Core, speech-input, Staged for release
