### ISSUE TITLE
Sundown / SunRise

### ISSUE THREAD

**Issue by mruiter** [athombv/homey#323] opened 2016-03-09 09:00 UTC
0.8.22

**What did you try to achieve?**
Flows for switching lights on sundown and of for Sunrise and other tasks 

*Please include detailed steps how we can reproduce the issue*
Just create a sundown / Sunrise flow

**What was the result?**
No activation of the flow on sundown or sunrise

**What did you expect as result?**
Switch on or off of flow on sundown and same for sunrise

...

**Comment by bvdbos** [comment] 2016-03-09 09:10
@182 ?

**Comment by mruiter** [comment] 2016-03-09 09:11
Did a search and did not popup. But now its also logged again for 8.22 :)

**Comment by MdeRhoter** [comment] 2016-03-09 09:48
Confirmed, neither sunrise nor sunset cards work.

**Comment by KroontjesPen** [comment] 2016-03-09 10:55
It looks like difficult to make to see by the first ticket: #8

**Comment by WeeJeWel** [comment] 2016-03-10 11:49
Duplicate of #182

**Closed by WeeJeWel** 2016-03-10 11:49 UTC
