### ISSUE TITLE
Homey Insights still strange graphs after update to firmware 1.5

### ISSUE THREAD

**Issue by RobPijpers** [athombv/homey#1804] opened 2017-09-05 12:16 UTC
**What is your Homey version (Settings → System)?**

1.5.0

**What did you try to achieve?**
Insights graph show still strange linesVh2IlBwEetu52RQ
![2017-09-05_14-08-48](https://user-images.githubusercontent.com/17836136/30060710-cb8cf600-9244-11e7-9369-7de766b0816b.png)

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment] 2017-09-11 12:01
dupe of bug #986

**Comment by RobPijpers** [comment] 2017-09-11 12:20
Thought this was fixed in 1.5.0, my mistake. Can you give an estimate when this will fixed because this bug makes insights pretty useless.

**Comment by bvdbos** [comment] 2017-09-11 12:30
You could use another line-type or bars etc. It's just this type of interpolation which gives these drawings. As for replacing these, I don't know if there's better libraries...

**Comment by jeroenvollenbrock** [comment] 2017-09-11 16:12
This is indeed caused by the interpolation algorithms. It is possible to select a different line-type. The original bug was about invalid data points, which has been resolved in 1.5.0. The smoothing line-type really requires your dataset to be somewhat 'smoothable', there is not much we can do about that.

**Closed by jeroenvollenbrock** 2017-09-11 16:12 UTC
