### ISSUE TITLE
can't connect to wifi

### ISSUE THREAD

**Issue by noukie1973** [athombv/homey#41] opened 2016-02-10 11:18 UTC

**Comment by noukie1973** [comment] 2016-02-10 11:19
can't connect. don't know why.

**Comment by JohanKuster** [comment] 2016-02-10 12:23
Did you select the Homey wifi conection on your device?

**Comment by noukie1973** [comment] 2016-02-10 14:17
Yep i asked for an upgrade from the router, but why is there no charging device included?

Groet Anouk 

Verstuurd vanaf mijn iPhone

**Comment by WeeJeWel** [comment] 2016-02-10 15:13
Please provide more information and steps on how to reproduce the issue.

The charger is under the cardboard in the box.

**Comment by TedTolboom** [comment] 2016-02-10 16:28
Same issue here... unable to connect to my regular wifi network.
2.4G WPA2-personal (AES) network with 64 random character key (used now for years for al my devices without any issues), key does start and end with a special character

Homey was able to connect to our guest network (shielded outside our private network); again WPA2-personal (AES), but with simple 8 character key (alphanumeric; no special characters used).

In both cases, setup screen comments that it takes extremely long.... (overloaded connection to Athom?)

While connected to the guest network, homey retrieved a new SW version (vxxxxx, unable to see while not connected)

Once completed, followed the advice out of the getting started guide to factory reset to change the wifi network: "If you only want to change Wi-Fi networks, follow the instructions above, but choose 'keep data' instead of wipe."

No joy, again not able to connect to my regular wifi network.... 
now also not able to connect to guest network...

**Comment by WeeJeWel** [comment] 2016-02-10 16:46
@TedTolboom Is your 64 character key HEX encoded?

**Comment by TedTolboom** [comment] 2016-02-10 17:11
(small correction) 63 ASCII character key

**Comment by noukie1973** [comment] 2016-02-10 17:30
Yes. I have exactly the same that's why I thought I need to upgrade my router from 2.4 to 5. 

Verstuurd vanaf mijn iPhone

**Comment by WeeJeWel** [comment] 2016-02-10 17:43
I will investigate long WPA passphrases. Definitely tested it. Maybe you can share yours (with a few numbers/letters changed)?

**Comment by TedTolboom** [comment] 2016-02-10 18:15
@WeeJeWel 
I've send my key (randomized, with some numbers / letters changed) to you as private (mail) message

**Comment by TedTolboom** [comment] 2016-02-11 09:42
Reproduced with SW v0.8.17: 
- still not able to connect to my private network; after several itterative attempts (~10x)
- Reconnecting to the guest network also required several attempts (4-5x) but in the end was successfull
For reference, Chrome browser on latest version of OS X

**Comment by TedTolboom** [comment] 2016-02-11 16:08
I did today some further investigation (on my 2nd access point)...

Short summary:
- Baseline setting (private network): 2.4Ghz - Mixed(B/G/N) - Channel 5 - Wide (40MHz) - standard PW -> NOK
- Option 1: 2.4Ghz - Mixed(B/G/N) - Channel 5 - **narrow (20MHz)** - standard PW -> NOK
- Option 2: 2.4Ghz - Mixed(B/G/N) - Channel 5 - Wide (40MHz) - **Easy PW (== Guest NW PW)** -> OK (able to complete setup) after 2nd try
- Option 3: 2.4Ghz - Mixed(B/G/N) - Channel 5 - Wide (40MHz) - **63 character ASCII PWD** DclFOfWz]7r4IP0gZO_t9R&V<=ddH8I7zuR#G1hEaM;\x&=laydAcu?Aw=ly2.- -> OK (1st attempt)
- Option 4: 2.4Ghz - Mixed(B/G/N) - Channel 5 - Wide (40MHz) - **63 character ASCII PWD minor change** **\n**lFOfWz]7r4IP0gZO_t9R&V<=ddH8I7zuR#G1hEaM;\x&=laydAcu?Aw=ly2.- -> NOK

In all cases, tried 3-4 times if not ok.
All passwords based on printable ASCII characters.

To me this looks like a password handling issue by Homey / website. All other settings seem to work with less strong passwords or passwords not starting with symbols (e.g. "\n")

Is there a way to see what password is send towards or received by Homey?

**Comment by TedTolboom** [comment] 2016-02-17 21:37
While waiting for a response from Athom, next attempt / several experiments, after a suggestions of a good friend / sr. SW architect... some variations with respect to the password used to identify if the setup page / Homey is correctly handling the password as entered (see previous remark) 

Wifi setup
Homey SW v0.8.17
Netgear R7000 router with DD-WRT (latest) FW, "XXXXXXX-homey" network, 2.4Ghz, B/G/N mixed, Channel 5, Wide (40Mhz)

```
AAbbCCddEEff11223344 -> OK, reset
\AAbbCCddEEff11223344 -> OK, reset
AAbbCCddEE\ff11223344 -> NOK, NOK, NOK, reboot > reset, NOK (MBP OK)
AAbbCCddEEff112233\44 -> NOK, NOK, NOK
AAbbCCddEEff11223344\ -> OK, reset
\AAbbCCddEEff11223344\ -> OK, reset
\AAbb\CCddEEff11223344 -> OK, reset
\AAbbCCddEE\ff11223344 -> NOK, NOK, NOK  (MBP OK)
AAbbCCddEE\ff11223344\ -> NOK, NOK, NOK
\AAbbCCddEE\ff112233\44 -> NOK, reboot > reset, NOK, NOK
AAbbCCdd$EEff11223344 -> OK, reset
AAbbCCdd$EEff$11223344 -> OK, reset
AAbbCCdd$EEff$$11223344 -> NOK, NOK, NOK (MBP OK)
\AAbb\CCddEEff$$11223344 -> NOK, reboot > reset, NOK, NOK
\AAbb\CCddEEff$11223344 -> NOK, NOK, NOK
\nAAbbCCddEEff11223344 -> NOK, NOK, NOK (MBP OK)
AAbbCCdd\nEEff11223344 -> NOK, NOK, NOK
AAbbCCddEEff11223344 -> OK
```
For reference, verified on several attempts the ability to connect to the Wifi network (with the used password) with my MacBook Pro; marked as "(MBP OK)"

These results demonstrate for me that the setup page ([setup.athom.com](http://setup.athom.com/)) and or Homey itself are incorrectly handling the password as entered into the text box.
Possibly the expression behind the textbox on the setup page (or Homey) is utilizing a path or string detection method that is failing on the allowed printable ASCII characters (see ref 10. on [Wi-Fi_Protected_Access](https://en.wikipedia.org/wiki/Wi-Fi_Protected_Access)). 
In above varations (based on my own password) with the "\" character (typical character in a path), the "\n" (new line) or the "$$".

Do other people experience similar issues with these (allowed) characters in there wifi passwords?

**Comment by WeeJeWel** [comment] 2016-02-18 19:43
@TedTolboom Thank you SO much for your extensive testing! You were completely right about the `\` character and the `$$` causing issues.

Thanks to your help I have resolved them, and will make sure these changes are shipped very soon. Lukcily, we can update the Recovery bundle from the web, so you won't even need to install a software update :-)

**Comment by TedTolboom** [comment] 2016-02-18 22:13
@WeeJeWel good to hear and you're welcome ! Specifically that you're able to solve it without SW update.
I hope this is contributing to resolve wifi connectivity issues for other owners....

Let me know when we're able to test it....;-P

**Comment by TedTolboom** [comment] 2016-02-28 11:39
The recovery bundle has been updated (apparently)... My wifi / password issue has been solved.
Thanx @WeeJeWel

**Closed** 2016-05-17 17:23 UTC
