### ISSUE TITLE
WebAPI : getDevices Type Error

### ISSUE THREAD

**Issue by hive** [athombv/homey#2888] opened 2018-10-22 14:09 UTC
**Metadata**

* **Homey WEBAPI Version**: 2.0.134

**What did you try to achieve?**

Call device.getDevice({id:x})

**What did you expect as result?**

For the API devices object to be returned

**What was the result?**

Error : "TypeError: Expected capabilities to be an Array, got object instead"

```
at Function.value (/lib/athom-api.js:2:793697)
    at t.<anonymous> (/lib/athom-api.js:2:779415)
    at a (/lib/athom-api.js:2:460955)
    at Generator._invoke (/lib/athom-api.js:2:461997)
    at Generator.e.(anonymous function) [as next] (/lib/athom-api.js:2:461134)
    at n (/lib/athom-api.js:2:7879)
    at /lib/athom-api.js:2:7975
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Any other remarks**
 Only occurred after upgrading, WebAPI version 2.0.129, works as expected.

**Comment by jeroenvollenbrock** [comment] 2018-10-22 17:20
Closing as duplicate of https://github.com/athombv/node-athom-api/issues/2

**Closed by jeroenvollenbrock** 2018-10-22 17:20 UTC
