### ISSUE TITLE
Fibaro Dimmer 2 fails Z-Wave pairing (and blocks future pairing)

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#315] opened 2016-03-07 21:43 UTC
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Pair Fibaro Dimmer 2

**What was the result?**

Device is quickly found, interviewing stage (3 devices) takes a long time. When interviewing 3 of 3, an issue pops up:

![screen shot 2016-03-07 at 22 14 38](https://cloud.githubusercontent.com/assets/17275712/13584140/59045404-e4b5-11e5-8144-d9b68e1ea7eb.png)

After this, there is no added device. In the non-responding devices there is an extra device, but classified as unknown:

![screen shot 2016-03-07 at 22 15 11](https://cloud.githubusercontent.com/assets/17275712/13584157/71810e5a-e4b5-11e5-9048-bd5e6da162ca.png)

I am able to remove the 'unknown device',, but after that, a new pairing session cannot be setup:

![screen shot 2016-03-07 at 22 23 17](https://cloud.githubusercontent.com/assets/17275712/13584185/9a1e0e4e-e4b5-11e5-9d56-fb8f7e5cf11e.png)

I have to reboot Homey to get it working again. With this Dimmer, the same results though. Restarting the Z-wave chip doesn't resolve it as well.

**What did you expect as result?**

Succesfull pairing

**Any other remarks**

 I was able to pair it once, and update the parameters to my preferences.  Then there was also an error during the interview stage (not sure which error and didn't make a screenshot of it). After that, the Dimmer (as 3 devices) was added twice (so 6 devices in total), although with the same node-id.  That gave some unpredictable results in controlling the device. Removal was no issue, both devices were removed with no issue. I rebooted the Homey after that to start the re-pairing. With above results, which I reproduced a number of times to be certain.

**Comment by ocatie** [comment] 2016-03-08 13:32
Duplicate of #240 

Fixed in 0.8.22. (in 0.8.23 you can also interact with the card, not unimportant)

**Closed by ocatie** 2016-03-08 13:32 UTC

**Comment by Muyz** [comment] 2016-03-08 18:15
Not fixed: I still have the "Another pair session active" popup when trying to pair a Dimmer2.
