### ISSUE TITLE
Cannot login with Google Play music app with application password

### ISSUE THREAD

**Issue by nicenemo** [athombv/homey#1820] opened 2017-09-16 18:14 UTC
**What is your Homey version (Settings → System)?**

1.5.2

Login to Google Play Music

I used a freshly generated app password.
For my  normal user login 2nd factor is enabled.
Copied and pasted from Google.

My google account is a google apps account. my email adres is one of my own domain so it does NOT
end in .gmail.com

Could not login.

Expected to be logged in.

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by Dijker** [comment] 2017-09-17 10:09
Issue Confirmed Homey v1.5.2, Google Play Music v1.0.4 
I was logged On to Play Music. 
After Logging out not able to logon with my Google Apps account (@owndomainname.com) with an App Password but also not able to logon with an plain @gmail.com  account. 

Don't know if you could find something in the log, 50B5BFC776 .

Removed the App and re-added but no succes on both accounts.

**Comment by AJediIAm** [comment] 2017-09-18 12:46
This issue is probably a duplicate of #1416. 
I have the same problem for a few months now. It used to work, but after a factory reset, I was no longer able to use google music due to this login issue.

**Comment by AJediIAm** [comment] 2017-09-20 16:13
I just tried the steps which come with version 1.0.6 of the app, but still no change.

**Comment by Dijker** [comment] 2017-09-20 20:15
Just updated Homey and the App and now it works for me, 
I am Logged On where I couldn't three days ago.

**Comment by AJediIAm** [comment] 2017-09-21 07:34
Homey updated to 1.5.3 over night and it now works.
When I logged in, the screen did not refresh itself with either an error or a confirmation, but when i refreshed, I was logged in.
I did get a notification that a login was performed on my google account from another city. I was expecting Homey to connect to google directly. Is this normal?

**Comment by bvdbos** [comment] 2017-09-21 07:36
Which city?

**Comment by AJediIAm** [comment] 2017-09-21 07:38
Amsterdam. I expect the Homey server is there.

**Comment by bvdbos** [comment] 2017-09-21 07:52
Worked for me, Got a nitification someone logged in from Asten. So maybe something with the ip-database not being up-to-date?

**Comment by AJediIAm** [comment] 2017-09-21 08:34
Probably. The important thing is that it works.

**Closed** 2017-09-26 10:25 UTC
Labels: Athom App
