### ISSUE TITLE
Vertical scroll for flows

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#245] opened 2016-02-26 05:55 UTC
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

I have more flows than height of my screen. I'd like to be able to select all flows, but there is no vertical scroll, so I can't select the last N amount of flows to edit.

**What was the result **

No ability to edit the last N amount of flows, I cannot select them as I cannot 'reach' them. 

**What did you expect as result?**

Vertical scroll to be able to select all flows

**Any other remarks**

Workaround: select a flow, click save ( so it drops down to the bottom of the list ) . Repeat until flow appears in screen.   But this is a very labourintensive workaround when debugging flows ;-)

**Comment by Dijker** [comment] 2016-07-23 06:26
@ralfvd 
I guess this is fixed now in. 0.8.39 
Or didn't you update¿

**Comment by jeroenvollenbrock** [comment] 2016-07-27 11:45
duplicate of #200

**Closed by jeroenvollenbrock** 2016-07-27 11:45 UTC
