### ISSUE TITLE
Klikanklikuit - fan not showing in floweditor

### ISSUE THREAD

**Issue by svenove** [athombv/homey#479] opened 2016-04-20 17:59 UTC
**What is your Homey version (Settings → System)?**
0.8.29

**What did you try to achieve?**
Add a new socket

*Please include detailed steps how we can reproduce the issue*
Add a new KlikAnKlikUit socket and set the type to "fan". 
Go to floweditor, the device is not there. 

**What was the result?**
Device not in floweditor 
...

**What did you expect as result?**
Device in floweditor
...

**Any other remarks**

...

**Comment by freemann** [comment] 2016-04-20 18:04
Duplicate of #433

**Comment by Dijker** [comment] 2016-05-28 21:50
Running 0.8.35 / KAKU 1.1.3 
I think this is still a problem?

**Comment by jeroenvollenbrock** [comment] 2016-07-27 14:16
Duplicate of #433

**Closed by jeroenvollenbrock** 2016-07-27 14:16 UTC
Labels: duplicate
