### ISSUE TITLE
Conecting Netatmo

### ISSUE THREAD

**Issue by petergab94** [athombv/homey#141] opened 2016-02-11 23:11 UTC
windows for connecting is empty :: 
![image](https://cloud.githubusercontent.com/assets/17183593/12993864/283da970-d11d-11e5-8473-0cbf2bbfa9a6.png)

**Comment by Muyz** [comment] 2016-02-11 23:15
This is a duplicate of issue [https://github.com/athombv/com.netatmo/issues/1](url)

Suggest to close this issue.

**Closed** 2016-02-12 07:51 UTC

**Comment by WeeJeWel** [comment] 2016-02-12 15:29
Heads-up: the NetAtmo app has been updated and is working again!
