### ISSUE TITLE
[Enhancement] Move cards

### ISSUE THREAD

**Issue by jjtbsomhorst** [athombv/homey#1058] opened 2016-11-06 20:29 UTC
**What is your Homey version (Settings → System)?**

0.10.7

**What did you try to achieve?**

-

**What was the result?**

-

**What did you expect as result?**

I would like to have an option to move cards in any column around. Today I made a flow that contains 5 or 6 action cards. Then I noticed that I placed them in the wrong order. It would be really helpfull to be able to move them to another location in the same column ( or move them to another column).

**Any other remarks**

...

**Comment by bvdbos** [comment] 2016-11-06 20:39
All actions fire at the same time unless you set delays for them... So there is no "wrong order"...

**Comment by jjtbsomhorst** [comment] 2016-11-06 20:43
You are sure about this? I think that there is some sort of order in place. Lets say you want to turn on the lights after homey has greeted you but you switch them.. Wouldn't homey do it the other way around?

**Comment by bvdbos** [comment] 2016-11-06 20:50
#61 #983 #408 and probably others...

**Comment by Dijker** [comment] 2016-11-06 20:59
@bvdbos
I agree, but still it looks better to order the cards especially when some cards have delays configured. it doesn't make sense (Visually) if the card with a delay of 10 seconds stays at the top... although it functions. 
For the Condition cards it is better to check all other boolean - AND Condition before a Confirmation is triggred. Although  that is the only use case it does matter afaik. And that is  fixed by re-adding the Confirmation  at the bottom and deleting the first Confirmation .....

I have read somewhere I think @WeeJeWel would look into it for "Better Flow Management" of something.... 
(Ahhh... Thanks, all the other Issues you reference ;-) ) 
So again a duplicate ;-)

**Comment by bvdbos** [comment] 2016-11-06 21:09
It would make sense if the cards with longest delay would go to the bottom.

**Comment by WeeJeWel** [comment] 2017-03-28 19:00
Duplicate of #61 (and fixed in v1.3.0)

**Closed by WeeJeWel** 2017-03-28 19:00 UTC
Labels: enhancement, Flow
