### ISSUE TITLE
Wrong graphic at Insights

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1500] opened 2017-04-24 15:29 UTC
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**

I use some Better Logic variables to register when temperatures change by 0.5 degrees celcius.
I look at the graphics at Insights...

**What was the result?**

"Block graphic" is wrong by showing measurement-dots with a line going up  or down to the next measurement-value.

**What did you expect as result?**

 The line should go up or down at the right measurement-dot.

**Any other remarks**

![wrong_graph](https://cloud.githubusercontent.com/assets/24574832/25344802/8178e7ee-2913-11e7-852f-71a2012198fd.png)

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by bvdbos** [comment] 2017-04-24 15:36
dupe of #1258 ?

**Comment by OpenMindNL** [comment] 2017-04-24 15:40
@bvdbos you are right.... pending since januari?!?! Unbelievable that this issue still exists as it should not be hard to make it work correctly!

**Comment by bvdbos** [comment] 2017-04-24 15:45
Actually, it might be harder then you think. I imagine an array of x,y which is processed from the end to the beginning (would explain some other phenomena too) but the processing has to be reversed... I can imagine this requires rewriting of external libraries. If it was as simple as https://www.w3schools.com/jsref/jsref_reverse.asp I presume this would have been done...

**Comment by OpenMindNL** [comment] 2017-04-24 15:52
Nah... just remember the first value until the code reads the next value.... and THEN draw the line up or down.
I think that the way it is done now is the hard way. The code first needs to find the next value and then draw a line at the previous value. 😁

**Comment by WeeJeWel** [comment] 2017-05-10 10:13
Indeed, duplicate of #1258 and a very stubborn issue.

**Closed by WeeJeWel** 2017-05-10 10:13 UTC
