### ISSUE TITLE
The login for Woonveilig doesn't work anymore

### ISSUE THREAD

**Issue by juroz** [athombv/homey#1330] opened 2017-02-17 09:14 UTC
**What is your Homey version (Settings → System)?**

Homey Firmware Versie: 1.1.9
Athom Cloud ID: 570b8f159aac671e67accd22

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*
After installation of Homey i go in the Homey app -> Devices ->Add a device -> Search for Woonveilig -> Click on Woonveilig untill i have to put in my username and password. 

**What was the result?**
When i input username and password i does nothing. No error nothing. I tested the username and password https://alarmsysteem.woonveilig.nl/nl_NL_woonveilig/web/woonveilig/home 
...

**What did you expect as result?**
That i could login in and use the app.
...

**Any other remarks**
Woonveilig did update there app recently
...

**Comment by juroz** [comment] 2017-02-17 09:15
F82A8C1B80 log

**Comment by BasKiers** [comment] 2017-03-24 13:01
Hi,

I just updated the woonveilig app to fix the crash that I saw in your log. Could you confirm that this issue is now fixed?

Regards,
Bas

**Comment by jeroenvollenbrock** [comment] 2017-05-16 10:35
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please let me know if you still encounter this issue with the [latest stable version](https://firmware.athom.com/).

Thank you!

**Closed by jeroenvollenbrock** 2017-05-16 10:35 UTC
Labels: Athom App, waiting for user feedback

**Comment by juroz** [comment] 2017-05-16 11:17
Sorry, It is working after the change. Thank you!

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: Jeroen Vollenbrock<mailto:notifications@github.com>
Verzonden: dinsdag 16 mei 2017 12:36
Aan: athombv/homey<mailto:homey@noreply.github.com>
CC: juroz<mailto:juroz@hotmail.com>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [athombv/homey] The login for Woonveilig doesn't work anymore (#1330)


Closed #1330<https://github.com/athombv/homey/issues/1330>.
