### ISSUE TITLE
Danalock status not updated lock/unlock

### ISSUE THREAD

**Issue by Oy1974** [athombv/homey#2254] opened 2018-02-22 16:36 UTC
* **Homey Version**: 1.5.6
* **Homey Log Code**:
* **Smartphone Platform**: android
* **Smartphone App Version**: 2.4.6 build 77

**If related to a Homey App:**
* **Homey App Version**: v2.0.3
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Danalock v3 Bluetooth/Z-wave

**What did you try to achieve?**

When auto unlock the door (bluetooth) the status isnt Always updated in the homey app. 

**What did you expect as result?**

That the status of the lock is correct in the app

**What was the result?**

Auto unlock the door, but the status of the lock in the homey app stays on locked.

**Any other remarks**

**Comment by jordenc** [comment] 2018-02-23 11:19
I think the same happens with my Nuki lock app.

**Comment by khangwei** [comment] 2018-02-26 00:39
yes - same problem with my danalock. 

Sometimes, through bluetooth unlock/lock or manual unlock/lock, danalock failed to update homey/homey failed to update to the correct status.

this is actually quite a big problem for a main door lock as I do not know if I can trust the status of the lock.

also, certain triggers/flows are related to if the lock is locked or not.

is it possible to poll the lock and update status?

thank you

**Comment by lubbertkramer** [comment] 2018-02-26 22:48
@RobinBol can you take a look with @jordenc if this is also the case in the Nuki app (see also the [forum topic](https://forum.athom.com/discussion/comment/62040/#Comment_62040) where the problem is discussed several times) If that's the case you guys can make a win/win here and also better for the talks with Homey  with Nuki Athom showed in Enschede

**Comment by Oy1974** [comment] 2018-02-28 16:43
Bug stil there on 1.5.7 

logcode 8F08807B13

**Comment by bvdbos** [comment] 2018-03-04 19:44
First it has to be clear whether the Homey receives the signal. Do the triggers work al the time? If that's the case, then it's a matter of Homey processing the correct status-update. Zwave shouldn't have to be polled afaik.

**Comment by Oy1974** [comment] 2018-03-09 20:49
@RobinBol any progres on this isseu?

**Comment by RobinBol** [comment] 2018-03-10 09:11
Not yet, it is on our to do list, soon we will receive some tools which allows us to test these locks better at the office.

**Comment by Oy1974** [comment] 2018-03-31 19:55
Whats your defenition of soon? this year or......

**Comment by Oy1974** [comment] 2018-04-20 20:50
with sending around a nice blog about smart locks and Homey,

[https://blog.athom.com/smart-lock-possibilities-smart-home/?utm_source=Athom+Newsletter&utm_campaign=01e3e53956-EMAIL_CAMPAIGN_2018_04_20_EN&utm_medium=email&utm_term=0_ac5b24c2f6-01e3e53956-89274881&mc_cid=01e3e53956&mc_eid=bba8528d0a](url)

I can expect you has fixed the bugs in the smartlock apps?? right!!! or athom is stil talking in one word

SOOOOON.

Some action would be nice

**Comment by Oy1974** [comment] 2018-04-24 16:11
Good to hear, finnaly there is some action.

But another question you mention "We just received a test Danalock which we can use to test the Danalock in combination with Homey"

I hope that iam wrong, but you didnt test it before??? because that would be **%$^$*&

**Comment by bvdbos** [comment] 2018-04-24 18:12
Athom doesn't have (and has to have) all devices which exist in this world. Programming should be doable based on the specfications... Until a device has it specific issues and doesn't follow the specs like it should.

**Comment by Oy1974** [comment] 2018-04-24 18:24
Indeed, but most of devices are not devolped by athom so thats not the case, the few apps of there own i expect that they tested very well and if there are problems (i dont mind if it happends) but just expecting they take action. And not saying after 2 months yeah now we got one, and gonna look at it.

**Comment by Moszkowizz** [comment] 2018-04-25 08:12
@Oy1974 of course we did test it, we had one model we used to test it with, but needed to send it back. Now we got another one to try to reproduce your issue:)

**Comment by Oy1974** [comment] 2018-04-25 15:08
@Moszkowizz only can say.... keep the communcation like this way in the future. This is a answer i and think the most user can live with. To the point and a bit of explonation, users would understand it better and for sure got more patient then.

Well done.  and if need some testing let me know.

**Comment by Moszkowizz** [comment] 2018-04-26 07:49
@Oy1974 Thanks for the feedback! We will do our best to update everybody more frequently on open Github issues

**Comment by Oy1974** [comment] 2018-05-20 09:45
Another 24 days past... no feedback no questions. And in comparison to athom i like to communicate. 

Only using the bluetooth option works, ofcourse because the homey app has nothing to do with.

Only using the athom homey app works also.

The problems come with using both bluetooth and zwave, then often status arnt updated. 

My patience is long but not that long, iam really  sorry for that..  but not gonna wait till (pasen en pinksteren op 1 dag vallen). 

The lock is on my front door  and its bad when opening it with bluetooth and closing it again because im home, and a minute later the homey app thinks hey Roy is home lets open the door for him. Very friendly ofcourse but waking up the next moring with a open door isnt a thing i want.

So i changed my whole flow setup for using the danalock wirh only using the zwave option and in combonation with a 10 euro  bluetooth  switch from ali and a fibaro binairy sensor (gps ist working in my home 
situation, nothing to do with homey precense options). Now iam testing this setup for over a week and til now a 100 % score. It locks when leaving the the bluetooth range..  impressive 30 meter and when comming home in a meter of 10 the door unlocks. 

So i got a working solution now and, i got no feeling to help you guys with testing a possible solution wich you maybe provied in 2020. 

You may clossed this isseu or try to find another user with more patience then 3 months. 

Last thing to say....iam very happy with my homey, but the lack of support and communication is killing your own busniss.

Have a nice weekend

**Comment by khangwei** [comment] 2018-06-22 02:01
hi @Moszkowizz, any luck with this please?

my danalock sometimes still fail to update Homey with the correct status.

**Comment by Moszkowizz** [comment] 2018-06-22 11:18
No luck yet, the developer is still hard at work though. I will ask him to post an update about his progress

**Comment by khangwei** [comment] 2018-06-22 12:52
No problem. Thanks for the update though. Appreciate the hard work!

**Comment by RobinBol** [comment] 2018-06-28 15:59
We tried to reproduce the issue, but did not manage to do so. No matter how we (un-) locked the door (manually, via the Danalock smartphone app), it always reported its updated state to Homey. Note we used the beta version of the Danalock for Homey App. 

One thing we did find, and heard from more users is the lack of Z-Wave range of the Danalock. In our office, approx. 12 meters through open air was already too far for the lock to reports its status back to Homey. The fact that your reports are not coming through is very likely related to the range issue, you could try to add some more Z-Wave routers between Homey and the lock or place Homey closer to the lock (even if just for testing).

Since this issue seems to be unrelated to a possible bug in the Danalock App for Homey or Homey itself I will close this issue.

**Closed by RobinBol** 2018-06-28 15:59 UTC
Labels: bug

**Comment by Oy1974** [comment] 2018-06-28 17:20
6 meters max between the danalock and homey, with a "gips wandje" between en 3 zwave powered devices between.  but as stated before got it working with not using the bluetooth function. So iam 100% sure it has nothing to do with the range isseus.

**Comment by khangwei** [comment] 2018-06-28 23:42
hi, thanks for testing. However, my homey is less than 3m away from my main door lock. i am certain it is not a range issue. I am not sure how you can replicate this problem but it is certainly affecting me since my main door lock status is not accurate 50% of the time...

**Comment by laustS** [comment] 2018-12-02 21:15
I have used the Danalock V3 Bluetooth Only version - the status is highly unreliable in their own app. !
