### ISSUE TITLE
[Suggestion] Flow unsaved reminder

### ISSUE THREAD

**Issue by Qx5** [athombv/homey#269] opened 2016-02-28 13:23 UTC
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**

Change a flow

**What was the result?**

Forgot to save and found this out later.

**What did you expect as result?**

Maybe a reminder when you leave a specific flow without saving your changes (or autosave)

**Any other remarks**

Current method makes me feel that Homey is buggy while it is just me that forgets to save the flow

**Comment by WeeJeWel** [comment] 2016-11-01 10:54
Duplicate of #217

**Closed by WeeJeWel** 2016-11-01 10:54 UTC
Labels: enhancement, Flow, Homey Core, interface
