### ISSUE TITLE
[com.heatmiser] Decrease the amount of updates in insights

### ISSUE THREAD

**Issue by michelderu** [athombv/homey#2386] opened 2018-03-29 12:28 UTC
Currently the heatmiser sends an update around every minute. This results in a huge amount of values for insights which makes it slow. I also think this finegrained log is unnecessary and adds no value.

Is it possible to limit heatmiser sending so many updates. Or is it possible to limit the amount of updates Homey registers?

**Comment by synegic** [comment] 2018-04-01 22:52
I opened an issue like this some time ago (https://github.com/athombv/homey/issues/2227). Currently there's no way around this other than rate-limiting the values themselves (receiving end of app or source) I'm afraid.

**Comment by jeroenvollenbrock** [comment] 2018-04-03 09:50
Duplicate of #2227

**Closed by jeroenvollenbrock** 2018-04-03 09:50 UTC
