### ISSUE TITLE
Kaku 1.15 flow trigger craches the app

### ISSUE THREAD

**Issue by posthok** [athombv/homey#689] opened 2016-06-16 08:33 UTC
**What is your Homey version (Settings → System)?**

0.8.38

**What did you try to achieve?**
Triggering flows

*Please include detailed steps how we can reproduce the issue*
TypeError: Cannot read property 'variables' of undefined
at Object.module.exports.self.capabilities.alarm_contact.get (/drivers/switch/driver.js:129:28)
at Object.<anonymous> (/drivers/switch/flows.js:51:39)
at emitThree (events.js:102:20)
at Object.emit (events.js:175:7)
at /homey-app/manager/flow.js:1:194
at /homey-app/helpers/client.js:1:868
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:835)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7),TypeError: Cannot read property 'variables' of undefined
at Object.module.exports.self.capabilities.alarm_motion.get (/drivers/switch/driver.js:117:28)
at Object.<anonymous> (/drivers/switch/flows.js:37:38)
at emitThree (events.js:102:20)
at Object.emit (events.js:175:7)
at /homey-app/manager/flow.js:1:194
at /homey-app/helpers/client.js:1:868
at Array.forEach (native)
at process.<anonymous> (/homey-app/helpers/client.js:1:835)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)

**What was the result?**
When a flow starts with an kaku device kaku app 1.15 crashes

**Comment by Dennishacq** [comment] 2016-06-16 08:51
Hi @posthok 
I'm working on a fix that should be online later today.

**Comment by posthok** [comment] 2016-06-16 12:26
Thanx dennis

**Comment by Dennishacq** [comment] 2016-06-17 10:06
duplicate of  #682

**Closed by Dennishacq** 2016-06-17 10:06 UTC
