### ISSUE TITLE
Homey sent no 433 signal with Promax RC50075 button pressed

### ISSUE THREAD

**Issue by uNiiek** [athombv/homey#967] opened 2016-10-06 19:27 UTC
**What is your Homey version (Settings → System)?**

Homey Firmware Versie: 0.10.3
Action app: Versie: 2.1.1

**What did you try to achieve?**

- Reboot
- PTP
- Reinstall Action app
- Re-pair remote

*Please include detailed steps how we can reproduce the issue*

Pairing of the remote goes well and recognizes the buttens are pressed in the wizzard. 
But if i set a flow: When butten 4 pressed on then do xxxx nothing happens

![433](https://cloud.githubusercontent.com/assets/18580351/19167235/0abb57d6-8c0b-11e6-84d2-3f159134a1c1.png)

**What did you expect as result?**

It fires the singnal and run my flow.

**Any other remarks**

...

**Comment by bvdbos** [comment] 2016-10-06 19:31
the same as issue #865 ?

**Comment by uNiiek** [comment] 2016-10-06 19:39
@bvdbos Not 100% sure if the same. But they look like each other.

**Comment by jeroenvollenbrock** [comment] 2016-10-17 11:35
Duplicate of #865

**Closed by jeroenvollenbrock** 2016-10-17 11:35 UTC
Labels: Athom App, duplicate
