### ISSUE TITLE
beenen

### ISSUE THREAD

**Issue by fvanbeenen** [athombv/homey#2139] opened 2018-01-06 11:07 UTC
**Metadata**

* **Homey Version**:    1.5.6-rc.8
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:** qubino 
* **Homey App Version**: v1.1.8
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:  ZMNHBD1 2flush

**What did you try to achieve?**

Turn of my light with the connected switch. 

**What did you expect as result?**

Homey to pickup te status change

**What was the result?**

Nothing happened

**Any other remarks**

**Comment by bvdbos** [comment] 2018-01-06 13:08
This has been superseded by #2140 I guess so can be closed?

**Comment by fvanbeenen** [comment] 2018-01-06 17:27
No it is a totally other problem. Thanks

**Comment by Dijker** [comment] 2018-01-06 18:09
Hi @fvanbeenen  
the description, especially the title is not very helpful in understanding your issue. 

Can you create a short to the point one line title starting with the App name (fe [com.qubino] ) and the problem (what doesn't work) or feature request (what you want to do but isn't possible at the moment).

Please look at some other Issues and take a look at https://github.com/athombv/homey/blob/master/CONTRIBUTING.md

Better descriptions get more attention from developers and are fixed faster.

**Comment by fvanbeenen** [comment] 2018-01-06 19:44
Kan het in het Nederlands?

**Comment by bvdbos** [comment] 2018-01-06 19:47
You could write it in Dutch and then also add the English translation from https://translate.google.com

**Comment by fvanbeenen** [comment] 2018-01-06 19:49
I have built in the ZMNHBD1 2flush. Homey recognizes it and I can turn the light on and off with Homey and with the switch. Only ... When I turn the light on or off with the physical light switch, it does not change on the homey app. Then the homey app stays on and the light is off.

**Comment by fvanbeenen** [comment] 2018-01-06 19:53
It does not communicate well with Homey .. so it seems.

**Comment by kukel** [comment] 2018-01-08 22:20
@fvanbeenen: please improve the title too, you **can** edit it...

**Comment by JPe2** [comment] 2018-01-09 13:52
https://github.com/athombv/com.qubino/issues/14
https://github.com/athombv/homey/issues/1685

**Comment by jeroenvollenbrock** [comment] 2018-01-10 16:40
Closing as duplicate of https://github.com/athombv/com.qubino/issues/14 and #1685

**Closed by jeroenvollenbrock** 2018-01-10 16:40 UTC
