### ISSUE TITLE
NFC not working any more in 08.30

### ISSUE THREAD

**Issue by CootNL** [athombv/homey#460] opened 2016-04-16 13:55 UTC
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**
via the NS NFC card the light on
*Please include detailed steps how we can reproduce the issue*
Use the NS NFC card to active the lights.

**What was the result?**
No response of homey or the light
...

**What did you expect as result?**
After using the NS NFC card that the light will be activated.
Restarted homey already a several times, but it will not work.
This function was working om 0.8.29
...

**Any other remarks**

...

**Comment by mruiter** [comment] 2016-04-18 20:45
cam confirm. my nfc is not reacting to a tag also

**Comment by WeeJeWel** [comment] 2016-04-20 11:50
Also when you hold a tag on Homey for more than three seconds?

**Comment by CootNL** [comment] 2016-04-20 19:08
Yes even more then 10 seconds and is still not working. Also not after a reset of homey.

**Comment by Arjanvde** [comment] 2016-04-20 19:23
I'm having no issues with NFC, both my "Arriva" OV-Chipcard and Nurburgring Ring Card which does apparently have NFC do work. Also on 0.8.30

**Comment by ThaYoung1** [comment] 2016-05-11 20:51
Just did some testing. Maybe you guys can pinpoint this issue a little bit better with this info.

My OV-Chipcard gives one tag Id (sent it to my smartphone with a push message). When holding my smartphone on Homey it sends out 4 different and random tag Ids.

**Comment by WeeJeWel** [comment] 2016-05-11 22:36
That sounds like correct behavior. A smartphone usually generates a random
tag id.

Is anyone actually still experiencing issues with NFC?

**Comment by bvdbos** [comment] 2016-05-12 04:32
I can't get my bank-card to generate a signal, can anyone else?

**Comment by ThaYoung1** [comment] 2016-05-12 06:50
@WeeJeWel Ok, so by design you won't be able to use your phone in combination with the "A tag has been detected" trigger card. 

With that in mind, NFC works correct here.

**Comment by freemann** [comment] 2016-05-12 06:53
You are able to use NFC with Homey, the only problem is dat nobody knows which random tag_id the phone generates.
If you are able to let your phone generate a fixed tag_id then you can use your phone for triggering stuff in Homey.

**Comment by CootNL** [comment] 2016-05-22 12:26
Still a problem with NFC with the last release 0.8.35

**Comment by mruiter** [comment] 2016-05-22 12:27
mine started working again from .34 release

Verstuurd vanaf mijn iPad

**Comment by jeroenvollenbrock** [comment] 2016-07-27 14:07
This should be fixed in 0.8.36, if you still have any issues where NFC does not work at all please contact support@athom.com

**Closed by jeroenvollenbrock** 2016-07-27 14:07 UTC
