### ISSUE TITLE
[ Homey app (V2) ] error while adding a smartwares plug

### ISSUE THREAD

**Issue by enbach** [athombv/homey#2031] opened 2017-12-07 13:27 UTC
**Metadata**

* **Homey Version**: 1.5.3
* **Homey Log Code**:
* **Smartphone Platform**: iOS
* **Smartphone App Version**: V2 beta app

**If related to a Homey App:**
* **Homey App Version**: V2 beta 1.0
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: smartwares SH5-RPS AND SH5-RPD

**What did you try to achieve?**

I’d tried to add my flamingo sf-501 as a smartwares device which works on the desktop app

**What did you expect as result?**

**What was the result?**

The device wasn’t added and a error message popped  @up
![fd353682-ca51-4cba-8836-eebeb350acef](https://user-images.githubusercontent.com/34342230/33717562-aa564734-db5a-11e7-9000-16635c311113.png)

**Any other remarks**

**Comment by WeeJeWel** [comment] 2017-12-07 14:36
I cannot reproduce the issue. Have you tried force closing the app and re-opening?

![screen shot 2017-12-07 at 15 35 57](https://user-images.githubusercontent.com/319873/33720474-5693d56c-db64-11e7-895f-a122c73c35a8.png)

**Comment by enbach** [comment] 2017-12-08 14:00
Seems to be fixed as of version 1.0 ( 102 )

**Closed** 2017-12-08 14:02 UTC
Labels: bug, Homey Smartphone App (Core), waiting for user feedback
