### ISSUE TITLE
1.5.6-rc.7: args.device is undefined

### ISSUE THREAD

**Issue by ArjanKranenburg** [athombv/homey#2138] opened 2018-01-05 15:37 UTC
**Metadata**

* **Homey Version**: 1.5.6-rc.7

**If related to a Homey App:** Virtual Devices
* **Homey App Version**: 0.6.8
* **Homey App Log Code**: 77cc8f58-037d-4398-964a-9abbb65aa9ae
* **Affected Devices (preferably product codes)**: Some modes, but not all or maybe not all the time.

**What did you try to achieve?**
A user experienced a crashing app. The crash log shows:
```
---- stderr ----
/drivers/mode/driver.js:62
        this.log(device.getName() + ' -> Condition checked: ' + simpleStringify(device.getState()) );
                        ^

TypeError: Cannot read property 'getName' of undefined
    at FlowCardCondition.flowCardCondition.register.registerRunListener [as _runListener] (/drivers/mode/driver.js:62:25)
    at FlowCardCondition._onRun (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/FlowCard.js:1:1191)
    at emitThree (events.js:136:13)
    at FlowCardCondition.emit (events.js:217:7)
    at ManagerFlow._onRun (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/manager/flow.js:1:2274)
    at _eventListeners.filter.forEach.t (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1219)
    at Array.forEach (<anonymous>)
    at HomeyClient._onMessage (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/lib/HomeyClient.js:1:1196)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
```

**What did you expect as result?**
No crash (obviously), since it does not happen on 1.5.3, i.e. I don't get these reports.

**What was the result?**
The code causing this in mode/driver.js is:
```
  registerFlowCardCondition(card_name) {
    let flowCardCondition = new Homey.FlowCardCondition(card_name);
    flowCardCondition
      .register()
      .registerRunListener(( args, state ) => {
        let device = args.device;
        this.log(device.getName() + ' -> Condition checked: ' + simpleStringify(device.getState()) );
```
Apparently the runListener was triggered with an args without a device. Isn't that wrong?

**Any other remarks**
Of course, I should code more defensively and check if the device is defined before using it.
I'll do that as well, but perhaps something can be improved on the Homey side as well?

**Comment by WeeJeWel** [comment] 2018-01-09 21:16
Can you paste the corresponding app.json Flow code?

**Comment by ArjanKranenburg** [comment] 2018-01-10 19:28
```
      {
        "id": "mode",
        "title": {
          "en": "Mode !{{is|isn't}} turned on",
          "nl": "Modus !{{is|is niet}} aangezet"
        },
        "args": [
          {
            "name": "device",
            "type": "device",
            "filter": "driver_id=mode"
          }
        ]
      },
```

**Comment by WeeJeWel** [comment] 2018-01-17 12:38
That should indeed work. Try saving your Flow again and try again. Maybe the name has changed in the meantime.

**Comment by ArjanKranenburg** [comment] 2018-01-17 21:43
I myself are still on the 1.5.3 to keep supporting VD on the stable version.
This came from a crash-report by one of the users.

In his report on VD, he already mentioned:

> Thanks for your reply. Weird thing is : Before the crashing started i
indeed made some flow changes, after your replies i've changed them back :
But it's still crashing....

and

> I fixed it a few days ago by removing the mode and creating a new one (and editing all the flows), but after 4 days it broke again :(

(the 'mode' is the virtual device)

@dennisbrouwer91: Can you help out with this? Do you still have crashes?
Did you already install the new Virtual Devices (0.7.1 in beta)? That version should prevent the crashes, but not fix the flows.

**Comment by dennisbrouwer91** [comment] 2018-01-19 13:27
Hey Arjan,

I didn't have crashes after i've changed my flows back to what is was. Also
didn't upgrade to beta (was waiting for it to come to the stable channel
but then the crashing stopped...)

2018-01-17 22:43 GMT+01:00 Arjan Kranenburg <notifications@github.com>:

**Comment by WeeJeWel** [comment] 2018-01-19 13:34
I'll close this for now, let me know if it ever happens again!

**Closed by WeeJeWel** 2018-01-19 13:34 UTC
Labels: App-SDK, Flow, bug, waiting for user feedback

**Comment by WeeJeWel** [comment] 2018-01-26 16:32
I've encountered this issue myself, due to a Flow made on the new Homey Smartphone App. I'm pretty sure there's a bug in the app.

**Comment by ArjanKranenburg** [comment] 2018-02-21 20:16
Are you guys working on this? Since the status is still closed.

**Comment by WeeJeWel** [comment] 2018-02-22 11:03
For triggers, this has indeed been fixed. Conditions & actions could not be reproduced.

**Comment by ArjanKranenburg** [comment] 2018-04-06 13:15
I still get crash-reports and can reproduce it with conditions and actions as well. Can you re-open this or shall I create another issue with the latest versions in it?
My Homey is on v1.5.8, the (Android) preview-app is on 0.8.5.115 and iOS is on v1.1.107.

I've added a (Virtual Device) Mode in the desktop App and created the flow on the mobile App.
Note that it has to be a VD-Mode, which has class 'other' and capability 'onoff'. A VD-Device with class 'socket' and capability 'onoff' works fine.

The flow is as follows:
![image](https://user-images.githubusercontent.com/2014478/38421407-4d22b5ec-39a7-11e8-93a8-1f2290479848.png)

When I update the flow in the app (both Android and iOS) by deleting and adding the condition-card, the flow is broken:
![image](https://user-images.githubusercontent.com/2014478/38421965-5599aea4-39a9-11e8-89f1-69b4e64aeb4d.png)

Then when the flow get's triggered, the VD-app crashes (v0.6.8) or reports (0.7.1):
2018-04-06 14:44:58 [log] [ManagerDrivers] [mode] Condition checked without device: {}

I can reproduce this issue with an action-card in the same way, although I don't get the broken flow.
