### ISSUE TITLE
Can't control Milight RGBW bulb

### ISSUE THREAD

**Issue by MartijnHarte** [athombv/homey#231] opened 2016-02-21 21:13 UTC
**What is your Homey version (Settings → System)?**

0.8.17

**What did you try to achieve?**

After succesfully adding a Milight RGBW bulb I am able to control Group 1 (only group I have in use), but the bulb does not respond to any command. Not directly at the devices screen (mobile card?) and not via the flow editor.

*Please include detailed steps how we can reproduce the issue*

1. Go to the devices screen
2. Add a device
3. Install the Milight app
4. Add a RGBW bulb
5. In my case click group 1 and then next
6. The bulb has been added succesfully
7. Click on the mobile card settings
8. Change the bulb settings (e.g. color)
9. The bulb doesn't do anything with it

Extra info (weird behavior):

10. Open the milight android app
11. Choose the interface which you always use to control the milight bulb
12. Change the bulb settings (e.g. color)
13. The bulb doesn't respond.
14. Turn the milight bulb off and then on again using the milight android app
15. Change the bulb settings (e.g. color)
16. The bulb does respond.
17. Repeat steps 8 - 13 and the bulb doesn't respond anymore.

**What was the result?**

The bulb doesn't respond to any command until it has been turned off and on again using the android app.

**What did you expect as result?**

I expected to be able to change the bulb settings using Homey's mobile card and flow editor.

**Any other remarks**

Homey does seem to know that I have only Group 1 in use, as other groups are greyed out when opening the mobile card.

It seems to be trying to control the bulb as the bulb isn't controllable anymore using the android app after controlling it with Homey.

This issue may be linked to Issue #59 although that one is closed?

**Comment by freekwebdesign** [comment] 2016-02-26 16:09
@MartijnHarte Thanks for reporting this issue.
I was able to reproduce your issue and will try to fix it in the upcoming version of the Milight app.
Sometimes it might help to reboot your Homey, then all the MiLight variables will be reset to the default values.

Answers on the other remarks you have:
Homey does not know to which groups your lights are connected. (This is why it shows all the groups as available)
This is unfortunately caused by a limitation of the MiLight bridge.

By using two different apps (Android and Homey) the status of the lights will get out of sync.
This is because the status of a light is stored in the app and not in the light itself.
Because of this both apps can show different values for the same MiLight group.
This is again a limitation of MiLight, because we can only send command to the light and not retrieve the status.
But ofcourse we hope that eventually you will only have to use the Homey app ;-)

**Comment by freekwebdesign** [comment] 2016-03-25 10:38
@MartijnHarte your issues should be fixed in v1.1.1.
If you are still experiencing issues, please let me know!

**Closed** 2016-03-25 10:38 UTC
