### ISSUE TITLE
Insights shows nasty extra horizontal bar in graphs

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#843] opened 2016-09-02 08:32 UTC
![temp2](https://cloud.githubusercontent.com/assets/7040452/18197622/6e4c5094-70f8-11e6-8e5e-de1c3cca79c6.PNG)
**What is your Homey version (Settings → System)?**

0.9.3

**What did you try to achieve?**

see temperature in insights of the last month
![temp1](https://cloud.githubusercontent.com/assets/7040452/18197615/65fc02fe-70f8-11e6-9c92-7892a63930be.PNG)

**What was the result?**
graph with nasty extra horizontal bar in same colour. as ypu can see one homey has the bar the other not , same app with same version of app and homeysoftware is used.
...

graph without horizontal bar 
...

**Any other remarks**

...

**Comment by bvdbos** [comment] 2016-09-02 08:48
I think an extra variable got logged somewhere during a previous install? After august 30th you got rid of it? Also: is this  really a temp-graph?

**Comment by nattlip** [comment] 2016-09-02 08:53
yes this is really a temp graph, from oregon scientific , not ll readings of the thermometer are correct , of course they could be filered but the graph shows the correct readings, remember this is science in the pure word so all readings will be shown.

**Comment by nattlip** [comment] 2016-09-02 08:59
i tried to delete the graph and did , but making a new graph with the smae variable gives the same graph with the same horizontal bar. if i delete the device i loose all readings.

**Comment by jeroenvollenbrock** [comment] 2016-09-02 10:20
Duplicate of #139

**Closed by jeroenvollenbrock** 2016-09-02 10:20 UTC
Labels: bug, duplicate, Homey Core, Insights

**Comment by Dijker** [comment] 2016-09-02 10:52
@nattlip if you download the data you should see the NUL values as described in #212 
These are the problem....

**Comment by nattlip** [comment] 2016-09-02 11:08
@Dijker : how do i donwnload the data file ?

**Comment by Dijker** [comment] 2016-09-02 11:22
![image](https://cloud.githubusercontent.com/assets/12412734/18202451/4908f144-7110-11e6-96a9-8f6842931d99.png)
here....

**Comment by nattlip** [comment] 2016-09-02 11:27
@Dijker : thank you !!
