### ISSUE TITLE
Zigbee networks fails after a day

### ISSUE THREAD

**Issue by epjjansen** [athombv/homey#2074] opened 2017-12-15 10:39 UTC
**Metadata**

**Homey Version**: 1.5.6 RC6
**Homey Log Code**:D1D54F2DC2
**Smartphone Platform**:
**Smartphone App Version**:
**If related to a Homey App**: IKEA Trådfri, Remotec Technologies

**Homey App Version**:
**Homey App Log Code**:
**Affected Devices (preferably product codes)**: IKEA Trådfri lights 8 pieces, Remotec Scene Master ZRC-90 (BW8510)
**What did you try to achieve?**
Turn the lights off/on/dimmlevel
Use any IKEA Zigbee Device

**What did you expect as result?**
Zigbee working as intended, i.e lights turning on

**What was the result**?
No Zigbee devices available, no flows working on Zigbee devices.
Couldn't turn devices of in Homey App in Windows
They worked before also after the update to 1.5.6 RC6
 Homey has been powered down for 30 minutes due to issue with 433Mhz (other issue)
Turned homey on again no issues, for at least a day.

**Any other remarks**
A Reboot of homey restarted the Zigbee network and my devices and flows are working again
Will monitor the Zigbee network in developer website.

**Comment by nieuwton** [comment] 2017-12-15 16:30
I have the same problem. See my message is the Athom Community Forum:
https://forum.athom.com/discussion/comment/64384/#Comment_64384

**Comment by philsniff** [comment] 2017-12-15 23:00
I have exact the same issue. After a day zigbee (Osram Plug and some xiaomi switches) won't work/react. Only reboot of homey can fix the Problem. Now i just came home and the zigbee network is crashed. there are just 20 hours from yesterday reboot. I Update to 1.5.6-rc7 and it works again.  But i think that als the reboot.

**Comment by nieuwton** [comment] 2017-12-16 09:17
Still the same problem with 1.5.6. Need to PTP.
Crash log: 19BD3E1EC2

**Comment by bvdbos** [comment] 2017-12-16 09:19
@nieuwton Which RC of 1.5.6?

**Comment by nieuwton** [comment] 2017-12-16 09:41
@bvdbos 1.5.6 rc7

**Comment by philsniff** [comment] 2017-12-16 10:32
my rc7 firmware now runs since about 12 hours. zigbee network works so long.
i will report after how many hours it will break if i recognize it

**Comment by CliffBroeren** [comment] 2017-12-16 12:31
Oh I'm Sorry i reported yet the same problem  #2077  with rc7 Again zigbee Broken

**Comment by philsniff** [comment] 2017-12-17 17:14
okay, after perhaps 30 hours i could add a new xiaomi one button switch, but no flow won't run with it.
 also one of my other xiaomi switches won't react anymor (switching fibaro plugs).
i decidet to reboot homey... and all works like it should!

so there is something wrong with zigbee after one day +- a few hours...

**Comment by philsniff** [comment] 2017-12-17 19:28
Before i rebooted homey i took a look into the zigbee settings. The first point where normaly was a button for setting the  zigbee settings was written „loading network settings....“ or something else. And there was no end in loading

**Comment by philsniff** [comment] 2017-12-17 19:29
For resetting the zigbee settings...

**Comment by nieuwton** [comment] 2017-12-27 10:59
68 hours since last reboot. Zigbee network still working.

**Comment by philsniff** [comment] 2017-12-27 11:51
Yes, my zigbee network Seems stable since some days. I think rc7 fixed it.

**Comment by philsniff** [comment] 2018-01-01 16:08
After several days without problems, perhaps 1,5 weeks, my zigbee devices failed. Reboot and all works again.

**Comment by nieuwton** [comment] 2018-01-06 22:43
My Zigbee network is still stable. Also after installing rc8. It seems that zigbee needs a learning curve.

**Comment by canedje** [comment] 2018-01-07 19:23
I also have no zigbee (Ikea bulbs) control after about 24 hours. After a reset it works again.
Using rc8

**Comment by epjjansen** [comment] 2018-01-08 08:42
After the update to rc8, some zigbee bulbs are working after 24 hours, some not
a reset helps to solve the issue

**Comment by CliffBroeren** [comment] 2018-01-08 09:18
I have RC8 and all zigbee devices work. but to a few hours I have to be homey PTP. because then zigbee crashed and no zigbee device is responding. it's once 4 hours and sometimes 10 hours sometimes 24 hours

**Comment by synegic** [comment] 2018-01-08 13:12
I have been seeing the exact same behaviour for a couple of weeks now. It actually worked fine before (1.5.6-rc.6).

I have 24 Zigbee devices connected to Homey;

- 8 IKEA Tradfri bulbs
- 8 Xiaomi Aqara Human Body sensors
- 4 Xiaomi Aqara Door/Window Contact sensors
- 2 Xiaomi Aqara Weather sensors
- 2 Xiaomi Aqara Switches (one single, one double)

Seeing same behaviour as reported above; all bulbs, sensors and switches stop responding and I have to PTP daily.

**Comment by RobinBol** [comment] 2018-01-15 15:23
@nieuwton the log id you post, is that send after you rebooted Homey when the problem occurred? From the logs I don't see anything strange.

**Comment by nieuwton** [comment] 2018-01-15 15:47
@RobinBol I think you are right, but I am not sure. It is a long time ago. It is also a long time ago that the zigbee network was lost. It looks like zigbee needed a learning curve to get stable. I have two zigbee networks, one plugwise and the other tradfri and Xiaomi. Could there have been an interference?
If I encounter the problem again, I will send the log before the PTP.

**Comment by RobinBol** [comment] 2018-01-15 16:06
One thing I'd like to know, when the network has become unresponsive, could you try to switch a zigbee bulb off/on manually (toggle the mains power), and then see if it becomes controllable again (that specific bulb), so without rebooting Homey.

**Comment by nieuwton** [comment] 2018-01-15 16:13
@RobinBol I can't remember if I tried toggling mains power of bulbs.

**Comment by synegic** [comment] 2018-01-15 16:18
@RobinBol I just encountered this issue again, have been all week. Yesterday seemed promising, but today it crashed again. Actually, just witnessed it crashing. After triggering good night scene, all bulbs went off but after that Zigbee crashed, shows the broken map in devtools and all IKEA bulbs are uncontrollable. It does not regain control of the bulb after turning it off/on again.

I will be PTP'ing now because my whole house is depending on these lights and switches.

Log ID from before PTP and crashed state: 82F066673B

**Comment by CliffBroeren** [comment] 2018-01-16 13:17
@RobinBol  One thing I'd like to know, when the network has become unresponsive, could you try to switch a zigbee bulb off/on manually (toggle the mains power), and then see if it becomes controllable again (that specific bulb), so without rebooting Homey.

I have a Zigbee ''Crash'' At the moment   i tried to switch the bulbs manually with the power on off.
Then with homey but that's not working   I'm on RC8    and this is the log before PTP AA36373CA0

i hope i helped you with this

**Comment by jeroenvollenbrock** [comment] 2018-02-08 11:41
Can you please let me know whether this issue persists in the latest rc or not?

**Comment by synegic** [comment] 2018-02-08 11:44
@jeroenvollenbrock I would really like to test (as I'm currently still forced to reboot multiple times a day because nothing works in my home without Zigbee), but Homey says there's no update available. Is it possible to join the DP release cycles so I can test and verify? Everything is better than the current version I'm stuck on (rc.8).

**Comment by nieuwton** [comment] 2018-02-08 12:17
@jeroenvollenbrock Homey 1.5.6 RC8. My zigbee network is stable since more than 5 weeks. It was a learning curve of zigbee. I didn't change anything. Could there be an interference with wifi?

**Comment by bvdbos** [comment] 2018-02-08 12:19
speaking for Jeroen, definitely
https://support.metageek.com/hc/en-us/articles/203845040-ZigBee-and-WiFi-Coexistence

**Comment by bvdbos** [comment] 2018-02-08 13:49
RC11 is available now...

**Comment by synegic** [comment] 2018-02-08 13:51
Thanks, didn't notice that (this morning it was not available yet). After manually hitting update, it just started updating. Will report back if it happens again, with log ID's.

**Comment by epjjansen** [comment] 2018-02-08 16:13
Installing RC11 right now, keep you updated with the findings

**Comment by powermarcel10** [comment] 2018-02-10 15:20
I'm still having this issue using RC11 :(. My log number is 712C18DEB6.

**Comment by powermarcel10** [comment] 2018-02-22 22:44
Any news on this?

**Comment by philsniff** [comment] 2018-02-23 08:30
i have no issues any more with zigbee. but i have only xiamo battery devices. the one ikea bulb was to the hue bridge paired, not with homey.

just for information ;-)

**Comment by epjjansen** [comment] 2018-02-23 09:02
Version Homey Firmware Version: 1.5.6 is more stable, Only one ikea bulb is missing a flow once every x days. Had 1 issue with timezone. Flows with specific times started hour to late. After setting Location from Manual to Automatically and back to Manual, this was fixed.

**Comment by bvdbos** [comment] 2018-02-23 09:06
Comments are being added to multiple bugs regarding the same issue... I suggest closing this one and continue in #2141. That said: The time-issue has been resolved already. And personally I have to issues with Zigbee.

**Comment by jeroenvollenbrock** [comment] 2018-02-26 14:25
Closing as duplicate of #2141

**Closed by jeroenvollenbrock** 2018-02-26 14:25 UTC
Labels: Zigbee, bug, waiting for user feedback, watch
