### ISSUE TITLE
[Feature Request] Change spoken language in a the voice flow chart

### ISSUE THREAD

**Issue by djanssen1** [athombv/homey#1544] opened 2017-05-15 10:19 UTC
It would be nice if you are able to set the language in a flow card. So when your Homey is in English for example and you want to speak in Dutch then you can change it so it speaks in Dutch. Or way around

**Comment by bvdbos** [comment] 2017-05-15 10:30
dupe of #1526

**Comment by jeroenvollenbrock** [comment] 2017-05-15 14:01
Closed as duplicate of #1526

**Closed by jeroenvollenbrock** 2017-05-15 14:01 UTC
