### ISSUE TITLE
Homey stops listening after a while

### ISSUE THREAD

**Issue by OpenMindNL** [athombv/homey#1726] opened 2017-08-05 21:31 UTC
**What is your Homey version (Settings → System)?**

1.5.0-rc.2

**What did you try to achieve?**

 Give Homey a speech command

*Please include detailed steps how we can reproduce the issue*

?
I say: OK Homey...  

**What was the result?**

no response... 

**What did you expect as result?**

Orange LED ring animation, indicating that Homey is listening.

**Any other remarks**

This happens at least once a day since updating from 1.3.2 to 1.5.0-rc.2. That's 3 times until now.
Homey needs reboot before it starts listening as it should.

**Please attach a Homey System log (Settings -> System -> Send Log)**

3FA384D9DB

**Comment by jghaanstra** [comment] 2017-08-07 06:19
This is a duplicate of https://github.com/athombv/homey/issues/1726 but the issue indeed persists on 1.5.0-rc2.

**Comment by bvdbos** [comment] 2017-08-07 07:34
Think you mean #1612 ?

**Comment by OpenMindNL** [comment] 2017-08-07 20:48
Well... I get the impression that there's more going wrong since the last update.

- Crashing apps (Hue, Sonos, Netatmo)
- Missing data collection from devices like Netatmo Weatherstation + extra indoor sensors.
- Missing data collection from Netatmo Welcome ... but that could be an IFTTT problem.
- KAKU controls (like AWST-8000 + 8002, AYCT-102) often need several presses before having any effect. Broke flow connections for them also. The KAKU wall sockets still work fine.

- And the newest right now: Homey doing the Mannequin Challenge. Just doing nothing... frozen orange LED ring. But when I ping Homey's IP, it replies. Homey Desktop also still seems to work, although it seems to be a little slower

Created a new crash log: 28DF235B11 ... and gonna do a PTP now.

**Comment by OpenMindNL** [comment] 2017-08-08 16:08
And... stopped listening... again.

**Comment by OpenMindNL** [comment] 2017-08-09 19:27
And again...

Log: C12FAAAE2D

**Comment by kukel** [comment] 2017-08-10 13:44
Did not have this problem on 1.5.0-rc2 and before, but do encounter it now on 1.5.0-rc5 (voice on phone app also not working, so it might be an external issue?)

**Comment by corvdniet** [comment] 2017-08-10 15:07
Same here (1.5.0-rc4)

**Comment by corvdniet** [comment] 2017-08-10 18:28
And is working again (after a couple of hours). Didn't do or change anything. Strange!

**Comment by jeroenvollenbrock** [comment] 2017-08-11 13:27
Closing as duplicate of #1612 The problems of yesterday were caused by a server outage at our speech processing partner.

**Closed by jeroenvollenbrock** 2017-08-11 13:27 UTC
