### ISSUE TITLE
Homey extremely slow after update to 1.5.1 

### ISSUE THREAD

**Issue by ivleth** [athombv/homey#1809] opened 2017-09-10 19:37 UTC
Hi, I thought I post it as well here as on the forum: https://forum.athom.com/discussion/comment/57990/#Comment_57990

Since the last update to 1.5.1 I have huge delays with flows being executed. Walking into a room with a fibaro (or aeotec) motion sensor normally switches light on instantly, now it takes about 10-20 seconds. On the app I see the motion triggered right away, but then it is waiting for the light to be turned on... Any ideas what would causing this? Also, what I noticed is that the Zwave network graph is kind of exploded, normally a device would have 1 or 2 lines to the homey, now each device has 5-10 lines? Maybe that's why switching on the light take a while? See https://imgur.com/a/n2vvV or attached.

![mesh](https://user-images.githubusercontent.com/3604185/30252298-331f3fc4-9670-11e7-906a-8e804eafdbb5.jpg)

**Comment by bvdbos** [comment] 2017-09-10 19:56
The more lines the better for zwave so that's not the issue. you receive a signal from a zwave-device, process that in Homey and then switch a zwave-light? What do the zwave-logs say (settings-zwave), could you add a log to this bug?

You could use direct association between the sensor and the light in zwave, almost instantly switching.

**Comment by ivleth** [comment] 2017-09-10 20:04
Thanks for the quick follow up. I am not using direct associations because I dim the lights during the night opposed to the day. (example: day 100% and at night 20%)
included the log of today.

ps, I will keep an eye on when what fails and will gather the log entries. Thanks!
[zwavelog.txt](https://github.com/athombv/homey/files/1290889/zwavelog.txt)

**Comment by ivleth** [comment] 2017-09-10 20:18
Ok, heb 1 casus, naar de wc en een halve minuut? later gaat pas een keer het licht aan...


---- Dit is BwSensor Wc beneden [ID 42] ---- (aeotec multisensor 6)

[2017-09-10T19:27:16.876Z] Node[42]: Received application command for COMMAND_CLASS_SENSOR_MULTILEVEL, data: 0x05012200de
[2017-09-10T19:27:17.368Z] Node[42]: Received application command for COMMAND_CLASS_SENSOR_MULTILEVEL, data: 0x0505013d
[2017-09-10T19:27:19.290Z] Node[42]: Received application command for COMMAND_CLASS_BATTERY, data: 0x0364
[2017-09-10T19:27:23.276Z] Node[42]: Received application command for COMMAND_CLASS_SENSOR_MULTILEVEL, data: 0x05030a0000
[2017-09-10T19:27:23.514Z] Node[42]: Received application command for COMMAND_CLASS_SENSOR_MULTILEVEL, data: 0x051b0100
[2017-09-10T19:27:23.680Z] Node[42]: Received application command for COMMAND_CLASS_WAKE_UP, data: 0x07
[2017-09-10T19:27:23.683Z] Node[42]: Marked as online
[2017-09-10T19:27:27.184Z] Node[42]: sendData to COMMAND_CLASS_WAKE_UP, params 0x08
[2017-09-10T19:27:27.336Z] Node[42]: Marked as offline

---- beweging gezien volgens lampje sensor ----

[2017-09-10T20:10:56.890Z] Node[42]: Received application command for COMMAND_CLASS_SENSOR_BINARY, data: 0x03ff
[2017-09-10T20:10:57.593Z] Node[42]: Received application command for COMMAND_CLASS_NOTIFICATION, data: 0x05000000ff07080000
[2017-09-10T20:12:16.595Z] Node[42]: Received application command for COMMAND_CLASS_SENSOR_BINARY, data: 0x0300
[2017-09-10T20:12:16.927Z] Node[42]: Received application command for COMMAND_CLASS_NOTIFICATION, data: 0x05000000ff07000000

---- Dit is Spots Wc beneden [ID 43] ---- (Qubino flush dimmer)
[2017-09-10T20:10:56.947Z] Node[43]: sendData to COMMAND_CLASS_SWITCH_BINARY, params 0x01ff
[2017-09-10T20:10:56.954Z] Node[43]: sendData to COMMAND_CLASS_SWITCH_MULTILEVEL, params 0x0163ff
[2017-09-10T20:11:39.678Z] Node[43]: Received application command for COMMAND_CLASS_SWITCH_MULTILEVEL, data: 0x016300
[2017-09-10T20:11:41.400Z] Node[43]: Received application command for COMMAND_CLASS_METER, data: 0x02213400000078000000000000
[2017-09-10T20:11:42.406Z] Node[43]: Received application command for COMMAND_CLASS_METER, data: 0x0221340000007a000000000000

**Comment by bvdbos** [comment] 2017-09-10 20:18
Which node is sending motion and which node is the switch for the light?

**Comment by StraDijk** [comment] 2017-09-11 06:33
I got the same issue.  Flows are executed with delays and Homey is stuttering.

**Comment by ivleth** [comment] 2017-09-11 10:40
I did some additional testing, and simply, everything which is zwave is huge delayed or not even responding at all. Switching on/off kaku is done instantly... For your information, the only thing changed is the software update to 1.5.1... So flows, devices and settings are still the same.

**Comment by jeroenvollenbrock** [comment] 2017-09-11 14:27
Was this an update from 1.5.0 to 1.5.1, or from an older version to 1.5.1?

**Comment by ivleth** [comment] 2017-09-11 14:50
From the previous stable release, 1.3x. I am not using the experimental channel. I upgraded from 1.3 to 1.5.0 to 1.5.1

It definately has something to do with load I guess, load is now around 0.5-0.7 and everything runs smooth.

**Comment by jeroenvollenbrock** [comment] 2017-09-11 15:55
It most likely had something to do with the load indeed, it may have been a migration script that was running, but unfortunately it is not possible to debug further, as the problem no longer occurs for you.

**Comment by ivleth** [comment] 2017-09-11 17:11
Actually... load is back at 1.5 and zwave is not working anymore... Can somebody look into my homey to see what is causing this?

**Comment by jeroenvollenbrock** [comment] 2017-10-27 07:47
Sorry, i missed your response. Can you provide us with a log while this is occuring? (settings->system->log)

**Comment by ivleth** [comment] 2017-10-27 07:59
Hi, it was due to unreachable devices which were causing the delays. Thanks for the follow up. You can close this.

**Comment by kukel** [comment] 2017-10-29 18:00
If unreachable devices causes this behaviour, I would not close the issue but find out if this can be prevented

**Comment by ivleth** [comment] 2017-10-29 18:02
that is true, e.g. set the limit of retries

**Comment by ivleth** [comment] 2017-10-30 08:16
Actually, I added this weekend a (battery powered) fibaro motion sensor on the far edge of my mesh network. Within a couple of meters there is outlet powered device (qubino dimmer). In the zwave diagram these connections are visible and things should work. Reality is that the sensor hangs up the network as it is timing out continuously. After removing the sensor things are starting to work again... So, I agree with Kukel, we need a solution for this...

**Comment by Lowlander61** [comment] 2017-11-22 19:22
Same issue's here, I just switched to Homey from Domoticz for a more stable system, it looks like I was wrong. Switching lights through the app works fine, but all flows with sensors are very slow. Motion is detected, I can confirm that in the app, but no switching of lights. I really hope there will be a solution soon.

**Comment by WeeJeWel** [comment] 2017-12-01 14:06
Duplicate of #1899

**Closed by WeeJeWel** 2017-12-01 14:06 UTC
Labels: bug, Z-Wave
