### ISSUE TITLE
KAKU Heater device not selectable in Flow

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1438] opened 2017-03-31 21:49 UTC
**What is your Homey version (Settings → System)?**
1.2.0 rc10

**What did you try to achieve?**
Add heater AGDR-3500 to homey as heater device, but not selectable in flows
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24570598/9010b8a4-166c-11e7-8f77-053ba531c16c.png)

*Please include detailed steps how we can reproduce the issue*
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24570606/9a63bc20-166c-11e7-82dd-cb61568a6a7c.png)

**What was the result?**
Heater 2 not selectable in flow

**What did you expect as result?**
Heater 2 selectable in flow

**Any other remarks**

**Comment by Dijker** [comment] 2017-04-01 06:40
Comparable to #433 
Heater, fan, kettle .... All need to be added¡

**Comment by BasKiers** [comment] 2017-04-04 12:21
Hi,

Heaters should already have flow cards. I suspect this issue is caused by the issue mentioned in #1432 where the device name is not updated in the flow interface. Could you try searching for "AGDR" and check if the device is listed under the old name?

Regards,
Bas

**Comment by BasKiers** [comment] 2017-04-04 14:53
So you also experience issue #1432. Can you confirm that you can find the device when searching for AGDR (or whatever the initial name of the heater socket is)?

**Comment by chrisboer** [comment] 2017-04-04 15:03
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24663552/8799615a-1958-11e7-845a-ae4dfea253ac.png)
I named them H1 and H2 but I see them both as AGDR-3500 see screendump

**Comment by BasKiers** [comment] 2017-04-04 15:06
Thanks for the response. I will close this issue since it is caused by issue #1432

**Closed by BasKiers** 2017-04-04 15:06 UTC
Labels: Devices, waiting for user feedback
