### ISSUE TITLE
philips hue, lux lamps wont turn off or on with command all lights of or on

### ISSUE THREAD

**Issue by nattlip** [athombv/homey#179] opened 2016-02-13 18:18 UTC
with voice command "all lamps off or on"

all connected to the bridge 
my hue color lamps turn off and on
my hue lux lamps dont react
my living white lamps react
my lliving white plugs react sometimes
my color strip reacts

every thing works if i i turn them off or on on the device page

in the philips hue app , all respond with the button "everything off"

**Comment by HiemstraJ** [comment] 2016-02-14 12:54
I also have issues with Hue lamps not responding to on or off commands. Rebooting Homey fixes it, but it sometimes comes back.

**Comment by nattlip** [comment] 2016-02-14 13:01
indeed once in 10 times all lamps react, especially off . the name changing of the bulb works good.

**Comment by HiemstraJ** [comment] 2016-02-14 21:01
I had a different related issue as well. At this moment I have only 1 flow, this contains some of my hue lights. When turning on lights outside homey (philips app), only the lights inside this flow will turn off with the 'turn off the lights' phrase. Expected behaviour: all lights should go off, shouldn't matter which route turned them on.

Maybe Homey remembers the lights state (on/off) and doesn't refresh them after the Philips app turned them on?

**Comment by WeeJeWel** [comment] 2016-02-15 15:12
When you say 'Lights off', are you sure that the Lux lights are turned on in Homey? If they are turned off already (out of sync due to another Hue app/remote/etc.), then Homey won't send the signal to turn them off.

**Comment by nattlip** [comment] 2016-02-15 16:26
i wi ll test one of these days. , but i made hue app myself for node.js, but your app has to check the status of the lights once in a while and update it in the app , hue  is made for more then one remote simultanously  in the house. all phillips hue apps do that for android and ios.

**Comment by AndreSomers** [comment] 2016-02-15 16:37
It is a bug that Homey doesn't turn off lamps it thinks are already off. It is unfortunate, but the Hue status needs to be polled from the bridge frequently. Other apps do that, Homey should too.

**Comment by WeeJeWel** [comment] 2016-02-15 16:43
Yes, polling is going to be implemented :)

**Comment by freemann** [comment] 2016-02-15 16:46
+1 for polling!

**Comment by HiemstraJ** [comment] 2016-02-15 18:52
I don't see why polling is part of this issue?? If I want all the lights turned off, just send a off command to all lights regardless of current state.

Coming home flow is **not** working correctly now:
- Turned all lights off yesterday with philips app;
- Come home trigger flow, which is supposed to turn on some lights;
- The voice is the flow is triggered correctly, no lights turned on.

**Comment by WeeJeWel** [comment] 2016-03-25 22:34
Please try again with v0.9.10 of the Hue app.

(And closing this issue as it's a duplicate of #94 )

**Closed by WeeJeWel** 2016-03-25 22:34 UTC
