### ISSUE TITLE
8.34 = no freeze at all 8.35 = freezing again.

### ISSUE THREAD

**Issue by posthok** [athombv/homey#635] opened 2016-05-21 13:47 UTC
**What is your Homey version (Settings → System)?**
0.8.35

**What did you try to achieve?**

While working with flows, Homey freezes with a static rainbow led

_Please include detailed steps how we can reproduce the issue_
After moving a flow a flow into a folder and refreshing the page it got frozen.
After powering off and working with flows again, within a short amount of time it got frozen again.
Actions: Making a folder and moving flows to the folder.

**What was the result?**
8.34 worked great. had no issues at all.
8.35 2nd chrash since updating

...

**What did you expect as result?**
a working homey.

**Any other remarks**

...

**Comment by freemann** [comment] 2016-05-21 13:50
I'm currently not at home and the android app and my.Athom.com shows homey is offline. 
My websites are still online, so Internet connection is working and this tells me my homey is also in a freeze....

**Comment by bvdbos** [comment] 2016-05-21 13:55
Unfortunately for you : not able to reproduce the way you describe...

**Comment by posthok** [comment] 2016-05-21 14:07
try to edit a flow and refresh the page.

**Comment by posthok** [comment] 2016-05-21 14:13
I got it every time i'll do that.

**Comment by Dijker** [comment] 2016-05-21 20:29
I have seen similar things, this afternoon and just now again moving some Flows into folders.
2016-05-21T17:59:26.468Z	LastLogSend:"DA9D40EA13"
2016-05-21T20:22:02.024Z	LastLogSend:"8EBE4C6658"
When it happens, 
- Ring stops rotating, 
- Now http response to site ...
- Ping reply's normal
- No respose checking KAKU (Ring should change)
- No response on NFC (expected Voice )
Had to pull the plug.  Logs send short after restart.

**Comment by freemann** [comment] 2016-05-21 20:56
mid evening I came home and indeed Homey was hanging with a frozen rainbow....
When I left home I started a debug session of the AndroidTV app and found the console with these error;
```
Error: connect ECONNREFUSED 192.168.1.61:80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
Error: socket hang up
    at createHangUpError (_http_client.js:200:15)
    at Socket.socketCloseListener (_http_client.js:232:23)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:477:12)

--- INFO: com.sony.androidtv has been killed ---
Disconnected from Homey, automatically reconnecting...
Trying to reconnect...
Debug session expired, exiting...
```

I hope it can help @WeeJeWel solve the freeze issue.

**Comment by posthok** [comment] 2016-05-22 04:55
I have regrets updating homey to 8.35 wanna go back to 8.34 knowing that's not possible.

**Comment by bvdbos** [comment] 2016-05-22 06:32
This looks like errors on the saving of flows in folders, like the correct id's aren't saved. What does the chrome-console say during this process? Are there any errors?

**Comment by bvdbos** [comment] 2016-05-22 07:13
https://forum.athom.com/discussion/comment/23245/#Comment_23245
even 10 minutes after moving the first flow...

**Comment by WeeJeWel** [comment] 2016-05-22 12:45
The issue has been identified as a memory leak and will be fixed asap!

**Comment by daneedk** [comment] 2016-05-23 08:07
Great, and how fast wil this fix be distributed?

**Comment by sossienl** [comment] 2016-05-23 20:40
Same here. what a pain

**Comment by sossienl** [comment] 2016-05-29 09:47
Any update on this? Would be good to understand when this is fixed.

**Comment by posthok** [comment] 2016-05-29 09:51
I think whe have to wait till next weeks firmware release

**Comment by sossienl** [comment] 2016-06-03 19:50
0.8.36 gives the same problems. Unresponsive Homey

**Comment by posthok** [comment] 2016-06-03 22:14
8.36 working fine for me. No freezes yet.

**Comment by sossienl** [comment] 2016-06-03 22:16
Good for you. Here a constant freeze / brick. No change after updating. Tomorrow try to restore.

**Comment by WeeJeWel** [comment] 2016-06-06 10:57
@sossienl Can you reproduce your freeze? I really want this fixed, but I need some steps to reproduce it. :'(

**Comment by sossienl** [comment] 2016-06-06 11:09
No, I have tried multiple times to understand the reason. After reboot I get no response at all. After a few hours it seems to be accessible (but very slow). I can't read any logs and that makes it a big guess.

It now seems that all my ZWAVE devices are not doing anything anymore. The ZWAVE page in settings is giving a lot of errors and restarting the chip gives: "Error: Z-Wave not ready yet. Please try again later."

I have uploaded the logs again with ID 6D62C2F21A
No other idea how to find the source of the problems as there is no debug / log environment.

**Comment by Arjanvde** [comment] 2016-12-19 13:17
Pam pam pam, pretty sure this one is back again.

My Homey just crashed, was sorting and ordering flows again. Did the following:

Create a folder (1), moved 2 flows (including devices) in that specific folder.
Created 6 flows (working flows including devices), put them in a folder(2) and moved that into folder (1).
Created another 6 flows  (working flows including devices), , put them in a folder(3) and moved that into folder (1).

Than sorted the flows/folders in folder (1) so that first the folders are displayed and then the flows.

@WeeJeWel  pretty sure that if you create a lot of flows (working flows including devices), and folders you will be able to crash Homey again.

**Comment by WeeJeWel** [comment] 2016-12-19 13:26
@arjanvde How do you determine that Homey is frozen? Does the LED Ring still rotate, is the webserver accessible, etc.?

**Comment by Arjanvde** [comment] 2016-12-19 13:27
Webserver unreachable, Homey not pingable, LED Ring is off so can't check the status, Homey doesn't respond to any Z-Wave/433 Remote Signals .

**Comment by Arjanvde** [comment] 2016-12-22 10:06
Please close this issue for now, been stress testing Homey a lot and can't reproduce this anymore on 1.0.5.

**Closed** 2016-12-22 12:15 UTC
