### ISSUE TITLE
Cannot add remote YCT-102

### ISSUE THREAD

**Issue by edtst** [athombv/homey#922] opened 2016-09-28 16:17 UTC
**What is your Homey version (Settings → System)?**

0.10

**What did you try to achieve?**

Add my KaKu YCT-102 remote

_Please include detailed steps how we can reproduce the issue_

I use the KaKu pairing wizard, select YCT-102. It then says I have to press a button, but it doesn't respond when I do. There I am stuck.

**What was the result?**

No pairing possible

...

**What did you expect as result?**

A paired remote
...

**Any other remarks**

When I select a KaKy switch and then use the remote, it works.
...

**Comment by BasKiers** [comment] 2016-09-29 17:54
Hi, on what switch in the pair wizard did you test the remote?

**Comment by bvdbos** [comment] 2016-09-30 20:25
works for me...

**Comment by edtst** [comment] 2016-10-01 09:33
I pressed several buttons, none react.

**Comment by BasKiers** [comment] 2016-10-03 17:25
Could you check if you are able to pair the remote as an AYCT-102?

**Comment by mblom** [comment] 2016-11-20 13:47
Had this issue been solved? I am running into same problem. When adding the ayct-102 and being asked to push a button on the remote, nothing happens. Bought my homey yesterday...

**Comment by BasKiers** [comment] 2016-11-22 13:24
Hi, 

This issue is not resolved since I cannot reproduce it. We have an AYCT-102 remote at the office that works. Could you give some more information so I can better reproduce the issue? For instance;  
did you try restarting Homey?
are you able to pair other 433mhz devices?
which 433 devices do you have paired?
what apps do you have installed?

Regards, 
Bas

**Comment by mblom** [comment] 2016-11-22 19:08
Hi Bas,

Ad 1: yes, I have restarted Homey (couple of times) via desktop app - settings - system - reboot
Ad 2: yes, I have one other 433 KAKU device
Ad 3: a ACD-1000 switch
Ad 4: Fibaro, Google Chromecast, Greenwave Systems, IFTTT, HTTP request flowkaarten, Milight, Nest, Sonos, Better Logic, KlikAanKlikUit, Kodi

I just found out that when I am in the screen to add the AYCT-102 and press some buttons, the text of that screen changes and says that I can also click on a button on the remote that is displayed in de desktop app. When I do this, I notice that for a certain combination of a key with channel a code is sent by Homey which is recognized by the ACD-1000 switch.

But when creating a flow that uses the remote no matter what key / channel combination I use, Homey does not do anything.

Regards,

Mark

**Comment by BasKiers** [comment] 2016-11-23 19:01
Hi,

Thanks for your detailed information of the problem. Unfortunately I could not find the issue yet. One thing I want to confirm is that you pressed the "save" button after you set the trigger card. The trigger card only works after you press save. If this is not the problem I will try to look into this later.

Regards,
Bas

**Comment by mblom** [comment] 2016-11-23 19:44
Hi Bas,

I did press the save button. Attached, you will find a screenshot of the flow. When I press "test", Homey says the text in the textbox. So the flow seems to be ok but is not triggered by my remote.

![2016-11-23_20-38-13](https://cloud.githubusercontent.com/assets/6285499/20576198/3d73576e-b1bd-11e6-82a2-636abb435a30.png)

Regards,

Mark

**Comment by bvdbos** [comment] 2016-11-23 19:48
@mblom Did you choose the correct channel and button in the trigger card (als-card)

**Comment by bvdbos** [comment] 2016-11-23 19:52
Or is this the same issue as #1099 ? Then is seems like something in the trigger-card of KaKu?

**Comment by mblom** [comment] 2016-11-23 20:40
I tried every combination of channel/button in de trigger card. My other KAKU ACD-1000 switch just works fine in an other flow so I do not think it relates to #1099.

**Comment by mblom** [comment] 2016-12-18 19:22
When I am in the screen "identify your remote" and use the same settings as in the picture (bottom switch on I) then nothing happens when I press a button on the remote.

Then, when switch to group III something happens and the screen "test your remote is shown". But still nothing happens when I press any button on the remote.

Pairing as a YCT-102 does not work either.

I have uploaded a screenshot of chrome after having pressed several buttons. Hope this helps!

![2016-12-18_20-17-45](https://cloud.githubusercontent.com/assets/6285499/21295927/9ff9bb66-c55f-11e6-9af8-cc9cb30ac156.png)

**Comment by BasKiers** [comment] 2016-12-21 16:18
Hi,

What I get from your reply is that Homey only responds to the signals of channel 3 of your remote. Could you check if the flow card does trigger when you select a button on channel 3 and try to trigger it with your remote? If it does trigger could you confirm that it does only work for channel 3 and not the other channels?

Lastly, could you sideload the kaku app with the command `athom project --run` and open the device pair wizard for the AYCT-102. When you press the buttons in the kaku app that don't work could you check if there are messages in your terminal like this `Info] [Signal kaku ~300] payload: 00111111010001010100110110000010` or not? Information on how to sideload an app can be found here: https://www.youtube.com/watch?v=lRZLvhF2sfk

I apologize that I am unable to fix this bug directly but the behavior seems really strange and I cannot find where this can go wrong in the app.

Regards,
Bas

**Comment by BasKiers** [comment] 2017-10-31 12:46
Hi,

I will close this app due to lack of updates. I you are still experiencing this problem please open a new issue in the issue tracker.

Regards,
Bas

**Closed by BasKiers** 2017-10-31 12:46 UTC
Labels: Athom App, bug
