### ISSUE TITLE
Unable to pair IR remote

### ISSUE THREAD

**Issue by JesperJanssen** [athombv/homey#50] opened 2016-02-10 18:41 UTC
I'm not able to pair my remote at all (Sony tv). I'm pressing the button for 10 seconds and also tried pressing it multiple times but nothing happens (the circle keeps spinning).

**Comment by stealthblade** [comment] 2016-02-10 19:29
I am also not able to pair any remote. Nothing is happening and the circle keeps spinning.

**Comment by coldshivery** [comment] 2016-02-10 19:30
I can also not pair a remote for my beamer it does not detect any button presses during pairing setup.

**Comment by hilvarenbeek** [comment] 2016-02-10 19:30
Same issue here. When adding an IR remote, the led ring turns off but pushing buttons doesn't help. Sometimes, I got a white cross on red circle when pushing a button for a short period. When I stop the pairing by pressing the 'x' the led ring stays off

**Comment by goldenice** [comment] 2016-02-10 20:46
These problems could be caused by two things:
1) The remote is not in our database;
2) Homey has trouble detecting the remote because the remote only sends the signal once per button press

For the first issue, a beautiful solution is on the way: a brand new pairing wizard, which allows for manual searching in our database, as well as automatic recognition. And when it's not found in our database, you can still add the remote yourself as a fallback.

The second issue is harder to solve: most remotes repeat the signal while the button is pressed, but sadly not all remotes behave like this. Because remotes aren't the most reliable devices, Homey needs at least a few samples to perform a decent search. This should be slightly better in the new pairing wizard. Pressing the button 15 times really fast should give Homey enough data to search on. If the remote isn't found then, chances are it just isn't in our database yet, in which case you'll have to wait a bit for the new pairing wizard. (Luckily, it's almost ready :) ) Just to be sure, could you let me know which remote and tv you use @JesperJanssen @stealthblade @coldshivery, and @hilvarenbeek ?

**Comment by Qx5** [comment] 2016-02-10 20:48
I have the same with a samsung smart tv remote and my philips fidelio e5 remote. Used the volume buttons to be sure the signal was repeating and turned off all lights. Can't wait for the new IR wizzard!

**Comment by hilvarenbeek** [comment] 2016-02-10 20:53
Humax RM-F04 (for IHDR-5200C), Marantz RC021SR (for NR1604), Philips SF308 (for TV), some old Samsung tv remote.

**Comment by coldshivery** [comment] 2016-02-10 20:57
I have a remote for my Optoma beamer. Model number of the Optoma remote is L-27-5KEY

**Comment by JesperJanssen** [comment] 2016-02-10 20:57
I tried remotes of the following equipment:

Sony TV KDL-40EX402 (Remote: RM-ED022)
Logitech Z5500
UPC Horizon Mediabox

**Comment by stealthblade** [comment] 2016-02-10 20:58
I have tested 2 Samsung Smart TV remotes. AA59-00445A and AA59-00790A.

**Comment by richredleg** [comment] 2016-02-10 21:08
The IR trigger does not work. When the IR learning function will stop the ledring not return to the raibow lighting.

I tried remotes of the following equipment:
UPC Horizon Mediabox (old one)
Harman Kardon DVD22
Harman Kardon AVR130
Samsun TV 
Marmitek HDMI Switch

**Comment by lvanderree** [comment] 2016-02-10 21:34
This counts for me as well:

the ledring does not go back to rainbow and non of my remotes seem to get recognized (or even seen).

I have a:
- Sony TV KDL-40W4720 
- Cambridge Audio Amplifier (Azur 651A)
- Samsung PVR (Horizon)

**Comment by hschenkelaars** [comment] 2016-02-11 10:11
Same here for:
- Samsung TV 
- Humax RM-106

**Comment by Sateprikkert** [comment] 2016-02-11 10:20
I use a Sony 65W855C and a Horizon Box. Both remotes are not detected.

**Comment by goldenice** [comment] 2016-02-11 11:52
![Good news everyone](http://g2f.nl/06ljpln)

We found the problem why so many devices wouldn't do anything. While scaling our serverpark to the right amount, some stuff changed, and those changes broke the connection between two of our servers.

This means we've fixed the issue, without even pushing an update to your Homey :smile: Worst case: your remote still isn't in the database. Average case: You'd have to reboot your Homey and the issue is fixed and your remote can be paired. Best case: The issue is fixed without even rebooting!

If it still doesn't work after a reboot, I'd be very interested in the brand and model number of both your remote and your tv / other target apparatus ;)

**Comment by evad1st** [comment] 2016-02-11 13:45
Okay worked great, until I tried to pair nr. 4 ..... 
Philips TV's worked fine, as well as KPN iTV and Philips/Pace Sat receiver....
Until now Philips Blu-Ray and  Pioneer receiver did not work, hangs after 3rd or 4th button to be pressed, same sequence .... I suspect issue related to the previous ...

**Comment by goldenice** [comment] 2016-02-11 14:05
No, I don't think so. It probably just cannot find your remote :/ Try the more generic buttons (OK, 0, 1, Power) instead of the more specific ones (play/pause, AV, etc.)

If it still doesn't find your remote, you'll have to waiting until the new pairing wizard is ready, which I'm currently working on ;)

**Comment by evad1st** [comment] 2016-02-11 14:18
Thanks for quick responding, that's exactly what I did :-) Okay I wait for the update then :-) and meanwhile try other remotes.

**Comment by stealthblade** [comment] 2016-02-11 16:38
My Samsung remotes now work :)

**Comment by Qx5** [comment] 2016-02-11 17:06
I think there might be still a small bug.

When trying to pair my philips fidelio e5 remote it seems to go fine but when it says that he needs just one more, the rainbow goes on and nothing is registered anymore. I tried turning of the rainbow in settings first but then it keeps hanging on the last button press. Even if it can't find my remote the rainbow shouldn't turn on in the process right? (on 0.8.17)

When pairing my samsung tv remote he finds something but volume is registered as up/down and channel up/down button is registered as left/right. Probably still the wrong match of remote?

**Comment by Timminater** [comment] 2016-02-11 17:57
ziggo horizon box remote isn't working

**Comment by goldenice** [comment] 2016-02-11 18:00
@Qx5 Yes, the rainbow should always turn of during IR pairing as it interferes with the IR-receiver. Having your remote found but with buttons mapped to different buttons is unfortunate; this is caused by IR-remote manufacturers reusing the codes, but using them for different buttons. The next version of the pairing wizard should make this better.

@Timminater Sorry to hear that, at least in the next version of the pairing wizard you can add it manually by learning Homey to copy the signals.

**Comment by JesperJanssen** [comment] 2016-02-11 18:29
It works a litle bit better now. I paired my Sony TV KDL-40EX402 remote with the Homey. I created a flow that when I pressed the scene button it should switch off the lights which works fine. However, if I create for example a flow that Homey has to press scene whenever I say select scene it will not send an IR signal to my TV since I do not see the scene menu appearing on my tv.

I tried the flows with the test flow button since the speech recoginition is not working at the moment.

**Comment by edtst** [comment] 2016-02-11 18:32
With the new 8.17 firmware I can pair my LG, but not Grundig remote. It recognizes the first button, then it gets hard (have to try pressing it quicky for minutes) and in the end it says 'only one more time' and when that happens it starts again and again. I have rebooted Homey several times.

TV + Remote: Grundig FINE ARTS 55 FLX 9490 SL Ultra HD

**Comment by hilvarenbeek** [comment] 2016-02-11 19:18
I can't get my Marantz RC021SR remote to get paired. I get 4 successful buttons, then when it says one more, Chrome's developer console has an error "Uncaught TypeError: Cannot read property 'length' of null" and the led ring turns on again. Chrome says the error occurs in VM2652 at Line 1, Column 535

**Comment by Qx5** [comment] 2016-02-11 19:29
@JesperJanssen I basically have the same. 
I think it internally actually matches the wrong remote but the signal of your remote is close enough to the remote Homey thinks it is. So triggering flows with the remote therefor works . But the TV maybe has a more strict margin on the IR code and will not react on the approximation of what Homey thinks the scene button is.

Just my hypothesis :wink:

**Comment by edtst** [comment] 2016-02-12 08:23
Tele2 TV also not working

**Comment by matthijsvdr** [comment] 2016-02-12 22:32
Homey did recognise my first remote, i removed it by accident (whoops) and now Homey does not recognise any remote in my home, or does even respond to anything after pushing buttons for several minutes on every remote (even some remotes that are reported to work above, KPN iTV for example).

I restarted Homey several times, even took the power off at some point. Anyone any idea's?

**Comment by bvdbos** [comment] 2016-02-14 08:26
It's strange detecting some keys works the first time but doesn't work later on even after powering down or rebooting. This seems like it has nothing to do with matching to a database of remotes. To me it looked like some internal state of the detection process (running) was not only kept in memory but saved to SD? Of course tried different remotes, angles, distances etc etc, also tried reinstalling with and without keeping my settings. Would there be anything else I could try?

**Comment by nattlip** [comment] 2016-02-14 09:45
where is the ir emittor and sensor in the homey ?

**Comment by Wimstradamus** [comment] 2016-02-14 19:22
trying to add ir remotes tonight but non ir recieved by homey, ass if its blind, Server issues again ?? 
(ziggo) cisco cable reciever remote
Humax cable reciever remote
yamaha audio reciever remote 
LG tv remote

**Comment by MarcoBannink** [comment] 2016-02-14 19:47
I am trying to pair the following remotes without result:
- Panasonic TV Remote
- Epsilon HTPC Remote
- Philips Home Theater Remote

I am running 8.17 and rebooted, but still no luck.

**Comment by ChrisVendel** [comment] 2016-02-15 14:32
Same problem here. Homey doesn't appear to 'see' ANY IR signals. Doesn't matter which remote I use (Sony, Panasonic, Philips).

**Comment by Fieldhome** [comment] 2016-02-15 18:49
I can sort of pair my Ziggo Cisco cable receiver remote, but the test option results in weird mappings.

Furthermore, my Onky receiver and Philips TV remotes look ok when paired, but when making a flow and trying to send a IR signal, both devices don't respond when testing the flow.

**Comment by Wimstradamus** [comment] 2016-02-15 19:19
Ok, just now i added 3 remotes so Homey can see :-)
Humax cable reciever remote
yamaha audio reciever remote 
LG tv remote

the batteries of my Cisco are dead so can add them right know.

**Comment by RemonBerends** [comment] 2016-02-15 20:55
I have the same problem as Qx5. When pairing my samsung remtoe from a recent model TV, it is detecting the first two different buttons, but when it shows, just one, then the led ring turns on and last button is not read.

**Comment by RemonBerends** [comment] 2016-02-15 21:08
The above is happening to multiple remote's. Till now unable to pair any IR remote.

**Comment by evdsman** [comment] 2016-02-15 21:18
Yesterday Homey did not recognize any IR signals, today it does but hangs after the last input while activating the led ring and continuing requesting for the last button-press. If I wait long enough the led ring deactivates and I can start over again. Tried it with different kinds of brands (LG/Sony/Samsung) and with all possible led settings, all result in the same. Hard or soft reset dit not work, factory reset neither. Here's a [video](https://drive.google.com/file/d/0B5jEolZFQHgzN2szXzlDVzM0NWc/view?usp=sharing) to show you what happens, any suggestions?

**Comment by RemonBerends** [comment] 2016-02-15 21:22
+1 same problem as evdsman describes ...

**Comment by goldenice** [comment] 2016-02-26 14:44
To keep different issues separated, I'm going to close this thread, as the new pairing wizard is shipped in version 0.8.20. If any issues occur with the new pairing wizard, please open a new issue. Thanks for your help and input on this one, it certainly helped us design the new pairing wizard!

**Closed by goldenice** 2016-02-26 14:44 UTC
