### ISSUE TITLE
Homey doenst send 433 MHz signals

### ISSUE THREAD

**Issue by robintielemans** [athombv/homey#865] opened 2016-09-18 18:01 UTC
**What is your Homey version (Settings → System)?** Latest version -> 0.9.3

x.x.x

**What did you try to achieve?** Reboot device, factory reset device. turn off 433 devices

*Please include detailed steps how we can reproduce the issue*
I add my 433 mhz action promax remote. it does recognize the button i press and when it is turned on/off, but does not send any to put on/off the lights regulated by the remote.

It worked about 2-3 months ago, but something seems have shut it down.

**What was the result?**
Didnt work
...

**What did you expect as result?**
Expected it to send out 433 mhz signals to turn down lights.

**Comment by bvdbos** [comment] 2016-09-18 18:21
What's your uptime? Did you send a log to Athom (settings-system). Did you, after that, restart Homey? Did you, after that, PTP (pull the plug) for a couple of minutes?

**Comment by robintielemans** [comment] 2016-09-19 06:31
Turned it off at the moment. Hasnt been online for longer than 3 hours tops. FW version 0.9.3. Did not send a log yet. Can I just send it without any context?

**Comment by bvdbos** [comment] 2016-09-19 07:12
Yes, wou can send the log without context, just copy the code you get in this bugreport. So sending 433 is working for three hours after a PTP and then it fails? Which apps do you have installed?

**Comment by robintielemans** [comment] 2016-09-19 07:42
Nope, just doesnt work at all. Even after PTP. I've installed the "Action" app. It supports the promax remotes as it did before. No other users experience this same issue. Will add log later, cannot turn it on at the moment.

**Comment by robintielemans** [comment] 2016-09-20 10:41
Just sent the log.. Code is AAC98C66D3  @bvdbos

**Comment by bvdbos** [comment] 2016-09-20 11:43
Now it's up to someone at Athom to pick this  up :-)

**Comment by BasKiers** [comment] 2016-09-23 15:24
Hello, 

If I'm right you are unable to send signals in the promax remote pairing wizard. This is intended behaviour since the protocol sends an encrypted signal and the only way I would be able to send all signals of the remote is if I copy all signals. This is not really necessary since remotes are only used as flow triggers, not actions. 

When you want to control a promax device you can add it as a promax socket. The pair wizard will then ask you to press the button on your remote multiple times (to copy the signal) and will store that to control your device. 

As long as I am not able to decrypt the signal this feature will not be added.

Regards,
Bas

**Comment by robintielemans** [comment] 2016-09-23 19:07
Hi @BasKiers. I am adding my remote with a certain button (e.g. press x to turn on light). It should copy the signal and send it out the same way as it got it. It worked perfectly fine about 2 months ago. Doesnt do anything as of yet.

**Comment by robintielemans** [comment] 2016-10-06 18:10
bump --

**Comment by robintielemans** [comment] 2016-10-13 11:56
bump -- @jeroenvollenbrock  @bvdbos  @BasKiers  @WeeJeWel

**Comment by jeroenvollenbrock** [comment] 2016-10-13 12:36
Is this still an issue on Homey version 0.10.3 / 0.10.5 ? The log you sent earlier lists a bug that is supposed to be resolved there.

**Comment by uNiiek** [comment] 2016-10-13 19:12
For me still doesn't work.

Re-paird the RC50075 remote --> Make new flow: 
![remote](https://cloud.githubusercontent.com/assets/18580351/19363099/5fbfa164-9189-11e6-81b8-c79b593cefd4.png)

Test says OK.
But if i push button 4 on on the remote nothing happent. 

Log after re-pair end new flow: D551E1700B
Homey version 0.10.5
Action app v2.1.1

**Comment by robintielemans** [comment] 2016-10-15 14:01
Same issue here, is not solved at all. @jeroenvollenbrock

**Comment by bvdbos** [comment] 2016-10-16 15:35
@uNiiek That's something else : this means it's not receiving signals while in the title @robintielemans says Homey doesn't send signals. Does sending signals to a socket through another flow (i.e. by speech) work for you two?

**Comment by robintielemans** [comment] 2016-10-16 16:31
@bvdbos it does recognize my keys pressed at the setup, but when I am making a flow like "when button 4 is pressed, say "hello"". Doesnt work. When I make a flow with "When time is 18:30 then push button 2" which is programmed to turn on a specific light (without use of homey, it works) it doesnt work either. Both ways dont seem to be working.

**Comment by bvdbos** [comment] 2016-10-16 16:42
The first one is a bug then. Receiving a signal doesn't trigger a flow. You might want to change the title of this  bug... Either that or the issue @uNiiek created ( #967 ) should be renamed. 

The second one doesn't work as @BasKiers said 23 days ago. Maybe it used to work before but copying of signals isn't supported anymore. Don't know why but that's a choice of Athom (even though you responded it "should" work). I guess it caused too much problems in the past...

**Comment by BasKiers** [comment] 2016-10-18 13:50
The bug @bvdbos was referencing is now fixed (since v2.1.2) of the action app. Thanks for the bug report!

I will close this issue since the original topic is no longer discussed. If you still want to track the original issue please open a new issue.

**Closed by BasKiers** 2016-10-18 13:50 UTC
Labels: Athom App, bug

**Comment by uNiiek** [comment] 2016-10-18 19:11
Its working, thanks for the fix!!
