### ISSUE TITLE
Kaku broken in 1.5.8? 

### ISSUE THREAD

**Issue by thezahir1** [athombv/homey#2311] opened 2018-03-09 06:02 UTC
As of today, after installing 1.5.8, all my KaKu (klikaanklikuit) devices won't work anymore with Homey ..
Do more people experience the same problem? 
Or does anyone know perhaps how to solve it ? 
Thanks in advance!

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by bvdbos** [comment] 2018-03-09 06:11
Did you try a PTP (Pull The Plug) of Homey?

**Comment by jeroenvollenbrock** [comment] 2018-03-14 11:21
Closing as duplicate of #2023

**Closed by jeroenvollenbrock** 2018-03-14 11:21 UTC
Labels: RF, bug, waiting for user feedback
