### ISSUE TITLE
Belkin Crash (0.10)

### ISSUE THREAD

**Issue by markaswift** [athombv/homey#892] opened 2016-09-24 18:30 UTC
Error:

Stack trace:

TypeError: Cannot read property 'clients' of undefined
at /drivers/insight/driver.js:17:20
at Array.forEach (native)
at connect (/drivers/insight/driver.js:16:11)
at init (/drivers/insight/driver.js:9:3)
at /homey-app/manager/drivers.js:150:31
at Array.forEach (native)
at eventListeners.clientDriverInit (/homey-app/manager/drivers.js:66:26)
at /homey-app/manager/drivers.js:20:38
at /homey-app/homey.js:1:1080
at Array.forEach (native)

Exit code: 0

**Comment by BasKiers** [comment] 2016-09-26 20:36
I've found the issue, this error is caused by a bug in 0.10.0. It will be resolved in version 0.10.1 soon

**Comment by jeroenvollenbrock** [comment] 2016-10-03 13:53
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.

**Closed by jeroenvollenbrock** 2016-10-03 13:53 UTC
Labels: App-SDK, bug, Staged for release
