### ISSUE TITLE
Timer did not recognized "minuten" with timer function.

### ISSUE THREAD

**Issue by maxxie01** [athombv/homey#1497] opened 2017-04-24 07:38 UTC
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**
speak to Homey "zet een timer over 3 minuten voor de eieren"
Homey confirm "ik zal je er aan herinneren".
Same with "1 minuut".

**What was the result?**
Homey give a alert after 3 hours.

**What did you expect as result?**
soft eggs (3 minutes). 

**Any other remarks**

**Please attach a Homey System log (Settings -> System -> Send Log)**
I do not think this is necessary. It's to reproduce.

**Comment by Tweake** [comment] 2017-04-24 15:41
Thanks for pointing this out. I have made some changes related to timezones on a server. If you try it now you should get a notification after 3 minutes instead of 3 hours and 3 minutes.

Please close this issue if it's resolved for you too. Thanks!

**Comment by bvdbos** [comment] 2017-04-24 15:55
This works but Homey also responds with "16.6" after that... With two different timers and an reminder (is the same I guess)

**Comment by maxxie01** [comment] 2017-04-24 19:29
Yes the timer function works better (good) but he always count 22 seconds extra. If I use 10 seconds "zet een timer over 10 seconden" or "zet een timer over 3 minuten", its always + 22 seconds. For me it's not a problem, but for a programmer it can be a challenge to find.

**Comment by bvdbos** [comment] 2017-04-24 19:35
19 seconds for me...
```
24-4-2017 21:34:26.713	Speech-output	Speech	{"text":"Dit is de herinnering waar je om gevraagd had","type":"say","session":"homey"}
24-4-2017 21:33:07.950	Speech-output	Speech	{"text":"Ik zal je er aan herinneren","type":"say","session":"homey"}
24-4-2017 21:33:06.609	Speech-input	Speech	{"transcript":"zet een herinnering over 1 minuut","confidence":1,"session":"homey","synthesize":false}
24-4-2017 21:32:24.709	Speech-output	Speech	{"text":"Dit is de herinnering waar je om gevraagd had","type":"say","session":"homey"}
24-4-2017 21:31:36.376	Speech-output	Speech	{"text":"Ik zal je er aan herinneren","type":"say","session":"homey"}
24-4-2017 21:31:35.336	Speech-input	Speech	{"transcript":"zet een timer over 1 halve minuut","confidence":1,"session":"homey","synthesize":false}
```

**Comment by maxxie01** [comment] 2017-04-25 07:00
The two Homey's at Sybrand's Place are both 2 seconds too early. Nice issue for Robert (sorry).

**Comment by bvdbos** [comment] 2017-04-25 07:28
Well, that's a different issue...

**Comment by bvdbos** [comment] 2017-04-25 11:12
imho that is...

**Comment by bvdbos** [comment] 2017-05-01 16:25
Just tested:
2017-5-1 18:18:43.263	Speech-output	Speech	{"text":"Denk er aan om uit de oven te halen","type":"say","session":"homey"}
2017-5-1 18:17:42.751	Speech-output	Speech	{"text":"Ik zal je er aan herinneren","type":"say","session":"homey"}
2017-5-1 18:17:41.472	Speech-input	Speech	{"transcript":"herinner me over 1 minuut om de pizza uit de oven te halen","confidence":1,"session":"homey","synthesize":false}

So output is about 2 seconds late. My Homey is about the same timeslot lagging atm... So maybe that's the cause of this second issue?
![2017-05-01 18_22_21-time is 18_22](https://cloud.githubusercontent.com/assets/1064079/25585528/573f00fc-2e9b-11e7-84a6-edaa190fd3d5.png)

**Closed** 2017-06-14 10:43 UTC
Labels: bug, speech-input, Staged for release
