### ISSUE TITLE
Voice commands are almost never working

### ISSUE THREAD

**Issue by jpernot** [athombv/homey#654] opened 2016-05-25 08:32 UTC
Homey Firmware Version: 0.8.35

**What did you try to achieve?**
Talk to my Homey

**What was the result?**

>95% of the voice commands are not interpreted. 
simple commands as "lights on" / "lights off" are almost never understood. In the speech input screen I see that Homey understands this as:
"What is on" / "What s" / "is full" / "what s all" / "is full" etc...

The same goes with flows where custom phrases are created by me to trigger flows. Both in Dutch and in English they almost never work.

My car with voice contol (linguatronic) understands me 99.99 % of the time so it's not me...

PS. all tests were performed in a very quite room, no background noise to interfere during my commands.

**Comment by maaikekaasenbrood** [comment] 2016-05-25 18:53
I'm having the same problem

**Comment by forrestfarmer** [comment] 2016-05-25 19:04
same here can't get ok homey to work either

**Comment by Ronaldhnl** [comment] 2016-06-02 19:00
Hey Guys, I have the same issues. I've had a 3% success rate.. It sometimes seems that when I reboot homey, or try it in the morning it has a success rate of about 60%. But later on it gets worse. This is THE key feature on this device and it needs to get improved A LOT before I can really start using it. 

Another thing, when I try the homey iPhone app, the speech recognition works a whole lot better most of the time.. but this is not how I want to interact with Homey of course.

**Comment by magtimmermans** [comment] 2016-06-03 15:02
Same here, for months now

**Comment by craftedpixelz** [comment] 2016-06-03 21:55
Have the same issue. I have like a 1% success rate right now. Kind of frustrating. I hope it improves.

**Comment by jeroenvollenbrock** [comment] 2016-07-27 15:43
Duplicate of #250

**Closed** 2016-07-27 15:44 UTC
Labels: duplicate

**Comment by magtimmermans** [comment] 2016-07-27 16:09
Why do you close it as this is still not solved!

**Comment by RoadXY** [comment] 2016-07-27 21:01
Because it's a duplicate of #250
