### ISSUE TITLE
Z-Wave Device creation - invalid_commandClass_COMMAND_CLASS_NOTIFICATION

### ISSUE THREAD

**Issue by djanssen1** [athombv/homey#1669] opened 2017-06-28 20:07 UTC
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**

Add a Fibaro Motion Sensor (Z-wave Plus)

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

Device card was created but when you click on the device card instead of values it showed a broken link icon with the text "Motion Sensor (Z-Wave Plus) invalid_commandClass_COMMAND_CLASS_NOTIFICATION" (see photo)

After a while the whole device card showed a broken link icon (see photo)
**What did you expect as result?**

...

**Any other remarks**

I deleted the device as it was not updating its values anymore. Deletion was also giving issues and when trying to add it was also having issue. Finally I first had to reboot

**Please attach a Homey System log (Settings -> System -> Send Log)**

9CC28C50E4

Photos:

![1](https://user-images.githubusercontent.com/28545735/27657608-871c46ce-5c4d-11e7-8f08-848fca9ca0bb.jpg)
![2](https://user-images.githubusercontent.com/28545735/27657607-871be756-5c4d-11e7-81a4-1c2295c8a94a.jpg)

**Comment by caseda** [comment] 2017-06-29 07:53
Just to add on to this issue for extra information I know about.

The inclusion fails down the road,
maybe in the het node information part already, which makes it so not all capabilities are checked/added.
And thus missing in homey.

Might have to do with the change in inclusion that was needed for the window/door sensor 2?
Looks like 1 of the checks is not being done anymore, to fail the inclusion beforehand

**Comment by RobinBol** [comment] 2017-10-16 14:07
Hi @djanssen1, in the meantime there have been many updates to the Fibaro app as well as Homey. This issue should therefore be solved, if you feel this issue should not have been closed, or is still an issue to you, please comment so we can re-open.

**Comment by bvdbos** [comment] 2017-10-16 14:09
@RobinBol just today: 
https://forum.athom.com/discussion/4023/fibaro-door-window-sensors-not-working-after-latest-1-5-11-fibaro-app-update

**Comment by maartenver** [comment] 2017-10-16 15:39
I thought my door sensor was broken so I bought a new one. But there is no way to even add a new door sensor. I did a reboot by turning homey upside down, and chose to keep the user data. This did not help. The interview just expires. Hopefully this can be fixed soon.

**Comment by RobinBol** [comment] 2017-10-16 16:05
Hm strange, does this 'missing command class' error occur ALWAYS? Even after trying to pair it 10 times? Or does the pairing succeed sometimes? Might a firmware difference between devices, could you report the firmware of your sensor (often on the box)?

@maartenver I think your issue is unrelated, so if necessary please open another issue. But I think it is a range issue, make sure the device is within 30cm of Homey during pairing.

**Comment by danone1973** [comment] 2017-10-16 20:01
@RobinBol  it is me having this post on Athom Homey regarding this issue.

https://forum.athom.com/discussion/4023/fibaro-door-window-sensors-not-working-after-latest-1-5-11-fibaro-app-update#latest

Basically those sensors were fine until the latest firmware update of the Fibaro app 1.5.11
Now I get this error. However, I can easily include those sensors and they can be used fine in the flows. But just cannot see their status under Devices and cannot rename them.
I have thrown away their boxes and have no way of finding the firmware version.
I do know someone with an HC2 and I shall get there this week so I can update the firmware of my sensors and report back here the result.

**Comment by maartenver** [comment] 2017-10-16 20:20
@RobinBol I have tried countless time, right next to Homey. So defiantly well within 30 cm of it. It's two door sensors that are giving me problems. One was fine until the recent Fibaro update. That was door sensor with z-wave plus. Today I bought a new one, the door 2 version. I have tried everything neither gets found by Homey.

**Comment by maartenver** [comment] 2017-10-16 20:24
@RobinBol, the issue is simular to the one that started this thread. I saw exactly the same as the screenshots showed.

**Comment by philsniff** [comment] 2017-10-17 08:46
i just have this error also with my door sensor (fibaro gen 1, non zwave plus)! never had this before. i think it comes with one of the last fibaro app-updates 1.5.10, 1.5.11! before it was all ok. and the sensor is in reach to homey and the battery ist just 3 weeks old!

i don't want to unscrew it agin and pair it again. hope it will work with one off the next updates...

all other fibaro door sensors (zwave plus) are working like they have to :-)

**Comment by RobinBol** [comment] 2017-10-17 08:53
@maartenver @philsniff does the contact AND tamper alarm work in Flows for the devices missing the notification command class?

**Comment by philsniff** [comment] 2017-10-17 09:07
the doorsensot has only contactalarm. i can't test it in a flow till i am at home again. but i will test it in the evening. just recognized that in the apps there is a diffence:

homey app 1 (under device the door sensor is broken like in the webapp)
but under homey app 2 is shown as closed (contact off) like it is. no broken symbol

**Comment by caseda** [comment] 2017-10-17 09:53
The broken (or actually the "offline") thing is not implemented yet in app v2

**Comment by philsniff** [comment] 2017-10-17 10:01
@caseda ah ok, thought that.

**Comment by lesterchan** [comment] 2017-10-17 15:50
I came here to say I also encounter the same error too for the latest update. The initial pairing was ok.

**Comment by caseda** [comment] 2017-10-17 16:37
it will be fixed in the next fibaro update

**Comment by maartenver** [comment] 2017-10-17 17:08
Just installed the last update 1.5.12, and for me, nothings has changed. Still can't add new door/window sensors. I took the power cord out, but that didn't make any difference. I am just wondering wheter it's the Fibaro app at fault, or maybe the z-wave software in Homey?

**Comment by caseda** [comment] 2017-10-17 17:42
@maartenver see my reaction on your forum post

**Comment by philsniff** [comment] 2017-10-17 17:51
the app-update 1.5.12 fixed my issue with the broken devicesymbol and the commandclass-error!
now my doorsensor (first gen, non zwace plus) is again in the device list! thx

**Comment by RobinBol** [comment] 2017-10-17 17:54
@djanssen1 could you confirm the issue is solved for you as well? Then I can close this issue!
@maartenver would you contact Athom support? We might be able to help you better that way.

**Comment by danone1973** [comment] 2017-10-17 20:43
I can confirm here that this has been fixed with the latest Fibaro app update. Thanks a lot!

**Comment by WeeJeWel** [comment] 2017-11-02 14:12
Great!

**Closed by WeeJeWel** 2017-11-02 14:12 UTC
Labels: bug, Z-Wave
