### ISSUE TITLE
KAKU not working via remote TMT-2100

### ISSUE THREAD

**Issue by CootNL** [athombv/homey#309] opened 2016-03-05 16:24 UTC
**What is your Homey version (Settings → System)?**

0.8.20

**What did you try to achieve?**
Connect via remote TMT-2100 KAKU
*Please include detailed steps how we can reproduce the issue*
Try to connect a socket via the remote TMT-2100, but he is not working

**What was the result?**
Not working
...

**What did you expect as result?**
That I good connect a socket via the remote
...

**Any other remarks**
Non of my Sockets or dimmer is working or seen by the system 
...

**Comment by jghaanstra** [comment] 2016-03-05 18:42
This is a duplicate of https://github.com/athombv/homey/issues/52

**Comment by Dennishacq** [comment] 2016-03-07 18:03
Hi CootNL,

Thank you for reporting your issue.
The TMT-2100 is not working with Homey because this remote uses the old KaKu protocol that is not supported in the current version of the KaKu app. 
The protocol will be added within a few weeks.

I'm closing this issue because it's a dubplicate as jghaansta already mentioned.

**Closed by Dennishacq** 2016-03-07 18:03 UTC
