### ISSUE TITLE
ELRO triggers stops responing after a while, resetting homey fixes it.

### ISSUE THREAD

**Issue by maaikekaasenbrood** [athombv/homey#782] opened 2016-08-10 17:19 UTC
Homey Firmware Version: 0.9.2
using ELRO remote as trigger stops working after a few hours

Since a few days (maybe since version 0.9.2) using the ELRO remote as the trigger for flow stops working after a while. Resetting homey fixes it, the flows are triggered again by the ELRO remote. Then after a few hours it stops responding again.

**Comment by freemann** [comment] 2016-08-10 22:24
Also having troubles with Elro.

In pairing process the remote is recognized, but the tests fail in a certain way;
Pressing B-off, will blink B-off, 
Pressing B-on, will blink B-off
waiting a few secs
Pressing A-off, will blink A-off, 
Pressing A-on, will blink A-off

So it looks like some sort of hang of a button. 

Also made some flows where B-on and C-off do a led-ring purple/green pulse. After pressing B-on the led ring blinks green and when directly pushing C-off, nothing happens. Waiting a 30secs and pressing C-off, the led ring blinks purple. Do I press again on B-on, nothing happens......

Very strange behavior....

**Comment by jeroenvollenbrock** [comment] 2016-08-11 10:28
@freemann, @maaikekaasenbrood: What version of the Elro app, and which elro product are you using? I cannot reproduce the issue with our elro remote.

**Comment by freemann** [comment] 2016-08-11 10:32
![screenshot - 11_08_2016 12_29_13](https://cloud.githubusercontent.com/assets/601053/17586062/b8162f32-5fbf-11e6-842a-c14555b0a793.png)

**Comment by maaikekaasenbrood** [comment] 2016-08-11 18:04
Elro version: v2.1.0
Elro remote: AB440R
today gain a reboot is required

**Comment by maaikekaasenbrood** [comment] 2016-08-19 11:30
maybe it has something to do with the fact that besides adding a remote (being taken throught the wizard pressing buttons etc.) I also added a separate switch based on the dip-switch-settings?

**Comment by maaikekaasenbrood** [comment] 2016-08-25 08:47
it definitely has to do with adding the extra socket based on the dip-switch settings. As soon as this socket is triggered the remote stops working. As the flow with the additional socket was triggered every day at midnight it seemed like it just stopped working after several hours. 
If I delete the socket, and reboot homey, the remote is working again and will continue to work.
but obviously I do want to be able to add this socket again, when it works properly.

**Comment by maaikekaasenbrood** [comment] 2016-08-29 18:17
in 0.9.3 the elro stopped working all together :(

**Comment by maaikekaasenbrood** [comment] 2016-09-28 19:25
in the 0.10.0 the elro is working again but still adding a separate socket via the dip-switch settings 'breaks'it, requiring the deletion of the extra socket and a reboot of homey.

**Comment by BasKiers** [comment] 2016-11-22 19:16
Hi,

Sorry for the late response. I was unfortunately unable to reproduce this issue. What I did do is update the elro app to the latest version of the 433 generator, hopefully this fixes your problem. Could you try installing elro v2.2.1 and checking if your issue is fixed?

Regards,
Bas

**Comment by jeroenvollenbrock** [comment] 2017-02-14 12:20
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please let me know.

**Closed** 2017-02-14 12:19 UTC
Labels: Athom App, waiting for user feedback
