### ISSUE TITLE
Realtime error if settings screen served via athom cloud 

### ISSUE THREAD

**Issue by irritanterik** [athombv/homey#1310] opened 2017-02-04 21:49 UTC
**What is your Homey version (Settings → System)?**  
1.1.4

**What did you try to achieve?**
Load settings screen of an app via Athom Cloud. Setting screen uses realtime api. On load the console displays an error. This error is generated before the settings page javascript is loaded. When this error occurs, realtime events does not work. The error does not occur on every app, but is consistent per app.

![image](https://cloud.githubusercontent.com/assets/15232724/22621782/bac9d04c-eb2b-11e6-8eb1-6cfb65e2592d.png)

When loading the page while having local access to Homey the error is not shown and realtime events are working ok.

*Please include detailed steps how we can reproduce the issue*
I added a test app on this issue, based on `athom project --create` and the example settings.html from dev docs.

**What did you expect as result?**
No difference in settings screen between Local and Cloud.
...
[com.test.zip](https://github.com/athombv/homey/files/752591/com.test.zip)

**Comment by WeeJeWel** [comment] 2017-02-06 12:39
Duplicate of #1093

**Closed by WeeJeWel** 2017-02-06 12:39 UTC
