### ISSUE TITLE
Logout in app does not work properly

### ISSUE THREAD

**Issue by fn002449** [athombv/homey#664] opened 2016-05-29 19:02 UTC
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**
Log out from android app (v 2.1 build 45)

*Please include detailed steps how we can reproduce the issue*
Click 'uitloggen' in the app. The app returns its login screen but if you go out of the app en get back in you are still logged in.

**What was the result?**
Still logged in

**What did you expect as result?**
Would be cool if I was logged out.

**Any other remarks**
In the 'send me a push notification' there are now 3 the same phones in the list.

**Comment by Dijker** [comment] 2016-05-29 21:21
Confirmed! It doesn't work on my Galaxy TAB S2 either.

**Comment by freemann** [comment] 2016-05-30 05:49
@Dijker 
Tablets are not officially supported!?

@fn002449 
please add the brand/type of the tested device and android version!

**Comment by Dijker** [comment] 2016-05-30 06:00
Thanks,
it isn't a tablet issue, same on Samsung Galaxy S7 Edge phone. 
Issue Confirmed again.

**Comment by bvdbos** [comment] 2016-05-30 06:03
I can't reproduce the multiple accounts for the same phone. However, logging out (but not really) I can confirm. I'm still able to receive push-messages when I'm on the login-screen...

**Comment by freemann** [comment] 2016-05-30 06:08
I known the issue is there, but its also known that Tablets are not officially supported and so testing on them isn't a good test cast :smiley: 

App testing on Tablet is more or less the same as testing the WebUI on Safari/etc.

My Nexus 5 with 6.0.1 - May 2016 update also has this issue.

The Android app version 2.1 very unstable and buggy against 1.0

**Comment by bvdbos** [comment] 2016-05-30 06:12
Still receiving messages after a crash might actually be a good thing :+1:

**Comment by RoadXY** [comment] 2016-05-30 10:17
That's because the doesn't have to be running to get notifications on your phone.
Android wakes the app if an message/notification is received.
That's how GCM works.

It like if we can clean up old phones in Homey, though.
My old phone is still there to select...

**Comment by fn002449** [comment] 2016-06-03 13:32
I'm on a Samsung galaxy s5 Neo android version 5.1.1

**Comment by goldenice** [comment] 2016-06-23 10:24
This is fixed with the release of app version 2.2+ on Android and iOS 1.1+ (which is pending approval)

**Closed by goldenice** 2016-06-23 10:24 UTC
