### ISSUE TITLE
An app is already being installed

### ISSUE THREAD

**Issue by edtst** [athombv/homey#462] opened 2016-04-16 18:35 UTC
**What is your Homey version (Settings → System)?**

0.8.30

**What did you try to achieve?**
Install an app

*Please include detailed steps how we can reproduce the issue*

Go to app store and try to install any app

**What was the result?**

Error: An app is already being installed
...

**What did you expect as result?**
Installed app.
...

**Any other remarks**

Rebooting doesn't make this go away
...

**Comment by TedTolboom** [comment] 2016-04-17 16:22
Same issue here...
Full reset of my Homey... I was able to install the KaKu app after the reset... 

After setting up KaKu, I wanted to install further apps (e.g. Kodi).
In the first attempt, the installation will fail with: "Something went wrong. Try again"
<img width="411" alt="schermafbeelding 2016-04-17 om 18 19 29" src="https://cloud.githubusercontent.com/assets/17163431/14588406/59c0ee0a-04c9-11e6-9f61-0d8723e8aa8c.png">

If you chose "Try again", it will fail with the error: "an app is already installed on Homey"
<img width="416" alt="schermafbeelding 2016-04-17 om 18 19 45" src="https://cloud.githubusercontent.com/assets/17163431/14588409/6683e37c-04c9-11e6-9b42-f5f1bde1cd2c.png">

Status.athom.com shows that the app store is operational.

**Comment by TedTolboom** [comment] 2016-04-19 10:58
@WeeJeWel you indicated on Slack that this would be caused by an issue with read-only access to the temporary storage of Homey and that it would be resolved with 0.8.31. Correct?

**Comment by WeeJeWel** [comment] 2016-04-19 11:08
Yes

**Comment by Dennizz** [comment] 2016-04-19 19:42
Is there any workaround possible at this time? I can't install any apps anymore. This was initially possible. It isn't since I uninstalled the Kodi app. When I tried to reinstall it failed. Now all app installs fail. (Same notifications as Ted)

**Comment by WeeJeWel** [comment] 2016-04-20 11:59
No, there's no workaround, I'm sorry.

**Comment by Bumblez** [comment] 2016-04-24 07:55
Question... I just got a new Homey (upgraded to 0.8.30). While installing apps, I noticed that I could install 2 apps, then the 3rd one would always fail. I then had to reboot Homey, after which I could install 2 more, then again the 3rd one would fail. So I installed all my apps this way, except for the Kodi and Logitech Harmony apps. These two will always fail even if I try to install them as the first app right after a reboot.
Is all this related to this issue here, and should all this be solved in 0.8.31 ?

**Closed** 2016-05-17 16:16 UTC
