### ISSUE TITLE
[com.lifx] LIFX only can trigger a scene? No other options available anymore in flows

### ISSUE THREAD

**Issue by j0o5t** [athombv/homey#2017] opened 2017-12-03 18:49 UTC
**Metadata**

* **Homey Version**: 153
* **Homey Log Code**:
* **Smartphone Platform**: iPhone
* **Smartphone App Version**: Latest

**If related to a Homey App**: LIFX
* **Homey App Version**: 3.1.2
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: LIFX Original v 2.1

**What did you try to achieve?**

Upgrade the LIFX app, LIFX light had to be deleted and re-added to home. Since, i only can trigger a "scene" when creating a flow for LIFX. All flows that used LIFX x are broken now.

**What did you expect as result?**

That i can use my LIFX in flows as i used to, set brightness, switch on and off, set colour.

**What was the result?**

Cannot use LIXF anymore in any flow.

**Any other remarks**

**Comment by Dijker** [comment] 2017-12-03 19:09
Please update the description (title) as it is not clear what the problem is without reading completely.

You should re-add your devices, and make sure every light you own is connected to the LIFX Cloud.
Did you remove the old devices after the update?
Does it work to edit/update flows with the new added devices?

**Comment by j0o5t** [comment] 2017-12-03 19:18
Yes, i did delete and re-add a device after the plugin update. My LIFX light does have the latest firmware. I did disconnect my LIFX light from power completely.

When adding LIFX to a flow, the only thing i can setup is a "Scene"??? No idea how to do that. The options that always where available are gone (switch light on, off, change colour, change brightness)...

When switching the LIFX from devices, Homey is switching the Light on and off, i can also set the colour and so on. Only in flows it is broken.

<img width="1144" alt="screen shot 2017-12-03 at 20 17 42" src="https://user-images.githubusercontent.com/29679807/33528791-1eb8280a-d867-11e7-82fc-489fd99b43a3.png">

**Comment by moekdegroot** [comment] 2017-12-04 08:27
That card is a global lifx card and indeed only used for calling a scene. 
You need to drag a light to the then colomn.

**Comment by j0o5t** [comment] 2017-12-04 08:56
Hi,

It is in the then column (please see image) and no other options can be selected. I can’t select anything else then scene.
So i can’t switch it on or off as was possible in flows.

Greetings Joost


On 4 Dec 2017, at 09:27, moekdegroot <notifications@github.com<mailto:notifications@github.com>> wrote:


That card is a global lifx card and indeed only used for calling a scene.
You need to drag a light to the then colomn.

**Comment by j0o5t** [comment] 2017-12-04 09:01
Please close the bug report on GitHub, issue is solved.

You were right, i dragged the LIFX item, not the light.

Dragging the light solved my problem.

Tnx!

Joost

On 4 Dec 2017, at 09:27, moekdegroot <notifications@github.com<mailto:notifications@github.com>> wrote:


That card is a global lifx card and indeed only used for calling a scene.
You need to drag a light to the then colomn.

**Comment by Dijker** [comment] 2017-12-04 09:05
Thanks for the Update, 
As owner of this Issue you can close it yourself using the button below when using the GitHub Web version.
(or we wait for one of the Athom Administrators)

**Closed** 2017-12-04 09:12 UTC

**Comment by moekdegroot** [comment] 2017-12-04 15:01
@j0o5t sorry, missed your second question...
But glad it worked out!
