### ISSUE TITLE
[com.google.chromecast] CAST_INIT_TIMEOUT

### ISSUE THREAD

**Issue by jahnkenneth** [athombv/homey#2207] opened 2018-02-08 10:44 UTC
**Metadata**

* **Homey Version**:1.5.5
* **Homey Log Code**: 71CBA5BB1C
* **Smartphone Platform**: iOS
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:  v3.1.3 - 06.02.18
* **Homey App Log Code**: 
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Tried to cast a web page url to chrome cast via a flow
http://www.vg.no

**What did you expect as result?**
Webpage url shown on tv (chrome cast)

**What was the result?**
The tv only shows two horizontal white lines.

**Any other remarks**

**Comment by Dijker** [comment] 2018-02-08 14:02
Duplicate of #2196  and #2205 ??

**Comment by jahnkenneth** [comment] 2018-02-08 15:37
Yes, it would seem so...

**Comment by jeroenvollenbrock** [comment] 2018-02-12 18:43
Closing as duplicate of #2205

**Closed by jeroenvollenbrock** 2018-02-12 18:43 UTC
