### ISSUE TITLE
KaKu Doorbell broken

### ISSUE THREAD

**Issue by edtst** [athombv/homey#916] opened 2016-09-28 11:09 UTC
**What is your Homey version (Settings → System)?**

0.10, but after updated Kaku from yesterday.

**What did you try to achieve?**

My standard doorbell flow

*Please include detailed steps how we can reproduce the issue*

Create a flow where a KaKu doorbell buttun is pushed and then some action.

**What was the result?**

Doorbell doesn't register
...

**What did you expect as result?**

Dingdong
...

**Any other remarks**

Other kaku modules work
...

**Comment by BasKiers** [comment] 2016-09-28 13:56
Hi,

I'm sorry but I am unable to reproduce your issue. Could you check the following things to narrow down the issue?

- In the pairing wizard, does the "test" button trigger the doorbell?
- In the pairing wizard, does the bell icon light up when you press your doorbell?
- When you pair your doorbell as AKCT-510, does the flow trigger for "on button pressed" work?

Regards,
Bas

**Comment by edtst** [comment] 2016-09-28 13:57
The doorbell is already paired. If I test it by pressing it in Homey it rings my client bells. The other way round (when I press my doorbell) it doesn't.

**Comment by BasKiers** [comment] 2016-09-28 15:21
Could you still try to the above things since I cannot reproduce the issue?

**Comment by edtst** [comment] 2016-09-28 16:11
When I tried it, I noticed an error in the flow. I am using the soundboard and the file I uploaded was missing after I rebooted Homey. Also the voice reset it self to the default. So the doorbell or KaKu  is not the issue, but something else.

**Comment by bvdbos** [comment] 2016-09-28 16:19
Media is removed from 0.10.0 until the new manager is there #886

**Comment by BasKiers** [comment] 2016-09-29 17:56
Although the soundboard app should work. 

I will close this issue since the issue in the main post is resolved. If there are still other problems please open a new issue.

**Closed by BasKiers** 2016-09-29 17:56 UTC
Labels: Athom App, waiting for user feedback
