### ISSUE TITLE
Homey Speech for Sunscreens

### ISSUE THREAD

**Issue by Veldkornet** [athombv/homey#1587] opened 2017-05-27 22:29 UTC
**What is your Homey version (Settings → System)?**

1.2.2

**What did you try to achieve?**
Open/close the sunscreen via voice command

*Please include detailed steps how we can reproduce the issue*
- Say "Doe het zonnescherm naar beneden" (Lower The sunscreen)

**What was the result?**
- Homey replies "Okay, ik maak de zonnescherm dicht" (Okay, I am closing the sunscreen), although it does correctly lower the sunscreen as I asked. 

- The same occurs if you tell Homey to raise the sunscreen, it replies that it will open the sunscreen. 

**What did you expect as result?**
Homey should say the opposite of what it does now, that it is opening the sunscreen when you tell it to lower the sunscreen. 

**Any other remarks**
I currently use a Somfy RTS for the sunscreen. While I understand why Homey says this, for a sunscreen it's incorrect. 
If it were blinds, lowering them would indeed be closing them. But with a sunscreen, lowering it is actually opening it. 

**Please attach a Homey System log (Settings -> System -> Send Log)**
Don't think that's needed. But I'm happy to do so if required.

**Comment by caseda** [comment] 2017-05-27 23:17
not a duplicate, but is the same thing with this as an result: https://github.com/athombv/homey/issues/1295

homey only knows 1 way of window covering devices, and close then is "going down" with roller shutters.

**Comment by Tweake** [comment] 2017-06-13 12:50
This issue is the result of the bigger issue #1295 as @caseda pointed out.

I will make sure the feedback for solar screens is correct as part of the fix for #1295

**Comment by jeroenvollenbrock** [comment] 2017-08-16 15:11
Closed as duplicate of #1295

**Closed by jeroenvollenbrock** 2017-08-16 15:11 UTC
Labels: speech-output
