### ISSUE TITLE
Error when opening flow just placed in newly created folder

### ISSUE THREAD

**Issue by kruimel0** [athombv/homey#631] opened 2016-05-20 21:19 UTC
**What is your Homey version (Settings → System)?**

0.8.35

**What did you try to achieve?**

Make a folder for flows and add flows.

*Please include detailed steps how we can reproduce the issue*

Create a folder, give it a name, put some flows in it, try to open a flow.

**What was the result?**

An error message (popup) saying -True- in Chrome, after which Homey crashed (LED ring stopped rotating, unplugging Homey resorted it, but the folder and flows were not saved correctly.

**What did you expect as result?**

A flow I could edit

**Any other remarks**

...

**Comment by bvdbos** [comment] 2016-05-22 06:31
What does the chrome-console say during this process? Are there any errors?
presumably the same as #635 ?

**Comment by Dijker** [comment] 2016-05-22 06:47
Afaik Homey crashes first, but you don't know yet. And the true you see is a result of Homey not responding.

**Comment by bvdbos** [comment] 2016-05-22 06:49
So no errors in the console while creating the folder, renaming or putting a flow in it and no error in console when opening the flow, just a hanging Homey?

**Comment by Dijker** [comment] 2016-05-22 06:57
I will try again with all console's open for monitoring.....  it happens not every time but have seen it several times yesterday re- ordering the flows.

**Comment by WeeJeWel** [comment] 2016-05-23 17:13
Closing this issue because duplicate of #635

**Closed by WeeJeWel** 2016-05-23 17:13 UTC
