### ISSUE TITLE
KAKU draadloos deur/raam contact amst-606

### ISSUE THREAD

**Issue by bashag** [athombv/homey#1266] opened 2017-01-15 15:31 UTC
**What is your Homey version (Settings → System)?** 1.1.2

Ik probeer een KAKU draadloos deur/raam contact amst-606 te koppelen met Homey.
Ik kan het contact wel toevoegen bij apparaten, maar als ik deze vervolgens in een flow zet dan werkt het niet. 
Ik heb van alles geprobeerd en als test de meest simpele flow gemaakt: contact gaat aan dan gaat een lamp aan.

Ik heb dit al bij 2 contacten geprobeerd, maar het werkt bij beide niet 

Bij voorbaat dank voor jullie hulp!!

groeten
Bas van 't Hag

**Comment by Dijker** [comment] 2017-01-15 16:27
This works without any problems here, 
If you could add the AMST-606 to Homey and that worked, 
Create a basic flow with the Contact Alarm in the trigger (IF or ALS column)
just add a Pulse Led Ring to the  Action:
![image](https://cloud.githubusercontent.com/assets/12412734/21964188/b93ae71e-db47-11e6-91d2-0a77e02e9a2d.png)
Save and test it by playing with the AMST-606 ...
That should work.

**Comment by Rocodamelshe** [comment] 2017-01-16 16:40
Can u also try to add a delay of 2 seconds before u put the light on?
Just like in [this issue?](https://github.com/athombv/homey/issues/1041)

**Comment by bashag** [comment] 2017-01-17 15:41
Well i have tried a couple of things, and replaced the battery

 

It does work when im about 2 metres from Homey, if I go further away I doesn’t work anymore. 

 

Is there a solution , because I want to use it as an alarmsystem as soon as possible!

 

 

Thanks 

 

 

 

 

Van: Rocodamelshe [mailto:notifications@github.com] 
Verzonden: maandag 16 januari 2017 17:41
Aan: athombv/homey <homey@noreply.github.com>
CC: bashag <b.vanthag@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [athombv/homey] KAKU draadloos deur/raam contact amst-606 (#1266)

 

Can u also try to add a delay of 2 seconds before u put the light on?
Just like in this issue? <https://github.com/athombv/homey/issues/1041>

**Comment by Rocodamelshe** [comment] 2017-01-17 16:15
So u did try the 2 seconds delay in the flow like:
https://cloud.githubusercontent.com/assets/19249884/19732695/e598a4b2-9ba1-11e6-866f-e80d51ee3b25.png

**Comment by bashag** [comment] 2017-01-17 16:30
Im sorry, yes  i did try the 2 secons delay, it works only when im close to the homey 

 

Van: Rocodamelshe [mailto:notifications@github.com] 
Verzonden: dinsdag 17 januari 2017 17:15
Aan: athombv/homey <homey@noreply.github.com>
CC: bashag <b.vanthag@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [athombv/homey] KAKU draadloos deur/raam contact amst-606 (#1266)

 

So u did try the 2 seconds delay in the flow like:
https://cloud.githubusercontent.com/assets/19249884/19732695/e598a4b2-9ba1-11e6-866f-e80d51ee3b25.png

**Comment by Phunkay** [comment] 2017-01-19 15:39
@bashag You're seem to be suffering the same (433MHz) Range issues many are experiencing, including myself. I have the same contact and it works fine when it's close to Homey but is very unreliable when (even only) a few meters away....
See also: https://github.com/athombv/homey/issues/951

**Comment by jeroenvollenbrock** [comment] 2017-12-05 15:08
Closing as duplicate of #951

**Closed by jeroenvollenbrock** 2017-12-05 15:08 UTC
Labels: Athom App, RF
