### ISSUE TITLE
Dutch translation error

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1265] opened 2017-01-15 12:31 UTC
**What is your Homey version (Settings → System)?**
1.1.2

**What did you try to achieve?**
Delete a flow or folder

*Please include detailed steps how we can reproduce the issue*
See attached picture

**What was the result?**
I get the message "Verwijder dit flow" and "Verwijder dit map" 
...

**What did you expect as result?**
"Verwijder deze flow" en "Verwijder deze map"

**Any other remarks**
![fout](https://cloud.githubusercontent.com/assets/23163409/21962454/e49b2e94-db26-11e6-9b08-a18f26740bb7.jpg)

**Comment by WeeJeWel** [comment] 2017-01-16 18:50
Thanks for reporting. Closing because duplicate of #1230

**Closed by WeeJeWel** 2017-01-16 18:50 UTC
