### ISSUE TITLE
OK Homey - magic word/sentence performance - false positives

### ISSUE THREAD

**Issue by elfrigo** [athombv/homey#2009] opened 2017-11-30 13:22 UTC
**Homey Version**:
Homey Firmware Version: 1.5.5

**Homey Log Code**:
9D4A78489F

**What did you try to achieve?**
When there is a conversation in the same room as Homey, on several occasions Homey starts listening on 'OK' (with something else) instead of just 'OK Homey'.
This happens with my voice most of the time (maybe I just use the word OK quite often?), but nonetheless I never say "OK Homey" by accident.

**What did you expect as result?**
A quiet Homey :)

**What was the result?**
A non-quiet Homey waiting for a user response.

**Comment by WeeJeWel** [comment] 2017-12-01 13:26
Duplicate of #250

**Closed by WeeJeWel** 2017-12-01 13:26 UTC

**Comment by elfrigo** [comment] 2017-12-18 21:09
This does not look like a duplicate of #250 

_#250 does not recognize anything. When I say clear sentences and words that were recognized in 0.8.17, all it hears is No, it or yes._

My voice recognition is fine. I use voice commands quite often AND with success. It's just that once in a while Homey starts listening on 'OK' (with something else) instead of just 'OK Homey'.
