### ISSUE TITLE
When rebooting homey lights are turned off (if they where on)

### ISSUE THREAD

**Issue by spoelly** [athombv/homey#1380] opened 2017-03-21 11:54 UTC
**What is your Homey version (Settings → System)?**

1.2.0-rc.8

**What did you try to achieve?**
Reboot Homey

*Please include detailed steps how we can reproduce the issue*
In the settings page go to system and click reboot

**What was the result?**
Homey rebooted but also turned all the ligts off when it got back up and running

**What did you expect as result?**
That homey saves the last status of all devices and in my case the lights will stay on when rebooting homey.

**Comment by Dijker** [comment] 2017-03-21 12:25
Probably due to an Flow you have that triggered (unexpectedly) after a restart. 
Guess this is the same issue as #1051 
@WeeJeWel  This is still an annoying issue and more people haver the same experience.

**Comment by Arjanvde** [comment] 2017-03-21 12:34
Sometimes I have the same issue, I can't reproduce this unfortunately.

**Comment by spoelly** [comment] 2017-03-21 12:44
Got this with hue and KAKU switches. Can it be that it is an app issue? because i use better logic for switching some flows.. that the boolean is reset.. or something?

**Comment by chrisboer** [comment] 2017-03-21 13:58
You can simply check this by looking at the boolean state before and after reboot !

**Comment by Dijker** [comment] 2017-03-21 15:02
@chrisboer  the bitflip or KAKU state before and after restarting are the same but if I trigger a flow on state changed to that state it still triggers the flow after a restart of Homey.

**Comment by spoelly** [comment] 2017-03-21 15:44
got the state changed also in my flow for a trigger, it does not sound logical that the state changes at a reboot.

**Comment by chrisboer** [comment] 2017-03-21 15:48
I have also the message when I reboot homey that my frontdoor is unlocked but actually nothing happens, I think if you put in a state change in a flow or a device change in as a trigger in a flow this happens.
You can just check it by temporary change the trigger of the flow concerning in "if this flow is triggered" and then reboot and check.

**Comment by WeeJeWel** [comment] 2017-05-10 10:25
Duplicate of #1051

**Closed by WeeJeWel** 2017-05-10 10:25 UTC
