### ISSUE TITLE
[nl.eneco.toon] Toon updates homey, but homey doesn't update toon.

### ISSUE THREAD

**Issue by JRTimmerman** [athombv/homey#2279] opened 2018-03-02 07:22 UTC
**Metadata**

* **Homey Version**: latest stable version
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**: latest stable toon
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Update toon from homey flow.

**What did you expect as result?**

Update toon to status assigned in homey

**What was the result?**

toon doesn't change.

**Any other remarks**
if toon is changed this is visible in homey.

**Comment by JRTimmerman** [comment] 2018-03-02 07:26
Look same as issue #2271 but now also with stable version. Did something change at eneco side?

**Comment by mveck** [comment] 2018-03-05 09:06
Seeing a lot of D02 and D03 errors in the Toon Thermostate. This might explain the problem. Eneco need to stabilize the servers (again?)

**Comment by RobinBol** [comment] 2018-03-12 10:31
Closing as duplicate of https://github.com/athombv/homey/issues/2271

**Closed by RobinBol** 2018-03-12 10:31 UTC
Labels: Athom App, bug
