### ISSUE TITLE
Repairing Toon each couple of weeks

### ISSUE THREAD

**Issue by Fiek1** [athombv/homey#1690] opened 2017-07-18 21:59 UTC
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**
Each couple of weeks, sometimes less than a week I get the massage ' toon is de verbinding kwijt. Voeg het apparaat opnieuw toe. Until now the app is Very unreliable.

*Please include detailed steps how we can reproduce the issue*
ADD toon and wait A week, device loses connection.

**What was the result?**
No conneection
...

**What did you expect as Resul
Working connection
...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by chrisboer** [comment] 2017-07-19 21:27
I get the error 

Er ging iets fout, probeer het opnieuw... 
missing agreementId

**Comment by RobinBol** [comment] 2017-09-25 18:17
Duplicate of https://github.com/athombv/nl.eneco.toon/issues/23

**Closed by RobinBol** 2017-09-25 18:17 UTC
Labels: Athom App, bug
