### ISSUE TITLE
Z-wave network instable, needs restart every couple of hours

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#557] opened 2016-05-02 08:47 UTC
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

I have 4 powered Z-wave devices, Homey and 3 Fibaro switches ( 2 relay switches, 1 dimmer). I have 4 battery powered Z-wave devices ( 2 Fibaro motion sensors and 2 Aeotec recessed door sensors)

I try to achieve a stable network

**What was the result?**

Every couple of hours, Z-wave network is not working anymore and Homey needs to be restarted. A chip restart in the Z-Wave settings page gives 'Error: undefined'

In Z-wave settings, the list of devices is not shown at the 'refresh' part.

Logfile before reboot: B6237BB75F

**What did you expect as result?**

A stable Z-wave network

**Any other remarks**

When Z-wave is unstable; Homey's webinterface seems also slow to respond (specifically on Settings and Flows), also other non Z-wave devices seem to take longer to take action.   CPU load on Homey is low.

**Comment by laurenssss** [comment] 2016-05-02 10:54
same happens here, every few hours, after a restart of homey, restart of z-wave chip and refresh of the node it is working again (not sure if all steps are required)
just before restart Homey also often doesn´t respond very well to voice any more

**Comment by dvanp** [comment] 2016-05-02 12:14
I do a daily reboot of Homey because of this, restarting the Z-Wave chip does work though, but crashes again after a few hours. After a reboot it seems to last longer. Also experiencing the slow web interface.

I am still on 0.8.29 though, so it might not be exactly the same problem.
@ocatie: do you want me to send a log before reboot?

**Comment by FrankSchiere** [comment] 2016-05-03 13:50
Same here

**Comment by ralfvd** [comment] 2016-05-04 06:40
In addition, if I don't reboot the device, after some more hours, Homey itself becomes unreachable (webinterface / ping). It also seems that flows aren't executed anymore.

**Comment by peaoo** [comment] 2016-05-06 00:32
Same here, after a few hours the z-wave network seems to time out. Sensors (fibaro multisensor, d-link door sensor) freeze with their current status and all my plugs, incl relay-switch (fibaro plug and relay switch)  show "Busy with another task", and my thermostats (danfoss) are losing connection to the Hub and are Displaying Error E5 ( #463 ).
When I try to restart my z-wave chip: Error: Undefined

Error Log: 1E958E3C02

Note: I noticed this error first after I included my new fibaro relay-switch. Before that .32 seemed to work fine. Dunno if this is accidential or if the relay causes this problem. Are besides the issue-opener and me some more  fibaro relay switch owners affected?

**Comment by TedTolboom** [comment] 2016-05-06 05:51
Same issue here.
~6 Hours after the last forced reboot (Homey completely unresponsive), Z-wave network fails

It shows at two devices: error busy with another task
<img width="515" alt="schermafbeelding 2016-05-06 om 07 46 43" src="https://cloud.githubusercontent.com/assets/17163431/15065324/da2b66f8-135e-11e6-8e79-5466a903c463.png">

In Settings, the drop down list is not available to refresh the corresponding nodes

Restart z-wave chip does not appear to do anything (no error code shown)

Z-wave network: 3x Greenwave powernode 6, 2x Fibaro motion sensor
Log: A0DB6E3792

**Comment by ocatie** [comment] 2016-05-06 15:36
Cause found, working on it.

**Comment by bvdbos** [comment] 2016-05-06 16:42
Meanwhile: https://forum.athom.com/discussion/comment/21223/#Comment_21223

**Comment by TedTolboom** [comment] 2016-05-09 12:48
@ocatie Good to hear that you found the cause. 
What is your expectation? 
Can it be fixed within the next release(s) or is it part of the re-write of the Z-wave SW?

**Closed** 2016-08-05 12:34 UTC
Labels: zwave
