### ISSUE TITLE
Dutch predefined speech word not recognized. 

### ISSUE THREAD

**Issue by Povlov** [athombv/homey#2015] opened 2017-12-01 21:41 UTC
**What did you try to achieve?**

Obtaining the value of the variable "temperature (multisensor 6)" by asking Homey "binnentemperatuur".

**What did you expect as result?**

Homey announcing the value of the variable.

**What was the result?**

On audio input no respons or "ik begrijp niet wat je bedoeld".
On browser-input  ??/manager/speech-input/ "binnentemperatuur", Homey responds correctly! 

**Any other remarks**

**Comment by Tweake** [comment] 2018-01-02 10:23
In that case Homey heard something other than "binnentemperatuur". You can verify this by going to <your Homey ip>/manager/speech-input/ and then talking to Homey. What homey heard through the microphone will also show up there. If Homey doesn't hear you correctly this is something that should automatically improve over time as the machine learning gets better at picking up the correct text.

**Comment by jeroenvollenbrock** [comment] 2018-01-10 17:17
I'm closing this issue as it cannot be reproduced and is probably caused by Homey not hearing you correctly.

**Closed by jeroenvollenbrock** 2018-01-10 17:17 UTC
Labels: speech-input
