### ISSUE TITLE
BUG: graph with spline follows unnatural curve, crosses back in time!

### ISSUE THREAD

**Issue by reneknuvers** [athombv/homey#2233] opened 2018-02-14 14:45 UTC
* **Homey Version**: 1.5.3
* **Homey Log Code**: n.a.
* **Smartphone Platform**: n.a.
* **Smartphone App Version**: n.a.

**What did you try to achieve?**
Added a temperature variable to an 'insights' plot

**What did you expect as result?**
A list of measurements with possibly a trend line running along these points.

**What was the result?**
Measurements that are close together in time, but not in measured value have a trend line that swirls back in time. The spline function tries to cross the point almost horizontally, where in case of a sudden increase or decrease of the value those make little sense.

<img width="1124" alt="homey-spline grafiek temperatuur" src="https://user-images.githubusercontent.com/12103751/36210025-ac158232-119d-11e8-9d25-5f749491f020.png">

**Any other remarks**
Some statistical plot libraries provide excelent trend line algorithms. Note that a trend line (or running average) does not necessarily cross each (or any) of the points.

**Comment by bvdbos** [comment] 2018-02-14 14:46
This is bug #986

**Comment by jeroenvollenbrock** [comment] 2018-02-21 16:16
Closing as duplicate of #986

**Closed by jeroenvollenbrock** 2018-02-21 16:16 UTC
