### ISSUE TITLE
KaKu: AWMR-230/AWMD-250 homey cannot switch on/off the switch/dimmer

### ISSUE THREAD

**Issue by scanno** [athombv/homey#729] opened 2016-07-28 11:33 UTC
**What is your Homey version (Settings → System)?**

0.9.1 / kaku app 2.1.0

**What did you try to achieve?**
Pair AWMR-230/AWMD-250 with homey by using the remkte to copy signals

**What was the result?**
Using the remote to switch the dimmer  and switch is fine (homey is also reacting on the remote).  But using Homey to switch on/off is not working (pressing the switch below the light bulb in the test page).

That homey correctly reacts on the remote tells me that homey correctly stored the signal. But homey somehow does not transmit the correct signal.

**What did you expect as result?**
Being able to switch on/off the kaku switch dimmer using homey.

**Any other remarks**
used to work fine on firmwares before 0.8.39 and the old app.

**Comment by Robinyoh** [comment] 2016-07-28 21:15
I paired my AWMD-250 as an ACD-XXX module with the "copy remote" way. This works for me, i can also dim the light by slider.

**Comment by scanno** [comment] 2016-07-28 22:00
@Robinyoh well i did also, but not working for me. So what is the difference (like i mentioned it used to work fine before)

**Comment by Robinyoh** [comment] 2016-07-29 19:12
did you power cycle homey?

**Comment by scanno** [comment] 2016-07-29 20:08
@BasKiers sadly with 0.9.1 and kaku app 2.1.0 still the same problem.

@Robinyoh sure i did. even factory reset does not work

**Comment by scanno** [comment] 2016-07-30 15:30
@BasKiers You mentioned that you were not able to reproduce the problem. Perhaps, if you still are not able to reproduce it, you can provide a debug version of the app and i could give you the debug logging that it produces.

**Comment by scanno** [comment] 2016-07-30 18:04
Hmmm this is interesting... Did a complete reset again and installed the 2.1.0 KaKu app again and tried to pair my dimmer. What i notices is that as soon as i try to switch on/off the dimmer with the remote right after i tried to switch off the dimmer in the test page, the dimmer does not react on the remote signal for 30 seconds.

When i pull the plug off homey, the remote works right away. So it seems like homey is transmitting a lot of garbage....

**Comment by jeroenvollenbrock** [comment] 2016-08-01 19:14
@ReinierH: log ID 4EB4AC71A3, mcu keeps crashing upon each TX.

**Comment by ReinierH** [comment] 2016-08-02 08:43
This is caused by a stackoverflow. This bug will be fixed in the next update

**Closed** 2016-08-06 16:46 UTC
Labels: Athom App, bug, RF
