### ISSUE TITLE
Error 500 HTTP PUT Request /api/manager/flow/order

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#683] opened 2016-06-10 20:39 UTC
**What is your Homey version (Settings → System)?**

0.8.38

**What did you try to achieve?**

Same as #630 

**What was the result?**

Nothing after 3 weeks

**What did you expect as result?**

Issues like #630 are reopened if a comment is placed.
I've hoped the issue I've mentioned 7 days ago wil be fixed today

**Any other remarks**

I CANT EDIT ANY FLOWS ANYMORE (FOR THREE WEEKS NOW)
If it's fixed in the next update, 4 weeks has been passed.

**Comment by kerkenit** [comment] 2016-06-10 20:40
https://github.com/athombv/homey/issues/630#issuecomment-223664117

**Comment by WeeJeWel** [comment] 2016-06-16 12:05
Duplicate of #630 

I get your addiction, though ;)

**Closed by WeeJeWel** 2016-06-16 12:05 UTC
