### ISSUE TITLE
[com.lg.webos] Describe your issue here

### ISSUE THREAD

**Issue by addebc** [athombv/homey#2493] opened 2018-05-28 22:37 UTC
**Metadata**

* **Homey Version**:
Latest

* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
Latest

* **Homey App Log Code**:

* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Ask homney to turn on or off TV

**What did you expect as result?**
TV To turn on or off and homey to continue working

**What was the result?**
Homey turned on or off the TV but the orange LED never went out acting as the command never finished. Tryed restarting app to retrieve controll of my Homey. Did not work so I had to restart the Homey itself.

Same result everytime. I have tried reinstalling the app no difference.

**Any other remarks**

If i turn TV off the icon in Homey still thinks it is on. Same if i turn it off in gui... After refresh it says TV is on.

TV is LG 4K OLED 55"

**Comment by jeroenvollenbrock** [comment] 2018-05-31 18:21
Closing as duplicate of #2052

**Closed by jeroenvollenbrock** 2018-05-31 18:21 UTC
