### ISSUE TITLE
ON/OFF Status LIFX bulb in flow

### ISSUE THREAD

**Issue by pimviergever** [athombv/homey#965] opened 2016-10-06 18:19 UTC
**What is your Homey version (Settings → System)?**

0.10.3

**What did you try to achieve?**
Create a flow with the condition that a  LIFX bulb should be off

_Please include detailed steps how we can reproduce the issue_
Create a flow with a lifx in the middle column, light needs to be off
Run the flow
Homeys thinks the light is on.
Flow stops

**What was the result?**

Flow stops

**What did you expect as result?**

That homey knows the on/off status of the LIFX bulb

**Any other remarks**

**Comment by bvdbos** [comment] 2016-10-08 07:06
confirmed and also the status-change if a lifx as a trigger doesn't work for me either...

**Comment by pimviergever** [comment] 2016-11-03 10:12
Any news on this issue?

**Comment by moekdegroot** [comment] 2016-11-17 16:21
Hi Robin, I know you must be swamped with the national release around the corner but if you could spare some time regarding the lifx status situation it would be very much appreciated. 
Thx!

**Comment by moekdegroot** [comment] 2016-11-18 09:48
No worries, just wanted to bump the issue so it wouldn't get lost a long the way. 
Thx for the update and good luck with everything!

**Comment by RobinBol** [comment] 2016-12-07 11:20
Guys, I have been trying to reproduce your issue. However it seems to work over here. I think that your problem lies in the fact that you are using a different way of interacting with the bulbs, so e.g. the lifx mobile app. The state change of the bulb is not broadcasted so that Homey can pick it up when changed using the mobile app. This also explains the comment of @bvdbos it works when changing the onoff of the bulb using Homey, but not when using external devices/apps.

**Comment by RobinBol** [comment] 2016-12-07 11:24
Will close it for now as it seems this is not a bug, I will try to look at a solution for Homey to receive/poll the Lifx bulb state so that when it changes through a third party it will be updated in Homey.

**Closed by RobinBol** 2016-12-07 11:24 UTC
Labels: Athom App

**Comment by moekdegroot** [comment] 2016-12-07 11:49
👍🏻 thx!
