### ISSUE TITLE
media.HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Play"

### ISSUE THREAD

**Issue by iDavied** [athombv/homey#1882] opened 2017-10-11 16:42 UTC
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**

Play a Spotify playlist through Sonos.

**What was the result?**

1. In http://192.168.1.170/manager/media/ every second a new song is started but there's no sound.

2. When I click on a specific song I get this error message:
 
media.HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Play"

**What did you expect as result?**

For Homey to start playing the playlist and skip to the next song (because it always starts a playlist with the same song).

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

E4086E457A

**Comment by bvdbos** [comment] 2017-10-11 16:45
dupe of #1554

**Comment by iDavied** [comment] 2017-12-10 19:34
I think I may have found a solution here. In my flow I used "next song" from the standard music function in the then column. However, when I use the "next song" from the sonos app in the then column, it seems to be working correctly.

It's not actually a solution to the malfunction of the standard music app, but at least I can play my music.

**Comment by iDavied** [comment] 2018-02-28 15:21
Unfortunately it was still only working intermittently, so I have now tried something else (or extra): first restarting the Sonos app. This can be done automatically thanks to the Candy app. Now it finally works. It's a pity it's been so difficult though. I reckon we have to thank the Sonos app (of Sonos itself) for that?

**Comment by WeeJeWel** [comment] 2018-09-26 14:12
Fixed in v4.0.9.

**Closed by WeeJeWel** 2018-09-26 14:12 UTC
Labels: Athom App, Media, bug
