### ISSUE TITLE
"Woonkamer" not recognised as zone

### ISSUE THREAD

**Issue by cjvs** [athombv/homey#1482] opened 2017-04-18 20:53 UTC
**What is your Homey version (Settings → System)?**

1.2.0

**What did you try to achieve?**

Switch all lights in the zone  "Woonkamer" off (through speech / type input)

**What was the result?**

Homey responds with "Ik kon geen lampen vinden om uit te zetten in de woonkamer"

**What did you expect as result?**
Lights in the zone "woonkamer" to be switched off.

**Any other remarks**

Changing the name from "woonkamer" into anything else will make it possible to trigger the lights in the zone. Other zones also work. The zone name "woonkamer" is just not possible.

**Please attach a Homey System log (Settings -> System -> Send Log)**
0339350B49

**Comment by jeroenvollenbrock** [comment] 2017-04-19 09:13
Duplicate of #1458

**Closed by jeroenvollenbrock** 2017-04-19 09:13 UTC
