### ISSUE TITLE
Youtube : unknown_error 

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1393] opened 2017-03-22 17:52 UTC
**What is your Homey version (Settings → System)?**
v1.2.0 rc8

**What did you try to achieve?**
Search for song

*Please include detailed steps how we can reproduce the issue*
<img width="1432" alt="spotify_youtube" src="https://cloud.githubusercontent.com/assets/23163409/24212680/6eafcddc-0f30-11e7-8b5c-efa46091eac3.png">

**What was the result?**
unknown_error while I have an youtube API installed
<img width="1432" alt="youtube_api" src="https://cloud.githubusercontent.com/assets/23163409/24212740/9d9f2994-0f30-11e7-91ec-b66ec50dab42.png">

**What did you expect as result?**
No error and able to search both in Spotify as well as Youtube

**Any other remarks**

...

**Comment by bvdbos** [comment] 2017-03-22 18:28
Did you install the latest version of the youtube-app, including the changes which were committed two days ago? Also, the error-message should go there unless the issue is due to Homey...
https://github.com/matjaz/homey-youtube

**Comment by chrisboer** [comment] 2017-03-22 19:37
If nobody tells me about this ;-) then I don't know but I installed the developper edition v0.6.0 problem solved

**Comment by chrisboer** [comment] 2017-03-22 19:40
Now I get 
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24217312/b7ebd414-0f3f-11e7-920b-25c4faa49b0e.png)

**Comment by TheMSB** [comment] 2017-03-24 12:47
@chrisboer Am I correct in detecting that you are trying to play a Spotify track on a chrome cast?

**Comment by chrisboer** [comment] 2017-03-24 14:06
@TheMSB no you are incorrect, like I stated Youtube track selected and I get this error
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24297536/70b9228a-10a3-11e7-852c-2759a8fb2d5c.png)

**Comment by chrisboer** [comment] 2017-03-24 14:07
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24297591/992cc60e-10a3-11e7-842d-529c92f0a164.png)

**Comment by bvdbos** [comment] 2017-03-24 14:08
Quite some youtube tracks may only be played on the youtube site itself, noticed that with facebook and other sites too. Did you try to see if that's what happening here?

**Comment by chrisboer** [comment] 2017-03-24 14:14
No issues in playing it on Facebook aswell so ?

**Comment by TheMSB** [comment] 2017-03-24 14:40
@chrisboer I assume you are side loading the youtube app at the moment? Do you get this error with all of the youtube songs or just a select few of them?

**Comment by chrisboer** [comment] 2017-03-24 14:44
@TheMSB what do you mean with side loading ? I get this error with all of the youtube songs, but I have not reinstalled youtube after the upgrade to 1.2.0 RC9 from RC8 that is something I can try but I already checked the version is still 0.6.0 so I don't expect much

**Comment by TheMSB** [comment] 2017-03-24 14:47
@chrisboer Which youtube app version are you using?

**Comment by chrisboer** [comment] 2017-03-24 14:49
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/24299416/6eaa3ffa-10a9-11e7-8aea-11bc45f35a9d.png)

**Comment by TheMSB** [comment] 2017-03-24 15:00
@chrisboer This seems to be an issue with the Youtube app itself. I will notify the developer.

**Comment by chrisboer** [comment] 2017-03-24 15:07
@TheMSB I already created an issue there aswell ;-) 
https://github.com/matjaz/homey-youtube/issues/12

**Comment by chrisboer** [comment] 2017-03-24 15:08
Maybe Athom should start paying me for testing ;-)

**Comment by TheMSB** [comment] 2017-03-27 08:20
Looks like this will be resolved in the Youtube app

**Closed by TheMSB** 2017-03-27 08:20 UTC
Labels: Athom App
