### ISSUE TITLE
Android app - Control buttons/sliders

### ISSUE THREAD

**Issue by zperx** [athombv/homey#642] opened 2016-05-22 14:53 UTC
**What is your Homey version (Settings → System)?**

Homey: 0.8.35
Phone: LG G2
App: 2.1 build 45
Android:4.4.2

**What did you try to achieve?**

To use the control buttons and sliders.

**What was the result?**

The control buttons and sliders are hard to access as they are partially out visible card.
Example (somfy):
![somfy card](https://cloud.githubusercontent.com/assets/18647800/15454586/422d4036-2035-11e6-82db-0ce2a2d93002.png)

**What did you expect as result?**

An ergonomic fit for purpose layout.

**Any other remarks**

Although the resolution is the standard 1080x1920 I don`t think the one size fits for all solution really works. These cards should be generated by the phone itself (among other things).

**Comment by goldenice** [comment] 2016-07-27 16:03
Duplicate of #644 (at least under the hood)

**Closed by goldenice** 2016-07-27 16:03 UTC
Labels: bug, smartphone
