### ISSUE TITLE
Unable to add IR TV remote

### ISSUE THREAD

**Issue by Sateprikkert** [athombv/homey#96] opened 2016-02-11 07:01 UTC
I tried to add my TV remote in the devices screen. Either pressing the button for min. 3 seconds or repeatedly pressing a button, it does not detect any input. The remote is for a Sony 65W855C tv.

**Comment by goldenice** [comment] 2016-02-11 10:00
This is a duplicate of #50, let's keep any further discussion there

**Closed by goldenice** 2016-02-11 10:00 UTC
