### ISSUE TITLE
KAKU switches not turning on

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#2292] opened 2018-03-05 08:23 UTC
* **Homey Version**: 1.5.6
* **Homey Log Code**: 57F2D559D9
* **Smartphone Platform**: na
* **Smartphone App Version**: na

**If related to a Homey App:**  KAKU 
* **Homey App Version**: v3.1.5
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Put on the TV which is on a KaKu device. 

**What did you expect as result?**
That KaKu device would switch on.

**What was the result?**
The KaKu device did not switch on nor did other KaKu devices, did a reboot of Homey and it worked again.

**Any other remarks**

**Comment by jeroenvollenbrock** [comment] 2018-03-12 10:39
Closing as duplicate of #2023

**Closed by jeroenvollenbrock** 2018-03-12 10:39 UTC
