### ISSUE TITLE
[Insights] Graph Line wrong after dataupdate

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#1166] opened 2016-12-17 18:23 UTC
**What is your Homey version (Settings → System)?**

1.0.3

**What did you try to achieve?**

Watch realtime if the power consumption is dropping or rising

**What was the result?**

After the data is updated (every 5 sec) the graph becomes a weird graph.
In the following example the it's strange, but when i'm go to bed before 12 o'clock last day, the graph is very strange.

**What did you expect as result?**

On updating of the Insights data and the page is open, the bottom line of the graph not moving to the last updated value, but stays at zero

**Any other remarks**

[Insights.mp4.zip](https://github.com/athombv/homey/files/659001/Insights.mp4.zip)

**Comment by Dijker** [comment] 2016-12-17 18:27
Duplicate of #1061 ?

**Closed** 2016-12-17 18:28 UTC
