### ISSUE TITLE
Homey Crashed!

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#2433] opened 2018-04-16 14:32 UTC
**Metadata**

* **Homey Version**: 1.5.9
* **Homey Log Code**: N/A

**What did you try to achieve?**
Tried to download the some insights (9 months old). Suddenly unresponsive page and now homey is offline, probably need a PTP.

**What did you expect as result?**
Donwload the CSV file/

**What was the result?**
Offline Homey.

**Comment by Arjanvde** [comment] 2018-04-16 14:43
Not sure how, came back online, log AA9E06FC22

**Comment by Dijker** [comment] 2018-04-16 14:44
I guess related to #2110 and other comparable  issues.....

**Comment by jeroenvollenbrock** [comment] 2018-04-30 09:52
Closing as duplicate of #2110

**Closed by jeroenvollenbrock** 2018-04-30 09:52 UTC
