### ISSUE TITLE
Unable to pair klik-aan-klik-uit remote

### ISSUE THREAD

**Issue by newmedia** [athombv/homey#52] opened 2016-02-10 19:07 UTC
Using the klik-aan-klik-uit wizard to add a socket, it asks to press the 'on' button on the remote for device 1. 

Is see the remote light blink (and the device connected to the socket turn on), but the homey does nothing.

The remote i'm using is a regular klik-aan-klik-uit remote (black edition)

**Comment by stealthblade** [comment] 2016-02-10 19:21
I have the same issue for the remote. I also have a issue with the motion sensor of KlikAanKlikUit.
When I use the "KlikAanKlikUit" motion card in the flow then it does not trigger anything. When I use the " Sensor" card and select "The motion alarm turned on" then it does work.

**Comment by stealthblade** [comment] 2016-02-10 21:04
The motion sensor is fixed in 0.8.17. The issue with the remote remains.

**Comment by BDV77** [comment] 2016-02-10 22:49
+1 with the remote issue

I tried to add a APA2-2300R remote, but homey does not respond to any input
This remote has no ability to set a channel and only 2 on/of options including a G button.
In the added device I can choose 4 channels so it looks like the wrong type of remote is added.

**Comment by richredleg** [comment] 2016-02-11 06:05
+1 with the remote issue

 Tried to add a APA3-1500R remote, but homey does not respond to any input.

**Comment by kkuyper** [comment] 2016-02-11 11:03
+1, cannot add KAKU devices this way

**Comment by pdegeus** [comment] 2016-02-11 17:29
+1 No response

**Comment by Dennishacq** [comment] 2016-02-11 17:51
Hey Guys, sorry for the late reaction,

@newmedia , @kkuyper , @pdegeus Are you still experiencing this bug with Homey v0.8.18 and KaKu v1.0.12? If so, do other 433MHz devices work? 

@BDV77 , @richredleg We don't have these two devices at our office yet, therefor i'm not 100% sure if these are compatible. I'll try to get them working asap.

**Comment by kkuyper** [comment] 2016-02-11 19:44
How can we force Homey to update to this version?

**Comment by Dennishacq** [comment] 2016-02-11 19:56
@kkuyper 
For the KaKu app: go to https://apps.athom.com/app/nl.klikaanklikuit and reinstall the KaKu app.
For Homey: You can force Homey to check for updates by unplugging Homey and plugging him back in.

**Comment by kkuyper** [comment] 2016-02-11 20:31
No update for the Homey yet.. :(

**Comment by Fieldhome** [comment] 2016-02-11 20:34
Also problems here with the ATMT-502 remote.
My Homey isn't doing anything after pushing the ON button on the remote when copying the signal.

**Comment by pdegeus** [comment] 2016-02-11 20:37
My Homey stays at 0.8.17 after reboot and KaKu is at 1.0.12. The problem persists.
I can't learn a signal from the remote when adding a socket either. Creating a new signal when adding a socket _does_ work, so the transceiver seems to be working.

**Comment by Dennishacq** [comment] 2016-02-11 20:49
Ooh oops little typo there, i meant 0.8.17.
I'm not able to reproduce this bug yet, i'll keep trying tomorrow.
@Fieldhome Did you make it to this screen?
![image](https://cloud.githubusercontent.com/assets/15836768/12990192/45b9b0b6-d109-11e5-86f8-8e629ede4b10.png)

**Comment by Fieldhome** [comment] 2016-02-11 20:53
No, the "Press the ON button on you remote" screen is the screen where i get stuck.
After pushing ON multiple times nothing happens.

Homey 0.8.17
KAKU app 1.0.12

**Comment by pdegeus** [comment] 2016-02-11 20:59
Same here, stuck at the screen with the remote image with red On button.
My remote has a channel selector (currently at ch. I) and a code selector -or whatever it's called- to avoid collisions with neighbors. It's set to M with possible values of A to P. Would that setting matter?

**Comment by BDV77** [comment] 2016-02-11 21:00
Updated the Homey to 0.8.17 KAKU app 1.0.12

Added KAKU remote (type APA2-2300R), in the screen I was able to toggle the bulb on and off!

Using the device in a flow nothing happens.

**Comment by newmedia** [comment] 2016-02-11 21:25
Updated the homey also to 0.8.17, and reinstalled the KAKU app (1.0.12)..  
Still keep stuck on the register remote screen (press button 1)..

KAKU remote type: AGDR2-3500R

**Comment by Dennishacq** [comment] 2016-02-11 21:29
@BDV77 This is probably because the code i predicted doesn't match the code from your remote, i will try to fix this tomorrow. 
@pdegeus Are you still using [this](http://www.klikaanklikuit.nl/shop/nl/producten/afstandsbediening-ayct-102/#tabs) remote?
@Fieldhome @newmedia I'm not sure why this is not working, i'll try to reproduce this problem tomorrow.

**Comment by pdegeus** [comment] 2016-02-11 21:40
@dennishacq yes, that's the one. Simple remote to control the main lighting in the living room. I've actually never seen the other remote types mentioned here, while I've seen this one lying around at friends and family.

**Comment by kkuyper** [comment] 2016-02-11 21:43
I have three diffirent remotes: YCT-102, PA3-1000R and a intertechno
PAR-1000. No response at all.

**Comment by Dennishacq** [comment] 2016-02-11 21:51
@pdegeus Could it perhaps be [this](http://www.klikaanklikuit.nl/advies/productwijzer/productwijzer-yct-102/#) one?

**Comment by mirakels** [comment] 2016-02-11 22:34
Mentioned in a different topic (#63, which you may close as duplicate then)) , but this one is more active... 
I have a  YCT-100 remote and UYC-1000 socket  and can't get them to work either.
versions: 0.8.17, 1.0.12

**Comment by Dennishacq** [comment] 2016-02-12 18:06
How many of you are experiencing problems with remotes from the first column? (The current models)
![image](https://cloud.githubusercontent.com/assets/15836768/13015786/494030ae-d1bb-11e5-85ae-1fcf135a7766.png)

**Comment by Fieldhome** [comment] 2016-02-12 18:15
Yep, problems with the ATMT-502

**Comment by richredleg** [comment] 2016-02-12 18:31
Yep, I have a APA3-1500R remote and wall socket.

If I add the socket with a copy of the remote. It is possible to switch the socket with homey. When I use the remote control socket I see homy change the status of the socket. It is not possible through the flow to start a trigger from the remote

**Comment by mirakels** [comment] 2016-02-12 20:04
YCT-100 is not on the picture, but I guess it shoudl resembel the YCT102

**Comment by antronics** [comment] 2016-02-12 22:25
Same problems with the ATMT-502

**Comment by newmedia** [comment] 2016-02-12 22:31
KAKU remote type: AGDR2-3500R is not on the picture. (black remote delivered with the waterproof contacts)

**Comment by Dennishacq** [comment] 2016-02-12 22:41
The old KaKu devices (including the ones with a code wheel) use a different protocol that isn't supported yet. This protocol will be added in the near future.
I'm not able to reproduce the problem which makes it really hard to debug it, but I'll keep trying.

**Comment by Fieldhome** [comment] 2016-02-13 00:09
ATMT-502 isn't an old type of device, or is it?

**Comment by lvanderree** [comment] 2016-02-13 18:48
the AWST-6000 motion sensor isn't being paired either.
I've reinstalled the kaku app, restarted my homey, unplugged homey, but the del-set action doesn't end up in a paired motion sensor

**Comment by Omemanti** [comment] 2016-02-14 08:56
Dont know if it connected because but every other IR remote I have cant be connected also

**Comment by Fieldhome** [comment] 2016-02-15 17:06
Any progress on this issue?

**Comment by RemonBerends** [comment] 2016-02-15 20:52
+1 Same problem with the older series YCT-102 and TMT-502

**Comment by Dijker** [comment] 2016-02-16 21:42
Homey learned the AYCT-102 (at least something works now,  I can confirm the Homey is not broken at the 433 RF)  but learning of the NEW ACDB-7000A fails (Doorbell responds so Push-button works)  :'(

**Comment by Dennishacq** [comment] 2016-02-17 11:14
@Dijker Good to hear that your AYCT-102 is working now. 
What is the distance between your ACDB-7000A and Homey?

@RemonBerends The old KaKu series aren't supported yet but will be added in the near future.

@Fieldhome I'm not able to reproduce the problem which makes it very hard to debug it. We're adding some debug functions to figure out in which part of the software the bug is caused.

**Comment by Dijker** [comment] 2016-02-17 11:24
@Dennishacq  Tried the ACDB-7000A (push button) several times beteeen 40 cm and 1 or 2 meters from Homey.  (New bought )

**Comment by Dennishacq** [comment] 2016-02-17 11:37
@Dijker Okay, did you get past the following screen?
![image](https://cloud.githubusercontent.com/assets/15836768/13108452/43ef98a4-d573-11e5-9597-dbd006550234.png)

**Comment by Dijker** [comment] 2016-02-17 12:03
@Dennishacq  that image keeps on the screen, nothing happens when I send the  code. once, twice ... for seconds long or several times .... (the AYCT-102  functioned as expected!)

**Comment by Fieldhome** [comment] 2016-02-17 14:00
@Dennishacq If there's anything i can do to help you debug this issue, please let me know. Currently my homey is idling a lot, telling me it's bored from time to time. ;-)

**Comment by jghaanstra** [comment] 2016-02-19 22:12
@Dennishacq I do have the **A**TMT-502 (new version) but it's the seem. Homey does not recognize the signal and is therefor stuck at the first "Copy a remote" screen telling you to press the on button.

**Comment by jghaanstra** [comment] 2016-02-21 09:02
Next to the ATMT-502 I'm also unable to pair the APA2-2300R remote. It does not respond on the screen where you have to push the On button. @BDV77 Where you able to at least pair your APA2-2300R? Your previous message suggest you did but where unable to use it after pairing.

**Comment by BDV77** [comment] 2016-02-21 11:37
**@jghaanstra** Indeed in the initial screen I was able to pair the remote, toggling also worded fine.

But after using the device in a flow nothing happens.

**Comment by jghaanstra** [comment] 2016-02-21 11:53
After trying it again I was indeed able to pair it. It seemed I had to double press the On button to achieve this but I'm not sure. But after pairing it doesnt indeed do anything in flows yet. Awaiting a fix.

**Comment by denniedegroot** [comment] 2016-02-25 20:29
I'm still having troubles with 0.8.20, 1.0.14 and the AGD2-3500R remote. I am able to add the device, the detection of the on/off button is correct during the wizard. However my flow is not triggering on any of the remote buttons.

**Comment by Fieldhome** [comment] 2016-02-25 23:10
After a Homey reboot the Kaku switches arent working anymore. Tried removing the devices and recreating them, but now my APA3-1500R also isn't recognized anymore.

**Comment by denniedegroot** [comment] 2016-02-27 10:51
After a reboot the flow now works, I have no idea why it suddenly started working but I am happy :).

**Comment by kkuyper** [comment] 2016-02-29 10:42
What is the status of this issue? Still I can't add KAKU devices with YCT-102 or PA3-1000R remote in the .20 version.

**Comment by kkuyper** [comment] 2016-03-09 13:06
Still not working in .22. @Dennishacq,can you give an update about this issue?

**Comment by Dennishacq** [comment] 2016-03-11 12:46
@kkuyper I'm making the basis of the old KaKu protocol today, this should be up monday.

I'm also making new flowcards for all remotes from the new KaKu serie.
I would really appreciate it if you could help me by providing me the protocol info for the:
-AKCT-510 
-APA2-2300R
-APA3-1500R
You can see the protocol info by using the code checker (which can be found in KaKu's add device menu)
I need the channel & unit number for each button.
Thank you in advance! :)

**Comment by kkuyper** [comment] 2016-03-11 17:05
@Dennishacq I have only the  YCT-102, PA3-1000R and a intertechno PAR-1000 remote. For these remotesI didn't see anything in the code checker when I press a button.

**Comment by Dijker** [comment] 2016-03-11 18:41
@Dennishacq are these in protocol equal to the old HomeEasy? (Sold for 3-5 years ago at the Karwei in the NL) I have a couple of them here and hope to make them available in Homey.

As far as I have seen they are 99,99% the same (models, design, function and assortiment in devices) only re-branded  (or maybe the KaKu are rebranded??)

I have the:
HE300WUE (White) ~ like the (A)YCT-102  (2x)
HE300UE (Black) ~ like the (A)YCT-102  (sold with the outdoor switches)
HE200EU ~ like the  ATMT-502
HE301EU ~ like the (A)KCT-510
HE308??  ~ like the AWST8802 (will disassemble when necessary)
and compatible switches ACD-1000 / AGDR-3500 
and one HE107W dimable Tip - switch (http://homeeasy.eu/RemoteControlLightSwitch1Gangwhite/HE107W/190/Product/86/ )

All work with learning, no switches or code-wheels.
Only the CodeChecker still reports no codes ;-( 
Let me know when I can help you. 
(and you want to help, cq have the time to help the Home-Easy owners ;-) )

**Comment by newmedia** [comment] 2016-03-11 21:55
I tried again today with my AGDR-3500R (black).. Still not working..
Nothing in the codechecker, no response in the 'add device' with 'old remote' or 'remote'

**Comment by Fieldhome** [comment] 2016-03-12 09:12
Thanks for the 1.0.15 update!
I can pair my build-in dimmers as an Old Sockets now, so i can use them! 
Pairing them as a dimmer unfortunatley still doesn't work,
Is support for Old Dimmers  coming in the future?

FYI: Also tried the TMT 502 with the code checker this morning. No results...

**Comment by lvanderree** [comment] 2016-03-12 09:36
I tried the AWST-6000 motion sensor but this unfortunately still doesn't work either, I can't find any codes for it either. 
My AYCT-102 remote works perfectly

**Comment by Dennishacq** [comment] 2016-03-12 10:26
@Dijker Home Easy is om my (very long) to-do list but It might take a while before these are inplemented.

@newmedia Do you have any other 433 devices that can or can't be paired?

@Fieldhome More features will be added in the future. I'm not sure if the old KaKu dimmers have a Dim-command, I'll figure this out later.

@Ivanderree That's odd, what happens if you use the code checker with your motion sensor?

The code checker currently only supports the new KaKu protocol. (without the code wheel)

**Comment by lvanderree** [comment] 2016-03-14 14:51
@Dennishacq no codes, or anything else, appears in the code checker, when pairing the motion sensor; it keeps asking to push a button.

If I can do anything more to debug please tell.

**Comment by Fieldhome** [comment] 2016-03-14 15:59
@Dennishacq: FYI, the dimmers i'm using are the "AWMR2-210 Mini inbouw dimmer".

**Comment by Arjanvde** [comment] 2016-03-14 20:55
I've bought the AWMR-300 Mini inbouw schakelaar and was able to connect it by quickly switching it on and off after the create new signal screen. Not sure whether this will work for the dimmer as well if it is in pairing mode. Eventually returned it and bought a Fibaro Relay.

**Comment by Dennishacq** [comment] 2016-03-19 10:04
@Dijker HomeEasy uses multiple protocols for their devices, You could try if the HomeEasy receiver responds to the old KaKu socket driver. 
@lvanderree I'm not sure why the AWST-6000 isn't working, i'll try to figure out a way to debug this.

**Comment by lvanderree** [comment] 2016-03-27 09:20
@Dennishacq have you already got some ideas of how to debug this? Maybe I can install some debug app, or write some JS to debug?

**Comment by pimviergever** [comment] 2016-04-08 19:07
Hi,
Tried to connect a wall socket, amst-606, awmt-003, and chinese contact sensors. All have similar result:
after 3,4 or 5 code checks, Homey doesn't recognize any kaku anymore.
here is my log: 5488B4CA5F

**Comment by jaxc0402** [comment] 2016-04-09 07:39
+1 for support older devices like sun-500

**Comment by Dennishacq** [comment] 2016-04-14 19:21
Hi guys,

I updated the KaKu app in the Appstore.
You should now be able to pair and use all KaKu devices from the new KaKu series.
Please let me know if you're still experiencing any issues :)

**Comment by Dijker** [comment] 2016-04-14 21:11
My ACDB-7000A now also works! (Paired and triggers Test Flow)

**Comment by laurenssss** [comment] 2016-04-15 15:10
AWST-8802 is not yet working
also no response in code checker

(homewizard does respond on the switch, so it is working)

**Comment by Dennishacq** [comment] 2016-04-15 15:14
@laurenssss
Do you have any other KaKu devices that you can successfully add to Homey?

**Comment by laurenssss** [comment] 2016-04-15 15:16
@Dennishacq yes, wall outlets (both dimmer and regular), built in dimmers, doorbell (once close enough to homey)

**Comment by lvanderree** [comment] 2016-04-18 17:29
the AWST-6000 still isn't paring or showing up in code checker either

**Comment by MdeRhoter** [comment] 2016-04-18 17:52
+1 to that, I have an AWST-6000 gathering dust in a drawer here. I'd love to be able to use it in a flow!

**Comment by Keverjeroen** [comment] 2016-04-19 18:01
Just received my Homey today. Tried to pair the KAKU remote APA3-1500R. When homey asked me to push some buttons, everything worked. After klicking next, I got a white loading screen. The LED ring turned white and now I can't reach Homey anymore..

**Comment by kruimel0** [comment] 2016-04-24 07:15
My Kaku worked quite perfectly (3 APA3 1500R sockets). However, appearantly out of thin air (I think due to a reboot of Homey), they all three stopped working, and I cannot add them back. Tried rebooting homey, re-installing the app, different sockets, nothing works.

**Comment by lvanderree** [comment] 2016-05-04 08:56
I noticed version v.1.1.2 has been released, but unfortunately  the AWST-6000 (motion detector) still isn't working. Is there anything we can do to help? Everything else seems to be working (although sometimes a bit slow, maybe because I couldn't finish the pairing requests).

**Comment by jaxc0402** [comment] 2016-05-22 14:40
Any news on a update for older Cocu / Kaku units like Sun-500?

**Comment by pimviergever** [comment] 2016-05-22 16:58
The AWMT-003 is recognized as wall switch but there is no response in the check screen or in the flows where it is used as trigger.
Does this sound familiar to anyone?
Firmware 0.8.25 and app version 1.12

**Comment by pimviergever** [comment] 2016-06-01 09:31
Hi! Will there be an update for the Kaku app?

**Comment by Dennishacq** [comment] 2016-06-01 15:36
Hi @pimviergever 
This bug should be fixed in the current KaKu version. 
Could you try to re-pair your AWMT-003 with KaKu version 1.1.3?

**Comment by pimviergever** [comment] 2016-06-01 19:53
Hi!
Tried to repair. The awmt-003 has 2 switches.
When I connect 1 switch, it detects 1 switch. At the device menu I cannot test it. I can only press the continue button.
Why can't I cannot the second switch? Why can't I test the connected switch?
After I pressed continue, i paired the other switch on the awmt-003. It show similar behavior and a new wallswitch appears.

I've made 4 flows: 2 switches, each switch on and off.
When I made a flow for the first switch, to turn the lights on or off. This works perfect!
The trouble starts when I made the 2 other flows to control the second switch. The lights do not respond on the second switch but on the first?
Firmware 0835 and Kaku 1.1.3
There seems to be improvements because the code checker is consistent on recognizing the switch (0 or 1)  status (on or off). This was not the case in 1.1.2.
Could you check if homey mixes up the signals from the switches?
Log 965D177E9D

**Comment by pimviergever** [comment] 2016-06-09 20:04
@dennishacq : do you need further explanation? Can I assist in improving the Kaku app?

**Comment by Dennishacq** [comment] 2016-06-09 20:48
@pimviergever Sorry for the late reaction. 
Could you post a screenshot of the 2 flows that switch your lights on?

**Comment by pimviergever** [comment] 2016-06-12 10:21
@Dennishacq because the awmt-003 didn't operate as expected I've removed the devices.
With firmware 0.8.38 and KaKu v1.1.3, the awmt-003 is not recognized anymore?

The flows itself were quite basic:
trigger: wallswitch on
then: turn lifx bulb on

I do not work with the on/off toggle but the on or off commands

![image](https://cloud.githubusercontent.com/assets/10696231/15990614/37d7569e-3098-11e6-85c6-f0da76ad937b.png)

**Comment by bvdbos** [comment] 2016-06-12 10:31
@pimviergever : you're talking about two things: pairing (it's recognized as a single switch instead of a double if I understand what you're saying correctly?) and starting a flow. The second issue appeared in 0.8.38 : https://github.com/athombv/homey/issues/682

**Comment by pimviergever** [comment] 2016-06-12 10:50
@bvdbos you're right. @Dennishacq asked me for further details on the flow i've used.

1st problem: awmt-003 are not recognized correctly. When it was recognized as a wallswitch, it gave different results when I operated it. the awmt-003 has 2 switches but I cannot pair them with homey as 1 device.

2nd problem: the flows i've created for the awmt-003 and the lifx bulbs are seperated for the on/off commands and the left/right switch. So the left switch has 2 flows and the right switch has 2 flows. 4 in total. (I know it's possible with the toggle on/off function but i don't use that)
When I operated the awmt-003 the result for turning the lights on would vary. The left switch would turn on all lights and the right switch was irresponsive.
I did see that there was a change in the results in the code checker (as mentioned earlier).

The problems mentioned in #682 only occur when I try to pair the awmt-003. When I delete them, the other kaku (mainly old/new sockets) operate without a problem.

**Comment by pimviergever** [comment] 2016-06-17 18:09
homey: 0838
kaku 1.1.6
when trying to pair an awmt-003 as a wallswitch:
- the test button after pairing does not work
- can only pair the awmt-003 switches as 2 seperate wallswitches
- i've created flows similar to the one above, when the second switch is turned off, it als turns the lights of first switch off.

would it be possible to add the awmt-003 as 1 device?

**Comment by Dennishacq** [comment] 2016-06-17 19:08
Hi @pimviergever I'll look into this in the near future. You could pair your wallswitch as a socket or sensor in the meantime.

**Comment by ageeweb** [comment] 2016-06-20 09:09
Yesterday I have update my Homey, to try connect Kaku with Homey, Sensor AWST-6000 is not working, Remote AYCT-102 sometimes, after a lot of bushes/trying

paring is working, but its not working in the low editor.

Homey is now turn off, I wait for better times...

**Comment by pimviergever** [comment] 2016-06-20 09:21
@Dennishacq thx for the tip. Just paired the AWMT-003 as 2 sensors. This works!
Now the flows work as predicted, no interference like before. 
The pairing also works, the testing also (not when I tried to pair the AWMT-003 as a wallswitch)

This week I'm going to test it. My LIFX bulbs will be powered on 24/7, Homey will control them by turning them on or off via flows. No news is good news :)

**Comment by pimviergever** [comment] 2016-06-22 20:57
No succes, homey keeps freezing after ca 12 hours.
Deleted the awmt as sensor, no problems so far

**Comment by jaxc0402** [comment] 2016-07-26 07:54
Any news on a update for older Cocu / Kaku units like Sun-500? I can provide one to @WeeJeWel @athom if needed.....

**Comment by WeeJeWel** [comment] 2016-07-26 08:05
@baskiers ^

**Comment by lvanderree** [comment] 2016-07-26 08:13
Since the update of the KaKu-app to 2.0 I am able to pair and use my AWST-6000!

Thanks for the update!

**Comment by jaxc0402** [comment] 2016-07-27 17:32
@BasKiers in need of an sun-500?? yust let me know, i can send one ;)

**Comment by jeroenvollenbrock** [comment] 2016-08-05 12:55
@jaxc0402 Thanks for submitting the SUN-500, we've added it to our collection of test devices. Unfortunately (for us), @BasKiers is currently enjoying his holidays, so we're limited to bugfixes-only while he is away. I've published a new version of the KAKU app which shows the generated code in the title when you add an AC-xxx. This can be used to pair a SUN-500 until the app has been updated with more devices. We're awaiting another shipment of some older kaku devices so we can test them out and add them to the KAKU app.

I'm going to close this issue as it contains a bundle of different issues of which most should be resolved in 0.9.2. If you still encounter any KAKU-related issues in 0.9.2+, please open a new ticket.

**Closed by jeroenvollenbrock** 2016-08-05 12:55 UTC
Labels: Athom App, bug, RF
