### ISSUE TITLE
When telling time, Homey adds a zero

### ISSUE THREAD

**Issue by 2benl** [athombv/homey#941] opened 2016-09-30 20:04 UTC
**What is your Homey version (Settings → System)?**

0.10.1

**What did you try to 

Let Homey tell the time every hour by using the every hour card and using the black time label in speech

**What was the result?**

Homey adds a zero when he's telling time. So It's 22 hour zero in stead of 22 hour. I'm using dutch as language by the way. 

**What did you expect as result?**

...no zero

**Any other remarks**

...

**Comment by bvdbos** [comment] 2016-10-01 07:34
I'm trying to reproduce but does this work with this flow?
![everyhourtelltime](https://cloud.githubusercontent.com/assets/1064079/19012576/36b8203a-87ba-11e6-97d7-f6c4b6ffd01f.png)
When does this run?

**Comment by bvdbos** [comment] 2016-10-01 08:01
Yep, run's at 10.00 and adds a zero... Confirmed...

**Comment by 2benl** [comment] 2016-10-01 08:50
Exactly. Thnx.

**Comment by Rocodamelshe** [comment] 2016-10-01 13:04
Looks to me he starts counting at 0.
He syas 15 uur 0.
A minute later he says 15 uur 1.
So maybe they can start the count at 01 and leave the 0 out of it

**Comment by PeterBox** [comment] 2016-10-01 14:15
Same problem here

**Comment by Tweake** [comment] 2016-10-07 13:55
Thanks for reporting the issue! I have found and fixed a bug in the speech output specific to the **Dutch** language. This fix will be included in Homey as of version 0.10.4.

If any of you also experienced this issue with Homey's language set to **English**, could you please let me know the specific speech output that caused the issue to occur? ( http://<your_Homey's_IP_address>/manager/speech-output/ ) Thanks

**Comment by Rocodamelshe** [comment] 2016-10-12 16:02
Is it also possible to let him say 5 uur 45 instead of 17 uur 45?

**Comment by bvdbos** [comment] 2016-10-15 08:31
confirmed fixed when used in a flow but doesn't work through the speech-input page anymore. It doesn't say 10 uur 1 but tien-nul-een...

**Comment by jeroenvollenbrock** [comment] 2016-10-17 11:53
@bvdbos: What exactly you you enter in speech-input?

**Comment by bvdbos** [comment] 2016-10-17 11:56
I write 10:01 in speech-input and I have a parrot flow. Before this was spoken as time (thus: 10 uur ....) but now it doesn't anymore. Not that important as from flows it still works...

**Comment by Tweake** [comment] 2016-10-17 12:22
In that specific case Homey will indeed say ten-zero-one. The reason for that we do special character filtering as part of speech input. This is needed boost speech trigger accuracy. You are making Homey say the cleaned up speech input, at which point the ":" has already be removed, so the text to speech parser can't know you want it to be pronounced as a time. So in this case everything is working as intended. 

If you go to <IP>/manager/speech-output/ or type directly type "10:01" into a say card in a flow, you should find that Homey pronounces the time just fine.

**Closed** 2016-10-17 13:00 UTC
Labels: Staged for release
