### ISSUE TITLE
[bug] Flowcard in if-colomn "every 7 days" is resetting afer ptp

### ISSUE THREAD

**Issue by Marc1979** [athombv/homey#2201] opened 2018-02-04 11:33 UTC
I have a flow which is (was) triggering every saturday at 0.00h. But it failed after a PTP, seems the "every X days" card is resetting after the PTP.

* Homey Version:1.5.6-rc.8
* Homey Log Code: nvt
* Smartphone Platform: nvt
* Smartphone App Version: nvt

**What did you try to achieve?**
Starting a flow on saturday 

**What did you expect as result?**
That the flow starts every saturday

**What was the result?**
No trigger on saturday after a ptp in the beginning of the week

This is the flow I used:
![shifts](https://user-images.githubusercontent.com/19633409/35777056-8daf691e-09a7-11e8-918a-751c70c3a154.JPG)

**Comment by Marc1979** [comment] 2018-02-04 11:39
Maybe an card in the If-column with day and time in it would help.
A trigger card like  if  "saturday at 0.00h"

**Comment by Dijker** [comment] 2018-02-04 12:25
Every 7 days could be also get out out of sync with  your expectations...
I would go for an alarm repeating at a predefined time on a self choosen day of the week. Just change the  flow to trigger on that alarm by name.

**Comment by Marc1979** [comment] 2018-02-04 15:36
@Dijker didn't thought about that one...thanks!

**Comment by Dijker** [comment] 2018-02-04 15:39
I guess the issue after a PTP is that it starts again by design. 

If you are happy with it you can close this issue ;-)

**Comment by Marc1979** [comment] 2018-02-04 15:41
happy..happy..?? Don't know if it's a big thing to see when a a logic is started/reset. Just as the betterlogic app..

**Comment by Dijker** [comment] 2018-02-04 16:08
something like 
![image](https://user-images.githubusercontent.com/12412734/35779460-be9dcd1a-09cd-11e8-863c-b8a92bf1e6a8.png)
there are so many ways to Rome.....

**Comment by Marc1979** [comment] 2018-02-04 16:45
@Dijker that is not working in my flow because of the ELSE colomn

**Comment by Dijker** [comment] 2018-02-04 22:03
Ok, right...
to work around you can make 2 flows:

Flow 1: (will only execute then once every 7 days on your choosen  day/time)
When:  Time - And:  WeekDay = {WhatYouWant} => Then: Trigger a Flow Flow2

Flow 2: (This wil doe the Shifts condition )
When: This Flow is Triggered - And: (Your Other Condition) - Then: Option1 - Else: Option2

This one wil not get out of sync after a restart or PTP!

**Comment by Marc1979** [comment] 2018-02-05 07:52
@Dijker
 That flow is better ;). Will add that flow to my homey..thanks for you're time! 
Will close this issue..

**Closed** 2018-02-05 08:04 UTC
