### ISSUE TITLE
Custom IR Device not working correctly

### ISSUE THREAD

**Issue by ronneman** [athombv/homey#929] opened 2016-09-29 16:17 UTC
**What is your Homey version (Settings → System)?**

0.10.1

**What did you try to achieve?**

Try to use a custom, non tv remote, IR Device

*Please include detailed steps how we can reproduce the issue*
First added a Samsung IR device.
Secondly added a custom IR device. Trained the on / off signals. 

**What was the result?**
When the custom IR device is used in a flow, e.g. to turn on the device it does not receive any signals.

**What did you expect as result?**

The TV remote IR device works fine for me. The custom IR device's receiver is very close to the tv one. So it should work 
...

**Any other remarks**

In version 0.10.0 it worked but just one remote at a time. This problem is solved now

**Comment by bvdbos** [comment] 2016-09-30 05:46
This worked for me when the custom device was the first device but not when it was the second device (after a generic Phlips) it seems. Reproduction not yet clear...

**Comment by ronneman** [comment] 2016-09-30 06:39
The custom device in my case is the second IR device. First one is a samsung generic remote. 
Updated the reproduction part a bit.

**Comment by Tvandongen** [comment] 2016-09-30 15:51
In my case I have added 2 custom devices after a generic Philips TV:
- Second added RF device: vodafone TV receiver
- Third added RF device: Philipts HTS8100 (home cinema Soundbar)
Both custom devices will not turn on. Other buttons not tested. After creating manual device it seems not to be possible to learn more buttons on the RF device

**Comment by bvdbos** [comment] 2016-10-02 07:58
I have a similar setup. This works for me... But can't get my TV receiver (KPN) to work yet. My MCI500h (stereo) sometimes receives the power-signal for too long a time so it jumps to eco-mode and I can only revive it by physically pushing the power-button on the device. This works:
![eerste nummer starten](https://cloud.githubusercontent.com/assets/1064079/19019326/8a8845e4-8884-11e6-9ff6-ed379b8720ab.png)

**Comment by nattlip** [comment] 2016-10-07 07:10
my first ir tryout

added samsung horizon set top box horizon to my devices
made simple flow : say yes to homey to power toggle the device
ledring off 
homey phone camera check ready
pressed test in flow
no ir emitting from homey
everlasting waiting sign in homey flow > 10 minutes.


![knipsel](https://cloud.githubusercontent.com/assets/7040452/19181501/c6a795f6-8c6d-11e6-9015-d1b26bca99e9.PNG)

**Comment by goldenice** [comment] 2016-10-11 12:04
This is actually an issue with the signal definition from our database, although instead of being stuck on the loading circle, it should have thrown an error.

**Comment by Tvandongen** [comment] 2016-10-11 20:40
@goldenice. how can it be an issue with the signal definition on your database, as at least both the Vodafone set top box and the Philips sound bar are not in the database (or are they added in the release of 10.4) ?
 Can of course not speak for the other participants, but the topic is about Custom IR devices, so I expect that there devices are also not in the database.

**Comment by jeroenvollenbrock** [comment] 2016-10-17 13:02
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please reopen this issue.

**Closed by jeroenvollenbrock** 2016-10-17 13:02 UTC
Labels: Infrared, Staged for release
