### ISSUE TITLE
Senddata_timeout

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1663] opened 2017-06-24 17:06 UTC
**What is your Homey version (Settings → System)?**
1.3.2

**What did you try to achieve?**
Close gate

*Please include detailed steps how we can reproduce the issue*
![afbeelding](https://user-images.githubusercontent.com/23163409/27510408-0bee07ac-5910-11e7-8756-6873110598be.png)

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
C9861FF185
...

**Comment by bvdbos** [comment] 2017-06-24 17:20
dupe of your own issue #1637 ?

**Comment by chrisboer** [comment] 2017-06-24 18:07
This was not on a zwave device but on the phone so this could indicate it is not zwave related but another issue.

**Comment by bvdbos** [comment] 2017-06-24 18:15
That's not possible afaik, senddata bug to the phone... completely different codebase/protocols...

**Comment by nattlip** [comment] 2017-06-24 18:31
where is this Senddata_timeout visible in homey on the phone in your garden  you didnt fill in any parameter or variables asked in the header of this isue. you could also include a screenshot of thew eror visible.

**Comment by chrisboer** [comment] 2017-06-24 19:37
Sorry but please look in the screendump it is possible this is why I filled this new issue.

**Comment by caseda** [comment] 2017-06-25 16:01
Then at least finish the issue by adding what the triangles say.. :wink:

**Comment by chrisboer** [comment] 2017-06-25 16:18
The triangles say Senddata_timeout

**Comment by caseda** [comment] 2017-06-25 16:25
Even for the mobile message? Cause that's not an error for mobile messaging

**Comment by bvdbos** [comment] 2017-06-25 16:29
Is your phone called "Komt Goed"? Seems unlikely and if so probably the cause of the error on the phone-message-card. @caseda Maybe only the last error is shown, even is there's multiple errors?

**Comment by caseda** [comment] 2017-06-25 17:29
i can see 2 different errors just fine.

And if the phone wasn't really that name, the autocomplete box would get a red border.

**Comment by chrisboer** [comment] 2017-06-25 20:30
My phone is called "Komt Goed Schatje" so unlikely but not impossible you see

**Comment by WeeJeWel** [comment] 2017-07-03 19:15
This happens sometime, try placing the device closer to Homey or by adding repeaters to your Z-Wave network.

**Closed by WeeJeWel** 2017-07-03 19:15 UTC

**Comment by chrisboer** [comment] 2017-07-03 20:18
I already did add repeaters but still issues worked fine for 6 months
