### ISSUE TITLE
After KAKU re-adding Doorbell ACDB-7000AC stopt working.

### ISSUE THREAD

**Issue by 2benl** [athombv/homey#734] opened 2016-07-30 07:50 UTC
**What is your Homey version (Settings → System)?**

0.9.1

**What did you try to achieve?**

Re-adding my doorbell as stated because off the new KAKU version. The old association will be dropped in the future

*Please include detailed steps how we can reproduce the issue*

Removed the old door bell from Devices. Pressed Add a device. Chose the KaKu app and chose ACDB-7000C. (also: The picture of the inside unit is correct. The picture of the outside unit isn't. My outside doorbell unit looks like the one ACDB-6600.) I used both ways of inclusion but they both fail. (I also tried the ACDB-6600, same result)

**What was the result?**

The app says it recieved the doorbell signal, but in the next testing screen the test button won't set my doorbell to go off. When included in flows the doorbell won't work either. So now I don't receive any more messages and pictures from people at the door. This worked fine before.

**What did you expect as result?**

A working doorbell like I had before.

**Any other remarks**

...

**Comment by 2benl** [comment] 2016-07-30 08:00
A few minutes later the doorbell started working without any change from my side. Strange that the test function in the device adding didn't work.

**Comment by BasKiers** [comment] 2016-08-29 20:23
Since I cannot reproduce this issue I will close it. Please reopen this issue if it still persists. Sometimes the problem is that the kaku device cannot store more senders so it needs a full reset (holding the pair button for +- 10 seconds and then pressing it once).

**Closed by BasKiers** 2016-08-29 20:23 UTC
Labels: Athom App, RF
