### ISSUE TITLE
Z-Wave hangs after resetting Z-Wave network

### ISSUE THREAD

**Issue by Kludon** [athombv/homey#876] opened 2016-09-23 19:53 UTC
**What is your Homey version (Settings → System)?**

0.10

**What did you try to achieve?**

I've updated my homey to 0.10. I Have a Fibaro wallplug that didn't respond. After that I started to reset my Z-Wave network. After pressing the reset network button it seams Z-Wave hangs and shows a loading sign (for 2 days).

**What was the result?**

Z-Waves hangs

![homey zwave2](https://cloud.githubusercontent.com/assets/22402967/18799443/e4f1d9ea-81d7-11e6-88c0-c0d9b78cf4e3.PNG)

![homey zwave](https://cloud.githubusercontent.com/assets/22402967/18799451/ec746cbe-81d7-11e6-9d06-f1d9cec303ba.PNG)

When I want to include my wallplug again I get the following error.

![homey zwave3](https://cloud.githubusercontent.com/assets/22402967/18799644/eb441b0e-81d8-11e6-8d4e-615143c02e9b.PNG)

**What did you expect as result?**

Resetting the Z-Wave network so I could include my Z-Wave Fibaro wall plug again.

**Any other remarks**

I tried to hard reset the homey by holding it upside down but that didn't solve the problem.

I've send my log to Athom:

0771145DEC

**Comment by bvdbos** [comment] 2016-09-23 20:06
What does (in console) `api('GET', '/wireless/zwave/state/', null, function( err, result ) { console.log( JSON.stringify(result, false, 4) ); });` say about the zwave-status?

**Comment by Kludon** [comment] 2016-09-24 05:36
@bvdbos I've pasted in node.js console app but it says : 
'api' is not recognized as an internal or external command,
operable program or batch file.

Can you help?

**Comment by Inversion-NL** [comment] 2016-09-24 12:48
Use Google Chrome console

**Comment by bvdbos** [comment] 2016-09-24 13:05
@Inversion-NL : nope, doesn't work anymore...

**Comment by jeroenvollenbrock** [comment] 2016-10-17 13:03
Can you please let me know whether this issue persists or not?

**Comment by uNiiek** [comment] 2016-10-17 13:32
@jeroenvollenbrock Same as #905. So, I think the problem still exists

**Comment by jeroenvollenbrock** [comment] 2016-10-17 13:50
In that case, let's close this issue as duplicate of #905, and continue there.

**Closed by jeroenvollenbrock** 2016-10-17 13:50 UTC
Labels: duplicate, Staged for release, Z-Wave
