### ISSUE TITLE
homey dous not react on speech

### ISSUE THREAD

**Issue by chrisesi** [athombv/homey#334] opened 2016-03-11 22:44 UTC
**What is your Homey version (Settings → System)?**
0.8.22

**What did you try to achieve?**
talk to homey
*Please include detailed steps how we can reproduce the issue*
homey dous not react when talking to him

**What was the result?**
no reaction
...

**What did you expect as result?**
reaction exemple "what is the time",homey saying "the time is...."
...

**Any other remarks**
in previous update 0.8.20 everything went well 
...

**Comment by jghaanstra** [comment] 2016-03-12 06:16
This is a duplicate and should be closed: https://github.com/athombv/homey/issues/321

0.8.22 broke speech.

**Comment by WeeJeWel** [comment] 2016-03-14 13:08
Duplicate of #321

**Closed by WeeJeWel** 2016-03-14 13:08 UTC
