### ISSUE TITLE
Insights: Graphic wrong

### ISSUE THREAD

**Issue by Phunkay** [athombv/homey#1080] opened 2016-11-18 22:35 UTC
**What is your Homey version (Settings → System)?**

1.0.1

**What did you try to achieve?**

The graphic of the my KAKU switches seems completely wrong when compared to the downloaded log data.

**What was the result?**

Here the first ON period in the graph starts when the light is switched off at night and ends when it is turned on the next morning. The second ON period in the graph is between when the light was turned off in the morning and back on in the afternoon. Essentially inverting the ON and OFF periods (Downloaded log data in corner right for reference)
![chart](https://cloud.githubusercontent.com/assets/22442908/20448948/da88b024-ade6-11e6-970d-50108b742b89.jpeg)

Here too the ON period is between OFF in the morning and ON in the afternoon.
![chart2](https://cloud.githubusercontent.com/assets/22442908/20449034/4883363a-ade7-11e6-8a07-eee27a28bda8.jpeg)

The graph drawing parameters seem to be offset.

**Comment by Keverjeroen** [comment] 2016-12-02 11:37
I see this happening in other logs too. For example from Hue light on/off status or Fibaro motion on/of. The strange thing is, that the graph sometime (after waiting a minute or so) turns the on/of status back to the right on/of state in the graph.. I am using Chrome btw.

**Comment by magtimmermans** [comment] 2017-01-05 10:50
same here

**Comment by JesperJanssen** [comment] 2017-01-16 21:29
I also have the same problem here. Log file seems to be ok. But the representation in the graph is or not available or inverted.

**Comment by bvdbos** [comment] 2017-08-18 05:12
confirmed fixed in 1.5rc6

**Comment by hfaas** [comment] 2017-08-26 18:26
I've seen this bug also for non-boolean type statistics.
It seems like the algorithm uses the measurement points as endpoints, instead of start-points, for the bar-graphs. Meaning it will draw a line from the previous measurement point to the current at a level value of the current point instead of using the level value of the previous point.

@jeroenvollenbrock: has this been corrected for all statistic types (e.g. also energy usage values)?

**Comment by jeroenvollenbrock** [comment] 2017-09-11 16:06
@hfaas It is, the points were added from right-to-left instead of left-to-right before

**Closed by jeroenvollenbrock** 2017-09-11 16:06 UTC
Labels: bug, Insights, Staged for release
