### ISSUE TITLE
[Enhancement] Rename Flow

### ISSUE THREAD

**Issue by kerkenit** [athombv/homey#1413] opened 2017-03-24 18:41 UTC
**What is your Homey version (Settings → System)?**

1.2.0-rc.0

**What did you try to achieve?**

I've a flow named _Lampen aan_ in the folder Morning, and a flow _Lampen aan_ in the folder Evening.
I have them included in another flow. I don't know witch I'm using.
I've renamed the flow _Lampen aan_ to _Lampen aan in de morgen_ and the other one to _Lampen aan in de avond

**What was the result?**
No change of the name in the flow's where the flow is included/triggered

**What did you expect as result?**

When I rename a flow the other flows where the current flow is included (based on guid) should be renamed as well

**Any other remarks**

The situation described is fictive. The problem is the same. (Nothing beats a liar)

**Comment by WeeJeWel** [comment] 2017-04-04 18:24
Duplicate of #330

**Closed by WeeJeWel** 2017-04-04 18:24 UTC
Labels: enhancement
