### ISSUE TITLE
[Apps] Stocks : Sometimes stock price of 0 is displayed in Insights

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#391] opened 2016-03-31 19:00 UTC
**What is your Homey version (Settings → System)?**

0.8.24.

**What did you try to achieve?**

Monitor stock prices. Sometimes ( most of the times one or two times a day ) the stock drops to zero. 

**What was the result?**

![screen shot 2016-03-31 at 20 56 43](https://cloud.githubusercontent.com/assets/17275712/14187419/386b14fe-f783-11e5-8523-d9167ae7d0d9.png)

![screen shot 2016-03-31 at 21 00 07](https://cloud.githubusercontent.com/assets/17275712/14187488/96b7d178-f783-11e5-9f40-057d08f5dd75.png)

**What did you expect as result?**

If there is an error in retrieving the stock price, don't store 0. This messes up flows that might act on it. 

**Any other remarks**

Luckily Homey isn't fast enough for High Frequency Trading ;-)

**Comment by nlrb** [comment] 2016-03-31 20:16
I can confirm the issue. Values should only be updated when the stock market is open.

**Comment by ralfvd** [comment] 2016-03-31 20:20
It is not only when the stock market is not open.

Also when the stock market is open, sometimes it will miss getting the
correct stock price. It might be that it is a local problem on my side (
internet down ), but also if the website they are getting the stocks from
(Yahoo?) is responding in an unexpected way.

**Comment by stefan-witkamp** [comment] 2016-04-02 12:08
This is fixed in an upcoming update, which will be published when the stable channel is > .23 due to other updates.

**Comment by stefanwitkamp** [comment] 2016-04-04 08:10
Fixed in a new update, will be pushed to app store when stable version > .23 due to other improvements/fixes.

**Closed** 2016-04-04 08:10 UTC
