### ISSUE TITLE
Pairing a second KaKu remotes renders the first one unfunctional

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#222] opened 2016-02-20 12:12 UTC
Homey version: 0.8.17

Kaku remotes: AYCT-102 & APA3-1500R

Both remotes are recognized. The second remote added will remain functional, the first one will not work anymore within a Flow. 

There is no difference if I first pair the '102' and then the 'apa3' or vice versa. 

Expected results: Both remotes are working independently. 

Other remarks: when deleting a device, the flows that use that device as a trigger are emptied or deleted as well. Not only the 'when' column (which I can relate to), but also the complete flow.

**Comment by Dennishacq** [comment] 2016-02-26 18:39
Hi ralfvd,

Thank you for reporting your issue.
I'm not able to reproduce the problem, could you show me a screenshot of your Flow?

**Comment by Luukvis** [comment] 2016-03-02 15:17
Hi Dennis. I have the same problem and a screenshot of a flow probably does not give you any extra information. I also tried to pair 2 KAKU remotes (one for the living room and one for the bedroom). When I pair the first remote I can attach buttons in a flow. It works really fine. 
When I add a second remote, the first remote doesn't work anymore, although the flows are still there. But the flows cannot be used any more. 
![kakuflow](https://cloud.githubusercontent.com/assets/16554361/13464608/3ca2bfc0-e092-11e5-8408-e43122787527.JPG)

**Comment by soler2000** [comment] 2016-03-04 23:52
Exactly the same issue I am having with the development of the Lightwave RF app,  seams to be a bug within Homey and not the KAKU app

**Comment by Dennishacq** [comment] 2016-03-19 09:46
@Luukvis  We found the cause of this bug, it will be fixed in one of the upcoming Homey updates.

**Comment by soler2000** [comment] 2016-03-19 12:24
I think this is already fixed,  it if fixed within my app as the args returned are now for the correct device

**Comment by Luukvis** [comment] 2016-03-20 12:58
@Dennishacq It seems that the bug is already solved in 0.8.24. This morning I was able to connect 3 KaKu (AYCT-102) remotes. I use a remote for every room (living, bedroom, study). It works fine now.

**Closed** 2016-04-14 19:18 UTC
Labels: bug
