### ISSUE TITLE
Somfy & Forest; closing/opening sunscreen/curtains with speech input does not result in response

### ISSUE THREAD

**Issue by cjvs** [athombv/homey#638] opened 2016-05-22 08:40 UTC
**What is your Homey version (Settings → System)?**
0.8.35 (after full reset and data wipe)

**What did you try to achieve?**
Closing/opening the curtains (forest) or sunscreen (somfy) by voice command:
- please open / close the curtains
- please open / close the blinds

**What was the result?**
Homey responds with:
- opening / closing blinds / curtains. However, the blinds or curtains do not open or close.

**What did you expect as result?**
Actual opening or closing of the blinds / curtains

**Any other remarks**
log 64429D8CC3, and same as issue #434 (marked closed, but apparently not...)
opening and closing of sunscreen and curtains through a flow or by the app does work. Only speech commands are not processed;

**Comment by zperx** [comment] 2016-05-22 16:37
Yes I can confirm. This does not work. It did not work with the 0.8.34 firmware either.

**Comment by cjvs** [comment] 2016-05-23 18:54
In addition, when I ask "close window covers". Homey responds with "closing window covers" immediately followed by "closing covers". (two subsequent responses to one question, and still no action...)

**Comment by cjvs** [comment] 2016-06-11 20:05
Update to 0.8.38 did not resolve the matter. Still no action on a voice command, even though Homey responds (both for somfy and forest)

**Comment by cjvs** [comment] 2016-06-22 15:21
Update to 0.8.39, did a full reset. And again it did not resolve the matter. Still no action on a voice command, even though Homey responds (both for somfy and forest). @Tweake Anything I can do to help test / solve the bug?

**Comment by Tweake** [comment] 2016-08-22 11:29
My apologies that it took such a long time before reviewing this issue. Made some changes which should get the speech commands working for both Somfy and Forest. Also removed the double confirmation. These improvements will be included in 0.9.3. Thanks for reporting the issue :)

**Comment by cjvs** [comment] 2016-09-01 19:51
Thanks for resolving the issue! My Homey is currently running on 0.9.3, with the forrest 0.11.1 and somfy 1.1.0 app. Voice control works. The response however...

**What is your Homey version (Settings → System)?**
0.9.3

**What did you try to achieve?**
Closing (only) the curtains (forest) by voice command. "please close the curtains"
**What was the result?**
Homey responds with: closing curtains. 

However, the curtains close AND (its pitchdark outside) the sunscreen (somfy) opens...

**What did you expect as result?**
Closing of the curtains only.

**Comment by Tweake** [comment] 2016-09-29 12:08
Hmm that's an interesting issue. I think we will end up creating a separate deviceclass for solar shades to fix the problem. This will require some planning, so I cannot offer you an immediate solution. When we have made progress with it I will report back here.

**Comment by cjvs** [comment] 2016-10-05 18:59
An update:
Currently on 0.10.3. This update has disabled voice control of both Somfy and Forest again... (actually already the case in 0.10.1 and 0.10.2)

**What is your Homey version (Settings → System)?**
0.10.3

**What did you try to achieve?**
Closing/opening the curtains (forest) or sunscreen (somfy) by voice command:

please open / close the curtains
please open / close the blinds
please open / close the shutters
please open / close the sunscreen

**What was the result?**
Nothing happens

**Any other remarks**
opening and closing of sunscreen and curtains through a flow or by the app does work. Only speech commands are not processed;

**Comment by Tweake** [comment] 2016-10-07 11:33
I'm sorry you are still not able to control your curtains as intended via voice. Your update on the issue is much appreciated and I'll get to work on a solution today. I'll keep you posted!

**Comment by Tweake** [comment] 2016-10-07 14:16
I found and resolved the issue, and the fix will be included in the 0.10.4 update. One thing to note is that I was able to verify the fix with Forest blinds, but not with Somfy solar screens. I'm confident the fix works regardless of window coverings brand, but your confirmation will be much appreciated.

**Comment by cjvs** [comment] 2016-10-14 19:51
Hi Tweake. I have updated to 0.10.5 today. Good news is that the curtains respond to voice commands! Thanks a lot!

The following works to open/close my forest shuttle curtain:
open/close curtain**s**
open/close blinds
open/close shutters

The Somfy sunscreen does **not** respond to the commands above (which in one way is good, since I dun not want my tarrace sunscreen to open when I close the curtains at night (do you follow?))

One note. I have one curtain on my forest shuttle. However, closing curtain (no plural) does not result in a response. It must be curtain**s**.

A separate device class (as previously suggested by yourselves) would be required for a tarrace solarscreen.

Thanks again! And keep up the good work guys!

**Closed** 2016-10-17 11:48 UTC
Labels: bug, Homey Core, speech-input
