### ISSUE TITLE
unable to remove/rename standard zones.

### ISSUE THREAD

**Issue by dicknystrand** [athombv/homey#2287] opened 2018-03-04 12:19 UTC
![skarmavbild 2018-03-04 kl 13 17 42](https://user-images.githubusercontent.com/37040361/36945445-943975aa-1fae-11e8-806e-defa1c8521dc.png)
**Metadata**

* **Homey Version**: Homey Firmware Version: 1.5.6
* **Homey Log Code**: 3151371588
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Renaming/removing default Zones. Moving Zones between zones. Creating new Zones like "sovrum"

**What did you expect as result?**
Removed/renamed zones will been removed or renamed. Newly created zones would have there given name. Moved Zones would been moved and so on.

**What was the result?**
Renamed Zones have there original name, deleted default zones reappearing, newly created zones have the name New Zone. Everything seems OK but after restarting Homey desktop appear as before the changes

**Any other remarks**

**Comment by Dijker** [comment] 2018-03-04 12:26
Duplicate of #2239, but you will have to wait for 1.5.7 to become stable.

**Comment by jeroenvollenbrock** [comment] 2018-03-12 10:34
Closing as duplicate of #2239

**Closed by jeroenvollenbrock** 2018-03-12 10:34 UTC
