### ISSUE TITLE
Speech to Text engines come back with no results

### ISSUE THREAD

**Issue by 4tetra4** [athombv/homey#1268] opened 2017-01-16 10:14 UTC
**What is your Homey version (Settings → System)?**

Any

**What did you try to achieve?**

To give instruction (built in and flow specific ones) to Homey.

**What was the result?**

We have a 5-10% success rate. 
Many of the of the speech inputs are converted incorrectly. (Nothing new here)
My issue is that most of the speech inputs came back with no results at all. It makes it impossible to correct the misinterpreted commands manually via a flow or app.
I was checking the results on the /manager/speech-input page.

**What did you expect as result?**

Working speech recognition. And results from the speech to text services.

**Any other remarks**

Language: English
Speakers: Native, Male-Female-Children
Ambient noise: Nothing-minimal
Echo: not noticeable
Distance: 1-2 meters
...

**Comment by jeroenvollenbrock** [comment] 2017-03-06 17:49
Closing as duplicate of #920.

**Closed by jeroenvollenbrock** 2017-03-06 17:49 UTC
