### ISSUE TITLE
[App LG webOS] Homey reports TV offline

### ISSUE THREAD

**Issue by efriethoff** [athombv/homey#1620] opened 2017-06-07 10:16 UTC
**What is your Homey version (Settings → System)?**

1.3.0-rc.12

**What did you try to achieve?**

I expected to see messages from Homey on my TV based on a flowcard

**What was the result?**

The messages are not shown, because Homey reports my TV to be offline, while this is not the case

**What did you expect as result?**

I expected to see Homey connected to my TV

**Any other remarks**

It seems that when I switch off the TV, Homey loses the connection, but never polls again to see if the TV is switched on again. 
When I re-install the LG webOS-app again while my TV is on, everything works again as expected.
The current flowcards act as expected.

Would it be possible to force a connection check or something?!
It now makes no sense to reinstall the app every day...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by WeeJeWel** [comment] 2017-06-08 10:10
Duplicate of https://github.com/athombv/com.lg.webos/issues/3

**Closed by WeeJeWel** 2017-06-08 10:10 UTC
