### ISSUE TITLE
Insight shows wrong on off (true/false) indication in diagram.

### ISSUE THREAD

**Issue by HarryHobma** [athombv/homey#1603] opened 2017-06-01 09:58 UTC
**What is your Homey version (Settings → System)?**

1.3.0 RC 11

**What did you try to achieve?**
Look into the trigger to change the switch indication.

*Please include detailed steps how we can reproduce the issue*
I have the same issue with motion detection but this is difficult to reproduce to much on off markings.
The newly installed wall plug for switching my kitchen boiler this is on command.

**What was the result?**

It looks like that the polling time before the actual switch time change the indication in insight changes to on / true while it is still off / False.
See below screen shot with the true false file in the same shot to clarify.
![schermafbeelding 2017-06-01 om 11 36 31](https://cloud.githubusercontent.com/assets/26304523/26674552/2215dc3c-46c1-11e7-8203-e27029ca26c1.png)

**What did you expect as result?**

The color change only on the moment of change from false to true and not change at the polling time before true which is still false.

**Any other remarks**

As indicated this is the same issue with my motion detection. All units are from fibaro.

**Please attach a Homey System log (Settings -> System -> Send Log)**

23A4DAFB29

**Comment by HarryHobma** [comment] 2017-06-01 10:06
I see it is also a duplicate of the below but hopefully this one will clarify enough to solve the problem.
Duplicate of #1080 #1141 #1134 and #1313 ?

**Comment by jeroenvollenbrock** [comment] 2017-06-12 12:12
Duplicate of #1595

**Closed by jeroenvollenbrock** 2017-06-12 12:12 UTC
