### ISSUE TITLE
feature: Disable a standard word

### ISSUE THREAD

**Issue by vanderaatje** [athombv/homey#1259] opened 2017-01-13 20:41 UTC
**What is your Homey version (Settings → System)?**
Homey Firmware Versie: 1.1.2

**What did you try to achieve?**
Open my curtains by IR

*Please include detailed steps how we can reproduce the issue*
Because IR is not working through homey I use the Logitech Harmony App for it. But now when I use the text open curtains in a flow homey is telling me it can't find any curtains. 

**What was the result?**
I receive the message "ik kon geen gordijnen vinden om aan te sturen" (no curtains found to controle)

**What did you expect as result?**
Because homey thinks I don't have any curtains I expect it not to answer on it

**Any other remarks**
Is there an option to disable certain default words even better have a check if you have the product.

**Comment by WeeJeWel** [comment] 2017-03-15 15:33
Duplicate of #1260

**Closed by WeeJeWel** 2017-03-15 15:33 UTC
Labels: enhancement, speech-input
