### ISSUE TITLE
kaku YC-400 and YC412 not reqonied as dimmer but as switch

### ISSUE THREAD

**Issue by B3rt** [athombv/homey#1302] opened 2017-02-01 23:06 UTC
**What is your Homey version (Settings → System)?**
1.1.2

**What did you try to achieve?**
just added the devices 

*Please include detailed steps how we can reproduce the issue*
nothing special, just choose device and add

**What was the result?**
it is added as on/off switch

**What did you expect as result?**
it should be added as a dimmer

**Any other remarks**
no

**Comment by bvdbos** [comment] 2017-02-02 05:25
You already filed this is https://github.com/athombv/nl.klikaanklikuit/issues/12, no need to do this twice. As this issue is with the KaKu-app, you might close this bug...

**Comment by B3rt** [comment] 2017-02-02 08:33
was not sure, in the app store at kaku app this github has linked to report bug to, not the kaku github

**Comment by BasKiers** [comment] 2017-02-20 13:29
Duplicate of https://github.com/athombv/nl.klikaanklikuit/issues/12 where I now answered the issue. I will close this issue.

**Closed by BasKiers** 2017-02-20 13:29 UTC
Labels: Athom App
