### ISSUE TITLE
USb plug makes Homey instable

### ISSUE THREAD

**Issue by annekrist** [athombv/homey#722] opened 2016-07-19 13:45 UTC
**What is your Homey version (Settings → System)?**

x.x.x

**What did you try to achieve?**

*Please include detailed steps how we can reproduce the issue*

**What was the result?**

...

**What did you expect as result?**

...

The usb cable and plug make the Homey tilt foreward. It only stands on its two front balls. The one in the back is pushed upwards by the cable. Design prob? Maybe if i place  a rock on top of the homey....;-) 
...
![homey](https://cloud.githubusercontent.com/assets/20539102/16952011/c066c4b2-4dc7-11e6-97cc-670d15e21585.jpg)

**Comment by Dijker** [comment] 2016-07-19 14:44
double #84

**Comment by elcovb** [comment] 2016-07-20 11:11
Here too. Got my Homey today. Like nobody tested the design...

**Comment by jeroenvollenbrock** [comment] 2016-07-27 16:05
Duplicate of #84

**Closed by jeroenvollenbrock** 2016-07-27 16:05 UTC
