### ISSUE TITLE
Enhance if this then flow management

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1484] opened 2017-04-20 08:13 UTC
**What is your Homey version (Settings → System)?**
1.2.0

**What did you try to achieve?**
Easily change and manage existing flow 
![afbeelding](https://cloud.githubusercontent.com/assets/23163409/25220416/fd16e21c-25b1-11e7-88b6-9781112ad55f.png)

*Please include detailed steps how we can reproduce the issue*
See arrow and text comments in picture

**What was the result?**

...

**What did you expect as result?**
More manageable flow

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**

...

**Comment by caseda** [comment] 2017-04-20 08:15
https://forum.athom.com/discussion/1430/software-status#latest
> Homey v1.3.0
> While some of us work on v1.2.0, in the meantime others have been working on v1.3.0 already. It features an updated version of the Flow Editor, with 'else' support (we heard you!), sortable columns, and a much needed improvement for the Flow picker component, which is also used in Insights.

**Comment by Arjanvde** [comment] 2017-04-20 08:18
Duplicate of #61

**Comment by spoelly** [comment] 2017-04-20 14:13
ow yes please +1

**Comment by jeroenvollenbrock** [comment] 2017-04-24 11:45
Closing as duplicate of #61 (Which has been resolved in version 1.3.0)

**Closed by jeroenvollenbrock** 2017-04-24 11:45 UTC
