### ISSUE TITLE
[0.9.2] app.json not handled correctly after stop/start of an app

### ISSUE THREAD

**Issue by gruijter** [athombv/homey#776] opened 2016-08-09 09:11 UTC
**What is your Homey version (Settings → System)?**

0.9.2

**What did you try to achieve?**

Override a default capability with new properties (e.g. change meter_power "units' from Wh to kWh, and "min" from 0 to -999999999)

*Please include detailed steps how we can reproduce the issue*

in app.json redefing the values of "units" and "min" of the standard capability meter_power

**What was the result?**

Redefinition of the values work after pairing, but gets reset to the default values after the app gets stopped-started again. When rebooting Homey the changed values are handled correctly again.

**What did you expect as result?**

That the values as specified in app.json are handled correctly after a stop/start of the app.

**Any other remarks**

see also #772 and #775

**Comment by WeeJeWel** [comment] 2016-08-23 12:56
Duplicate of #772

**Closed by WeeJeWel** 2016-08-23 12:56 UTC
Labels: App-SDK, bug, Homey Core
