### ISSUE TITLE
Sensortype not found (ST-814 humidity sensor)

### ISSUE THREAD

**Issue by djefmo** [athombv/homey#549] opened 2016-04-30 10:00 UTC
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

I have an Everspring ST814 device which can report Temperature & Humidity. Humidity is not reported.
It gives the error: Sensortype not found. Additionally, after several minutes, the temperature sensor gives an error as well: TRANSMIT_COMPLETE_NO_ACK

*Please include detailed steps how we can reproduce the issue*

Inclusion in the network goes well; it detects three devices (the main device, the temperature sensor and the humidity sensor). However when you click on the node x.2 (which is the humidity sensor), instead of showing the humidity, it gives the error. A few minutes later the temperature sensor stops working as well. (see printscreen)

**What was the result?**

I can't use the humidity sensor, since this sensortype can't be found. And the temperature sensor can't be read either 
<img width="273" alt="screen shot 2016-04-30 at 12 09 55" src="https://cloud.githubusercontent.com/assets/18704157/14935314/dd122226-0ecc-11e6-8026-f4bc5d62094b.png">

**What did you expect as result?**

A working sensor. 

**Any other remarks**

The humidity error was also reported on Github on issue 387, however it was stated that the problem was solved in version 0.8.30. However, it still doesn't appear to work. 

[https://github.com/athombv/homey/issues/387](url)

<img width="383" alt="screen shot 2016-04-30 at 11 59 01" src="https://cloud.githubusercontent.com/assets/18704157/14935251/01f04732-0ecb-11e6-8957-048d07dee688.png">

**Comment by ocatie** [comment] 2016-05-02 15:42
Could you reproduce the error and then send us a system log by pressing the Send Log button in Settings -> System. With the code that will popup I can acces the log.

**Comment by djefmo** [comment] 2016-05-03 12:58
Here the log number:
A6B63C347B

Until now, no error yet regarding the temperature sensor.

**Comment by ocatie** [comment] 2016-05-03 13:22
Fixed in 0.8.33

**Comment by djefmo** [comment] 2016-05-03 13:43
Great!

Now it also gave the temperature error: TRANSMIT_COMPLETE_NO_ACK
Reported under log number: FF6CBC5310

Or is this problem also fixed on 0.8.33? Thanks Taco!

**Comment by ocatie** [comment] 2016-05-03 14:04
No, thats a more generic error meaning the send command is not being acked by the device.

**Comment by djefmo** [comment] 2016-05-03 14:08
That I do understand, but that error must come from somewhere? Hope the error log solves this problem as well. 

PS. Is there any way to remove/recount the nodes in Homey? Every time I remove a device; I can't use that node number anymore. I only have two Z-wave devices, however, when I add a new device I'm already at node number 12.

**Comment by djefmo** [comment] 2016-05-03 14:11
<img width="1127" alt="screen shot 2016-05-03 at 16 10 42" src="https://cloud.githubusercontent.com/assets/18704157/14985855/a1247cee-1149-11e6-9f5b-6e77f23f6a79.png">

**Comment by ocatie** [comment] 2016-05-03 14:38
The node numbering is done by the sigma firmware, I have no control over that. The number doesn't impact Z-Wave stuff in any way.

**Comment by djefmo** [comment] 2016-05-22 16:15
With firmware 0.8.35 problem is partially solved; 
- The "Error: Sensortype not found" is solved
- However, when the sensor is placed in a different room than were the homey is, the error TRANSMIT_COMPLETE_NO_ACK still exists. This is probably due to the fact that the sensor is outside the Z-wave range? Although in the room where the sensor is placed, several Fibaro relay switches are placed as well. So, it should send and receive data via this powered module, right? 

Could it be that the 'signal hopping' through nodes is not working properly?

**Comment by djefmo** [comment] 2016-05-31 10:16
Taco?

**Comment by djefmo** [comment] 2016-05-31 10:17
@ocatie : any ideas yet?

**Comment by ocatie** [comment] 2016-06-03 09:07
The "hopping" is managed by the protocol so there shouldn't be any issues there. The TRANSMIT_COMPLETE_NO_ACK mostly indicates the device is out of range or switched off.

**Comment by djefmo** [comment] 2016-06-03 09:46
Are you sure the "hopping" works properly? Since I read many stories about the poor Z-wave range. The device isn't switched off, it's just placed in a different room than the Homey and right next to a Fibaro relay switch inside Homey's range. So it should connect to the humidity sensor! Is there any way to view the Z-wave signal structure?

**Comment by djeskoswe** [comment] 2016-06-13 20:20
Same with my tkb switch if i move it to far from homey but i the same room as another tkb switch that works,  i must agree the mesh "hopping" don't work ok.

**Comment by jeroenvollenbrock** [comment] 2016-07-27 14:56
duplicate of #457

**Closed by jeroenvollenbrock** 2016-07-27 14:56 UTC
Labels: waiting for user feedback, zwave, zwave - device specific
