### ISSUE TITLE
Fibaro motion sensor firmware 2.7 -> alarm wont go off

### ISSUE THREAD

**Issue by robintielemans** [athombv/homey#492] opened 2016-04-22 12:14 UTC
My homey is on firmware 0.29.

I already tried to add to association group 3. Put 1 at group 4. Alarm is constantly "on" and wont go off.

I have tried several setups. None worked for me. Does anyone have the same issue or knows how to make my motion sensor detect movement? luminance, temperature etc. works fine.

**Comment by Robinyoh** [comment] 2016-04-24 16:35
When i changed My homey to firmware 0.8.30 it worked with default settings.

**Comment by Robinyoh** [comment] 2016-04-24 17:00
My Fibaro motion is on firmware 2.6 ( is there a way to upgrade it trough homey?)
Homey on firmware 0.8.30

With default settings it is working with a timer of 30 seconds.
When i edit parameter 6 (default 30) to for example 15, alarm is constantly "on" and wont go off. Even if i change it back to 30. 
- I need to remove the node in zwave setting.
- I need to reset the motion detector with long press on B-button untill color change to yellow and then press 1 times short, color changes to red. 
- I need to add it again in devices and chose group 3. 
- Now it works again with default settings of 30 seconds.
![schermafbeelding 2016-04-24 om 18 58 40](https://cloud.githubusercontent.com/assets/18645811/14768959/b10a397a-0a4e-11e6-8e4b-c83b8a7d4cb5.png)

**Comment by robintielemans** [comment] 2016-04-24 18:54
I tried it, but still on "alarm on" 24/7. :(

**Comment by bvdbos** [comment] 2016-04-24 19:05
Could you follow this:
https://forum.athom.com/discussion/comment/18833/#Comment_18833
Does temperature and illuminance get send every two hours and is your alarm working (figuring out if there's a difference between 2.6 en 2.7 FW)

**Comment by robintielemans** [comment] 2016-04-24 19:56
My luminance and temperature is working fine. I had it working for a little while untill my alarm does not wanna go off again.

**Comment by Robinyoh** [comment] 2016-04-29 01:52
My motion (default 30sec) Lumiance and temp are working, only battery stays at 100%. Its brand new, so maybe its really at 100%.

https://forum.athom.com/discussion/comment/18833/#Comment_18833
When adding your motion sensor, add it in Association Group 3.
After your inclusion you can add any of the parameters, Except for 1 to 12.
These will "brick" your sensor in always alarm mode.

I got parameter 2 working, but 6 will "brick" my device.

Will this be fixed in next release firmware?

**Comment by ocatie** [comment] 2016-05-02 17:48
Both the tamper and motion alarm are mapped to the generic alarm in the device card. If either of those are true during the interview the generic alarm is on. It will turn off when a report of either the tamper alarm or the motion alarm off is received.

**Comment by Robinyoh** [comment] 2016-05-04 12:58
Hi Taco,

Thx for your response!

When i disable the tamper alarm, parameter 89, the generic alarm will go off in 30 seconds.
![schermafbeelding 2016-05-04 om 14 48 56](https://cloud.githubusercontent.com/assets/18645811/15014738/ff3d86fe-1207-11e6-9a9b-dd54215e3c2d.png)

When i edit parameter 6 to 20 seconds, the generic alarm won't go off anymore.
![schermafbeelding 2016-05-04 om 14 50 21](https://cloud.githubusercontent.com/assets/18645811/15014775/354d894c-1208-11e6-9d78-827a418685a6.png)

I use firmware 0.8.32 dutch voice and firmware fibaro motion 2.6 (what is written on the box)

**Comment by bvdbos** [comment] 2016-05-04 19:04
Did you read the link I posted and the comment you made yourself? 
"After your inclusion you can add any of the parameters, Except for 1 to 12." -> you set parameter 6, this "bricks" the sensor...

**Comment by Robinyoh** [comment] 2016-05-05 00:24
i know, so i asked when they think this will be fixed? because editing the alarm timer should be very helpfull, 30 seconds is in some setups to long.

**Comment by ocatie** [comment] 2016-05-06 11:05
I don't have the time to help with specific configuration values for every device unfortunately. I'll dig deeper in the configuration parameters when we start working on the Fibaro app. With the app your device will be completely plug&play.

**Comment by bvdbos** [comment] 2016-05-06 11:17
@ocatie The issue here is the setting of the parameters 1-12, you think this is a Fibaro-thing? I couldn't find anything on the internets about this?

**Comment by ocatie** [comment] 2016-05-06 11:45
I can't reproduce a crash on Homey by sending a parameter between 1 and 12 to a device. I see in the Z-Wave devtools that the configuration is send to the device, what the device does with it is up to the manufacturer.

Could you define what you mean by bricking the sensor?

**Comment by bvdbos** [comment] 2016-05-06 12:15
If sending parameter 1-12 (except 2?) the alarm stays on all the time: 
> These will "brick" your sensor in always alarm mode.

**Comment by ocatie** [comment] 2016-05-06 12:18
Then I think editing these settings changes what/how the device sends reports to Homey. Then Homey doesn't receive the frames on which it turns the alarm off anymore. Is this plausible? I didn't look up what these parameters edit in the device.

**Comment by bvdbos** [comment] 2016-05-06 12:24
http://manuals.fibaro.com/motion-sensor/
only parameter 12 changes something afaik... parameter 6 : 

> Motion alarm will be cancelled in the main controller and the associated devices after the period of time set in this parameter. Any motion detected during the cancellation delay time countdown will result in the countdown being restarted. In case of small values, below 10 seconds, the value of parameter 2 must be modified (PIR sensor’s “Blind Time”).
> 
> Available settings: 1-65535
> Default setting: 30 (30 seconds)
> Parameter size: 2 [bytes]

**Comment by Robinyoh** [comment] 2016-05-06 13:57
I did another test. 

editing parameter 1 2 3 4 8 9 and 12 won't brick the motion alarm to never go off. After 30 sec the generic alarm will go in off state. I just past it from the forum, my bad.

Did also a test with tamper alarm off and led signal mode to one time green to detect when motion is detected after timer runs to 0. (89,1,0;80,1,5)
This works with this setting. In the period of the 30 sec it won't blink, only resetting the timer and after the 30 sec generic alarm will go off and it wil blink again one time when motion is detected, generic alarm go on. 

When i add parameter 6 to it (89,1,0;80,1,5;6,2,20), the fibaro motion won't blink any more after 20sec or 30 for the test. Maybe it is set to it maximum? 65535 seconds.
I will test this but i have to wait 18 hours.

**Comment by Robinyoh** [comment] 2016-05-06 22:09
The alarm will go off after a couple of hours, but not in the specific seconds i programmed it in:

(89,1,0;80,1,5) 30 seconds timer default
Fri May 06 2016 15:26:10 GMT+0200 (CEST),true
Fri May 06 2016 15:26:40 GMT+0200 (CEST),false

(89,1,0;80,1,5;6,2,20) 20 seconds timer
Fri May 06 2016 19:30:06 GMT+0200 (CEST),true
Fri May 06 2016 21:04:05 GMT+0200 (CEST),false

(89,1,0;80,1,5;6,2,30) 30 seconds timer
Fri May 06 2016 21:06:57 GMT+0200 (CEST),true
Fri May 06 2016 23:15:44 GMT+0200 (CEST),false

(89,1,0;80,1,5;6,2,10;2,1,5) 10 seconds timer
Fri May 06 2016 23:23:27 GMT+0200 (CEST),true
Sat May 07 2016 00:07:10 GMT+0200 (CEST),false


It looks like homey sends the wrong timer settings in seconds.

**Comment by TedTolboom** [comment] 2016-05-07 06:07
@Robinyoh Good work!

I'm just thinking out loud... 
if this is the case at parameter 6... it could very well be that this is applicable for other (timing related) parameters... As example for parameter 42 (illumination reports), see #464 

I will see if I can do a similar experiment for parameter 42 (has to be very low values due to the stability of my Homey though)

**Comment by TedTolboom** [comment] 2016-05-07 08:45
Hmm... nice... 
First interval based on new settings: parameter 42 @ 30 seconds ... 
Sat May 07 2016 08:27:07 GMT+0200 (CEST),131
Sat May 07 2016 10:19:22 GMT+0200 (CEST),58

which equals: 6735 seconds (factor 224) 

I will follow-up (with more data points and settings) in #464

**Comment by ocatie** [comment] 2016-05-09 11:22
Fixed in 0.8.33. Thnx guys! Swapped the value bytes for size 2 and 4.

**Comment by Robinyoh** [comment] 2016-05-09 11:30
when will FW 0.8.33 be released?

**Comment by bvdbos** [comment] 2016-05-09 11:37
Slack may 6th : https://athomcommunity.slack.com/archives/general/p1462551316002079

**Comment by RoadXY** [comment] 2016-05-09 12:42
This week, somewhere.

**Comment by Robinyoh** [comment] 2016-05-09 14:11
Great, looking forward to it!

**Comment by Robinyoh** [comment] 2016-05-15 12:19
It working now!
Can set the timer for example to 10 seconds (6,2,10)
But only works when you edit the parameters in a flow.
![schermafbeelding 2016-05-15 om 14 15 42](https://cloud.githubusercontent.com/assets/18645811/15273943/cd93935c-1aa7-11e6-8214-8cd2bbf2cacc.png)

When i edit the device settings card i get this:
![schermafbeelding 2016-05-15 om 14 16 57](https://cloud.githubusercontent.com/assets/18645811/15273951/ea868bea-1aa7-11e6-8da5-8851019673eb.png)

**Comment by Robinyoh** [comment] 2016-05-17 10:23
We can close this issue i think? Don't know how to do that....

**Comment by ocatie** [comment] 2016-05-17 10:58
Could you send a log after this error message?

**Comment by Robinyoh** [comment] 2016-05-17 11:02
![schermafbeelding 2016-05-17 om 13 02 20](https://cloud.githubusercontent.com/assets/18645811/15320217/a57d7854-1c2f-11e6-92a3-67521337aa6e.png)

**Comment by Robinyoh** [comment] 2016-05-21 17:16
working now without an error in 0.8.35, you can close this issue. Thx great job!

**Closed** 2016-05-23 11:29 UTC
Labels: waiting for user feedback, zwave, zwave - device specific
