### ISSUE TITLE
[com.ikea.tradfri] Problem with IKEA Rotating Dimmer

### ISSUE THREAD

**Issue by igitlin** [athombv/homey#2749] opened 2018-08-09 19:47 UTC
There is a problem with the operation of the IKEA dimmer - there is no smooth adjustment.
If you create Flow from a dimmer and a Philips Hue bulb, the brightness is adjusted with great delay and jumps. I try to edit dimmer sensitivity, but will achieve smooth adjustment and could not.
With the direct connection of the dimmer to the lamp, the adjustment is smooth and without delay.

**Metadata**

* **Homey Version**: 1.5.12
* **Homey Log Code**: 96832EAD50
* **Smartphone Platform**: iOS
* **Smartphone App Version**: 

**If related to a Homey App:** IKEA Tradfri
* **Homey App Version**: v1.2.2
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: IKEA Rotating Dimmer

**What did you try to achieve?**
I try to edit dimmer sensitivity

**What did you expect as result?**
will achieve smooth adjustment and could not

**What was the result?**
there is no smooth adjustment

**Any other remarks**

**Comment by Dijker** [comment] 2018-08-09 20:09
I guess this is the same issue as in #2561

**Comment by RobinBol** [comment] 2018-08-13 12:30
Closing as duplicate of https://github.com/athombv/homey/issues/2561

**Closed by RobinBol** 2018-08-13 12:30 UTC
Labels: Athom App
