### ISSUE TITLE
Voicecommand "dim licht in Woonkamer naar 50%" is not dimming Hue lights

### ISSUE THREAD

**Issue by SailingDuck** [athombv/homey#1524] opened 2017-05-03 08:51 UTC
**What is your Homey version (Settings → System)?**

1.2.2 / Philips Hue app v2.2.4

**What did you try to achieve?**

Tried dimming the lights to a percentage with the new voice commands. 

*Please include detailed steps how we can reproduce the issue*

Say: "dim licht in Woonkamer naar 50%"

**What was the result?**

Homey responding: "Ik kon geen dimbare lampen vinden in de woonkamer"

**What did you expect as result?**

Homey dimming lights to 50%

**Any other remarks**

- Lights are dimmable because "Dim hue spot 1 naar 50%" is working. But this means I have to repeat it 
three times because I have three hue spots (hue spot 1, hue spot 2, hue spot 3). 
- Exaxt zonename is "Woonkamer" right below the master zone "Thuis"

**Please attach a Homey System log (Settings -> System -> Send Log)**

2E46D580BF

**Comment by Tweake** [comment] 2017-05-11 10:17
Thanks for reporting the issue. Could you please post a screenshot of all devices in the _woonkamer_ so I can better understand what might be causing the issue? Thank you

**Comment by SailingDuck** [comment] 2017-05-11 15:04
Here it is. 
![](https://i.imgur.com/74Hqqu2.png)

**Comment by ajterpstra** [comment] 2017-05-20 10:32
Had the same problem, I found Kodi and Chromecast in the room. Moves these 2 to somewhere else and the problem was resolved with me.
The App causes something that does not work anymore

**Comment by Tweake** [comment] 2017-05-22 13:04
Thanks for posting the screenshot. The issue is occurring because you have a device named "woonkamer" which is not a light. 

Device names are prioritised over Zone names. When Homey detects a device name it only focusses on that device and ignores all other devices in the Zone with the same or similar name.

Let's say you currently have some lights in the Zone "living room" and a Chromecast also named "living room". When you say "turn on the light in the living room" Homey detects a device name 'thinks' I should turn on the light of this specific device which was mentioned. After Homey starts switching on the light of your Chromecast it realises that this is not possible. So, no lights end up switching.

To prevent this from happening, from version 1.2.0 on Homey will give a warning when you rename a device to something which conflicts with a Zone name. Previously added devices are not checked though, which is why you are experiencing this issue. 

Renaming the Chromecast will resolve your issue.

**Comment by SailingDuck** [comment] 2017-05-22 13:44
Ah, thanks for clarifying. It's working now!

**Closed** 2017-06-21 09:52 UTC
Labels: speech-input
