### ISSUE TITLE
Speech input vs microphone flow card comparison is capital sensitive [ 0.8.17]

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#211] opened 2016-02-17 22:25 UTC
When I enter into the microphone flow card "Good night" (leaving the living room to turn of all lights), Homey does not respond.

When checking /manager/speech-input/, Homey correctly shows "good night"

If I change the text entered in the microphone flow card to "good night", Homey starts listening and acting upon it...

I would suggest to make a change to convert the text entered in the microphone flow card to small caps, similar to speech-input does.

Additional question, how is interpunction treated (?, etc); adding a "," will break the microphone flow card?

**Comment by bvdbos** [comment] 2016-02-18 04:46
If this is true it might well be a big issue with an easy fix... I'd say take it asap.... all strings to lower :+1:

**Comment by KroontjesPen** [comment] 2016-02-18 07:41
Before bricking "Good night" was working very well. Even the , and . in a sentences.
The unbricking is this evening so I can checked later of if it is still that way.

**Comment by HiemstraJ** [comment] 2016-02-18 07:55
This issue is the same as #180, fixed in .18

**Comment by bvdbos** [comment] 2016-02-18 07:58
I knew it was somewhere. Searching for "capital" didn't reveal it. Github Search doesn't include the titel of the issue...

**Comment by TedTolboom** [comment] 2016-02-18 08:58
I searched with several keywords at both GitHub / Athom forum... to check
if it is a known issue.
I was not aware that Github Search does not include the title of the issue

It would be helpful (already mentioned several times) though if a list of
known issues is tracked / maintained by Athom (including what will be
solved in which software release.

This would reduce these type of duplicate issue...

On Thu, Feb 18, 2016 at 8:58 AM, Bas van den Bosch <notifications@github.com

**Comment by WeeJeWel** [comment] 2016-02-18 13:27
Duplicate of #180

**Closed by WeeJeWel** 2016-02-18 13:27 UTC
