### ISSUE TITLE
KAKU socket designated as a fan

### ISSUE THREAD

**Issue by Fiek1** [athombv/homey#721] opened 2016-07-13 17:45 UTC
**What is your Homey version (Settings → System)?**

x.x.x
0.8.39

**What did you try to achieve?**
Making a flow with a KAKU socket designated as a fan

*Please include detailed steps how we can reproduce the issue*
I added a KAKU socket and designated it as a fan. When you go tot the flow editor this device is not listed in the available devices. I tried adding several times.

**What was the result?**
I can't choose the socket designated as a fan. 
...

**What did you expect as result?**
The socket designated as a fan available in the flow editor
...

**Any other remarks**

When I add the wall socket again and choose the option 'iets anders', then it's visible in the flow editor.

**Comment by Fiek1** [comment] 2016-07-22 19:47
Still not working with the latest version

**Comment by jeroenvollenbrock** [comment] 2016-07-27 16:04
duplicate of #433

**Closed by jeroenvollenbrock** 2016-07-27 16:04 UTC
