### ISSUE TITLE
[nl.eneco.toon] No Control on Toon only View Information

### ISSUE THREAD

**Issue by Jaapie123** [athombv/homey#2306] opened 2018-03-08 17:57 UTC
**Metadata**

* **Homey Version**: 1.5.7
* **Homey Log Code**: E4D98AE3CC
* **Smartphone Platform**: Android
* **Smartphone App Version**: BETA

**If related to a Homey App:**
* **Homey App Version**: 1.3.3
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: 

**What did you try to achieve?**

I can connect the Toon but Can't Control them. Every change on Toon i cant see But i Cant Change Toon with Homey.

**What did you expect as result?**

Change Temparature

**What was the result?**

No Change and on Android error: Someting went Wrong Addressing Device Toon (timeout 5000ms

**Any other remarks**

**Comment by bvdbos** [comment] 2018-03-08 19:59
duplicate of #2279 #2293 and #2271. Please use the searchbox next time and close this issue... Something seems to have changed at Toon's side and Athom is working on it. Meanwhile I've seen people who created a workaround on the forum.

**Comment by jeroenvollenbrock** [comment] 2018-03-12 10:57
Duplicate of #2293

**Closed by jeroenvollenbrock** 2018-03-12 10:57 UTC
