### ISSUE TITLE
Homey goes offline when it is configured

### ISSUE THREAD

**Issue by Eternity-again** [athombv/homey#1892] opened 2017-10-14 11:56 UTC
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**

Yesterday I had to remove 2 motion z-wave sensors, so:
Removing a device 
- open the settings page of z-wave
- click on remove
- interact with the sensor
- homey reports that the device was succesfully removed
- **homey goes offline....sometimes 5 minutes**
- homey comes online after a couple of minutes

Inclusing the sensor
- go to the devices page
- click on the + to add a devce
- select the App (Aeotec in my case)
- start the inclusion
- node found and inclsusion starts
- homey goes offline......
- **homey comes online after a couple of minutes**
- devices is added correctly

Install App
- Select from the App store
- start installation
- homey goes offline......
- **homey comes online after a couple of minutes**
- App is added correctly

So, the problem is not that it doesn't work. The problem is that removing and adding a devices that 15 minutes, because I have to wait till Homey is reachable again.

If Homey is just controlling my stuff, it is fast and works flawlessly! N delays, no hanging, fast response via the web and app (2x) interface. It is just during adding / removing / installing stuff that Homey keeps going offline. Seems as if Homey can't keep up with the requests (lack of memory / cpu). I have 30 Apps installed and this is the memory situation:

*Please include detailed steps how we can reproduce the issue*
Install an App / remove and re-include a z-wave device

**What was the result?**

**What did you expect as result?**
I hoped to see Homey respond swiftly to any configuration change, and stay online!

**Any other remarks**
I have 30 Apps installed
storage 870mb free of 1,64 gb
memory 512 free, swap 335mb

**Please attach a Homey System log (Settings -> System -> Send Log)**

6407EF0386

**Comment by jeroenvollenbrock** [comment] 2017-10-26 15:11
Duplicate of #1815

**Closed by jeroenvollenbrock** 2017-10-26 15:11 UTC
Labels: bug, Homey Core, Native
