### ISSUE TITLE
Chromecast Ultra support

### ISSUE THREAD

**Issue by LyoshaDovolen** [athombv/homey#2347] opened 2018-03-19 10:48 UTC
Please add Chromecast Ultra support.
https://store.google.com/gb/product/chromecast_ultra?hl=en-GB

**Comment by jeroenvollenbrock** [comment] 2018-03-19 11:00
Closing as duplicate of https://github.com/athombv/com.google.chromecast/issues/46

**Closed by jeroenvollenbrock** 2018-03-19 11:00 UTC
