### ISSUE TITLE
[com.fibaro] FGD-212 (Dimmer 2) does not update onoff state correctly

### ISSUE THREAD

**Issue by robiebab** [athombv/homey#1522] opened 2017-05-02 16:36 UTC
**What is your Homey version (Settings → System)?**

1.2.2
Fibaro dimmer 2

**What did you try to achieve?**
turn off the lights

**What was the result?**
1 dimmer stayed on and homey gives the status off

**What did you expect as result?**
the lights went off and homey gives the status off

node 76  had this problem today, see attachment.

[BUG.txt](https://github.com/athombv/homey/files/971118/BUG.txt)

**Comment by WeeJeWel** [comment] 2017-05-10 10:09
Can you please describe how you were trying to switch the dimmer? And does it work manually from the Zones & Devices overview?

**Comment by robiebab** [comment] 2017-05-10 10:15
I used a flow to trigger the lights to turn off. To give the dimmer the correct status again, i needed to switch it on/off again to give homey the correct status. This problem occures sometimes

**Comment by SkorpionNL** [comment] 2017-05-10 14:13
I do have this issue regularly with the Fibaro Dimmer 2 (I own multiple dimmers). I always use the flow card "set brightness to X" and Set brightness to 0 to turn it off.

**Comment by RobinBol** [comment] 2017-11-20 15:37
@robiebab can you explain more clearly what the problem is? Is the Dimmer 2 not turning off when you use a Flow to turn it off? Or is the Dimmer 2 turning off when you use a Flow to turn it off but the mobile card still shows it is turned on? Could you also answer Emile's question regarding the controlling from the Zones & Devices overview, does this work as expected? What do you mean with 'giving Homey the correct status'?

@SkorpionNL using the dim Flow cards should also update the `onoff` state of the device, did you try to refresh the Homey desktop interface? Maybe the realtime event did not update the mobile card correctly. Does this also happen with the new smartphone app?

**Comment by SkorpionNL** [comment] 2017-11-20 16:06
@RobinBol : switching the dimmer on/off always worked for me when turning on/off and dimming to 0% in the app or OS X interface or via flow. This problem in my opinion has to do with a congested Z-wave queue or something. It sends the off command to the dimmer. The dimmer gets the status “off” but it doesn’t actually turn off the light. It was solved for me, but it is back again since FW 1.5.

**Comment by WeeJeWel** [comment] 2017-12-01 14:10
Duplicate of #1899 (and should therefore be fixed in 1.5.6)

**Closed by WeeJeWel** 2017-12-01 14:10 UTC
Labels: Athom App, bug, waiting for user feedback, Z-Wave
