### ISSUE TITLE
433 microcontroller issue

### ISSUE THREAD

**Issue by sleutelsnet** [athombv/homey#2882] opened 2018-10-17 16:45 UTC
As my 433 signals are not getting through, I tried resetting the controller via:
https://developer.athom.com/tools/signals

Which yielded the error:
invalid_manager_id: microcontroller

Homey Firmware Versie: 1.5.13-rc.11

**Comment by Dijker** [comment] 2018-10-17 20:43
duplicate of #2851 and expected as the button will be removed when .13 is stable.
(it often didn't work anyway and needed a PtP)

**Comment by KyleAthom** [comment] 2018-10-18 14:34
Exactly like mentioned in #2851 , this is intended and the button will be removed in the future.

**Closed by KyleAthom** 2018-10-18 14:34 UTC
