### ISSUE TITLE
KaKu Asun 650: Use of square button can be a safety hazard  

### ISSUE THREAD

**Issue by KroontjesPen** [athombv/homey#218] opened 2016-02-19 14:50 UTC
Homey 0.8.17 -  KaKu 0.1.13

Often by pushing the square button the Asun 650 don't stop.
This is in both directions but unpredictable. When used for a garage door it becomes a safety hazard.  
Because of the way the Asun 650 is working the square button can be omitted.

**Comment by Dijker** [comment] 2016-02-19 15:44
guess you didn't read the dutch manual of the Asun 650? ;-) 

http://www.klikaanklikuit.nl/shop/nl/fileuploader/download/download/?d=0&file=custom%2Fupload%2FFile-1420187323.pdf 

WAAR MOET U OP LETTEN? [...]
•	Dit product is niet bedoeld voor het openen en sluiten van (garage)deuren. 
(This product is not intended for the opening and closing of (garage) doors.)

Indirect control/use of mechanical equipment (like doors opening or closing) will always be a safety hazard, use a door with pinch protection and use it as intended. 

But maybe they can still optimize the square button for use with sunscreens! :-)

**Comment by KroontjesPen** [comment] 2016-02-19 16:14
By focusing more on that potential free contact than on having a garage door, I have not looking if it was advisable to do that.
But also for a sunshade it is not safe to rely on that square button.

**Comment by athomey** [comment] 2016-02-19 17:43
How is this a Homey bug?

**Comment by KroontjesPen** [comment] 2016-02-19 18:06
Sorry, drop the case. 
Only no idea where you put things like this then.

**Comment by Dijker** [comment] 2016-02-19 18:36
No problem Theo,
don't know about where to put the problem about the safety hazard ;-) 

We can ask Athombv if the unpredictable stop button is a Homey problem, Kaku App problem or just a Kaku Asun 650 issue  (radio interference etc.) 

Do you have the problem if you use the default Kaku remote?

I will buy two Asun 650's for my own and test what I can see. 
I like to stop the sunscreen half way, so I will test it.

If you want to drop the case you can close it yourself or wait and maybe rename the title?
something like: 
KaKu Asun 650: Binds - Square / stop button not working predictable

Maybe Athombv will answer and they will close it.

**Comment by KroontjesPen** [comment] 2016-02-19 18:47
The Asun 650 is normally used with a wall switch or remote on/off. 
For my sunshade: On is ↓(make shade) Off is ↑(no shade). 
To stop halfway you press the same button again.
So an unpredictable square button is not needed.

**Comment by Dennishacq** [comment] 2016-02-19 20:00
After doing some tests here it seems that the KlikAanKlikUit app is working and all the correct signals are transmitted. Could you give us more information to help us reproduce the problem?
As mentioned by Dijker: It's really unwise to use the ASUN-650 for your garage door. This makes it very easy for burglars to enter your home.

**Comment by KroontjesPen** [comment] 2016-02-19 20:40
To test with an sunscreen you have to be careful not to overhead the motor.
For testing I used the device on the devices page.
Then a sequence of button with sometime 2x the square button in a row.
Suddenly the square button is not reacting anymore. 
If you have an temporary object in your garden and don't want to lower your sunshade to low DON'T use the square button. 

It is not possible to send a other signal then an On or Off.  
An On after an On gives Stop. Idem with an Off after an Off.
What you the square button can sending I rely don't no.

**Comment by KroontjesPen** [comment] 2016-02-19 22:03
For info.
The On and Off commands are broken off by the ASUN-650 after two minutes. 
Therefor sunshade or other motor device has needed end switches in both directions.

**Comment by Dijker** [comment] 2016-02-19 22:46
@KroontjesPen 
Thats correct, as designed: The ASUN650 switches 2 min "Up" or 2 min "Down" and returns to NC after that. So because your UP is black I think your garage door is open ;-)
Most sunscreens I have seen  stop at the end (up or down) automatically. 
The will be ON max 2 minutes extra from where ASUN650 switches off.

Did you manage to create a flow with the blinds card?  
(see other issue, I don't see the blinds cards from KAKU.)

**Comment by KroontjesPen** [comment] 2016-02-20 07:21
@Dijker 
In the manual on page 9, 12 and 14 you can see that there is no place to connect or used a square button. So that "correct, as designed" I can't follow. Specially when its behavior is not trustfully. 
The problem is that this button is also on the Android app and can be used unwillingly. 

What you mean by this: "_The will be ON max 2 minutes extra from where ASUN650 switches off._" is not clear to me.

In the thread "Blinds KaKu", not be able to put this device in a flow, I have already reacted that I conforming that.

**Comment by Dijker** [comment] 2016-02-20 08:16
@KroontjesPen 
Sorry, 
Something was missing:
The Blinds/screen/device  will be ON (powered)  max 2 minutes (extra from the start) whereafter the  ASUN650 switches off. (Not Connected  = Not Powered)
imho:  as designed  for the ASUN 650

**Comment by Dennishacq** [comment] 2016-02-20 12:49
@KroontjesPen 
Maybe this helps to explain how my driver works:
![image](https://cloud.githubusercontent.com/assets/15836768/13196775/b35080c0-d7d8-11e5-9b4e-c278c1e3cff9.png)

**Comment by KroontjesPen** [comment] 2016-02-20 14:08
Because of weather conditions is further testing not possible.
For myself I delete this device because it not save on the Android app. 

Lets wait and see of accidents happens with sunshade go's lower than you temporary want to and the **square button didn't stop** it.

**Comment by Dijker** [comment] 2016-02-21 00:14
Bad weather so I had time for testing ;-) 

@Dennishacq 
I think the Stop button is not a good idea as the working is unpredictable as I can confirm. I agree with @KroontjesPen 

Technical you are right, Sending an ON after a ON and a OFF after an OFF  resets the ASUN650 to NC. Sending an ON or OFF once switches the ASUN650  for 120 seconds (mine 125 sec.) where after it resets to NC.

I think KAKU sends (to overcome interference of signals not detected at the receiver) the signal more than once at the press of a button. 
The ASUN650  switches to Up or Down on first received signal and ignores repeating signals for until approx 2 seconds no repeating signal is received. This is how KAKU and specially the ASUN650 works, also with its own remote.

I created two flows with a paired KAKU switch card to a ASUN650  with LED indicators. 
on trigger - ASUN650  ON - 3 seconds - ASUN650  ON 
on trigger - ASUN650  OFF - 3 seconds - ASUN650  OFF 

Both work fine, 
If I lower the time between to 2 seconds between switching it no longer works, the second signal is ignored.

I think a button on the card that doesn't always work as expected is annoying for consumers.
Let them use it the way KAKU uses it by pressing it on the device card in the app twice (with enough time in between)

As a Feature request:
I would like a flowcard with four options:
- UP (once)
- Down (once)
- UP (3 - 110 seconds)
- Down (3 - 110 seconds)

That will safe a second card on flows, we like the screen approx. 14 seconds down ;-)
If possible: 
- Prevent Homey sending the same signal within 3 seconds as this does not work.
- IF the Up is send before a trigered card Down-100seconds finishes you should terminate the Down-100seconds card. (and vice versa)

That will not make it foolproof as an other paired KAKU remote can change the state of the ASUN650 if someone messes around and Homey will never know ;(

Video time? 
https://www.youtube.com/watch?v=7lNr55HpZDA

**Comment by KroontjesPen** [comment] 2016-02-21 07:03
Thanks @Dijker for finding the reason why the square button acting this way. :+1: 

(Let sunshade down by wind force 8, I need curtain some repairing aid.) ;-)

**Comment by BasKiers** [comment] 2016-09-06 18:59
Since KaKu 2.2.1 I've tried to implement the stop button. It should work but there are situations in which you can deliberately mess up the state which should not happen in normal use.

**Closed** 2016-09-19 12:09 UTC
Labels: Athom App, bug, Devices, interface, RF
