### ISSUE TITLE
Hue light doesn't switch off

### ISSUE THREAD

**Issue by Fiek1** [athombv/homey#1307] opened 2017-02-04 18:37 UTC
**What is your Homey version (Settings → System)?**

1.1.4

**What did you try to achieve?**
Automatic switch off Hue hall lamp

*Please include detailed steps how we can reproduce the issue*
I made a flow when Hue hall lamp is switched on, it switches off with a delay of 60 seconds

**What was the result?**
Doenst work since latest firmware update and hue update

**What did you expect as result?**
automatic switch off
![image](https://cloud.githubusercontent.com/assets/18599711/22620686/624785b4-eb11-11e6-83d1-2ed00b552820.png)

**Comment by Rocodamelshe** [comment] 2017-02-07 18:35
Sounds like [https://github.com/athombv/homey/issues/1293](url)

**Comment by WeeJeWel** [comment] 2017-02-13 13:01
Duplicate of #1293

**Closed by WeeJeWel** 2017-02-13 13:01 UTC
Labels: Athom App
