### ISSUE TITLE
[nl.klikaanklikuit] I´m on fw 1.5.8. My doorbell hasn´t worked for several weeks. Nor have my temperature device or wall plug. No 433-units are working. Is that a applikation issue or homey-issue? I have tried restarting.

### ISSUE THREAD

**Issue by danieljonasson123** [athombv/homey#2332] opened 2018-03-14 12:38 UTC
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by bvdbos** [comment] 2018-03-14 12:43
Please use the search-function first, type text in the message and fill in the data asked. But for this case, there is already an issue:
https://github.com/athombv/homey/issues/2023
Receiving 433 signals is problematic on 1.5.6 and later. Your wallplug should work though, did you try a PTP (pull the plug).

**Comment by danieljonasson123** [comment] 2018-03-14 12:46
Got it. Thanks!

**Comment by danieljonasson123** [comment] 2018-03-15 07:56
Put the cord for ten minutes. Only managed to check one unit and it´s working now. I think my other devices will work also now.

**Comment by Dijker** [comment] 2018-03-15 08:13
@danieljonasson123 Thanks, 
you can Close this issue yourself now with the button  below. 
and follow the other Issue mentioned by bvdbos. 
(on 433 issue's always first PTP)

**Comment by jeroenvollenbrock** [comment] 2018-03-19 10:48
Closing as duplicate of #2023

**Closed by jeroenvollenbrock** 2018-03-19 10:48 UTC
