### ISSUE TITLE
ThermoSmart - RESUME does not work correctly.

### ISSUE THREAD

**Issue by Eternity-again** [athombv/homey#2901] opened 2018-10-30 15:31 UTC
**Metadata**

* **Homey Version**:Homey Firmware Versie: 1.5.13-rc.11
* **Homey Log Code**:98D08DECD3
* **Smartphone Platform**: Android Oreo
* **Smartphone App Version**: Beta

**If related to a Homey App:**ThermoSmart
* **Homey App Version**:v2.0.4
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

In a flow I let Homey increase the SET temperature with 2 degrees. After a condition is met, I want Homey to RESUME the ThermoSmart program. So, it will drop with 2 degrees, or even lower if it has become night and a new scheduled temp is activated in the ThermoSmart web settings.

**What did you expect as result?**

RESUME will follow the temperature schedule as programmed/defined in the ThermoSmart webpage.

**What was the result?**

The ThermoSmart webpage shows that the schedule is resumed, BUT Homey does not update the temperature. In my case the value remains at the increased value.

**Any other remarks**
The ThermoSmart action card shows a spinning icon and it stays that way:
<img width="340" alt="schermafbeelding 2018-10-30 om 15 27 49" src="https://user-images.githubusercontent.com/10754229/47729880-486f6b00-dc61-11e8-8268-0dbda73b6d63.png">

See: https://github.com/athombv/homey/issues/2900 1

**Comment by jeroenvollenbrock** [comment] 2018-10-30 17:35
Closing as duplicate of #2900

**Closed by jeroenvollenbrock** 2018-10-30 17:35 UTC
