### ISSUE TITLE
Speech stutters.

### ISSUE THREAD

**Issue by Povlov** [athombv/homey#1627] opened 2017-06-13 11:20 UTC
**What is your Homey version (Settings → System)?**

1.2.2
**What did you try to achieve?**
Have Homey speak.
Generally, my Homey is performing less reliable, less satisfying.

*Please include detailed steps how we can reproduce the issue*
Use speech cards to make homey announce things

**What was the result?**
Speech is produced fragmented (intervals of 1 sec. silence) , and sometimes sturrering te-te-te-te-temperature...
...

**What did you expect as result?**
Speech as it used to be with the very same flows. Fluent and not interrupted.
...

**Any other remarks**
Strange error btw when trying to produce log code!
...

**Please attach a Homey System log (Settings -> System -> Send Log)**
None available.
![screenshot 2017-06-13 at 13 16 26](https://user-images.githubusercontent.com/24312420/27080124-d90544dc-503a-11e7-8c1c-e6a297f70be5.png)

...

**Comment by bvdbos** [comment] 2017-06-13 11:29
duplicate of #1624 or #1297. Probably a reboot will fix this as this is probably a memory-issue...

**Comment by jeroenvollenbrock** [comment] 2017-06-14 12:36
How many apps do you have installed? (settings->apps)

**Comment by Povlov** [comment] 2017-06-14 17:46
Just updated to 1.3.1, so this is the readout:  
Door het aantal geïnstalleerde apps (28), kan Homey in sommige gevallen minder snel zijn.

I just might need to give up a few toys (Action doorbell, ledring collection, candy) ?

**Comment by jaimevisser** [comment] 2017-06-15 11:24
Even when not going above the app amount warning limit my homey has trouble outputting speech without interruptions (even with rather short sentences).

**Comment by Veldkornet** [comment] 2017-06-16 11:19
I have the same issue, not always, but about 70% of the time. Is there not a memory leak or something?

Log: FD8414BFE4

![image](https://user-images.githubusercontent.com/10297361/27224603-57aa2f02-5296-11e7-81cf-0666d8f899d7.png)

**Comment by jeroenvollenbrock** [comment] 2017-07-12 15:37
This is caused by, and therefore a duplicate of #1195

**Closed by jeroenvollenbrock** 2017-07-12 15:37 UTC
