### ISSUE TITLE
Location not workin iOS11

### ISSUE THREAD

**Issue by gldrenthe89** [athombv/homey#1824] opened 2017-09-18 14:11 UTC
After installing iOS 11 and having the latest Homey app (TestFlight version) location is stil not working. 
Any update on a fix. Almost al flows rely on this. Homey is now a nice multi color LED light and not a smart system anymore

**Comment by bvdbos** [comment] 2017-09-18 15:54
Dupe of #1683 ?

**Comment by gldrenthe89** [comment] 2017-09-18 16:44
Yes, Correct. 
This issue can be closed/deleted

**Comment by Inversion-NL** [comment] 2017-09-20 18:25
Only the guys from Athom and you can close the issue @gldrenthe89 ;-)

**Closed** 2017-09-21 17:09 UTC
