### ISSUE TITLE
[AppV2] Feature Request: iOS custom notification sound

### ISSUE THREAD

**Issue by Refl0w** [athombv/homey#1900] opened 2017-10-18 13:54 UTC
**What is your Homey version (Settings → System)?**

1.5.3

**Any other remarks**

Already requested this feature in the begin stage of the old app. Please give iOS users the option to select custom push notification sounds in the flows/app. 

I.E.

- Doorbell push notification **->** Ring ring
- Camera push notification **->** Snapshot sound
- Alarm push notification `->` Alarm sirene

I know homewizard has this feature, would be awesome if Homey can add this as well! Since iOS users can't add custom sounds for certain apps, and needs to be choosen within the app, if the app supports this feature.

**Comment by bvdbos** [comment] 2017-11-13 17:08
see also #1632

**Comment by WeeJeWel** [comment] 2017-11-20 16:56
Duplicate of #1632

**Closed by WeeJeWel** 2017-11-20 16:56 UTC
Labels: enhancement, Homey Core, Homey Smartphone App (Core)
