### ISSUE TITLE
0.8.17 : Flow editor doesn't allow scrolling vertically (0.8.20 still an issue)

### ISSUE THREAD

**Issue by ralfvd** [athombv/homey#200] opened 2016-02-16 16:06 UTC
If I have a lot of cards in the 'then' column, the flow editor doesn't scroll.  E.g. in attached screenshot, the "Animate" card isn't completely visible. 
![screen shot 2016-02-16 at 17 04 34](https://cloud.githubusercontent.com/assets/17275712/13082081/6824c342-d4cf-11e5-8716-7823ce892448.png)

Browser is on maximum size of my window. 

There is a horizontal scroll, but vertical scrolling seems to be disabled.

**Comment by Dijker** [comment] 2016-02-16 21:52
I can confirm this problem, vertical scrolling seems to be disabled.
also if you have more flows than fit on your screen this is a problem! 
(window for screenshot re-sized, but also happens at 1920x1080, you need a couple of flows more...)

![image](https://cloud.githubusercontent.com/assets/12412734/13092336/ad7ef194-d4ff-11e5-966a-1a7237818237.png)

**Comment by KroontjesPen** [comment] 2016-02-16 21:54
If I remember well it was also for the ...and... column. Maximum 13 cards it was.

**Comment by WeeJeWel** [comment] 2016-02-17 11:04
In 0.8.18, the columns have scrollbars as well. :-)

The flow list will be updated soon!

**Comment by ralfvd** [comment] 2016-02-26 11:06
0.8.20 ; still an issue . No vertical scrollbar in the 'then' column

**Comment by Arjanvde** [comment] 2016-02-28 10:25
X2 having the same issue as well.

**Comment by WeeJeWel** [comment] 2016-02-29 18:19
Partially fixed in 0.8.21. Scrolling works better, argument helper elements (e.g. color, autocomplete) cards at the bottom might still be hidden.

**Comment by Rob-Houweling** [comment] 2016-05-26 20:00
0.8.25 still a lot of issues with scrolling on Android device using chrome. 
Can't view all insights for instance. Scrolling in the left column of the flow results in dragging the action items. No scrolling in left column of settings page.

**Comment by WeeJeWel** [comment] 2016-11-01 10:52
Fixed in 0.10.7

**Closed by WeeJeWel** 2016-11-01 10:52 UTC
Labels: bug, Flow, Homey Core, interface
