### ISSUE TITLE
Scrollbar 'then' column doesn't go to top, many-device flows UN-editable (showstopper) [0.8.24]

### ISSUE THREAD

**Issue by athomey** [athombv/homey#383] opened 2016-03-29 12:05 UTC
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

I wanted a flow to switch on about 14 Hue lights in my living room, so I have to add 28 device-cards in a flow, because brightness and color are seperate cards (why two cards, why ow why, but that's for another topic!?).

**What was the result?**

I got an unusable list of 24 devices in the "then" column, which if I try to scroll to the top of the list (mouse and PgUp both same problem), I miss about 10+ devices which I cannot scroll to.

**What did you expect as result?**

That I could use Homey to switch on 14 lights in my living room, but that doesn't work.

**Any other remarks**

I'm using Google Chrome 49. 

OFF-TOPIC >>> It's also a horrible experience in Homey setting 14 lights to the same color. Nowhere you can edit the HTML color directly, or (what would even be better) support Hue groups, like other Hue apps and Domotica solutions. Homey is the only one I know that does every light seperately (not talking about scenes, talking about groups, see https://forum.athom.com/discussion/719/request-support-for-philips-hue-groups-like-veraedge-and-hue-apps-support-0-8-17#latest))  <<< OFF-TOPIC

![image](https://cloud.githubusercontent.com/assets/16608801/14107211/ff25d418-f5b6-11e5-8a92-cdd9c17fc7fc.png)

**Comment by Arjanvde** [comment] 2016-03-29 12:29
Alignment issue, i mentioned it on #314

**Comment by athomey** [comment] 2016-03-29 13:29
@Arjanvde Thank you for the reference to the other/same issue. however the workaround metioned there of zooming as a workaround doesn't work for 20 cards, then it still is unworkable/unreachable.

**Comment by jghaanstra** [comment] 2016-03-29 16:44
I posted a Stylish script on the forum which can act as a temporary workaround for this issue.

https://forum.athom.com/discussion/1011/simple-stylish-script-to-fix-some-ui-issues

**Comment by jeroenvollenbrock** [comment] 2016-07-27 13:03
Duplicate of #200

**Closed by jeroenvollenbrock** 2016-07-27 13:03 UTC
