### ISSUE TITLE
[com.google.chromecast] Cannot cast Swedish State Radio

### ISSUE THREAD

**Issue by emsa23** [athombv/homey#2026] opened 2017-12-06 22:53 UTC
Cannot cast Swedish Radio Such as "P4 Stockholm" to Chromecast (not Cromecast Audio haven't tried) the screen shows radio station logo and load bar but then fails, the flowcard also shows failure.

**Comment by Dijker** [comment] 2017-12-06 23:14
Which flowcard do you use? and what URL you send to the Chromecast?

**Comment by bvdbos** [comment] 2017-12-07 05:30
using the url's from
http://sverigesradio.se/sida/artikel.aspx?programid=3756&artikel=3771842
won't work, that's m3u-files. It's simple text-files, they contain an URL to the real stream, like
http://http-live.sr.se/srextra17-mp3-192
works on the radio-app and on the chromecat-device using "cast a video-URL" and "cast a website".

**Comment by emsa23** [comment] 2017-12-07 09:07
Have not tried various urls - this is for the Radio flowcard where you indeed get a match for "P4 Stockholm" but with failure as above.

**Comment by bvdbos** [comment] 2017-12-07 10:23
Then it's a dupe of #1808 but for both: you can't use the cast a radio-station as the station is not in the predefined list of stations. @BasKiers, could you carify that card, "choose station" as a title or something like that?

**Comment by emsa23** [comment] 2017-12-07 11:14
Ok, but what do you mean by "predefined"? It does pop up in the list when you search?

**Comment by jeroenvollenbrock** [comment] 2017-12-07 13:56
Closing as duplicate of #1808

**Closed by jeroenvollenbrock** 2017-12-07 13:56 UTC
