### ISSUE TITLE
Device Cards Position not saved

### ISSUE THREAD

**Issue by mike9011** [athombv/homey#1028] opened 2016-10-21 10:02 UTC
**What is your Homey version (Settings → System)?**

0.10.7

**What did you try to achieve?**

Try to drag and move device cards to another place in the same zone.

_Please include detailed steps how we can reproduce the issue_

Drag a devie to another position between other device cards, the position is not being saved.

**What was the result?**

After a refresh of the page, the device card is on the place it was before.

**What did you expect as result?**

The position of the device card is saved.

**Any other remarks**

Already tried in Incognito and did a ctrl+F5.

**Comment by philsniff** [comment] 2016-10-21 11:54
i can underline this. i can't sort my devices, it isn't saved

**Comment by bvdbos** [comment] 2016-10-21 13:28
Were we able to do that before 0.10.x?

**Comment by philsniff** [comment] 2016-10-21 13:37
Yes, i know it! But when was the cut! Before 0.10? I don't know.

**Comment by mike9011** [comment] 2016-10-21 14:37
Yes im 100% sure this was possible.. only i dont know since which version this was still working.

**Comment by Phunkay** [comment] 2016-10-21 14:51
Worked here before, not anymore since some versions. Issue 819 also concerns ordering where the device order changes when an app updates. Related?

**Comment by caseda** [comment] 2016-10-21 21:28
did this even work? it never worked for me because the devices are sorted by "last edited/updated" even if you move them around, when you came back to the page it will all be back in the old situation

**Comment by WeeJeWel** [comment] 2016-10-24 14:30
Actually this has never been implemented 🙈

**Comment by mike9011** [comment] 2016-10-24 14:40
Oh haha... i thought it was.. :sweat_smile:  
Now i need to scroll trough all my Philips Hue lights before i see my Aeotec Sensor (on mobile) But i don't want to remove the hue lights and re-add them to have my sensor on top. 

So it would be great if this can me implemented!

**Comment by bvdbos** [comment] 2016-10-24 14:45
I agree, for the laptop this is not a problem but for mobile some kind of sorting would be nice. Even if it is on alphabet (then we can rename the devices with a character in front of them so we can choose tho irder ourselves). But drag-n-drop ordering would be better....

**Comment by WeeJeWel** [comment] 2016-10-25 18:24
It's on my todo list! :)

**Comment by WeeJeWel** [comment] 2016-11-07 13:58
Fixed in 0.11.0 :-) The position is also visible in the mobile interface now.

**Comment by philsniff** [comment] 2016-11-07 14:19
Great! Thx

**Comment by mike9011** [comment] 2016-11-07 16:45
Great, thanks!!!

**Comment by mike9011** [comment] 2016-11-21 07:53
@WeeJeWel it doens't work very well.. when i place for example my Multisensor in the first position, and go to the settings menu and go back, the position of the Multisensor is changed to another position. (checked the console, and it looks like the position is saved) Also tried it in the Homey Desktop Application, but that doesn't make a difference.

**Comment by Arjanvde** [comment] 2016-11-21 09:11
"Very wel"l is sort of a misunderstanding.

In my case it doesn't work at all, I can't really sort any devices, once sorted the order changes quite randomly again. @WeeJeWel, your free to debug on my Homey if needed.

**Comment by WeeJeWel** [comment] 2016-11-21 13:44
@Arjanvde Very much. It works fine here, so I wonder what goes wrong. Can you invite emile@athom.nl?

**Comment by djeskoswe** [comment] 2016-11-21 13:48
Same problem here , 

i can invite if @Arjanvde dont have time today.   just let me know

**Comment by WeeJeWel** [comment] 2016-11-21 13:48
Sure!

**Comment by bvdbos** [comment] 2016-11-21 13:49
Works for me on my computer, also works on my FP2 after logging out and logging in again...

**Comment by djeskoswe** [comment] 2016-11-21 14:00
log out did work when moving sonos device , but my fibaro sensor always jumps back to the start

**Comment by Arjanvde** [comment] 2016-11-21 14:40
I've invited @WeeJeWel.

I've switched computers from my Mac to Windows at work and the issue is still there.

**Comment by WeeJeWel** [comment] 2016-11-21 15:55
Thanks for helping me out! Fixed in 1.0.2 :)

For the interested: it was replacing `b.order < a.order` with `a.order - b.order`. :')

**Comment by Arjanvde** [comment] 2016-11-21 15:58
Ah thanks!

**Comment by Arjanvde** [comment] 2016-11-25 19:24
For this is solved. Also the position is now reflected on my mobile device.

**Comment by WeeJeWel** [comment] 2016-11-25 19:24
Great!

**Closed by WeeJeWel** 2016-11-25 19:24 UTC
Labels: Devices, interface, Staged for release
