### ISSUE TITLE
Old name of renamed device shows up in Flow editor

### ISSUE THREAD

**Issue by corvdniet** [athombv/homey#1432] opened 2017-03-31 07:18 UTC
**What is your Homey version (Settings → System)?**
1.2.0-rc.10

**What did you try to achieve?**
Rename a zwave plus device

*Please include detailed steps how we can reproduce the issue*
Add a zwave plus device. Renamed the device. 

**What was the result?**
In the flow editor the old (original name) shows up

**What did you expect as result?**
To see the renamed name of the device in the flow editor

**Any other remarks**
In the devices display +  in the zwave network graph the device shows up with the renamed name.

**Comment by twellocity** [comment] 2017-04-02 12:02
The same here with adding klik aan klik uit devices. in the flow design they have still the original names. this is a big problem when ( like me) having more the same devices !! 

please ATHOM help!

**Comment by camilleversteeg** [comment] 2017-04-02 16:35
Same problem here, i rebooted the device and it seems that flows are correct now. But the issue is still there,  i just renamed a device and flows are not updated:

![image](https://cloud.githubusercontent.com/assets/15101655/24588999/2500c578-17d3-11e7-8b21-ae486d53b8d4.png)

**Comment by WeeJeWel** [comment] 2017-04-04 15:26
This should be fixed in the next release

**Comment by chrisboer** [comment] 2017-04-04 16:33
@WeeJeWel next release of homey or next release of KaKu

**Comment by corvdniet** [comment] 2017-04-11 19:09
Fixed in 1.2.0-rc.12. Thnx

**Closed** 2017-06-01 10:58 UTC
Labels: bug, Flow, interface, Staged for release
