### ISSUE TITLE
Zwave devices become unresponsive but zwave chip seems fine

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#847] opened 2016-09-03 10:23 UTC
**What is your Homey version (Settings → System)?**
0.9.3

**What did you try to achieve?**
Use my Zwave devices, mostly toggle them on/off.

**Please include detailed steps how we can reproduce the issue**
Just use Homey a while with zwave devices from Greenwave and Fibaro. Eventually you will not be able to control the devices using Homey anymore.

**What was the result?**
After some time of use, usually a day or two Zwave isnt working anymore. The Zwave settings dont show anything special. The buttons on the settings page are not greyed out. But when trying to toggle any Zwave device there is no actual response. And although it seems Homey toggles a device on in the UI, when opening the device card again after this the status of the device is off again. The only way to resolve this (as far as I know) is to reboot.

**What did you expect as result?**
A reliable and working Zwave network. I dont like to reboot Homey every day.

**Any other remarks**
I'll post a log when this happens again. Forgot to do it last time.

**Comment by Fire69** [comment] 2016-09-05 20:20
Same here, but worse.
Just did a test.  Ok after reboot, but about 2 hours later nothing is working anymore!
When you physically toggle the device (relay, dimmer, roller shutter) the card gets updated, so there is still communication.
Also tried changing settings for a device.  I get the message that settings have been saved successfully, but in fact nothing has been saved.

Here's a log after I tried toggling some devices: 5748226C5E

**Comment by freemann** [comment] 2016-09-05 20:37
I have to say its "fairly" stable over here.

**Comment by MdeRhoter** [comment] 2016-09-08 16:06
I have the same issue, I've even scheduled a nightly reboot of Homey, but that's not enough. On average I seem to get around twelve hours of Zwave connectivity to my sensors before they stop reporting motion. They still blink, so they do try - and they're all well within range.

Lux and temp seem to have their own agenda, they sometimes continue when motion has long gone.

**Comment by jeroenvollenbrock** [comment] 2016-09-08 19:14
Could everyone who is affected by this issue tell me how many (not-disabled) Homey apps you have installed? If this amount is higher then 10, would it be possible to remove a few apps and verify if that solves the issue?

**Comment by Fire69** [comment] 2016-09-08 20:52
I have 15 apps.
Can't remove 5 without messing up a lot of my flows :-/

**Comment by MdeRhoter** [comment] 2016-09-08 21:15
I also have 15 apps installed, I may be able to uninstall 5 of them - but it will mess with a number of my flows, are you saying you have no Zwave+ issues at all on your vanilla Homey with just the Fibaro app installed?

**Comment by MdeRhoter** [comment] 2016-09-08 21:19
Okay, I'm desperate - I removed 5 so I am now at exactly 10 apps. Fingers crossed!

**Comment by freemann** [comment] 2016-09-08 21:22
Here removed around 11 apps (9 active, 2 inactive) and now have only 9 apps installed which are all 9 active;
https://files.slack.com/files-pri/T04E9KJ7T-F29NFSR5L/screenshot_-_08_09_2016___22_53_48.png

I didn't removed/changed Z-Wave apps, so the situation around Z-Wave on my Homey isn't changed.

**Comment by MdeRhoter** [comment] 2016-09-09 17:01
Twenty hours later with a reboot at 3 am, Zwave+ does seem more responsive!

**Comment by mruiter** [comment] 2016-09-09 17:50
doe you have the aeotec app installed mderhoter. im having the same trouble and it is caused by the aeotec app or a device from aeotec. seems to be the multisensor as this is now the only device i have added .

**Comment by freemann** [comment] 2016-09-09 18:19
@mruiter did you try to exclude the multi sensor and include a different node? Then you could say it's the multi sensor or the app itself.

**Comment by MdeRhoter** [comment] 2016-09-09 18:44
I do not have the Aeotec app installed, just the Fibaro one. Just lost one sensor again. Sigh.

**Comment by Fire69** [comment] 2016-09-11 12:19
48 hours later, everything is still working here.
Enabled some apps again one by one, I have 10 active now.
I'll continue enabling them and report back if it should stop working again.

**Comment by MdeRhoter** [comment] 2016-09-11 14:10
Which Zwave devices are in your network?

(Also, I'm jealous)

**Comment by Fire69** [comment] 2016-09-11 15:10
All Fibaro: single/double relays, dimmer 2, roller shutters, motion sensors (non plus version)

**Comment by MdeRhoter** [comment] 2016-09-11 16:00
What's the range like? The devices that stay online the longest seem to be those closest to Homey - at least in my case.

Maybe I'll get some additional Homeys for the far away sensors (I hear Marktplaats has a few)

**Comment by Fire69** [comment] 2016-09-11 17:54
I have 1 device added on the first floor, that's about 10m and 1 floor up, that's the furthest away from my Homey.
It's working fine, but there are several devices in between, so I guess the mesh network is working fine too :-)

**Comment by MdeRhoter** [comment] 2016-09-11 20:43
Currently the Dimmer 2 is my only non-battery powered Fibaro device, does that still help with building a mesh? It's near the least responsive motion sensor (and it itself also is very unreliable, it works  only 1 out of 10 times on a good day).

**Comment by Fire69** [comment] 2016-09-11 20:47
Don't think it will do you much good if it's at the end of the range itself.  The sensor will probably connect through it, but if it loses the connection itself, they'll both be unreachable.

**Comment by bvdbos** [comment] 2016-09-11 21:04
What's the distance of Dimmer2 to Homey? Battery-powered devices don't help in creating a mesh and with only one main-powered device you can't really speak about a mesh...

**Comment by MdeRhoter** [comment] 2016-09-11 21:16
Dimmer 2 is maybe 2 meters from Homey, but there is a wall between them. I did the connectivity test, it reported a direct connection (green led).

Is there a way to tell how the sensor connects?

**Comment by Fire69** [comment] 2016-09-12 18:24
OK, I overdid it.  Have 13 apps active and my z-wave died...

**Comment by jghaanstra** [comment] 2016-09-30 05:41
Firmware 0.10.x has made my zwave network pretty stable. Issue closed.

**Comment by jghaanstra** [comment] 2016-09-30 17:17
Unfortunately this just happened again. I should not have closed the bug and will reopen ... 

Homey log: E6EA965AF8

**Comment by WeeJeWel** [comment] 2016-10-10 20:50
Should be more stable in 0.10.4. If not, please report back!

**Comment by Fire69** [comment] 2016-10-11 07:16
Haven't had any more problems here since 0.10.3 (knock on wood...)

**Comment by jeroenvollenbrock** [comment] 2016-10-17 13:06
I'm closing this issue as it is supposedly fixed in the latest update. If the problem persists, please reopen this issue.

**Closed by jeroenvollenbrock** 2016-10-17 13:06 UTC
Labels: bug, Homey Core, Staged for release, Z-Wave
