### ISSUE TITLE
logic issues

### ISSUE THREAD

**Issue by Deentje** [athombv/homey#924] opened 2016-09-28 20:02 UTC
**What is your Homey version (Settings → System)?**

Homey version 0.10.0

**What did you try to achieve?**

Automatic switching lights on lux intensity between a certain time frame --> worked at 0.9.3
![fibaro2](https://cloud.githubusercontent.com/assets/19371484/18930075/f408b212-85c6-11e6-91a8-80f52ee72480.jpg)

**What was the result?**

Lights does not go on when lux is lower that mentioned value
.

**What did you expect as result?**

That lights switch on when lux value comes below 35 between mentioned time frame

**Any other remarks**

This flow worked before in previous version 0.9.3

**Comment by bvdbos** [comment] 2016-09-29 08:12
Dupe of #895 probably?

**Comment by WeeJeWel** [comment] 2016-09-29 10:31
Fixed in 0.10.1!

**Comment by jeroenvollenbrock** [comment] 2016-09-29 14:36
Even though this issue is fixed in 0.10.1, the "test flow" button may stil show this error. That will be fixed in 0.10.2

**Comment by WeeJeWel** [comment] 2016-10-10 18:05
Duplicate of #977 (and fixed in 0.10.4)

**Closed by WeeJeWel** 2016-10-10 18:05 UTC
Labels: Flow

**Comment by gruijter** [comment] 2016-10-14 21:10
in 0.10.5 I still (or again?) have a problem with tokens. Although I do not get a red triangle anymore, the logic fails when doing 'If humidity > 60 do something".

It seems to be comparing strings, and does not convert the string into a number first.

**Comment by WeeJeWel** [comment] 2016-10-17 12:09
The 'Humidity' demo token value is `100`, so that's why it fails :)

**Comment by gruijter** [comment] 2016-10-17 13:26
Ok, that explains it. But this is not at all clear when a user is testing a flow. Maybe enhance the function by letting Homey ask for a value of used trigger tokens?

**Comment by WeeJeWel** [comment] 2016-10-17 15:04
That's on the list! :D
