### ISSUE TITLE
KaKu ACDB-7000AC doorbell no longer works as a trigger button

### ISSUE THREAD

**Issue by MdeRhoter** [athombv/homey#353] opened 2016-03-17 14:18 UTC
What is your Homey version (Settings → System)?

0.8.0.24

What did you try to achieve?

Use my doorbell as a trigger in a flow

What was the result?

The flow does not trigger

What did you expect as result?

The flow to trigger

Any other remarks

It worked in 0.8.0.22, with both KaKu 1.0.14 and 1.0.15, but when I had to hard-reset my Homey, it stopped working.

Pairing the doorbell transmitter works fine, but when someone presses the actual doorbell, it is not picked up by my Homey.The transmitter works, because the chime does respond.

**Comment by Dennishacq** [comment] 2016-03-17 18:33
Thank you for submitting this issue.
Did you try to pair your doorbel again?

**Comment by MdeRhoter** [comment] 2016-03-17 18:51
Yes I did - I had to after the hard reset. I ran into other KaKu issues as well, the wizard for the dimmers won't let you pick the device. I'm pretty sure that was different a while ago. The dimmers work, and it's just a cosmetic thing, but still :)

Also, when adding a socket and choosing to copy a remote signal, the wizard says to "press a random button". That should be "press the button that controls your socket".

If you want it to work, that is.

**Comment by Dennishacq** [comment] 2016-03-18 09:19
Thank you for pointing these things out, I'll fix these issues today.

**Comment by MdeRhoter** [comment] 2016-03-18 11:48
Thank you, much appreciated! Will this be an update to the Kaku app or the Homey firmware?

**Comment by Dennishacq** [comment] 2016-03-18 12:28
The device picker and "Press a random button" bugs are fixed but i'm unable to reproduce the issue with your doorbell. This issue might already be fixed in the next KaKu update.
These fixes will be added to KaKu v1.0.16.

**Comment by MdeRhoter** [comment] 2016-03-18 12:37
Thanks! I'll give it a try when it releases.

**Comment by MdeRhoter** [comment] 2016-03-18 14:47
Update: the doorbell worked just now! No reboot, no changes, it may have been a temporary glitch - I'll test some more over the weekend. If you want, close this issue, I'll re-open (or create a new one) once I have more definite repro steps.

**Comment by Dennishacq** [comment] 2016-03-18 20:05
Glad to hear that your issue is solved :)

**Closed by Dennishacq** 2016-03-18 20:05 UTC
