### ISSUE TITLE
Plugwise only sees 4 of my devices

### ISSUE THREAD

**Issue by FreekBloemhof** [athombv/homey#178] opened 2016-02-13 15:54 UTC
I tried adding a couple of my Plugwise devices, but when I enter the ID of my Stretch Homey only sees 4 devices. I have about 25 "plugs". 

How to troubleshoot this?

**Comment by nattlip** [comment] 2016-02-13 18:22
i dont have a stretch only a plugwise source server , is there coming a interfaxe to it ?

**Comment by freekwebdesign** [comment] 2016-02-16 16:11
@FreekBloemhof Thanks for reporting this issue.
We will try to get more Plugwise plugs so we can test with more then 4 plugs.
Troubleshooting is the easiest if we can do this at our office.

But it could be helpful if you are able to login to your Stretch using the following url: http://stretch:plugwiseID@192.168.0.0/core/appliances
You have to replace 'plugwiseID' with your plugwise ID.
And the IP address '192.168.0.0' with the IP address on which your Stretch is running.

This will provide a XML list with all your devices.
If you can send me this XML output in a personal message I will try to reproduce your device setup.

**Comment by freekwebdesign** [comment] 2016-02-16 16:12
@nattlip what is connected to your source server?
Because at the moment we have no plans on supporting that.

**Comment by bvdbos** [comment] 2016-02-16 16:25
@freekwebdesign I think nattlip means plugs with a stick? That's what I have at home and in the office. Plugwise is working on the Zigbee :
http://www.maartendamen.com/wp-content/uploads/downloads/2010/08/Plugwise-unleashed-0.1.pdf

**Comment by freekwebdesign** [comment] 2016-02-16 17:28
@bvdbos @nattlip 
We are not going to support the Plugwise stick at the moment.
So the solution would be to replace the Plugwise Stick with a Plugwise Stretch.

**Comment by freekwebdesign** [comment] 2016-02-26 15:51
@FreekBloemhof a new version of the Plugwise-app will be released in the beginning of next week.
This should solve your problem.

**Comment by FreekBloemhof** [comment] 2016-03-17 08:44
Still waiting, still no new version.

**Comment by freekwebdesign** [comment] 2016-03-18 10:14
@FreekBloemhof My apologies for the long wait.
Due to some miscommunications the new version of the app wasn’t released earlier.
The new version (1.0.6) is now available in the App Store.
I hope this update fixes your problem.

**Comment by jeroenvollenbrock** [comment] 2016-07-27 11:30
Can you please let me know whether this issue persists or not?

**Comment by RobinBol** [comment] 2016-07-27 16:35
Version 2.0.1 is a complete re-write of the app. This will most likely fix this issue.

**Comment by jeroenvollenbrock** [comment] 2016-08-16 16:04
This issue is being closed due to inactivity. Please reopen if the problem persists.

**Closed by jeroenvollenbrock** 2016-08-16 16:04 UTC
Labels: Athom App, bug, waiting for user feedback
