### ISSUE TITLE
Google Chromecast App not detecting devices

### ISSUE THREAD

**Issue by hschenkelaars** [athombv/homey#110] opened 2016-02-11 16:33 UTC
The google Chromecast app doesn’t seem to work. I have a Chromecast audio and video but homey can't find any devices. Both Chromecasts and Homey are on the same SSID. When trying to add a Chromecast player the swirl keeps turning but nothing happens. 

Any idea how to troubleshoot this any further ?

**Comment by WeeJeWel** [comment] 2016-02-11 16:43
Duplicate of #81

**Closed by WeeJeWel** 2016-02-11 16:43 UTC
