### ISSUE TITLE
433.92 sensors  not working after uppdate to 1.5.6/1.5.8

### ISSUE THREAD

**Issue by Leonidas37** [athombv/homey#2318] opened 2018-03-10 11:34 UTC
Thank you for reporting an issue. Please take some time to
review the contributing guidelines if you haven't done so.

This issue tracker is for bugs and issues found within Homey.
If you require more general support contact our support team
at: support@athom.com

Please fill out as much of the fields below as you're able.
The Homey log code can be generated at Settings -> System -> Send Log.
The Homey App log code can be generated at Settings -> Apps (hold ALT to show the 'Send Log' link).

If possible, please provide examples that demonstrates the problem,
keeping it as simple and clear as you are able to.

-->

**Metadata**

* **Homey Version**: 1.5.8
* **Homey Log Code**:
* **Smartphone Platform**: Android
* **Smartphone App Version**:

**If related to a Homey App:** wireless weather sensors 
**Homey App Version**: v 1.2.1
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:
Telldus thermo/hygro sensor. Oregon sensors

**What did you try to achieve?**

Include 433.92 sensors to Homey

**What did you expect as result?**

**What was the result?**

homey cant find any 433 sensors
**Any other remarks**
Try too unplug for 10 min but no result. After updating to 1.5.6 homey cant find any 433 sensors, before 1.5.6 there was no problem too find sensors Oregon or Telldus

**Comment by bvdbos** [comment] 2018-03-10 11:39
known issue, if you searched for "433" you would have found #2023 
https://github.com/athombv/homey/search?q=433&type=Issues&utf8=%E2%9C%93

**Comment by jeroenvollenbrock** [comment] 2018-03-13 15:58
Closing as duplicate of #2023

**Closed by jeroenvollenbrock** 2018-03-13 15:58 UTC
