### ISSUE TITLE
[nl.klikaanklikuit] Doorbell stopped working with homey. i think it since 4.0.7 can i revert back?

### ISSUE THREAD

**Issue by runner780** [athombv/homey#2748] opened 2018-08-09 16:20 UTC
**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by KyleAthom** [comment] 2018-08-10 04:55
Duplicate of https://github.com/athombv/homey/issues/2717

**Closed by KyleAthom** 2018-08-10 04:55 UTC
