### ISSUE TITLE
[1.1.4 - 1.1.9] Still significant amount of "queue_full" error messages and delayed report processing

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#1316] opened 2017-02-06 20:26 UTC
**What is your Homey version (Settings → System)?**
Homey SW 1.1.4
Z-wave driver 1.1.4
Fibaro 1.1.19, Greenwave 1.0.10, Neo 1.1.13

Log: BD092AEA8A

**What did you try to achieve?**
Verify that #1246 has been solved in Homey SW 1.1.14 and debugging battery reports on Neo motion sensor to be send during (manual or automatic) wakeup (due to improved getOnWakeUp function in Homey's core)

**What was the result?**
During debugging of the getOnWakeUp function to retrieve the battery status of the Neo motion sensor, running both the Z-wave driver and Neo app in debugging mode, I noticed the following:

**1. Large amount of "queue_full" error messages**
 A lot of "queue_full" error messages in the new Z-wave logging, as well as the debugging log. In ~1900 seconds (half an hour) after a restart of Homey, related to #1311, I see 109 queue_full error messages out of 427 ProcessSendData reports... See attached file with logging.

[170206_Homey_Z-wave-log_uptime 1900.txt](https://github.com/athombv/homey/files/755756/170206_Homey_Z-wave-log_uptime.1900.txt)

Additional examples out of the debugging logging (running NEO app):
```
[debug]  COMMAND_CLASS_SENSOR_MULTILEVEL SENSOR_MULTILEVEL_GET args: { 'Sensor Type': 'Luminance (version 1)',
  Properties1: { Scale: 1 } } err: { [Error: queue_full] message: 'queue_full' } result: null
[debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: { [Error: queue_full] message: 'queue_full' } result: null
[debug] node.on('online') arguments: { '0': false }
[debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: { [Error: queue_full] message: 'queue_full' } result: null
```
running Fibaro app:
```
[debug] node.on('online') arguments: { '0': true }
[debug]  COMMAND_CLASS_SENSOR_BINARY SENSOR_BINARY_GET args: {} err: null result: { 'Sensor Value (Raw)': <Buffer 00>, 'Sensor Value': 'idle' }
[debug] node.CommandClass['COMMAND_CLASS_SENSOR_BINARY'].on('report') arguments: { '0': { value: 3, name: 'SENSOR_BINARY_REPORT' },
  '1': { 'Sensor Value (Raw)': <Buffer 00>, 'Sensor Value': 'idle' },
  '2': null }
[debug]  COMMAND_CLASS_SWITCH_MULTILEVEL SWITCH_MULTILEVEL_GET args: {} err: { [Error: timeout] message: 'timeout' } result: null
[debug]  COMMAND_CLASS_SWITCH_MULTILEVEL SWITCH_MULTILEVEL_GET args: {} err: { [Error: timeout] message: 'timeout' } result: null
[debug] node.on('online') arguments: { '0': false }
[debug]  COMMAND_CLASS_SWITCH_MULTILEVEL SWITCH_MULTILEVEL_GET args: {} err: { [Error: timeout] message: 'timeout' } result: null
[debug]  COMMAND_CLASS_SWITCH_MULTILEVEL SWITCH_MULTILEVEL_GET args: {} err: { [Error: timeout] message: 'timeout' } result: null
[debug]  COMMAND_CLASS_SWITCH_MULTILEVEL SWITCH_MULTILEVEL_GET args: {} err: { [Error: queue_full] message: 'queue_full' } result: null
[debug]  COMMAND_CLASS_SWITCH_MULTILEVEL SWITCH_MULTILEVEL_GET args: {} err: { [Error: queue_full] message: 'queue_full' } result: null
[debug]  COMMAND_CLASS_SWITCH_MULTILEVEL SWITCH_MULTILEVEL_GET args: {} err: { [Error: timeout] message: 'timeout' } result: null
[debug]  COMMAND_CLASS_SENSOR_MULTILEVEL SENSOR_MULTILEVEL_GET args: {} err: { [Error: timeout] message: 'timeout' } result: null
[debug]  COMMAND_CLASS_METER METER_GET args: { Properties1: { Scale: 0 } } err: { [Error: timeout] message: 'timeout' } result: null
[debug]  COMMAND_CLASS_SWITCH_MULTILEVEL SWITCH_MULTILEVEL_GET args: {} err: { [Error: timeout] message: 'timeout' } result: null
[debug] node.on('online') arguments: { '0': true }
```

2. Battery reporting not always provided on expected time (with manual wakeup), but "bursted" after power down of Z-wave device

```
[debug] node.on('online') arguments: { '0': true }
[debug] node.CommandClass['COMMAND_CLASS_BATTERY'].on('report') arguments: { '0': { value: 3, name: 'BATTERY_REPORT' },
  '1': { 'Battery Level (Raw)': <Buffer 4b>, 'Battery Level': {} },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_BATTERY'].on('report') arguments: { '0': { value: 3, name: 'BATTERY_REPORT' },
  '1': { 'Battery Level (Raw)': <Buffer 4b>, 'Battery Level': {} },
  '2': null }
[debug] node.CommandClass['COMMAND_CLASS_BATTERY'].on('report') arguments: { '0': { value: 3, name: 'BATTERY_REPORT' },
  '1': { 'Battery Level (Raw)': <Buffer 4b>, 'Battery Level': {} },
  '2': null }
[debug] node.on('online') arguments: { '0': true }
```
And:
```
[debug] node.on('online') arguments: { '0': true }
[debug]  COMMAND_CLASS_BATTERY->BATTERY_GET args: {} cb: true
[debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: null result: { 'Battery Level (Raw)': <Buffer 3e>, 'Battery Level': {} }
[debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: null result: { 'Battery Level (Raw)': <Buffer 3a>, 'Battery Level': {} }
[debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: null result: { 'Battery Level (Raw)': <Buffer 3a>, 'Battery Level': {} }
[debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: null result: { 'Battery Level (Raw)': <Buffer 3a>, 'Battery Level': {} }
[debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: null result: { 'Battery Level (Raw)': <Buffer 3a>, 'Battery Level': {} }
[debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: null result: { 'Battery Level (Raw)': <Buffer 3a>, 'Battery Level': {} }
[debug]  COMMAND_CLASS_BATTERY BATTERY_GET args: {} err: null result: { 'Battery Level (Raw)': <Buffer 3a>, 'Battery Level': {} }
[debug] node.CommandClass['COMMAND_CLASS_BATTERY'].on('report') arguments: { '0': { value: 3, name: 'BATTERY_REPORT' },
  '1': { 'Battery Level (Raw)': <Buffer 3a>, 'Battery Level': {} },
  '2': null }
```
It looks like rebooting of Homey does not resolve this issue, the burst seems to be triggered by power cycling of the device bursting the queued reports to Homey.

**What was the expected result**
I was under the impression that the reports that could not be handled by Homey / Z-wave driver would stored in the storage and be processed on a later moment in time. Considering the behaviour of the sensor bursting battery reports, it seems like in some cases the device is not able to send the reports to Homey

**Any other remarks**
@WeeJeWel @jeroenvollenbrock if you need access to my Homey to further investigate, please let me know
...

**Comment by TedTolboom** [comment] 2017-02-18 23:10
What is your Homey version (Settings → System)?
Homey SW 1.1.9
Z-wave driver 1.1.4
Fibaro 1.2.1, Greenwave 1.0.10, Neo 1.1.14

Log: D24EC69343

After update to 1.1.9 and Fibaro app to 1.2.1, I'm still seeing a substantial amount of queue_full errors; 111 out of 308 ProcessSendData's get the Error: queue_full message.
```
[2017-02-18T22:17:37.992Z] ProcessSendData[13468]: Error: queue_full
[2017-02-18T22:18:45.191Z] ProcessSendData[13491]: Error: queue_full
[2017-02-18T22:19:29.483Z] ProcessSendData[13494]: Error: queue_full
[2017-02-18T22:19:50.456Z] ProcessSendData[13497]: Error: queue_full
....
[2017-02-18T22:35:00.735Z] ProcessSendData[13753]: Error: queue_full
[2017-02-18T22:35:00.792Z] ProcessSendData[13754]: Error: queue_full
[2017-02-18T22:35:02.467Z] ProcessSendData[13757]: Error: queue_full
[2017-02-18T22:35:02.513Z] ProcessSendData[13758]: Error: queue_full
[2017-02-18T22:35:02.550Z] ProcessSendData[13759]: Error: queue_full
[2017-02-18T22:35:03.673Z] ProcessSendData[13762]: Error: queue_full
[2017-02-18T22:35:03.703Z] ProcessSendData[13763]: Error: queue_full
[2017-02-18T22:35:03.733Z] ProcessSendData[13764]: Error: queue_full
[2017-02-18T22:35:03.778Z] ProcessSendData[13765]: Error: queue_full
[2017-02-18T22:35:05.023Z] ProcessSendData[13768]: Error: queue_full
[2017-02-18T22:35:06.197Z] ProcessSendData[13771]: Error: queue_full
[2017-02-18T22:35:06.289Z] ProcessSendData[13772]: Error: queue_full
[2017-02-18T22:35:38.130Z] ProcessSendData[13776]: Error: queue_full
```
In addition, I do see quite some 'COMMAND_CLASS_SECURITY' related questions passing by:
```
[2017-02-18T19:10:18.372Z] Node[137]: Received application command for COMMAND_CLASS_CRC_16_ENCAP, data: 0x013105030a00077776
[2017-02-18T19:10:18.389Z] Node[137]: Decapsulated frame from COMMAND_CLASS_CRC_16_ENCAP to COMMAND_CLASS_SENSOR_MULTILEVEL, data 0x05030a0007
[2017-02-18T19:10:18.690Z] Node[137]: Received application command for COMMAND_CLASS_CRC_16_ENCAP, data: 0x013105030a00077776
[2017-02-18T19:10:18.713Z] Node[137]: Decapsulated frame from COMMAND_CLASS_CRC_16_ENCAP to COMMAND_CLASS_SENSOR_MULTILEVEL, data 0x05030a0007
[2017-02-18T19:11:01.080Z] Node[137]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
[2017-02-18T19:11:01.081Z] Node[137]: sendData to COMMAND_CLASS_SECURITY, params 0x8076ceedcfc3fb5ac6
[2017-02-18T19:11:01.098Z] ProcessSendData[10659]: To node: 137 with data: 0x988076ceedcfc3fb5ac6 and txOptions: ACK,AUTO_ROUTE
[2017-02-18T19:11:01.438Z] Node[137]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
[2017-02-18T19:11:01.439Z] Node[137]: sendData to COMMAND_CLASS_SECURITY, params 0x804fde90e1b1d268f4
[2017-02-18T19:11:01.670Z] Node[137]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
[2017-02-18T19:11:01.671Z] Node[137]: sendData to COMMAND_CLASS_SECURITY, params 0x80bdd98368ce961fa1
[2017-02-18T19:11:05.006Z] ProcessSendData[10660]: To node: 137 with data: 0x98804fde90e1b1d268f4 and txOptions: ACK,AUTO_ROUTE
[2017-02-18T19:11:08.517Z] ProcessSendData[10661]: To node: 137 with data: 0x9880bdd98368ce961fa1 and txOptions: ACK,AUTO_ROUTE
[2017-02-18T19:12:11.966Z] Node[137]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
[2017-02-18T19:12:11.971Z] Node[137]: sendData to COMMAND_CLASS_SECURITY, params 0x803ee7c05a551778df
[2017-02-18T19:12:12.000Z] ProcessSendData[10669]: To node: 137 with data: 0x98803ee7c05a551778df and txOptions: ACK,AUTO_ROUTE
[2017-02-18T19:12:12.230Z] Node[137]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
[2017-02-18T19:12:12.231Z] Node[137]: sendData to COMMAND_CLASS_SECURITY, params 0x80910a94e053a69a48
[2017-02-18T19:12:12.303Z] ProcessSendData[10670]: To node: 137 with data: 0x9880910a94e053a69a48 and txOptions: ACK,AUTO_ROUTE
```
Any ideas what could cause this?

**Comment by TedTolboom** [comment] 2017-03-12 19:13
Any progress on this issue?

I have been working on optimizing the polling interval distribution for my Greenwave powernodes to resolve the queue_full overkill caused by polling on 84 capabilities, with only 4 intervals to distribute;
Looked into differentiating the polling interval over the different capabilities (on/off, measure, meter) per device.
In the Z-wave driver the polling interval name is 'hard-coded' as: `if(changedKey === 'poll_interval')` which would block this approach; solved it by changing the Z-wavedriver `if (changedKey.startsWith('poll_interval'))` ... not really elegant solution but working.

<img width="613" alt="schermafbeelding 2017-03-04 om 14 40 29" src="https://cloud.githubusercontent.com/assets/17163431/23835012/162d1692-0760-11e7-801e-7a1a638fa4b3.png">

Result is that I did not see as many queue_full messages as I had before, even in periods where the powernode-6's are being polled.

So this works as containment (will file the corresponding changes to the Greenwave app and Zwavedriver) but is not the final solution.

**Comment by WeeJeWel** [comment] 2017-03-14 18:09
Duplicate of #1246

**Closed by WeeJeWel** 2017-03-14 18:09 UTC
Labels: bug, Z-Wave
