### ISSUE TITLE
[Feature Request] Global Event Log / Journal / Diary 

### ISSUE THREAD

**Issue by OliverIckler** [athombv/homey#2704] opened 2018-07-20 13:57 UTC
**Metadata**

* **Homey Version**: 1.5.11
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

Why is there no global event log for triggers from all components?
If a motion sensor triggers motion, i want to see it in my diary.
If a window is opened or closed i want to see it in my diary.
Maybe i want to see, if someone changes the temperature on an device.

**What did you expect as result?**

It would be a nice feature to activate an automatic diary entry for each trigger of a device.
So i can decide what i am interested in my diary.
Maybe a global log with all events will be nice too.

**What was the result?**

**Any other remarks**

**Comment by Dijker** [comment] 2018-07-20 14:16
please look into  the App Store: 
https://apps.athom.com/app/nl.nielsdeklerk.log
or
https://apps.athom.com/app/nu.dijker.papertrails
or
https://apps.athom.com/app/gov.nsa.logger

This Feature request is asked for multiple times, 
https://github.com/athombv/homey/issues?utf8=%E2%9C%93&q=is%3Aissue+logging+label%3Aenhancement

so this is a duplicate of #1847 and #2050 

Please note that this however is a bug tracker and not a regular support channel. 
please take another look at Athoms contributing guidelines? The more information we have, the easier it will be to reproduce the issue and provide a solution. If you are unable to do this or just want to receive regular support, please contact us through support@athom.com instead of using the bug tracker.

For almost 24x7 support from the community please search or ask this kind of questions on the Forum  https://forum.athom.com/search?q=log or on the #Homey channel at Slack.

**Comment by jeroenvollenbrock** [comment] 2018-07-23 09:30
Closing as duplicate of #2050

**Closed by jeroenvollenbrock** 2018-07-23 09:30 UTC

**Comment by OliverIckler** [comment] 2018-07-23 13:36
I don't need a log for debugging or developing.
The other tickets describes not a diary!
I need a diary, what happend in my house!

**Comment by Dijker** [comment] 2018-07-23 13:40
I guess both simple Log and Papertrails perfectly suite for that.
Have you looked at it? (you can even use them both for different diary's)

**Comment by OliverIckler** [comment] 2018-07-23 13:43
Yes I use Simply Log, but to get an entry to Simply Log i have to write a flow!
Why should i write a flow for each of my 40 Window/Door Sensors, when they are opened or closed.
That must Homey do by himself -> In a diary.

**Comment by Dijker** [comment] 2018-07-23 13:55
I guess not everyone needs this, 
but you could create it it with 2 flows for all your Contact (Window/Door) sensors and fe Papertrails. 
loot at the following triggers:
![image](https://user-images.githubusercontent.com/12412734/43080647-72c99066-8e90-11e8-8d21-aebc44c06a1d.png)

else it is maybe more a duplicate of 1847 and that one is still open as Feature request ;-)

**Comment by OliverIckler** [comment] 2018-07-23 14:00
Ok ... i am impressed :-)
Never noticed that "Device" feature in flows can do such things.
There is my diary, with a few flows :-)
Thanks

**Comment by Dijker** [comment] 2018-07-23 14:04
Bitte schön ;-)

**Comment by OliverIckler** [comment] 2018-07-23 14:06
Auch noch von jemand der Deutsch spricht :-) noch schöner ...
