### ISSUE TITLE
[nl.eneco.toon] Describe your issue here

### ISSUE THREAD

**Issue by robertb89** [athombv/homey#2329] opened 2018-03-13 12:54 UTC
Hello,

After last update from homey eneco toon is stop working for the heat. To read the electic and the gas still works. I allready installed the app again and the problem is still there. I cant set the temperature or changed to a other program.

**Metadata**

* **Homey Version**:
* **Homey Log Code**:
* **Smartphone Platform**:
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**

**What did you expect as result?**

**What was the result?**

**Any other remarks**

**Comment by jeroenvollenbrock** [comment] 2018-03-13 16:30
Closing as duplicate of #2271

**Closed by jeroenvollenbrock** 2018-03-13 16:30 UTC
Labels: Athom App, bug
