### ISSUE TITLE
DNS Fallback not working.

### ISSUE THREAD

**Issue by lvefferen** [athombv/homey#2124] opened 2018-01-02 13:29 UTC
**Metadata**

* **Homey Version**: 1.5.3
* **Homey Log Code**: 46930FDA1F
* **Smartphone Platform**: iOS
* **Smartphone App Version**: 1.3.3 -b70

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Normal operation of Homey connecting to Athom Cloud (and all related features.

**What did you expect as result?**
Normal connection to Athom Cloud and related features working.

**What was the result?**
No connection to Athom cloud and non working related features.

**Any other remarks**
It seems that Homey is not reverting to a secondary DNS server when the first failes (fallback). In my case a had a non working Pi-Hole machine (pi-hole was turned of and ip was unavailable). All computers worked because they used the secondary DNS server in the DHCP scope. Homey did not and remained limited functional even through a series of reboots and re-join WiFi network in recovery mode.

Very simple to reproduce: 
1. Setup DHCP to supply multiple DNS servers
2.Join homey in network
3. verify operation.
4. Disable First DNS server
5. Verify Homey lost Athom Cloud connection.
6. Reboot, after reboot the problem is stil there.
7. Restore primary DNS functionality
8. Homey almost instantly restores Athom Cloud connection.

**Comment by jeroenvollenbrock** [comment] 2018-02-12 15:31
Should be resolved in 1.5.6-rc.13, can you confirm this?

**Comment by jeroenvollenbrock** [comment] 2018-02-27 11:51
I’m closing this issue because it has been inactive for a while. This probably means that it is not reproducible, or it has been fixed in a newer version.

Please open a new issue if you still encounter this issue with the [latest Homey version](https://firmware.athom.com/).

Thank you!

**Closed by jeroenvollenbrock** 2018-02-27 11:51 UTC
Labels: Native, Staged for release, bug, waiting for user feedback
