### ISSUE TITLE
strange behaviour

### ISSUE THREAD

**Issue by cautje** [athombv/homey#1099] opened 2016-11-23 19:22 UTC
**What is your Homey version (Settings → System)?**

1.0.1

When i swich an klikaanklikuit wall socket (APA3 1500R) on by the homey app it is swicht on and off imidiatly.
I hear it klicking and i see it in the app switching from off to onn and back.

Then i use this wall socket in ansimple flow, i see in de homey app the swicht on and of but noting in real live.

Then i swich again by hand in the app en it works perfect and the waal switch works.

*Please include detailed steps how we can reproduce the issue*

Make a flow? But i think that it will work at your office.

**What was the result?**

...
I cant use the batroom fan because i cant switch it on or off

**What did you expect as result?**

Using an wall swich in an normal flow, started with an klikaanklikuit AWMT-003 Inbouwzender
...

**Any other remarks**

Other flows work ok.
...
![image](https://cloud.githubusercontent.com/assets/19371264/20575639/825e52be-b1ba-11e6-8479-515883edc4b2.png)

**Comment by BasKiers** [comment] 2016-11-23 20:14
Hi,

Just to be sure, you do not have any other flows interfering with the switch? Could you try turning off all flows (checkbox left of the flow) and then try to turn on the socket with the Homey app to check if you still experience this issue?

Regards, 
Bas

**Comment by cautje** [comment] 2016-11-24 08:48
Hi Bas,
Yep, the same.
I also changed the wallsocket for another klikaanklikuit type.
And again the same behaviour.
The wall socket is on the attick, but by teh app it works fine.
That is the strange thing.
Could it be that homey is bussy if it has to be sent by a flow and that in that case the transmit power is low?
THX!

**Comment by cautje** [comment] 2016-12-22 15:44
Hi,
I see the same in another setup.
in the bathroom i use an Klikaanklikuit AWMR-210 Mini Inbouw 
I swich these lighs on and off by a flow.
The trigger is an Z-wave PST02-A 4 in 1 Multi-Sensor magneet contact.
This works perfect.

When i use an klikaanklikuit AMST-606 Magneet Contactsensor in steat of the zwave device it doen not work anymore. Wirelles range is not the issu, for testing i set an push notice to my phone. On on and one off message, receiving alle te messages!!!
But the light do not change...

What can couse this?

THX!!!

![image](https://cloud.githubusercontent.com/assets/19371264/21430971/b9fe9d52-c865-11e6-8b6d-6492ef0ea882.png)

**Comment by cautje** [comment] 2016-12-26 13:21
@BasKiers i think i found IT.
In the last collum i made a delay, minimum 2 seconds.
Than IT works fine, onley the delay is not so Nice.
I think IT has to do with sending and receiving klikaanklikuit in the same time.
Mayby you can fix this in homey.

**Comment by Rocodamelshe** [comment] 2016-12-27 16:50
That sounds like t[his issue](https://github.com/athombv/homey/issues/1041)

**Comment by cautje** [comment] 2016-12-27 19:58
Yep! ThatS the same

**Comment by BasKiers** [comment] 2017-01-03 15:43
Hi, 

Thanks for debugging the issue and coming up with a quick fix. I will look into this issue soon but this is most likely not a bug in the app itself so I will have to do some debugging with a colleague to try to reproduce this issue.

Regards,
Bas

**Comment by jeroenvollenbrock** [comment] 2017-02-06 14:10
Closing as duplicate of #1041

**Closed by jeroenvollenbrock** 2017-02-06 14:10 UTC
Labels: Athom App
