### ISSUE TITLE
Name change not visible in presence flow

### ISSUE THREAD

**Issue by 0burner0** [athombv/homey#2051] opened 2017-12-11 16:08 UTC
Homey Firmware Versie: 1.5.5
* **Homey Log Code**:
* **Smartphone Platform**:  IOS and Android
* **Smartphone App Version**:

**What did you try to achieve?**

I renamed a user account to my daughter's name.
I had two accounts created under my own name.

Now I see her name on the login screen.
But when making flows, he continues to give the old name (presence etc).

Have already tried a PTP but nothing helps. Also two weeks of waiting did not have the desired effect.

**What did you expect as result?**
That the old username changed to the newly entered name.

**What was the result?**
The old name remained visible

**Comment by WeeJeWel** [comment] 2017-12-13 10:13
Duplicate of #330 (same thing, basically)

**Closed by WeeJeWel** 2017-12-13 10:13 UTC
Labels: bug, Cloud, Homey Core
