### ISSUE TITLE
Javascript error "invalid namespace" in app settings

### ISSUE THREAD

**Issue by SergeRegoor** [athombv/homey#1093] opened 2016-11-22 20:01 UTC
**What is your Homey version (Settings → System)?**
1.0.1

**What did you try to achieve?**
Open any app's settings in Chrome.

**What was the result?**
Non-breaking client-side error:
socket.io.js:1647 realtime homey:app:nl.xxx.yyy Invalid namespace

**What did you expect as result?**
No error message.

**Any other remarks**
Seems like every app gives this error message. The error message is visible in the developer console of Chrome.

**Comment by jjtbsomhorst** [comment] 2016-11-22 20:27
I can acknowledge this.

**Comment by nattlip** [comment] 2016-11-22 20:53
with chrome windows 7 i can open appsettings plugwise source and wu

**Comment by WeeJeWel** [comment] 2016-11-23 13:46
I cannot reproduce. Which app for example does this?

**Comment by SergeRegoor** [comment] 2016-11-23 15:04
I've seen this issue with my own apps while developing, but also with the apps CountDown and Pushover.

**Comment by WeeJeWel** [comment] 2016-11-23 15:08
Okay thanks. Does it happen locally, or using xx.homey.athom.com as well?

**Comment by SergeRegoor** [comment] 2016-11-23 15:13
Both.

**Comment by SergeRegoor** [comment] 2016-11-23 15:37
![invalid-namespace](https://cloud.githubusercontent.com/assets/22777508/20567973/14332e1e-b19b-11e6-9177-aff5cbfea3d4.png)

**Comment by robertraaijmakers** [comment] 2016-12-24 19:19
Get this message as well.. no clue how to solve it. Tried changing namespace, am running Homey 1.0.5.
Maybe has something to do with Windows and Homey? Am running it from the command line, tried athom project --run as well as athom project --install.

socket.io.js:1647 realtime homey:app:eu.benext Invalid namespace
Emitter.emit @ socket.io.js:1647
Socket.emit @ socket.io.js:813
Socket.onpacket @ socket.io.js:921
(anonymous) @ socket.io.js:1512
Emitter.emit @ socket.io.js:1647
Manager.ondecoded @ socket.io.js:428
(anonymous) @ socket.io.js:1512
Emitter.emit @ socket.io.js:4389
Decoder.add @ socket.io.js:6740
Manager.ondata @ socket.io.js:418
(anonymous) @ socket.io.js:1512
Emitter.emit @ socket.io.js:4389
Socket.onPacket @ socket.io.js:2514
(anonymous) @ socket.io.js:2331
Emitter.emit @ socket.io.js:4389
Transport.onPacket @ socket.io.js:2947
Transport.onData @ socket.io.js:2939
ws.onmessage @ socket.io.js:4058

**Comment by irritanterik** [comment] 2017-02-06 14:34
I added a test app with this issue on #1310. The error *is* breaking. Realtime events triggered from app.js are not received on settings page with `Homey.on ('event',...)` if this error occurred.

**Comment by WeeJeWel** [comment] 2017-02-06 16:01
Fixed in 1.1.5. It occured when no `api.js` while was present.

**Comment by irritanterik** [comment] 2017-02-06 17:17
Great!

**Closed** 2017-02-14 12:14 UTC
Labels: bug, Homey Core, Staged for release
