### ISSUE TITLE
[Request] When Homey asks question: Do X when answer Yes, Do Y when answer No.

### ISSUE THREAD

**Issue by SkorpionNL** [athombv/homey#1352] opened 2017-03-06 12:42 UTC
**What is your Homey version (Settings → System)?**

1.1.9

**What did you try to achieve?**

I would like to be able to make a flow where Homey asks me a question and the action is depending on the answer. For example when I let Homey ask: 

Homey: Do I need to close the shutters?
Me: Yes
Homey: Ok, I will close the shutters => closes shutters

Homey: Do I need to close the shutters?
Me: No
Homey: Ok, I will keep the shutters open => Does nothing

Homey: Do I need to close the shutters?
Me: No response
Homey: I did not get any response => Does nothing

**What was the result?**
ATM when I use the ask for confirmation card, Homey can ask: Do I need to close the shutters?
When I confirm, Homey does close the shutters, but when I respond negative, in this situation the flow isn't fired and I can't put an action flow to that like:

 Homey says: Ok, I will keep the shutters open.

...

**What did you expect as result?**
I would like to attach separate flows/actions to an answer that I give when Homey asks a question in stead of flow not fired when answer was No and Homey expected Yes.

...

**Any other remarks**

...

**Comment by WeeJeWel** [comment] 2017-03-15 15:11
Duplicate of https://github.com/athombv/homey/issues/444 (else-functionality)

**Closed by WeeJeWel** 2017-03-15 15:11 UTC
Labels: enhancement, Flow
