### ISSUE TITLE
Somfy RTS control

### ISSUE THREAD

**Issue by markmg** [athombv/homey#565] opened 2016-05-03 06:58 UTC
**What is your Homey version (Settings → System)?**

0.8.32

**What did you try to achieve?**

Open and close blinds

When i press up or down in a flow or under devices Somfy only responds for 2 seconds 

**What was the result?**

Blinds not fully opening or closing in one command

**What did you expect as result?**

Fully closing or opening the blinds 

Example using a flow or control device on Homey, sending command 3 times as example, it only responds for 2 seconds 
https://www.youtube.com/watch?v=CL48TdFA_3A

Example using the Somfy remote sending 1 command
https://www.youtube.com/watch?v=RL8v6Pwk2cI

**Comment by markmg** [comment] 2016-05-19 06:48
Small update.
With the Memory (MY) button the blinds respond and move all the way down to the memory position

Using buttons up and down it only responds for 2 seconds

**Comment by Dennishacq** [comment] 2016-05-20 13:32
Duplicate of reaction in #596

**Closed by Dennishacq** 2016-05-20 13:32 UTC
