### ISSUE TITLE
not possible to change action sequence in flow

### ISSUE THREAD

**Issue by ttje47** [athombv/homey#983] opened 2016-10-10 22:04 UTC
**What is your Homey version (Settings → System)?**
V0.10.3

**What did you try to achieve?**
changing actions in a flow

_Please include detailed steps how we can reproduce the issue_
have more actions in a flow column and I wanted to change the sequence by moving a lower action to a higher position.  That is not allowed

**What was the result?**
actions stay on their place af first definition

**What did you expect as result?**
you should be able to move actions in the desired order

**Any other remarks**
not sure if this is a bug or a function request.

**Comment by markaswift** [comment] 2016-10-11 09:36
+1

**Comment by Arjanvde** [comment] 2016-10-11 09:38
I think this is the same as #61

**Comment by bvdbos** [comment] 2016-10-11 09:38
Then you should use timers? All actions are executed at the same time if you don't use timers... Doesn't have to do anything with the visual representation...

**Comment by markaswift** [comment] 2016-10-11 09:38
It sure is.

**Comment by markaswift** [comment] 2016-10-11 09:40
Timers are not useful with time critical flows that depend on completion of a prior task I'm afraid. Plus, having such logic reliant on a 3rd party isn't advisable.

**Comment by WeeJeWel** [comment] 2016-10-11 09:48
All actions execute, regardless of a previous action failed. So it really wouldn't make a difference :-)

**Comment by markaswift** [comment] 2016-10-11 09:49
I get that, it's an enhancement. As people start to use Homey to replace controllers though, it's a necessary one.

**Comment by bvdbos** [comment] 2016-10-11 09:50
It's a reasonable request for enhancement which is the same as #61 ?

**Comment by WeeJeWel** [comment] 2016-10-11 09:50
Ah, right :-) I'll think about a nice way to solve this!

**Comment by ttje47** [comment] 2016-10-11 15:54
Sounds great!  The Flow function of Homey is a powerfull and user friendly interface that need some more intelligence.  Hopefully it doesn't take too long to develop it.  Thanks.

**Comment by KroontjesPen** [comment] 2016-10-11 17:35
It is that the timer value is hidden. 
Therefore is a card position leading but also better to understand the flow,

**Comment by WeeJeWel** [comment] 2017-03-28 19:01
Duplicate of #61 (and fixed in v1.3.0)

**Closed by WeeJeWel** 2017-03-28 19:01 UTC
Labels: enhancement
