### ISSUE TITLE
Homey needs z-wave backup & restore functionality

### ISSUE THREAD

**Issue by nlrb** [athombv/homey#1689] opened 2017-07-15 14:46 UTC
**What is your Homey version (Settings → System)?**

1.3.2

**What did you try to achieve?**

Create a backup of my z-wave network configuration.

**What was the result?**

Could not find the button to create a backup or restore a backup.

**What did you expect as result?**

To be able to backup the z-wave network and settings. A lot of people have extensive z-wave networks managed by Homey. If this gets corrupted or they reset the z-wave chip by accident, it cannot be restored currently. As often modules are built into wall sockets, it is not easy to add all devices again, let alone with all configuration settings.

**Any other remarks**

Entering this as a sub-item of #451, such that it can get higher priority than full backup/restore functionality.

**Please attach a Homey System log (Settings -> System -> Send Log)**

n/a

**Comment by bvdbos** [comment] 2017-07-18 05:41
Though I understand it might be difficult, creating backups of zwave network information is possible judging a quick google-lookup...

**Comment by caseda** [comment] 2017-07-19 06:02
Pretty much a duplicate of https://github.com/athombv/homey/issues/451 as not just backing up the zwave chip is enough

**Comment by WeeJeWel** [comment] 2017-07-19 09:21
Duplicate of #451. If/when we create a backup & restore function, it will definitely include Z-Wave.

**Closed by WeeJeWel** 2017-07-19 09:21 UTC
