### ISSUE TITLE
force reload playlists

### ISSUE THREAD

**Issue by bvdbos** [athombv/homey#1562] opened 2017-05-18 18:24 UTC
**What is your Homey version (Settings → System)?**
1.3.0rc7

**What did you try to achieve?**
Commemorate Chris Cornell so added songs to google and soundcloud playlists and hoped to see them in Homey. It takes a long time (hours? not there yet...) to see the changed playlists in Homey...

Would be really helpfull if there was a way to force a reload of a playlist...

**Comment by WeeJeWel** [comment] 2017-11-20 14:59
Duplicate of #1474

**Closed by WeeJeWel** 2017-11-20 14:59 UTC
Labels: Athom App

**Comment by bvdbos** [comment] 2017-11-20 15:21
Oeps 😂
