### ISSUE TITLE
Some devices does not turn on when flow is activated

### ISSUE THREAD

**Issue by pewi72** [athombv/homey#2013] opened 2017-12-01 17:52 UTC
When my flow for lighting up the house some of the device does not active 

**Metadata**

* **Homey Version**:1.55
* **Homey Log Code**:1738B9828F
* **Smartphone Platform**:Android
* **Smartphone App Version**:

**If related to a Homey App:**
* **Homey App Version**:
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**: Fibaro dimmer (old) and Qubino dimmer and fibaro plug

**What did you try to achieve?**

When the flow is activated some of the devices (lights)  in the network does light up
and some is not

**What did you expect as result?**

That all devices (lights) in the flow is activated
**What was the result?** 
Some lights is not activated

Some of the devices Does not light up
**Any other remarks**
The problem is not every time its random, for example 1 fibaro plug is activated the other one is not
Qubino dimmer works one day the next it's not

**Comment by bvdbos** [comment] 2017-12-01 18:04
Any reason why this isn't the same as #1899 ?

**Comment by pewi72** [comment] 2017-12-01 18:12
Oops that was a long post i think it covers every thing, just to be clear it's not only fibaro and that 
i can manually turn it on and off after the flow is activated.

**Comment by jeroenvollenbrock** [comment] 2017-12-05 14:58
Closing as duplicate of #1899

**Closed by jeroenvollenbrock** 2017-12-05 14:58 UTC
