### ISSUE TITLE
Upgrade to 0.10.0 leaves Homey without apps and menu items

### ISSUE THREAD

**Issue by jghaanstra** [athombv/homey#890] opened 2016-09-24 14:13 UTC
**What is your Homey version (Settings → System)?**
0.10.0

**What did you try to achieve?**
Do an upgrade from 0.9.3 to 0.10.0

**Please include detailed steps how we can reproduce the issue**
All I did was start the upgrade process. Some of the apps I had installed on 0.9.3 where Greenwave, Fibaro, BetterLogic, Countdown, Buienradar, Kodi, KlikAanKlikUit, SolarPanels, LIFX, iCalendar, HarmonyHub, Hyperion, Screensaver (installed locally), WeatherUnderground, HTTP Requests, E-Mail.

**What was the result?**
Homey upgraded to version 0.10.0 but only left me with for menu items under the settings section (apps, microphone, voice and language). The apps section is completely empty. When trying to access the device section I get a pop-up saying "not ready". And pretty much all my flows are broken as they depend on one of the missing apps. 

**What did you expect as result?**
A proper upgrade to version 0.10.0.

**Any other remarks**
I have send a log to Athom with ID: 53A9370A60.

And I see a lot of failed websocket requests with the following error:

```
VM772:35 WebSocket connection to 'ws://<<ip>>/socket.io/?token=<<token>>&EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
WrappedWebSocket @ VM772:35
WS.doOpen @ socket.io.js:4026
Transport.open @ socket.io.js:2882
Socket.open @ socket.io.js:2303
Socket @ socket.io.js:2184
Socket @ socket.io.js:2110
Manager.open.Manager.connect @ socket.io.js:309
(anonymous function) @ socket.io.js:619
```
I'd really like to know the right way to resolve this, preferably without loosing my devices and flows.

**Comment by Dijker** [comment] 2016-09-24 14:40
Exact the same problem here, 
Maybe not exactly the same apps installed but at least these: BetterLogic, Countdown, Buienradar, KlikAanKlikUit, SolarPanels, HTTP Requests.
After updating last phase was red ring. That disappeared after logging into the homey.

PTP didn't  help. (Multiple times, longer waited,  etc...)

Apple can be installed from app store. But disappeared after PTP.

**Comment by hanek004** [comment] 2016-09-24 20:07
Same issue with my Homey. Would like to resolve it without factory reset, i.e. without losing apps+settings, devices, vars and flows.

**Comment by rboeije1** [comment] 2016-09-25 07:48
Same with me. Different apps,  (Altough KAKU, buienradar were the same.) Also the not ready message. Not sure about the red ring, as I upgraded from other room. But according to webpage the upgrade was succesful, But it wasn't. I did not yet do a swipe to factory settings, but I can't send log as that page is not available.

**Comment by CootNL** [comment] 2016-09-25 07:56
reinstall fix the problem

**Comment by Dijker** [comment] 2016-09-25 08:26
@CootNL 
Did you do a full wipe or keep settings?

**Comment by CootNL** [comment] 2016-09-25 11:45
I did a full wipe. Keeping settings is not working.

**Comment by jghaanstra** [comment] 2016-09-25 18:02
I can confirm a full wipe (erase all data) brings your Homey back to live. You will of course have to start from scratch again. Another option that might be able to restore your configuration would be to use the Wifi recovery procedure but you need OSX and a Raspberry Pi with a powered USB hub for it.

**Comment by Dijker** [comment] 2016-09-26 12:57
I have send some logs from Chrome Console:
api('POST','/manager/system/journalct/')
{"status":200,"result":"0C13C8A853"}
{"status":200,"result":"534A53C4E7"}

Will we be able to get Homey back with all information by updating to 0.10.1? 
Will it be possible to update? (my auto updating is disabled, the update button/menu is not vissible)
What is the expected delivery time  for that update? (days? weeks?)

**Comment by Arjanvde** [comment] 2016-09-26 13:09
If the team founds the root of this issue, I would be interested in the cause of this issue and how they have solved it.

**Comment by jeroenvollenbrock** [comment] 2016-09-26 18:54
This problem can be fixed in two ways: You can either wait for the 0.10.1 release and update through the recovery wizard (hold homey upside down for 10 seconds after Homey has started up), or contact me via slack to receive a recovery script that can be executed through the developer console of chrome after logging in to Homey. Devices, flows and apps will be preserved using both ways.

**Comment by jeroenvollenbrock** [comment] 2016-10-03 13:53
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.

**Closed by jeroenvollenbrock** 2016-10-03 13:53 UTC
Labels: bug, Migrations, Staged for release
