### ISSUE TITLE
Input validation not working for global tags on custom made action card

### ISSUE THREAD

**Issue by TedTolboom** [athombv/homey#1346] opened 2017-02-25 00:03 UTC
**What is your Homey version (Settings → System)?**
1.1.9

**What did you try to achieve?**
Debugging of custom made action card and testing the use of global tags as input, in particular the validation of input. In this case: "Change brightness over time" action card for the Fibaro FGD-212 dimmer (part of 1.2.4 currently Beta)

*Please include detailed steps how we can reproduce the issue*
Tried the use of global tags on a custom made action card, composed of multiple arguments (range, numerical and drop down). For the range and numerical arguments, the min, max attributes are defined:
```
{
"name": "brightness_level",
"type": "range",
"min": 0,
"max": 1,
"step": 0.01,
"label": "%",
"labelMultiplier": 100
},
{
"name": "dimming_duration",
"type": "number",
"min": 0,
"max": 127,
"placeholder": {
	"en": "Duration",
	"nl": "Tijdsduur"
	}
}
```
**What was the result?**
If I manually enter values out of the specified range, it will not allow the input; ie. direct validation.
If I link a global tag to these arguments, with a value out of the specified range, no error message is shown. 

<img width="490" alt="schermafbeelding 2017-02-24 om 23 27 42" src="https://cloud.githubusercontent.com/assets/17163431/23325453/b179d166-faf5-11e6-9b28-1b6e45c543a0.png">

Action card is successfully completed, yet the command behind the action card is not executed.

**What did you expect as result?**
Validation as specified in the arguments will block execution and provide an error message as implemented in the standard dim-cards:

<img width="467" alt="schermafbeelding 2017-02-24 om 23 18 26" src="https://cloud.githubusercontent.com/assets/17163431/23325460/ba35b694-faf5-11e6-858d-7d9ab7a3ad78.png">

**Any other remarks**
I would assume that validation is done based on the arguments specified; for all as defined on the action card. It looks like the validation of the standard action cards is not linked to the arguments, but 'hard-coded' into the default action cards. Most robust solution would be to implement this to the arguments.

**Comment by WeeJeWel** [comment] 2017-03-15 14:06
Thanks for the extensive issue! Under the hood it's a duplicate of #1346, so I'm merging this issue by closing it.

**Closed by WeeJeWel** 2017-03-15 14:06 UTC
Labels: bug, Flow

**Comment by TedTolboom** [comment] 2017-03-15 14:19
#1346 as duplicate of #1346 .... am I missing the logic?

**Comment by WeeJeWel** [comment] 2017-03-15 14:25
Ha, oops, I mean #1345
