### ISSUE TITLE
Hue Lights problems with third party apps

### ISSUE THREAD

**Issue by Arjanvde** [athombv/homey#356] opened 2016-03-17 20:25 UTC
**What is your Homey version (Settings → System)?**

0.8.24

**What did you try to achieve?**

When i'm in my bedroom and want to switch my hue lights off i need to use the Philips HUE app to switch all the lights off. After i switched them off with the app "alles uit" I cannot get the lights to respond anymore until i have switched them all off with Homey (even though they are allready switched off) 

Step 1, i switch my hue lights on:

![schermafbeelding 2016-03-17 om 21 11 57](https://cloud.githubusercontent.com/assets/17526110/13859858/de08f1a0-ec85-11e5-91f7-21ad5cc0d3e4.png)

Step 2, I switch my Hue lights off with the Philips Hue app with "Alles Uit"
![img_4288](https://cloud.githubusercontent.com/assets/17526110/13859892/0a029978-ec86-11e5-8b7d-ae671167b89e.PNG)

Step 3, to get the lights to respond again i have to switch them off first with a flow like this before i can use them again
![schermafbeelding 2016-03-17 om 21 18 21](https://cloud.githubusercontent.com/assets/17526110/13859926/33f22e2e-ec86-11e5-94c9-cb2f3f5dc9ff.png)

**What was the result?**

Hue Lights don't respond anymore, in my case i build in some voice and Slack feedback to check if the signal has come through.

**What did you expect as result?**

Lights to be switched on/off at any time even though the lights might be altered by third party apps.

**Any other remarks**

Off course the simplest question arise is why not take the remote with you to the bedroom?! Simple the signal of the remote doesn't reach Homey so I need to source an alternative remote either 868 or Zigbee.

**Comment by jordenc** [comment] 2016-03-18 11:53
Might be related to #345 (or actually the other way around)

**Comment by Arjanvde** [comment] 2016-03-18 12:12
@jordenc looks like this could be the cause of the issue #345

**Comment by WeeJeWel** [comment] 2016-03-22 15:45
Indeed a duplicate of #345

**Closed by WeeJeWel** 2016-03-22 15:45 UTC
