### ISSUE TITLE
Switching 12 lights on in a Flow is unreliable 

### ISSUE THREAD

**Issue by tompesman** [athombv/homey#1871] opened 2017-10-10 08:03 UTC
**What is your Homey version (Settings → System)?**

1.5.3

**What did you try to achieve?**

I've 12 Ikea TRADFRI GU10 bulbs in one flow. The action is to switch them on.

**What was the result?**

Some lights switch on. Sometimes all lights, sometimes a few.

**What did you expect as result?**

Switch all lights on.

**Any other remarks**

I've tried adding some delays so that not 12 lights are switched at the same time, but only 2 per second, still unreliable, but better. When I switch the lights on with a voice commands (no flow), like "Switch all lights on" actually works better. It looks like the switch-on commands are queued differently.

Not sure if this is an Ikea TRADFRI or ZigBee or Homey-core issue.

**Please attach a Homey System log (Settings -> System -> Send Log)**

75BA291227

**Comment by CyberSponk** [comment] 2017-10-10 08:17
Same with Lightify-Bulbs. You can look here: https://github.com/athombv/homey/issues/1859

**Comment by RobinBol** [comment] 2017-10-16 15:23
Closing this issue as it is indeed a duplicate of #1859

**Closed by RobinBol** 2017-10-16 15:23 UTC
