### ISSUE TITLE
KlikaanKlikuit ACM-3500 can no longer be paired.

### ISSUE THREAD

**Issue by kaandorp** [athombv/homey#744] opened 2016-08-01 20:44 UTC
**What is your Homey version (Settings → System)?**

0.9.1 / Kaku 2.1.0

**What did you try to achieve?**
I'm trying to add my ACM-3500 which is currently controlled by an AWST-8802. This work perfectly fine until I updated to 0.9.1.

*Please include detailed steps how we can reproduce the issue*
I'm adding a Kaku device. I choose the AC-XXX (Because the ACM-3500 is not available. Why actually?) Then I choose copy a remote, but when I press the buttons on the remote nothing happens and so I cannot pair the device.

**What was the result?**
Pairing kust doesn't work.

**What did you expect as result?**
Normal pairing as it did in the previous firmware version.

**Any other remarks**
Created a logfile: 4B70BDFCCA

**Comment by kaandorp** [comment] 2016-08-04 21:37
Just to add to this: when I try to add the AWST-8802 as device on its own this works fine, but when I try to use it as remote to be copied in Homey nothing happens.

**Comment by BasKiers** [comment] 2016-08-23 20:39
ACM-3500 does not yet have official support yet. Your issue was caused by a different bug where the app expected the kaku signal from an old remote for the AC-XXX devices. This is now fixed for the AC-XXX device. I would suggest to pair your device as three AC-1000 sockets (with app version 2.2.0). This should now work, if not please reopen this issue.

**Closed by BasKiers** 2016-08-23 20:39 UTC
Labels: Athom App, bug, RF
