### ISSUE TITLE
Aldi app does not work properly with new Quigg set

### ISSUE THREAD

**Issue by ericbv** [athombv/homey#1424] opened 2017-03-29 15:45 UTC
**What is your Homey version (Settings → System)?**

Homey version:1.2.0-rc.10
Aldi app: v1.1.0

**What did you try to achieve?**
I wanted to pair my new QUIGG set from the aldi to my homey.
remote : RCT DS1 CR-A 3726
socket  : RCR DS1 3711-A IP20 DE 3726
From some googleling i found out this is a rebrand of a similar silvercrest set:
http://www.lidl-service.com/static/193890283/276299_A_DE.pdf

*Please include detailed steps how we can reproduce the issue*
Try to pair a new quigg socket.
The remote signals of the A buttons will be recognized. But homey cannot control the device, homey will however see the remote presses and change its internal state of the device.

Buttons B,C,D do not work at all.

**What was the result?**
I am not able to control socket A via the homey.
I am not able to pair socket B,C,D.
...

**What did you expect as result?**
I expected to pair all the sockets and control them via homey
...

**Any other remarks**
I'm willing to provide extra information if required.
I've developed homey apps before and am willing to do some experiements.

...

**Comment by BasKiers** [comment] 2017-10-31 13:06
Hi,

I've just released an update to the Aldi app. Could you check if this fixes your problem. We do not have the hardware anymore so I am unable to test if this update actually fixes your issue.

Regards,
Bas

**Comment by ericbv** [comment] 2017-10-31 17:38
Hi Bas,

Just tried to add the sockets with the aldi app that i just installed from the appstore (v1.1.2).
Unfortunately it didnt work. 
- I am only able to pair the first device on the remote. Other devices on the remote do not pair.
- The socket that i could pair wouldnt switch when i tried to turn it on and off via homey.
- The homey did however update its state of the paired socket when i used the remote.

I actually have this quigg set double , so I would be willing to send one of my sets to the Homey office so you guys can resolve the issue.

Regards,
Eric

**Comment by jeroenvollenbrock** [comment] 2017-12-05 15:40
Closing as duplicate of #1172

**Comment by ericbv** [comment] 2017-12-06 10:28
Please reopen the devices that i am trying to pair is not the Quigg-GT-8000 as mentioned in #1172. So it is not an duplicate.

**Comment by WeeJeWel** [comment] 2018-04-11 09:06
Hi! Thank you for requesting support for a device.

We use GitHub for issue tracking in existing software only. Could you please fill out this form to request support for your device? We will then consider to support it! https://go.athom.com/request-device-support

I am closing this issue now. Please continue to report any bugs you may encounter in the future here.

**Closed by WeeJeWel** 2018-04-11 09:06 UTC
Labels: Athom App, Device Request, enhancement
