### ISSUE TITLE
Time off by an hour

### ISSUE THREAD

**Issue by AndreSomers** [athombv/homey#87] opened 2016-02-11 06:23 UTC
After setting up Homey, including checking the location (correct), I asked homey for the time. It was an hour off. 

I did not find a related setting, so I have no idea how to change it.

**Comment by freemann** [comment] 2016-02-11 06:47
Related to: 
https://github.com/athombv/homey/issues/47

maybe your "solution" is here.

**Comment by AndreSomers** [comment] 2016-02-11 10:13
Hmmm... might be it. Strange though. Would be nice to have this working out of the box. It also makes me wonder what time is used for the When's and And's in the flows...

**Comment by WeeJeWel** [comment] 2016-02-11 14:47
Duplicate of #47

**Closed by WeeJeWel** 2016-02-11 14:47 UTC
