### ISSUE TITLE
[nl.eneco.toon] communication with Toon broken

### ISSUE THREAD

**Issue by pakacom** [athombv/homey#2271] opened 2018-02-27 21:35 UTC
**Metadata**

* **Homey Version**:1.5.7 Experimental
* **Homey Log Code**: 08CE76D602
* **Smartphone Platform**:ios 11
* **Smartphone App Version**:1.1.105

**If related to a Homey App:**
* **Homey App Version**:1.3.6
* **Homey App Log Code**:
* **Affected Devices (preferably product codes)**:

**What did you try to achieve?**
Tried to set temperature

**What did you expect as result?**
That the temperature has changed

**What was the result?**
Error something went wrong addressing device Toon  (timed out after 5000ms.)

Error something went wrong  addressing device Toon (network request failed)

**Any other remarks**
After i upgrade from 1.5.6 Experimental to 1.5.7 Experimental i can not change temperature on toon.
for this it has always worked well.
I have already done a reboot and a ptp without good result.
have already removed the toon app from homey and reinstall it.
and i have removed and install the toon on the device page.

![img_0007](https://user-images.githubusercontent.com/36424478/36756063-4f6233f2-1c0e-11e8-8aef-87abde8031df.png)

![img_0008](https://user-images.githubusercontent.com/36424478/36756080-57dc6d36-1c0e-11e8-8667-910addffdfaf.png)

**Comment by bvdbos** [comment] 2018-02-27 21:51
So this did work in 1.5.6 experimental?

**Comment by pakacom** [comment] 2018-02-27 22:07
Yes it Work on 1.5.6 experimental and not on 1.5.7 experimental

**Comment by lubbertkramer** [comment] 2018-02-28 07:07
@pakacom but you get the error in the new beta app, does it still work in the (old) stable app / desktop and web environment?

**Comment by pakacom** [comment] 2018-02-28 07:34
it also does not work in the old app and not in the desktop and web environment.
if I try it with the toon app from eneco on my mobile phone then it works but not with the homey app

**Comment by kukel** [comment] 2018-03-01 15:58
Did work when 1.5.6 were RC's and failed after an update to 1.5.6 Final where a PTP fixed it. After the 1.5.7 upgrade it fails again and a PTP does not help

**Comment by chrisboer** [comment] 2018-03-05 12:40
Also does not work on 1.5.6 experimental I have same issues.

**Comment by RobinBol** [comment] 2018-03-05 12:46
There seems to be an issue with the Toon API that might be related to this, the developers have been notified.

**Comment by kukel** [comment] 2018-03-11 10:39
And any progress??? Let me (repost) an 'important' link https://www.athom.com/fi/press/#6f530d39-dfc8-478e-b8a5-3c3e60d4af43

This happening and not being fixed in two weeks does not sound like a partnership... (in a partnership you would be notified upfront). I'm seriously thinking of burning my Toon (and maybe even switch Energy supplier)

**Comment by kukel** [comment] 2018-03-12 12:31
Then what changed in the APIv1? It 'worked' before and suddenly does not work at all anymore. If **they (=Eneco)**  changed something, they **should** fix it if there is a partnership. If Athom changed something, (either in Homey core or in the Toon app), Athom should fix it. This is exactely why my former neighbour (mid-high end Domotica guy) told Athom that Homey is not 'end-user' ready.

**Comment by RobinBol** [comment] 2018-03-12 12:51
Well, you should ask the Toon developers, not me. We received some info concerning APIv3 and will see if we can make something work a.s.a.p.!

**Comment by kukel** [comment] 2018-03-12 14:50
Sorry, I was not asking you directly, I was asking on the 2271 issue on the "Homey issues". But since you mentioned you were in contact with the (Toon?) developers, I assumed you are one of the developers of the Toon app on Homey and would have more information. It worked before and the last month even 'stable' (after re-adding the Toon device), so I cannot imagine a (sudden) manifestation of a bug makes it totally not work for (even after a PTP) for over two weeks. And sure I can (try to) ask the Toon developers, but if Athom as a Toon **partner** does not have the information, the chance that I do get is limited. Would be good if Athom communicated about things like this on their Blog... (sorry for the sort of rant, I seriously still like Homey, but these are things where it/Athom should/could grow, communicating about problems/issue). Thanks anyway. anxiously waiting for a fix...

**Comment by Felyrion** [comment] 2018-03-13 22:23
Today i got the update to 1.5.8 and my Toon stopped functioning as a result. Isnt it weird that an update on Homey breaks the functioning of the device but now its a bug on the side of Toon? 
Can't the "old" way from before this update (1.5.3) be used then (until the new APIv3 is implemented)? Or is this thought too simplistic?

**Comment by RobinBol** [comment] 2018-03-13 23:28
Nothing changed on the Homey side, as mentioned; their API is broken.

**Comment by Felyrion** [comment] 2018-03-21 14:04
Is there any update on the timeline for when to expect a solution? For a partnership this is taking awfully long to be fixed!

Also, the title of this issue should probably be updated to reflect that the problems are not limited to the experimental release.

**Comment by kukel** [comment] 2018-03-21 16:08
@RobinBol 
> Nothing changed on the Homey side, as mentioned; their API is broken.

Maybe not in the Toon App on Homey, but everybody has problems after an update of the core of Homey. So something **DID** change there. The Toon app for sure uses the core of Homey so it is not unthinkable that a change in the  core (authentication (caching)?) resulted in this behaviour. And @Felyrion  is right, this takes waaaaay to long.  Going to mail support@athom.com about this tonight (without wanting to blame someone specific).

**Comment by RobinBol** [comment] 2018-03-21 17:09
@Felyrion no, we are waiting for some things from the Toon API developers. About the title, good suggestion.

@kukel It is also not related to changes in the core of Homey, correlation does not imply causality. It is just a coincidence that people think the 1.5.8 firmware update caused this issue, often people perform the update and then check if everything is still working, or they suddenly notice something is not working and then remember the recent firmware update.

We will release an update of the app as soon as we are running the Toon API v3 without major issues.

**Comment by kukel** [comment] 2018-03-22 14:20
@RobinBol:  True that a correlation does not mean causality. But Some of us use Homey on a daily basis, and if, twice, directly after a Homey update (1.5.6 and 1.5.7) Homey stopped communicating with Toon (**immediately** after the update) and the fact that Homey and Toon do not have a good track record, it is not weird to think that there is a relation. And yes, it can be a bug on the Toon side, for sure, which for an unknown reason manifests itself or e.g. an unintended fix for something in Homey made a bug in Toon visible and I can even understand that if the latter is the case, Athom does not want to fix this on the Homey side. And it could be something different. I can all understand this. But just provide more detail (what IS the bug???) information, progress etc.  Athom wants the community to participate in reporting things, developing things, fine great, I'm al in favour. But Athom should keep its customers up to date as well (and 'were working on it' is not enough detail). For me, 50% of what I use Homey for (lightning and heating) is **NOT** working now for over 3 weeks (and it could be 33% if TV worked as well but https://github.com/athombv/nl.philips.ir/issues/5 draws very little attention)

**Comment by Pauweltje** [comment] 2018-03-28 05:40
@RobinBol Waiting for this and give feedback with love! :kissing_heart:

**Comment by mveck** [comment] 2018-03-29 05:38
As already noted all related to abandoning APIv1 bij Toon/Eneco. Using Olisto as a workaround now. (Using http card to instruct Olisto to chance temperature). Works perfect for me.

**Comment by Pauweltje** [comment] 2018-03-29 05:40
@mveck Mind 2 share an example of your flow?
Thanks

**Comment by Dijker** [comment] 2018-03-29 05:43
@mveck @Pauweltje pls discuss the workaround on the Forum!
Thanks for your Update!

**Comment by Pauweltje** [comment] 2018-03-31 21:12
@Dijker I already did and sort it out myself and posted the steps I've made.. But thanks for your reply 😂

**Comment by Felyrion** [comment] 2018-04-07 11:03
Any update on this? This issue is now almost 1,5 month known. It's getting rediculous. Other platforms have integrations, so you guys should be able to get this done, seeing you are "partners" (< yes, that's ment to sound sarcastic).

For now I moved most devices to Alexa (some published trough homey) including Toon, so some stuff is at least working.

**Comment by daneedk** [comment] 2018-04-07 11:25
A new version of the Toon app has been published a couple of days ago, it uses the new Toon api v3 instead of the old api v1 and for me it seems to be working ok untill now. It does not show the correct figures for Power Meter and Gas Meter but that was known at release.

**Comment by chrisboer** [comment] 2018-04-07 11:26
Stop complaining the 2.0.4 versie is in the appstore works perfectly.

**Comment by daneedk** [comment] 2018-04-07 11:33
Damn, it triggerd me t actually look at it again, communication seems to be lost again, changes made in Homey don’t get to Toon and changes made in Toon don’t get to Homey....
Back to the drawing board I guess.

Homey didn’t crash but here’s a log anyway: FDF80A6B64
@RobinBol if you want to troubleshoot on my system, please contact me.

**Comment by kukel** [comment] 2018-04-07 11:57
@chrisboer 
> Stop complaining the 2.0.4 versie is in the appstore works perfectly.

I don't think **you** are in the position of telling us to stop complaining. The communication of Athom regarding this issue plain out sucks. If an fix was released, then why this issue was not targeted at a certain release? Is it still not closed? With a textual update. Athom has to learn a lot before becoming a serious company instead of a startup (and a really creative one that I still support). And as for @daneedk , it still does not work for me. Oh and then in the release notes I read I need to reparir... Great all my history will get lost... Great... And Why don't I see that in the NEW mobile app while I do see that in the soon to be dropped webapp? Sorry, but the incompatibility of the Toon v1 api and the v3 api should NOT make the data in Homey become void. The Toon app in Homey should be able to keep all its data.

And I just re-added the toon device: 

![afbeelding](https://user-images.githubusercontent.com/833920/38454657-79b16346-3a6b-11e8-8cfe-33a034599d5d.png)

Great... So it DOES NOT WORK. and yes, I still complain.

**Comment by RobinBol** [comment] 2018-04-07 12:13
@daneedk this is something I encountered myself as well (sporadically), but this also happened in the Toon iOS app (which uses the same API), hence the disclaimer in the app description. I will report any findings to the Toon API developers. Thanks for the feedback!

@kukel What more do you want to know? A complete explanation has been added to the app description. This issue is not closed yet (I guess you refer to that in the first part of your post) since, as said already, there are still some known issues. That however does not mean that we did not make an effort to re-establish communication with Toon, which we did. Regarding the re-pairing, you know this is something that is caused by the migration from API v1 to v3, which is is not something we have control over. You don't see this re-pairing message in the new smartphone app yet since it is a beta preview app (which you obviously know as well), and we do not claim all functionality is implemented at the moment. I'd like to remind you that this is a GitHub issue, not a support channel, if you like support or to ventilate your frustrations please send an email to our support department.

Now regarding the problem you demonstrate; did you try it once more? Do you have an application (not system) log? Based on this information I can not help you.

**Comment by Felyrion** [comment] 2018-04-07 19:35
Alright, I did not receive notifications on this issue, so I was not informed of a new version, hence my reaction. A small heads-up on this issue would have prevented this ;)

I will try to switch the Toon back to Homey in the coming days and report back on the experience.

**Comment by RobinBol** [comment] 2018-07-02 11:38
I am closing this issue since the root problem (the broken communication) has been fixed, and I haven't received any further complaints regarding this problem. If there are other problems you are encountering with the app please create a [new issue](https://github.com/athombv/homey/issues/new) and let us know!

**Closed by RobinBol** 2018-07-02 11:38 UTC
