### ISSUE TITLE
Fibaro motion sensor (plus)

### ISSUE THREAD

**Issue by robiebab** [athombv/homey#1350] opened 2017-03-03 21:50 UTC
**What is your Homey version (Settings → System)?**
1.1.9

**What did you try to achieve?**
If i enter a room where a fibaro motionsensor is active the lichts should go on instant

**What was the result?**
if i'm in the room it go's on after 5-20sec
...

**What did you expect as result?**
instant
...

**Any other remarks**
fibaro app 1.2.4
Log code:
89CA603399
...

**Comment by RobinBol** [comment] 2017-03-06 18:27
@WeeJeWel Probably related to the secure delay you mentioned last week?

**Comment by WeeJeWel** [comment] 2017-03-15 15:13
Might be. At my home it works instantly. Try reducing the amount of apps on your Homey or poll intervals.

I'm closing this issue because it's not a bug but most likely a too-active Homey, and thus we can't fix it with software.

**Closed by WeeJeWel** 2017-03-15 15:13 UTC
Labels: Athom App
