### ISSUE TITLE
Can not save changes regarding setting of a z-wave device 

### ISSUE THREAD

**Issue by HuubNabben** [athombv/homey#559] opened 2016-05-02 14:45 UTC
**What is your Homey version (Settings → System)?**

Homey IOS: 0.8.29

**Other information
I am working with
MacBook Pro
IOS: OS X 10.11.4
Kernel version: Darwin 15.4.0
Homey IOS: 0.8.29
Chrome version 50.0.2661.94 (64-bit)

**What did you try to achieve?**

I included the FIBARO smoke sensor. Inclusion was successful. Next i wanted to make changes in the settings of the sensor (the time between waking up, in seconds). So I select the device by clicking on the settings-icon on the device. Than the settings appear and for a short time i can see a button for 'save changes'. This button disapears again. Than I can type a new interval but I can not save it as there is no savings button any more..

**What was the result?**
The changes are not saved

**What did you expect as result?**
The changes to be saved

**Any other remarks**
Not applicable.

**Comment by ocatie** [comment] 2016-05-02 16:35
Could you provide me with a screenshot?

**Comment by HuubNabben** [comment] 2016-05-03 08:43
I hope this shows wat I mean. I can not scroll up or down and can not save settings even when I change the interval rate.

Just let me know if you need more information.
Thanks for your help.

Verstuurd vanaf mijn iPad

**Comment by mtudor** [comment] 2016-05-11 06:32
I have seen the same thing, with the "Save changes" button off-screen. In the short term I was able to work around it by using TAB to cycle round the fields to the save button.

**Comment by WeeJeWel** [comment] 2016-05-11 10:52
Can someone provide a screenshot? :-)

**Comment by mtudor** [comment] 2016-05-11 10:55
Dammit Emile, you're so demanding ;-)

![image](https://cloud.githubusercontent.com/assets/1683723/15178731/407f32f4-176f-11e6-8110-5c1f3d9df039.png)

**Comment by WeeJeWel** [comment] 2016-05-11 10:58
Ahhhh. This is fixed in 0.8.32 if I'm not mistaken. The scrollbars were missing.

**Comment by mtudor** [comment] 2016-05-11 11:03
Sorry Emile...

![image](https://cloud.githubusercontent.com/assets/1683723/15178890/67faa22c-1770-11e6-9cf3-84ea2f2af9c3.png)

**Comment by freemann** [comment] 2016-05-11 11:23
pictures tell more than a thousand words;
![screenshot - 11-5-2016 13_20_51](https://cloud.githubusercontent.com/assets/601053/15179367/70b6941a-177b-11e6-937d-86b64b116140.png)

**Comment by WeeJeWel** [comment] 2016-05-17 15:12
I cannot seem to reproduce this issue. Try setting `overflow: auto` to `overflow: scroll` using Chrome's inspector. Does that work?

![screen shot 2016-05-17 at 17 11 47](https://cloud.githubusercontent.com/assets/319873/15327636/7465956c-1c52-11e6-9956-674d999896bb.png)

**Comment by freemann** [comment] 2016-05-17 15:41
It looks like this issue is solved in 0.8.34 :question:

**Comment by mtudor** [comment] 2016-05-17 16:32
Confirmed that this is fixed for me in 0.8.34 also, the scrollbar is back!

**Closed** 2016-07-27 15:01 UTC
Labels: zwave
