### ISSUE TITLE
Weird UI behaviour (related to z-wave apparently)

### ISSUE THREAD

**Issue by Fire69** [athombv/homey#339] opened 2016-03-14 09:53 UTC
**What is your Homey version (Settings → System)?**

0.8.22

**What did you try to achieve?**

I wanted to open the card for the first device in a zone.

**What was the result?**

When I hovered my cursor over the icon to open the card, the icon disappeared.
When I clicked anyway (the cursor changed to the little hand), it didn't open the card for that device but instead opened the settings for a z-wave device (node 2.1 in this case) 
![image](https://cloud.githubusercontent.com/assets/1757287/13740593/eb5b4f8a-e9d1-11e5-9296-8226753abb05.png)

When I checked that device, it was marked as unreachable.
I went in to the z-wave settings and did a refresh of the node (2.1).
Then I went back to the card I was trying to open in the first place.
Behaviour was still the same, but now it opened the settings for node 2!
I went in to the z-wave settings again and did a refresh of node 2 this time.

Finally, with no more z-wave device marked as unreachable, I could now open the card for the device!

The above behaviour was the same for every zone, no matter what device I selected (Hue, Z-wave, Kodi, ...).
But only for the first device in the zone!

Here is a log: 687C43988F

**What did you expect as result?**

The correct card opening...

**Any other remarks**

...

**Comment by jghaanstra** [comment] 2016-03-14 17:37
This related or a duplicate from this issue: https://github.com/athombv/homey/issues/242

**Comment by jeroenvollenbrock** [comment] 2016-07-27 12:50
Duplicate of #242

**Closed by jeroenvollenbrock** 2016-07-27 12:50 UTC
