### ISSUE TITLE
Flow Folders do not work

### ISSUE THREAD

**Issue by ajterpstra** [athombv/homey#884] opened 2016-09-24 08:23 UTC
**What is your Homey version (Settings → System)?**

0.8.36 - 0.10.0

**What did you try to achieve?**
All folders removed and then restart homey, folders recreated.
I can create them, modify and delete, but can not put flow in the folders

**Comment by bvdbos** [comment] 2016-09-26 07:20
same as #877 ?

**Comment by ajterpstra** [comment] 2016-09-26 12:36
It looks a lot like me problem. but I can not do even the flow in the First level subfolder

**Comment by WeeJeWel** [comment] 2016-09-27 17:20
Duplicate of #877

**Closed by WeeJeWel** 2016-09-27 17:20 UTC
Labels: interface
