### ISSUE TITLE
Please fix the Toon app!

### ISSUE THREAD

**Issue by Pauweltje** [athombv/homey#2379] opened 2018-03-27 23:11 UTC
It's now more then 1 month that the app isn't working anymore!
I 've read that is has something to do with the new api v3, that Toon is using right now.

I hope you'll dig into it and find out what the cause is....

I am using this Toon-App on a daily basis...but I am very sad that it is not working anymore!

please fix it....

regards,
Pauweltje

**Comment by bvdbos** [comment] 2018-03-28 04:51
This is not a shoutbox.... dupe of #2271 and for more information see there.... Please go shouting at Eneco...

**Comment by Pauweltje** [comment] 2018-03-28 05:18
At least you are responding :smiley:

**Comment by WeeJeWel** [comment] 2018-03-31 10:15
Duplicate of #2271. We are waiting for the developers at Toon to fix their problems.

**Closed by WeeJeWel** 2018-03-31 10:15 UTC
