### ISSUE TITLE
Ask for conformation

### ISSUE THREAD

**Issue by rpeters01** [athombv/homey#692] opened 2016-06-21 12:23 UTC
**What is your Homey version (Settings → System)?**

0.8.38

**What did you try to achieve?**

continue after ask for conformation in a flow

**What was the result?**

...I get an red triangle (Timeout)

**What did you expect as result?**

...Flow continue after answer  ( yes )

**Any other remarks**

...if i look what homey heard in speech input it certainly heard yes.
I did power off connection for about 10 minutes, did create a new flow, still does not work.

**Comment by jeroenvollenbrock** [comment] 2016-07-27 15:55
Duplicate of #691

**Closed by jeroenvollenbrock** 2016-07-27 15:55 UTC
Labels: bug, Flow
