### ISSUE TITLE
[iOS] Power Meter capability (with long value) shows as phone number in device card

### ISSUE THREAD

**Issue by swttt** [athombv/homey#711] opened 2016-06-28 22:27 UTC
**What is your Homey version (Settings → System)?**

0.8.39

**What did you try to achieve?**

Show my power meter total in a device card.

**What was the result?**

My power meter numbers are kinda high, now it gives a link like its a phone number. (within the device card)

**What did you expect as result?**

A regular number without a link to call the number shown

**Any other remarks**

iOS 9 with the latest app update (1.1.1 build 17)

**Comment by WeeJeWel** [comment] 2016-08-01 07:19
This should be fixed in 0.9.1. If not, please report back, preferably with a screenshot!

**Comment by swttt** [comment] 2016-08-03 08:21
Indeed is fixed! Great work :smile:

**Comment by swttt** [comment] 2016-08-03 13:30
Weird, just popped up again.

![img_2519](https://cloud.githubusercontent.com/assets/17660608/17367159/32962d7a-598f-11e6-914b-b707a8d7b7d9.jpg)

**Comment by WeeJeWel** [comment] 2016-08-04 11:54
Oh, haha. I thought this was caused by decimals not being rounded.

Should be fixed in 0.9.2 using the `<meta name="format-detection" content="telephone=no">` tag.

**Comment by swttt** [comment] 2016-08-04 11:56
Great :) will test when 0.9.2 is released then.

**Comment by swttt** [comment] 2016-08-05 15:30
Semi fixed, the above error is gone. But now i have one digit less :sweat_smile:

**Comment by WeeJeWel** [comment] 2016-08-05 15:31
Screenshot?

**Comment by swttt** [comment] 2016-08-05 15:34
Here you go:
![image](https://cloud.githubusercontent.com/assets/17660608/17441732/c7091892-5b32-11e6-89b7-7def4216c08f.png)

**Comment by WeeJeWel** [comment] 2016-08-22 18:56
Now it's simply a too long number to be displayed.. haha. That's something that will be fixed throughout Homey as well pretty soon.

**Comment by WeeJeWel** [comment] 2016-08-22 18:56
I'm closing this issue as of now because the initial bug has been solved :)

**Closed by WeeJeWel** 2016-08-22 18:56 UTC
Labels: bug, smartphone
