### ISSUE TITLE
KaKu devices not working

### ISSUE THREAD

**Issue by chrisboer** [athombv/homey#1543] opened 2017-05-14 20:25 UTC
**What is your Homey version (Settings → System)?**
1.2.2

**What did you try to achieve?**
Normal evening flow to go off and have the lights go on

*Please include detailed steps how we can reproduce the issue*
90 % kaku devices, but none of the kaku devices went on.

**What was the result?**

...

**What did you expect as result?**

...

**Any other remarks**

...

**Please attach a Homey System log (Settings -> System -> Send Log)**
809235DE11
...

**Comment by jeroenvollenbrock** [comment] 2017-05-15 14:05
I've taken a look at your log file, and it appears as if your Homey ran out of memory. Did a reboot solve the problem? You could also try updating to version 1.3.0-rc.7, as it contains a few memory-based fixes.

**Comment by Reemster** [comment] 2017-05-15 14:17
I have (maybe had) the same problem with KaKu. maximum of 1/2 days Kaku works. (received and transmit) i fix it with a homey reboot every night. I already update homey to 1.3.0. time will tell if kaku works, without a reboot every day.

**Comment by chrisboer** [comment] 2017-05-15 17:52
@jeroenvollenbrock I have indeed rebooted homey and it worked again I am currently installing v1.3.0 and will keep you posted on the issues

**Comment by jeroenvollenbrock** [comment] 2017-05-16 10:14
Closing as duplicate of #1228

**Closed by jeroenvollenbrock** 2017-05-16 10:14 UTC
Labels: waiting for user feedback
