### ISSUE TITLE
Milight offline

### ISSUE THREAD

**Issue by djeskoswe** [athombv/homey#680] opened 2016-06-10 17:35 UTC
**What is your Homey version (Settings → System)?**

.38

**What did you try to achieve?**

Reboot and use Milight

*Please include detailed steps how we can reproduce the issue*

Reboot 

**What was the result?**

Milight shows offline , add device and all good
...

**What did you expect as result?**

Milight to work , reinstall app does not help 
...

**Any other remarks**
log : 672B03AE1F

![capture1](https://cloud.githubusercontent.com/assets/17300121/15973218/806fad04-2f42-11e6-8252-7086abbc5c5f.JPG)

...

**Comment by Zwoops** [comment] 2016-06-11 12:35
I'm also experiencing this, re-adding the milight bulbs brings them back (they respond a bit laggy though..) and rebooting wipes their connection to homey somehow.

Log: 051E91BD37

**Comment by RobinBol** [comment] 2016-06-16 12:11
Thanks for reporting, this is a known issue caused by some changes in 0.8.38. An update for the Milight app will be released soon.

**Closed by RobinBol** 2016-06-16 12:11 UTC
