### ISSUE TITLE
error_token_not_a_number

### ISSUE THREAD

**Issue by markaswift** [athombv/homey#977] opened 2016-10-08 21:11 UTC
**What is your Homey version (Settings → System)?**

10.3

**What did you try to achieve?**

Drag a number token for use in logic card.

*Please include detailed steps how we can reproduce the issue*

Drag a number token into the logic card (for example, in my case, Belkin insight power usage).

**What was the result?**

"error token_not_a_number".

**What did you expect as result?**

Use of numbers in logic card.

**Comment by gruijter** [comment] 2016-10-08 21:57
I can confirm this. I found out exactly the same. I would like to use the token "energy" in a logic condition. 
'If energy < 4 watts do something"
This however does not work because the token is a string. 

![2016-10-08](https://cloud.githubusercontent.com/assets/19174120/19216186/ab6a1278-8db2-11e6-9e59-cc4c648e369a.png)

I managed do do it with better logic, by making it a number using a math.js expression. See picture, where the logic condition card fails, but the better logic condition card does work

**Comment by WeeJeWel** [comment] 2016-10-10 13:26
This only happens when using the 'Test' button. When the device actually triggers, it'll work.

I'll fix these example token values in 0.10.4

**Comment by gruijter** [comment] 2016-10-10 13:28
great. Thx!

**Comment by markaswift** [comment] 2016-10-10 15:21
Thanks @WeeJeWel

**Comment by gruijter** [comment] 2016-10-14 21:11
See #924. Logic fails in 0.10.5

**Comment by bvdbos** [comment] 2016-10-15 08:04
console says : 
[div.card, div.card, div.card, prevObject: Z.fn.init[1], context: document, selector: "#editor .cards[data-type="condition"] > .item:nth-child(1) .card[data-order="0"]"]

**Comment by jeroenvollenbrock** [comment] 2016-10-17 13:00
I'm closing this issue as it is fixed in the latest update. If the problem persists, please reopen this issue.

**Closed by jeroenvollenbrock** 2016-10-17 13:00 UTC
Labels: Staged for release

**Comment by batiban** [comment] 2017-10-30 23:26
Hi I've made a Flow with a Token which supposed to be an integer "Number" but actually I don't see any option to set it as a Number. So I get "Token_not_a_number" error.
I'm using the Homey software in Windows. is java the only way to do that?
