### ISSUE TITLE
Flows are not triggered - Fibaro devices stop responding until Homey Restart

### ISSUE THREAD

**Issue by exiof** [athombv/homey#1999] opened 2017-11-24 17:11 UTC
After upgrade of Homey or Fibaro app my devices keep disconnecting from Homey - when I restart the homey it works igen.

I can't exactly say what happend but 1.5.5 and Fibaro 1.5.13 came about the same day.

**Metadata**

* **Homey Version**: 1.5.5
* **Homey Log Code**: 726A33BDB1

**If related to a Homey App:** Fibaro
* **Homey App Version**: v1.5.13
* **Homey App Log Code**: c062e5e1-08a1-457f-b856-ec94c8cacbbc
* **Affected Devices (preferably product codes)**: Fibaro Dimmer 2 and other fibre devices!

**What did you try to achieve?**
Nothing in particular - it have been working for ages but after either a Homey update or App update I have to restart my homey every day to get it working again.

When a sensor sees motion my light does not turn on - I reboot homey and it works again - I can't see whats wrong.

**Any other remarks**

**Comment by caseda** [comment] 2017-11-25 07:45
Related: https://github.com/athombv/homey/issues/1899
Will most likely be fixed in 1.5.6

**Comment by WeeJeWel** [comment] 2017-12-01 13:27
What do you mean with 'keep disconnecting'?

**Comment by exiof** [comment] 2017-12-01 15:58
Well - not disconnecting - i just loose the ability to manage the z-wave devices from Homey - and i reboot homey and it works again..

**Comment by jeroenvollenbrock** [comment] 2018-02-27 11:42
Closing as duplicate of #1899

**Closed by jeroenvollenbrock** 2018-02-27 11:42 UTC
Labels: Z-Wave, waiting for user feedback
