### ISSUE TITLE
Homey Speech Recognition

### ISSUE THREAD

**Issue by SynoUser-NL** [athombv/homey#1241] opened 2017-01-06 13:34 UTC
**What is your Homey version (Settings → System)?**
V0.x.x - V1.1.2

**What did you try to achieve?**
I am trying to get Homey to understand my speech commands. The OK Homey trigger has a hit rate of about 80-90%, which is acceptable. However with subsequent speech commands to trigger flows or to execute buit-in voice commands the speech recognition hit rate is 1% at best.

When using a parrot flow (Homey repeats what it hears after recognition processing) the outcome is nowhere near my actual voice command.

I have tried:
- speaking slower: no improvement
- changing voice pitch: very slight improvement
- changing Homey location within room: no improvement
- changing Homey location to another room: no improvement
- changing firmware: no improvement (almost the opposite, actually)
- other person speaking: no improvement

With all efforts background noise was kept to an absolute minimum (i.e. no music, tv, etc..). By comparison: the hit rate of speech recognition using the Android App is much, much higher, around 8-90%.

**What was the result?**
See above.

**What did you expect as result?**
I expect Homey to have at least a 60-75% hit rate when using speech commands using its built-in microphone. Preferably higher ofcourse so that speech recognition actually becomes usable.

**Any other remarks**
Feel free to contact me for any additional details you require, of which you are aware other users are reporting as well. I'm at your disposal in helping to get this solved.

Thanks for your time and efforts, sincerely,
DenW

edit 14-01-2017: And now with 8 days on GitHub and a lot of supporting messages: 0 response from Athom..
When is this issue getting any attention?

**Comment by Fire69** [comment] 2017-01-06 19:16
Same problem here...
It works when I'm closer than 1m away, which is pretty ridiculous.

**Comment by ericjanvanputten** [comment] 2017-01-06 19:33
Works standing next (within 1 meter-ish) to homey, but at 3-4 meters almost no recognition. 
via phone >90% correct understanding

**Comment by xrayman78** [comment] 2017-01-06 19:50
Same here, recognition rate is very low in a room with background noise. When totally silent mostly i have to say the command several times (within 3 meters). This should be prio 1 for Athom! it is the main interface for interaction.

**Comment by dhanstede** [comment] 2017-01-06 19:52
Speech recognition here is about 30%. To low, same problem.

**Comment by ericjanvanputten** [comment] 2017-01-06 20:03
actually in a silent room the command 'okay homey' works okay further away as well, but then totally noodles it up with the rest of the recognition

**Comment by Fire69** [comment] 2017-01-06 20:09
'OK Homey' is not the problem for me, works pretty much as expected up to 5-6m.
It's after that that nothing works unless < 1m

**Comment by Willieku** [comment] 2017-01-06 20:38
when homey start listning i made a flow that sonos stops. so it is no sound.    i am at 2,5 meters.   then homey understand me best.  when at 5 meter  ok homey   works  but does not understand what i say.
every sound in the room disturb the understanding.   a cup that rinkels, a cuff   even the dog which is snurring disturb understanding.
Het is mij opgevallen that after i had PTP for other reasen,  the understanding went bad and i must scream to homey.  after some time this goes better.   no explonation about this...

**Comment by chrisboer** [comment] 2017-01-06 21:18
Lol  a cuff even the dog which is snurring disturb understanding.

Really laughing here

**Comment by philsniff** [comment] 2017-01-06 22:58
Nothing more than "okay, homey" Works here. Before Firmware 1.0.1 it was a little better but now unusable!

**Comment by Fire69** [comment] 2017-01-07 14:21
https://github.com/athombv/homey/issues/920

**Comment by mauritsivs** [comment] 2017-01-07 17:55
same here, lenguage set to english, 
"ok homey" works ok. (though it even thinks its said during random conversations)

voice command recogniton
at <1m 60% succes, 
at >1m 5% succes.

**Comment by markaswift** [comment] 2017-01-08 10:25
Same, been like this a year with no improvement. I don't use voice anymore.

**Comment by Dom2061** [comment] 2017-01-08 15:44
Voice control is absolutely CRUCIAL to me because I am disabled. At the moment, I can't use Homey at all because recognition is so poor. Imagine Homey with, 'Alexa'-like communication… this is potentially a world-beating product which is faltering on something central to its usability and appeal.

**Comment by MarvinSchenkel** [comment] 2017-01-12 21:53
@Dom2061 If you have an Android phone or Google Home, I have a work around for you that will fix the speech recognition for you:
https://forum.athom.com/discussion/comment/43417/#Comment_43417

**Comment by dhanstede** [comment] 2017-01-15 08:12
Can someone of the employees of Athom respond to this issue? It's also an (active) topic on the forum. I don't expect a solution for the next release, but at least an explanation and strategy how athom wants to solve this problem in the future.

**Comment by magtimmermans** [comment] 2017-01-15 08:20
Same here

**Comment by ericjanvanputten** [comment] 2017-01-15 09:58
would be good to have a switch to google/amazon for voice

**Comment by B-maxX** [comment] 2017-01-15 10:03
Same here. 
And without my Laptop I can't switch a KAKU device. 
I like homey but voice is a really  disappointment

**Comment by gerjan01** [comment] 2017-01-15 11:06
Ok Homey, works 90% good, but the rest often works bad. maybee 30% good reconition

with background noise, reconition is down to 10% (homey keeps lisening far after when i am done, and returns to stand-by)

**Comment by Dom2061** [comment] 2017-01-15 13:50
Thanks for the advice, MarvinSchenkel, but I'm afraid I don't have Google home or an android phone and even if I did, I'm not sure I understand what to do.
As some of the others have mentioned, trying to find workarounds shouldn't be such a big issue in a product which is being retailed as voice-activated.

**Comment by jjtbsomhorst** [comment] 2017-02-04 16:20
Voice recognition works fairly to poor. Some days I get a 100% success rate on all things and other days it is as low as 30%. It also depends on what I say. When I use the standard triggers for lights and such those are worse then for instance the short 'netflix' command I created for a flow

**Comment by jeroenvollenbrock** [comment] 2017-03-06 16:21
Closing as duplicate of #920.

**Closed by jeroenvollenbrock** 2017-03-06 16:21 UTC
