### ISSUE TITLE
Kaku-app crashes with exit code 0

### ISSUE THREAD

**Issue by MdeRhoter** [athombv/homey#900] opened 2016-09-26 10:53 UTC
**What is your Homey version (Settings → System)?**

0.10.0

After the update the Kaku-app continuously crashes with the following information:

Stack trace:
false
Exit code: 0

As a result, none of my Kaku devices work. Restarting Homey does not help, neither does restarting the app.

**Comment by BasKiers** [comment] 2016-09-26 15:00
Could you please install v2.5.0 of the KaKu app and check if your problem still persists?

If you still have this issue could you post a screenshot of the usage graph of kaku in `settings -> developers` when running the app.

Thanks in advance

**Comment by MdeRhoter** [comment] 2016-09-26 16:19
I don't know what you did, but it seems to work! Running v2.5.0, it's all fine so far. If it runs for 24 hours without crashing, I'll let you know. Fingers crossed!

**Comment by bvdbos** [comment] 2016-09-26 17:58
For me with 2.5 this bug just surfaced for the first time. Didn't have it on 2.4...

**Comment by MdeRhoter** [comment] 2016-09-26 18:13
Hang on, so you didn't have it before the (auto) update of the Kaku app, but now you do?

I feel a little like that's my fault :)

**Comment by bvdbos** [comment] 2016-09-26 18:17
LOL, don't feel guilty. If I wanted stability I would have unchecked automatic updates ;-)

**Comment by sleutelsnet** [comment] 2016-09-26 19:49
My kaku 2.4.0 crashes as well (fw 0.10.0) but not on all devices. It crashes on e.g the doorbell. I can pair it up to Homey, the first trigger from the doorbell causes Homey to crash.
Work around (for now) is to reset the 433 microcontroller via a post command after the doorbell has been rang.

**Comment by BasKiers** [comment] 2016-09-27 13:34
@sleutelsnet This is an issue caused by the old drivers that are still in the KaKu app. As of v2.5.0 I've removed these drivers. You should remove the doorbell and add it again and this will fix your crashes

**Comment by MdeRhoter** [comment] 2016-09-27 13:38
No crashes here since 2.5.0 - the only device I couldn't re-add is the AYCT-102 remote. I can live without that for a while, I much prefer the rest being stable. Thanks @BasKiers!

**Comment by BasKiers** [comment] 2016-09-28 15:22
Will look into this issue if it persists after 0.10.1 since I am unable to reproduce it. I've found users that experience this issue get it working for now by enabling/disabling the app multiple times or a PTP.

**Comment by bvdbos** [comment] 2016-09-30 20:28
After having disabled KaKu for more then 30 seconds (should be more then 60 seconds I presume - because of saving changes?) this didn't happen for me anymore.

**Comment by bvdbos** [comment] 2016-10-01 09:04
Also I could add the AYCT-102 remote on KaKu 2.6 (don't know if I could on 2.5)

**Comment by MdeRhoter** [comment] 2016-10-01 10:08
Yup, that works now!

**Comment by bvdbos** [comment] 2016-10-08 20:32
then you can close this issue?

**Closed** 2016-10-10 09:17 UTC
Labels: App-SDK, bug
